import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
export {identity,json,P,B,product,security,execution,caller,canonical,sha} from '../team-hub-d1/aws.mjs';
import {identity,json,P,product,security,execution,caller,sha} from '../team-hub-d1/aws.mjs';
export const E='docs/architecture/team-hub-authority-endpoint-deployment-evidence-2026-10-08',read=n=>json(E+'/'+n+'.json'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
export function pin(){const root='infrastructure/domains/team-hub/.build/authority-status/30ac97e5b48f3867268403c13766e9439aa2e0821d87585a685cfdfae1b997d1';const expected={'candidate.json':'30ac97e5b48f3867268403c13766e9439aa2e0821d87585a685cfdfae1b997d1','product.template.json':'5a2d99f4919fd07c619f483e556a0464b9cbaad0be00665201438b0f4ec7d0e9','runtime.zip':'cd58cc3553867f268af79bc9c710fe35e1bab07882d39b423e05b39626a7eedd','security.template.json':'503d08c93fddc869a11bc01c6ec57fe4e7449e618e0c9435e7bf2ed996351abc'};for(const [f,h]of Object.entries(expected))assert.equal(sha(root+'/'+f),h);const c=json(root+'/candidate.json');return {...c,root,zipPath:root+'/runtime.zip',zipSha256:c.runtimeSha256,key:c.templateKey,url:c.templateUrl,changes:{security:c.securityChanges.modify,product:['AuthorityStatusInvokePermission','AuthorityStatusRoute','ParityReadFunction']}};}
const exec=promisify(execFile);let credentials;
const allowed={sts:['get-caller-identity','assume-role'],iam:['get-role','get-policy','get-policy-version','get-role-policy','list-role-policies','list-attached-role-policies'],dynamodb:['get-item'],cloudformation:['get-template','describe-stacks','list-stack-resources','describe-stack-events','create-change-set','describe-change-set','execute-change-set'],s3api:['head-object','put-object'],lambda:['get-function-configuration','get-policy']};
export async function aws(s,a,input={},restricted=false){assert.ok(allowed[s]?.includes(a));const c=pin(),write=['create-change-set','execute-change-set','put-object'].includes(a);if(a==='assume-role')assert.equal(input.RoleArn,caller);
if(write){assert.ok(!fs.existsSync(E+'/STOP.json'));for(const n of ['artifact-review','preflight','policy-review','before/inventory','before/preservation','routes-before','runtime-security-before'])assert.equal(read(n).complete,true,n);
if(s==='s3api'){assert.equal(input.Bucket,c.bucket);assert.ok([c.key,c.assetKey].includes(input.Key));assert.equal(input.Body,input.Key===c.key?c.root+'/product.template.json':c.zipPath);assert.equal(input.ServerSideEncryption,'AES256');}
else{const k=input.StackName===product?'product':'security';assert.equal(input.StackName,k==='product'?product:security);assert.equal(restricted,k==='product');if(a==='create-change-set'){assert.equal(input.ChangeSetType,'UPDATE');assert.equal(input.ChangeSetName,'team-hub-authority-status-'+k+'-20261008');if(k==='product'){assert.equal(input.TemplateURL,c.url);assert.equal(input.RoleARN,execution);assert.equal(read('publication').verified,true);assert.equal(read('security-installed').verified,true);}else assert.equal(input.TemplateBody,fs.readFileSync(c.root+'/security.template.json','utf8'));}else{const g=read(k+'-gate');assert.equal(g.ready,true);assert.equal(input.ChangeSetName,g.changeSetId);assert.equal(input.DisableRollback,false);assert.ok(Date.now()-Date.parse(g.at)<300000);}}}
const env={...process.env,AWS_MAX_ATTEMPTS:'1'};if(restricted){assert.ok(credentials);Object.assign(env,{AWS_ACCESS_KEY_ID:credentials.AccessKeyId,AWS_SECRET_ACCESS_KEY:credentials.SecretAccessKey,AWS_SESSION_TOKEN:credentials.SessionToken});delete env.AWS_PROFILE;delete env.AWS_DEFAULT_PROFILE;}
fs.mkdirSync('.tmp/team-hub-authority-deploy',{recursive:true});const f='.tmp/team-hub-authority-deploy/'+crypto.randomUUID()+'.json',request={...input};if(a==='put-object')delete request.Body;fs.writeFileSync(f,JSON.stringify(request));try{const {stdout}=await exec('aws',[s,a,'--cli-input-json','file://'+f,...(a==='put-object'?['--body',input.Body]:[]),...(restricted?[]:['--profile','default']),'--region','eu-north-1','--output','json','--no-cli-pager'],{env,windowsHide:true,maxBuffer:32e6});if(write)fs.appendFileSync(E+'/aws-writes.jsonl',JSON.stringify({at:new Date().toISOString(),service:s,action:a,stack:input.StackName,key:input.Key,restricted})+'\n');return stdout.trim()?JSON.parse(stdout):{};}catch(e){const code=(e.stderr??'').match(/\(([^)]+)\)/)?.[1]??e.code??'COMMAND_FAILED';if(write)save('STOP',{at:new Date().toISOString(),service:s,action:a,code});throw Error(s+' '+a+': '+code+(write?'':': '+String(e.stderr??'').replace(/\s+/g,' ').slice(0,800)));}finally{fs.unlinkSync(f);}}
export async function assume(){credentials=(await aws('sts','assume-role',{RoleArn:caller,RoleSessionName:'TeamHubAuthorityStatus',DurationSeconds:3600})).Credentials;const i=await aws('sts','get-caller-identity',{},true);assert.equal(i.Account,'058264289478');assert.ok(i.Arn.startsWith('arn:aws:sts::058264289478:assumed-role/ProjectRespawn-TeamHub-Ntgre-Deploy/'));save('restricted-identity',{at:new Date().toISOString(),identity:i});return i;}
