import fs from 'node:fs';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import assert from 'node:assert/strict';import crypto from 'node:crypto';
const exec=promisify(execFile),E='docs/architecture/team-hub-authority-endpoint-deployment-evidence-2026-10-08/before';
const allowed={sts:['get-caller-identity'],iam:['get-role','list-role-policies','get-role-policy','list-attached-role-policies','get-policy','get-policy-version'],lambda:['get-function-configuration'],dynamodb:['get-resource-policy']};
async function aws(s,a,args=[]){assert.ok(allowed[s]?.includes(a));const {stdout}=await exec('aws',[s,a,...args,'--profile','default','--region','eu-north-1','--output','json','--no-cli-pager'],{windowsHide:true,maxBuffer:20e6});return JSON.parse(stdout);}
const decode=p=>typeof p==='string'?JSON.parse(decodeURIComponent(p)):p,hash=p=>crypto.createHash('sha256').update(JSON.stringify(p)).digest('hex');
const result={at:new Date().toISOString(),identity:await aws('sts','get-caller-identity'),roles:[],awsWrites:0,complete:false};assert.equal(result.identity.Account,'058264289478');const save=()=>fs.writeFileSync(E+'/installed-iam.json',JSON.stringify(result,null,2)+'\n');save();
async function policy(arn){const p=(await aws('iam','get-policy',['--policy-arn',arn])).Policy;const v=(await aws('iam','get-policy-version',['--policy-arn',arn,'--version-id',p.DefaultVersionId])).PolicyVersion;return {arn,version:p.DefaultVersionId,document:decode(v.Document)};}
for(const kind of ['Read','Command']){const conf=await aws('lambda','get-function-configuration',['--function-name','ProjectRespawn-TeamHub-Ntgre-Parity'+kind]);const name=conf.Role.split('/').at(-1);const role=(await aws('iam','get-role',['--role-name',name])).Role;const inline=[];for(const n of (await aws('iam','list-role-policies',['--role-name',name])).PolicyNames){const r=await aws('iam','get-role-policy',['--role-name',name,'--policy-name',n]);inline.push({name:n,document:decode(r.PolicyDocument)});}const attached=[];for(const p of (await aws('iam','list-attached-role-policies',['--role-name',name])).AttachedPolicies)attached.push(await policy(p.PolicyArn));const boundary=await policy(role.PermissionsBoundary.PermissionsBoundaryArn);result.roles.push({kind,name,arn:role.Arn,roleId:role.RoleId,trust:decode(role.AssumeRolePolicyDocument),inline,attached,boundary,codeSha256:conf.CodeSha256,authority:conf.Environment.Variables.TEAM_HUB_AUTHORITY,normalWrites:conf.Environment.Variables.TEAM_HUB_NORMAL_WRITES});save();}
result.resourcePolicies=[];for(const suffix of ['Operational','Journal']){const arn='arn:aws:dynamodb:eu-north-1:058264289478:table/ProjectRespawn-TeamHub-Ntgre-'+suffix;try{const r=await aws('dynamodb','get-resource-policy',['--resource-arn',arn]);result.resourcePolicies.push({arn,policy:decode(r.Policy),revision:r.RevisionId});}catch(e){if(!e.stderr?.includes('PolicyNotFoundException'))throw e;result.resourcePolicies.push({arn,policy:null});}}
const accepted=JSON.parse(fs.readFileSync('docs/architecture/team-hub-c1-evidence-2026-10-07/c2-product.template.json')),security=JSON.parse(fs.readFileSync('docs/architecture/team-hub-c1-evidence-2026-10-07/c2-security.template.json'));
for(const r of result.roles){assert.equal(r.attached.length,0);assert.equal(r.inline.length,1);assert.deepEqual(r.inline[0].document,accepted.Resources['Parity'+r.kind+'Role'].Properties.Policies[0].PolicyDocument);assert.deepEqual(r.boundary.document,security.Resources['Parity'+r.kind+'Boundary'].Properties.PolicyDocument);r.acceptedC2Match=true;}
result.complete=true;save();console.log(JSON.stringify({roles:result.roles.map(r=>({name:r.name,inline:r.inline.length,attached:r.attached.length,boundary:r.boundary.arn,version:r.boundary.version,acceptedC2Match:r.acceptedC2Match})),resourcePolicies:result.resourcePolicies,complete:true}));
