import assert from 'node:assert/strict';import {aws,read,save,product} from './aws.mjs';
const p=read('live-endpoint'),names=['Requests','AuthorizationFailures','DependencyFailures','CoreDependencyFailures','TransactionConflicts','WriterNotAuthoritative','AuthorityUnavailable','AuthorityEpochMismatch'];assert.equal(p.complete,true);const r={at:new Date().toISOString(),window:p.metricWindow,logs:[],custom:[],native:[],pending:[],complete:false};const sum=x=>x.length?x.reduce((n,p)=>n+p.Sum,0):null;
async function metric(ns,name,dimensions){const a=await aws('cloudwatch','get-metric-statistics',{Namespace:ns,MetricName:name,Dimensions:dimensions,StartTime:p.metricWindow.start,EndTime:p.metricWindow.end,Period:60,Statistics:['Sum']});return {namespace:ns,name,dimensions,datapoints:a.Datapoints,observed:sum(a.Datapoints)};}
function parse(message){let v;try{v=JSON.parse(message);if(typeof v.message==='string')v=JSON.parse(v.message);else if(v.message&&typeof v.message==='object')v=v.message;}catch{return null;}return v?._aws?.CloudWatchMetrics?.[0]?.Namespace==='ProjectRespawn/TeamHub'?v:null;}
for(const runtime of ['read','command']){let next;const events=[];do{const a=await aws('logs','filter-log-events',{logGroupName:'/project-respawn/Ntgre/team-hub/parity-'+runtime,startTime:Date.parse(p.metricWindow.start),endTime:Date.parse(p.metricWindow.end),...(next?{nextToken:next}:{})});for(const e of a.events??[]){assert.ok(!/\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,}\b|\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/.test(e.message));const v=parse(e.message);if(v){const allowed=new Set(['_aws','Environment','Runtime','event','operation','requestId','status','code',...names]);assert.ok(Object.keys(v).every(k=>allowed.has(k)));events.push({eventId:e.eventId,timestamp:e.timestamp,metric:v});}}const old=next;next=a.nextToken;if(old===next)break;}while(next);
const expectedRequests=p.requests.filter(q=>q.label.startsWith('business-denial-')?q.runtime===runtime:runtime==='read'&& !['missing-token','invalid-token'].includes(q.label)&&!q.label.includes('tampered-signature'));
for(const q of expectedRequests){const match=events.filter(e=>e.metric.requestId===q.requestId);if(match.length!==(q.label.startsWith('business-denial-')?2:1)){r.pending.push('logs:'+q.label);continue;}assert.equal(match.reduce((n,e)=>n+e.metric.Requests,0),1);assert.equal(match.reduce((n,e)=>n+e.metric.WriterNotAuthoritative,0),q.label.startsWith('business-denial-')?1:0);}
const unknown=events.filter(e=>!expectedRequests.some(q=>q.requestId===e.metric.requestId));assert.equal(unknown.length,0,'Unexpected requests in metric window');const expected=Object.fromEntries(names.map(n=>[n,events.reduce((x,e)=>x+(e.metric[n]??0),0)]));r.logs.push({runtime,events,expected,expectedRequests:expectedRequests.length});for(let i=0;i<names.length;i+=4)r.custom.push(...await Promise.all(names.slice(i,i+4).map(async n=>{const m=await metric('ProjectRespawn/TeamHub',n,[{Name:'Environment',Value:'Ntgre'},{Name:'Runtime',Value:runtime}]);m.expected=expected[n];if(m.observed===null||m.observed<expected[n])r.pending.push(runtime+':'+n);else assert.equal(m.observed,expected[n]);return m;})));}
for(const runtime of ['Read','Command'])for(const n of ['Invocations','Errors','Throttles']){const m=await metric('AWS/Lambda',n,[{Name:'FunctionName',Value:product+'-Parity'+runtime}]);if(n==='Invocations'&&!(m.observed>0))r.pending.push(runtime+':Invocations');if(n!=='Invocations'&&m.observed!==null)assert.equal(m.observed,0);r.native.push(m);}
for(const n of ['Count','4xx','5xx']){const m=await metric('AWS/ApiGateway',n,[{Name:'ApiId',Value:'t54b88casf'}]);if(n==='Count'&&!(m.observed>=p.requests.length))r.pending.push('API Count');if(n==='5xx'&&m.observed!==null)assert.equal(m.observed,0);r.native.push(m);}r.complete=!r.pending.length;save('metrics-latest',r);console.log(JSON.stringify({complete:r.complete,pending:r.pending,events:r.logs.reduce((n,x)=>n+x.events.length,0),custom:r.custom.map(x=>({name:x.name,runtime:x.dimensions[1].Value,observed:x.observed,expected:x.expected}))}));
