import test from'node:test';import assert from'node:assert/strict';import{createBuilderProject,restoreBuilderProject,demoImportFindings,exportSummary,DEMO_SOURCE_PLACEHOLDER}from'../overlayBuilderDemoState.js';import{generateSuggestions,applySuggestion}from'../overlayBuilderSuggestions.js';import{recentDemoActivities,routeDemoEvent}from'../overlayBuilderEvents.js';import{overlayThemes,resolveTheme}from'../overlayThemes.js';import{moveFrame,resizeFrame}from'../overlayGeometry.js';import{createHistory}from'../overlayHistory.js'
import{applyGamePreview,gamePreviewDefinitions}from'../gamePreviewDefinitions.js'
test('builder state is deterministic, scene-specific and safely restorable',()=>{const a=createBuilderProject(),b=createBuilderProject();assert.deepEqual(a,b);assert.equal(a.scenes.length,5);assert.equal(restoreBuilderProject('{}').selectedSceneId,'scene-main-gameplay');assert.notEqual(a.scenes[0].widgets,a.scenes[1].widgets)})
test('geometry clamps, resizes and locked state can be enforced by caller',()=>{const bounds={width:1920,height:1080},f={x:0,y:0,width:400,height:200};assert.equal(moveFrame(f,{x:-99,y:-99},bounds).frame.x,0);assert.ok(resizeFrame(f,'se',{x:50,y:50},bounds).width===450)})
test('themes switch through configuration',()=>{assert.equal(Object.keys(overlayThemes).length,3);assert.equal(resolveTheme('neon-cyan').primary,'#22d3ee');assert.equal(resolveTheme('bad').id,'respawn-purple')})
test('suggestions are deterministic, actionable and reversible',()=>{const p=createBuilderProject(),s=p.scenes[1];s.widgets[0].frame.x=0;const list=generateSuggestions(s,s.preview);assert.ok(list.length);const history=createHistory(s);const changed=applySuggestion(s,list.find(x=>x.action));history.commit(changed);assert.deepEqual(history.undo(),s);assert.deepEqual(history.redo(),changed)})
test('activity routing reports enabled and missing widgets',()=>{const p=createBuilderProject();assert.equal(routeDemoEvent(p.scenes[1],recentDemoActivities[0]).ok,true);assert.equal(routeDemoEvent(p.scenes[0],recentDemoActivities[0]).ok,false)})
test('OBS concepts remain unmistakably demonstrations',()=>{assert.equal(demoImportFindings().sceneCount,6);assert.match(exportSummary(createBuilderProject()).status,/No OBS changes/);assert.match(DEMO_SOURCE_PLACEHOLDER,/not-live/)})
test('game previews are local draft assets and preserve editor geometry',()=>{assert.equal(gamePreviewDefinitions.length,4);for(const item of gamePreviewDefinitions){assert.match(item.image,/^\/images\/overlay-previews\//);assert.doesNotMatch(item.image,/^https?:/)}const scene=createBuilderProject().scenes[1],before=structuredClone(scene.widgets);scene.preview=applyGamePreview(scene.preview,'dead-by-daylight');assert.equal(scene.preview.backgroundType,'game-draft');assert.equal(scene.preview.gameName,'Dead by Daylight');assert.deepEqual(scene.widgets,before)})
