import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
export const E='docs/architecture/team-hub-core-integration-evidence-2026-10-07',product='ProjectRespawn-TeamHub-Ntgre',security=product+'-ReadProofSecurity',execution='arn:aws:iam::058264289478:role/'+product+'-ReadProofExecution',caller='arn:aws:iam::058264289478:role/'+product+'-Deploy';
export const read=n=>JSON.parse(fs.readFileSync(`${E}/${n}.json`)),save=(n,v)=>fs.writeFileSync(`${E}/${n}.json`,JSON.stringify(v,null,2)+'\n'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
export function pin(){const c=read('candidate');for(const k of ['product','security'])assert.equal(sha(`${E}/${k}.template.json`),c[k+'Sha256']);assert.equal(sha(c.zipPath),c.zipSha256);assert.equal(sha('config/domains/core/domain-endpoints.Ntgre.json'),c.coreManifestSha256);for(const f of c.sourceHashes)assert.equal(sha(f.path),f.sha256);return c;}
const exec=promisify(execFile);let credentials;
const allowed={sts:['get-caller-identity','assume-role'],accessanalyzer:['validate-policy'],iam:['simulate-custom-policy','simulate-principal-policy','get-role','get-policy','get-policy-version','list-role-policies','get-role-policy','list-attached-role-policies'],cloudformation:['describe-stacks','get-template','list-stack-resources','describe-change-set','describe-stack-events','create-change-set','execute-change-set'],s3api:['put-object','head-object'],lambda:['get-function-configuration','get-policy'],logs:['filter-log-events'],cloudwatch:['get-metric-statistics','describe-alarms']};
export async function aws(service,action,input={},restricted=false){
 allowed.cloudtrail=['lookup-events'];
 assert.ok(allowed[service]?.includes(action),'Out-of-scope AWS action');const c=pin();
 const write=['put-object','create-change-set','execute-change-set'].includes(action);
 if(service==='sts'&&action==='assume-role')assert.equal(input.RoleArn,caller);
 if(write){assert.ok(!fs.existsSync(`${E}/STOP.json`));assert.equal(read('policy-review').complete,true);
  if(service==='cloudformation'){assert.ok([product,security].includes(input.StackName));const k=input.StackName===product?'product':'security';assert.equal(restricted,k==='product');
   if(action==='create-change-set'){assert.equal(input.ChangeSetType,'UPDATE');assert.equal(input.ChangeSetName,`team-hub-core-integration-${k}-20261007${c.attemptSuffix??''}`);if(k==='product'){assert.equal(input.TemplateURL,c.url);assert.equal(input.RoleARN,execution);assert.equal(read('publication').verified,true);}else assert.equal(input.TemplateBody,fs.readFileSync(`${E}/security.template.json`,'utf8'));}
   else {const gate=read(k+'-gate');assert.equal(gate.ready,true);assert.equal(input.ChangeSetName,gate.changeSetId);assert.equal(input.DisableRollback,false);assert.ok(Date.now()-Date.parse(gate.at)<300000);}
  }else{assert.equal(input.Bucket,c.bucket);assert.ok([c.key,c.assetKey].includes(input.Key));assert.equal(input.ServerSideEncryption,'AES256');assert.equal(input.Body,input.Key===c.key?`${E}/product.template.json`:c.zipPath);assert.equal(read('security-installed').verified,true);}
 }
 const env={...process.env,AWS_MAX_ATTEMPTS:'1'};if(restricted){assert.ok(credentials);Object.assign(env,{AWS_ACCESS_KEY_ID:credentials.AccessKeyId,AWS_SECRET_ACCESS_KEY:credentials.SecretAccessKey,AWS_SESSION_TOKEN:credentials.SessionToken});delete env.AWS_PROFILE;delete env.AWS_DEFAULT_PROFILE;}
 fs.mkdirSync('.tmp/team-hub-core-integration',{recursive:true});const requestFile='.tmp/team-hub-core-integration/request-'+crypto.randomUUID()+'.json',request={...input};if(service==='s3api'&&action==='put-object')delete request.Body;fs.writeFileSync(requestFile,JSON.stringify(request));
 try{const {stdout}=await exec('aws',[service,action,'--cli-input-json','file://'+requestFile,...(service==='s3api'&&action==='put-object'?['--body',input.Body]:[]),...(restricted?[]:['--profile','default']),'--region','eu-north-1','--output','json','--no-cli-pager'],{env,windowsHide:true,maxBuffer:32e6});if(write)fs.appendFileSync(`${E}/aws-writes.jsonl`,JSON.stringify({at:new Date().toISOString(),service,action,stack:input.StackName,key:input.Key,restricted})+'\n');return stdout.trim()?JSON.parse(stdout):{};}
 catch(e){const code=(e.stderr??'').match(/\(([^)]+)\)/)?.[1]??e.code??'COMMAND_FAILED';if(write)save('STOP',{at:new Date().toISOString(),service,action,code});throw Error(`${service} ${action}: ${code}`);}finally{fs.unlinkSync(requestFile);}
}
export async function identity(){const r=await aws('sts','get-caller-identity');assert.equal(r.Account,'058264289478');assert.equal(r.Arn,'arn:aws:iam::058264289478:user/RavenTest');return r;}
export async function assume(){const r=await aws('sts','assume-role',{RoleArn:caller,RoleSessionName:'TeamHubCoreIntegration',DurationSeconds:3600});credentials=r.Credentials;return r.AssumedRoleUser.Arn;}
