import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {read,save,pin,E,sha} from './aws.mjs';
const c=pin();assert.equal(read('acceptance').status,'ACCEPTED_DARK_CORE_INTEGRATION');
const status=JSON.parse(fs.readFileSync('docs/architecture/domain-migration-status.json')),team=status.domains.find(x=>x.domain==='Team Hub');assert.equal(team.legacyAuthority,true);assert.equal(team.coreIntegration.authority,'LEGACY_WRITER');assert.equal(team.coreIntegration.stage,'PRE_CUTOVER');assert.equal(team.coreIntegration.normalWritesEnabled,false);assert.equal(team.frontendStatus,'NO_INDEPENDENT_CUTOVER');assert.equal(status.domains.find(x=>x.domain==='Shared/Core').architectureStatus,'INDEPENDENT_CONTRACT_RELEASE_1_ACCEPTED');
const report='docs/architecture/team-hub-2b5a2-live-core-integration.md',docs=[report,'docs/architecture/README-PHASE2-MIGRATION.md'];let links=0;
for(const doc of docs){const text=fs.readFileSync(doc,'utf8');for(const match of text.matchAll(/\]\(([^)]+)\)/g)){let url=match[1];if(/^(https?:|#)/.test(url))continue;url=url.split('#')[0];assert.ok(fs.existsSync(path.resolve(path.dirname(doc),url)),doc+' link '+url);links++;}}
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(f=>f.isDirectory()?files(dir+'/'+f.name):[dir+'/'+f.name]);}
const paths=[...files(E),...files('scripts/team-hub-core-integration'),...files('domains/team-hub/core-integration'),'domains/team-hub/cutover/core-client.mjs','config/domains/team-hub/core-integration.Ntgre.json',report];
const patterns=[/\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/,/eyJ[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/["'](?:SecretAccessKey|SessionToken|refreshToken|password)["']\s*:\s*["'][A-Za-z0-9/+_=!@#$%-]{16,}["']/i];
for(const p of paths){const text=fs.readFileSync(p,'utf8');assert.ok(!patterns.some(pattern=>pattern.test(text)),'Sensitive pattern in '+p);}
const ignore=fs.readFileSync('.gitignore','utf8');for(const item of ['.tmp/','.aws/','.env'])assert.ok(ignore.includes(item));
save('final-check',{at:new Date().toISOString(),accepted:true,linksValidated:links,secretPatternScan:'PASS',scanScope:'Current integration source, scripts, manifest and all current/historical integration evidence',filesScanned:paths.length,pins:'PASS',coreManifestUnchanged:true,authority:'LEGACY_WRITER',normalWritesEnabled:false,ledgerChanges:0,productSha256:c.productSha256,runtimeSha256:c.zipSha256,securitySha256:c.securitySha256});console.log(JSON.stringify({accepted:true,links,filesScanned:paths.length,secretScan:'PASS',authority:'LEGACY_WRITER',normalWritesEnabled:false}));
