import fs from 'node:fs';import assert from 'node:assert/strict';import Ajv from 'ajv';
import {read,save,pin,E,sha} from './aws.mjs';
const c=pin(),proof=read('live-proof'),observation=read('observability'),preservation=read('preservation'),security=read('actual-security');
assert.equal(read('product-installed').verified,true);assert.equal(read('security-installed').verified,true);assert.equal(proof.complete,true);assert.equal(proof.failed,false);assert.ok(proof.checks.every(x=>x.pass));assert.equal(proof.checks.length,29);assert.equal(proof.checks.filter(x=>x.label==='normal-route-denied'&&x.status===403).length,13);assert.equal(observation.complete,true);assert.equal(preservation.complete,true);assert.equal(security.complete,true);
for(const x of observation.observations){assert.equal(x.metrics.Errors,0);assert.equal(x.metrics.Throttles,0);}assert.ok(observation.alarms.every(a=>a.state==='OK'));assert.equal(proof.authority,'LEGACY_WRITER');assert.equal(proof.normalWritesEnabled,false);
const acceptedAt=new Date().toISOString(),manifest={schemaVersion:'team-hub.core-integration.v1',domain:'TeamHub',environment:'Ntgre',account:'058264289478',region:'eu-north-1',status:'ACCEPTED_DARK_INTEGRATION',stack:'ProjectRespawn-TeamHub-Ntgre',apiId:'t54b88casf',authority:'LEGACY_WRITER',stage:'PRE_CUTOVER',normalWritesEnabled:false,normalReadRoutesEnabled:false,frontendCutover:false,coreManifest:'config/domains/core/domain-endpoints.Ntgre.json',coreManifestSha256:c.coreManifestSha256,coreLambdaArn:'arn:aws:lambda:eu-north-1:058264289478:function:ProjectRespawn-Core-Ntgre-Contracts',contractVersions:['environment.v1','authorization.decision.v1','directory.assignment.v1'],runtimeSha256:c.zipSha256,productSha256:c.productSha256,securitySha256:c.securitySha256,acceptedAt,report:'docs/architecture/team-hub-2b5a2-live-core-integration.md',proof:E+'/live-proof.json'};
// Exact release schema: unknown fields and changed endpoint, revisions or authority fail closed.
const schema={$schema:'http://json-schema.org/draft-07/schema#',type:'object',additionalProperties:false,required:Object.keys(manifest),properties:Object.fromEntries(Object.entries(manifest).map(([k,v])=>[k,{const:v}]))};
const validate=new Ajv({strict:true}).compile(schema);assert.ok(validate(manifest));for(const patch of [{authority:'TARGET_WRITER'},{normalWritesEnabled:true},{environment:'Production'},{coreLambdaArn:manifest.coreLambdaArn+':foreign'},{accessToken:'not-a-token'}])assert.equal(validate({...manifest,...patch}),false);
const out='config/domains/team-hub/core-integration.Ntgre.json';fs.writeFileSync(out,JSON.stringify(manifest,null,2)+'\n');save('manifest.schema',schema);save('manifest-validation',{at:acceptedAt,valid:true,positive:1,negative:5,sha256:sha(out)});
const writeOperations=fs.readFileSync(E+'/aws-writes.jsonl','utf8').trim().split('\n').map(JSON.parse);
save('acceptance',{at:acceptedAt,status:'ACCEPTED_DARK_CORE_INTEGRATION',checks:29,normalRouteDenials:13,actualRoleChecks:security.checks.flatMap(x=>x.results).length,manifest:out,productSha256:c.productSha256,runtimeSha256:c.zipSha256,securitySha256:c.securitySha256,authority:'LEGACY_WRITER',stage:'PRE_CUTOVER',normalWritesEnabled:false,frontendCutover:false,resources:{product:40,security:7},awsWriteOperations:writeOperations.length,awsMutationScope:['ProjectRespawn-TeamHub-Ntgre','ProjectRespawn-TeamHub-Ntgre-ReadProofSecurity','exact Team artifact objects'],cognitoMutations:0,coreDeploymentChanges:0,teamBusinessWrites:0,legacyChanges:0,tournamentChanges:0,productionChanges:0,ledgerChanges:0,requiredBlockers:[]});
const statusPath='docs/architecture/domain-migration-status.json',status=JSON.parse(fs.readFileSync(statusPath)),team=status.domains.find(x=>x.domain==='Team Hub');status.scope='Team Hub 2B5A-2 dark Core integration accepted; LEGACY_WRITER / PRE_CUTOVER retained; normal writes disabled';status.currentDomain='Team Hub';status.currentPhase='M5 / 2B5A-2 DARK_CORE_INTEGRATION_ACCEPTED';
team.phase='M5_2B5A2_DARK_CORE_INTEGRATION_ACCEPTED';team.awsStatus='UPDATE_COMPLETE';team.lastVerified=acceptedAt;team.coreIntegration={...team.coreIntegration,status:'ACCEPTED_DARK_CORE_INTEGRATION',liveProof:'PASS_ADMIN_AND_ORDINARY',manifest:out,acceptance:E+'/acceptance.json',runtimeSha256:c.zipSha256,awsWriteOperations:writeOperations.length};team.nextStep='Separately reviewed writer-fence, full frontend integration and rollback-rehearsal gates; preserve LEGACY_WRITER / PRE_CUTOVER until explicit cutover authorization';team.blockers=team.blockers.map(x=>x.includes('Persistent Command/Read synthetic parity verified.')?'Synthetic mutation parity and dark live Core integration accepted. Writer-fence, frontend cutover and rollback-rehearsal dependencies remain unresolved; normal target writes disabled.':x);if(!team.evidence.includes(manifest.report))team.evidence.push(manifest.report);fs.writeFileSync(statusPath,JSON.stringify(status,null,2)+'\n');
const root='docs/architecture/README-PHASE2-MIGRATION.md';let text=fs.readFileSync(root,'utf8');text=text.replace(/<!-- TEAM CORE INTEGRATION START -->[\s\S]*?<!-- TEAM CORE INTEGRATION END -->/,`<!-- TEAM CORE INTEGRATION START -->\n**Current Team Hub Core integration (7 October 2026): ACCEPTED — DARK LIVE CORE INTEGRATION.** Both Team runtimes call the accepted Core contracts; 29 live checks and 32 actual-role checks passed. All 13 deployed normal routes deny. Product/security remain 40+7, UPDATE_COMPLETE. LEGACY_WRITER / PRE_CUTOVER retained; normal writes and frontend cutover disabled. [Integration report](team-hub-2b5a2-live-core-integration.md). Earlier Team entries below are historical.\n<!-- TEAM CORE INTEGRATION END -->`);text=text.replace('TEAM HUB 2B5A-2 — CORE INTEGRATION; separate authorization required |','Team Hub dark integration accepted; writer-fence/frontend/rollback gates remain separate |');fs.writeFileSync(root,text);
const report=`# Team Hub 2B5A-2 — accepted dark Core integration

7 October 2026. **ACCEPTED_DARK_CORE_INTEGRATION.** [Migration control](README-PHASE2-MIGRATION.md). Team Hub now uses the [accepted live Core manifest](../../config/domains/core/domain-endpoints.Ntgre.json) in both deployed runtimes. **LEGACY_WRITER / PRE_CUTOVER is preserved; normal Team Hub reads/writes remain denied and frontend cutover is false.**

## Accepted scope and architecture

Owner: Team Hub, shared-contract integration. Existing independent product/security roots in account 058264289478, eu-north-1, Ntgre. Core owns global authorization and bounded directory contracts; Team retains ownership of membership and resource authorization. Existing Cognito, Core, LegacyPlatform, Tournament and production were not deployed or modified. No new root, API, route, database, index, secret, authority record, frontend import or shared-backend schema.

The [dark entry](../../domains/team-hub/core-integration/entry.mjs) bundles the accepted manifest, validates its environment/revisions and invokes Core using each Team runtime's own AWS role. The [handler](../../domains/team-hub/core-integration/handler.mjs) contains no synthetic grants or business repository. Every API Gateway event returns 403 before delegation. The IAM-only direct proof envelope requires a delegated JWT independently verified by Core; decoded claims alone grant nothing. Directory proof additionally requires a fresh teams.admin grant. Manager-specific business integration remains outside this dark acceptance.

## Deployment and security

Both stacks are UPDATE_COMPLETE with rollback enabled. Product **40 → 40**, security **7 → 7**; all physical resource IDs preserved. Net changes from the starting state are the two Team handlers, their runtime policies/boundaries and exact artifact deployment permissions. No additions, deletions, replacements, nested effects or stateful-resource changes. [Preservation](team-hub-core-integration-evidence-2026-10-07/preservation.json).

Product SHA256: \`${c.productSha256}\`.

Runtime ZIP SHA256: \`${c.zipSha256}\`.

Security SHA256: \`${c.securitySha256}\`.

Runtime identity and boundary allow only owned logging, the existing AWS-managed Lambda encryption path, and the exact Core function's unqualified/$LATEST ARNs. Named versions, other aliases/functions, direct Cognito access and all DynamoDB/business writes remain denied. [32 actual-role checks](team-hub-core-integration-evidence-2026-10-07/actual-security.json). No synthetic verification lease, authority transition, source fence or target write was enabled.

Historical failures are preserved: the initial security update rolled back at IAM's 6,144-character boundary limit; all original policies and runtime hashes were verified restored before correction. Duplicate region conditions and same-scope deny statements were consolidated without permission expansion. The first live Team-to-Core call then failed with InvokeFunction AccessDenied despite unqualified-ARN simulation allow. Safe transport diagnostics established the actual denial; adding only the same function's $LATEST form to both the allow and explicit-deny exceptions resolved it. Core source/runtime/manifest remained unchanged. [Rollback](team-hub-core-integration-evidence-2026-10-07/rollback-verified.json), [size correction](team-hub-core-integration-evidence-2026-10-07/policy-size-correction.json), [qualifier review](team-hub-core-integration-evidence-2026-10-07/latest-arn-review.json), [AWS ARN matching reference](https://docs.aws.amazon.com/lambda/latest/dg/lambda-api-permissions-ref.html). Failed attempts are retained under attempt-1, attempt-2 and attempt-3; they are not accepted candidates.

## Live proof and observability

**29/29 checks passed** using existing Admin/SuperAdmin and ordinary test accounts through normal Amplify sign-in. Both Command and Read runtimes passed admin authorization, exact self-account resolution, bounded/minimized directory search, ordinary teams.admin denial, ordinary directory denial and tampered-JWT rejection. All **13 deployed normal API routes returned 403** using a real admin JWT. No user/group/password changes were made. [Sanitized receipt](team-hub-core-integration-evidence-2026-10-07/live-proof.json).

Acceptance-window metrics: Command 16 invocations, Read 13, Core 26. Errors **0**, throttles **0**, Core dependency failures **0**; 16 Team proof log records and 26 Core application records; all **10 alarms OK**. No tokens, cursor values, private account values or credentials persisted in evidence. These are bounded-window metrics, not all-time totals. [Observability](team-hub-core-integration-evidence-2026-10-07/observability.json).

100 domain/integration tests, 41 resource-accounting tests, the explicit Team offline infrastructure check and Ntgre local-output validation passed. The historical READ_PROOF synth was tooling validation only; the deployed candidate came from the freshly inspected 40+7 templates. No Legacy synthesis or budget refresh. Ledger still reconciles 2,621 Legacy declarations, with no migration/retirement changes.

## Manifest, rollback and next gate

[Accepted dark integration manifest](../../config/domains/team-hub/core-integration.Ntgre.json), [schema validation](team-hub-core-integration-evidence-2026-10-07/manifest-validation.json), [acceptance decision](team-hub-core-integration-evidence-2026-10-07/acceptance.json). The original Team read-proof endpoint manifest remains historical and unchanged; the new integration manifest explicitly disables consumer cutover.

Immediate prior runtime and candidate artifacts are preserved for inspected rollback. Old parity artifact objects remain preserved, but obsolete parity download grants were removed once they were no longer the immediately installed rollback candidate. Returning to the old synthetic implementation would require its matching reviewed security/product pair, not a code-only switch.

Remaining blockers for this dark integration: **NONE**. This does not establish Team business cutover or Manager-specific end-to-end workflows. Next gate: separately reviewed writer-fence, frontend integration and live rollback rehearsal. Current domain: Team Hub. Phase: 2B5A-2 accepted. AWS changes: scoped Team security/product updates and exact artifact objects. Team business writes, Core deployment changes, Legacy changes, Tournament changes, production changes, Cognito mutations and ledger changes: **0**.
`;
fs.writeFileSync(manifest.report,report);console.log(JSON.stringify({accepted:true,checks:proof.checks.length,normalRoutesDenied:13,actualRoleChecks:32,manifest:out,awsWriteOperations:writeOperations.length}));
