import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {initialize,transition,validateControl} from './authority-control.mjs';
import {createWebsiteAdapter} from '../../src/features/team-hub/services/website-adapter.mjs';
import {teamPolicy,coreInvokeResources} from '../team-hub-2b5/security.mjs';
import {metricEvent} from '../../domains/team-hub/cutover/observability.mjs';
const metadata={changedAt:'2026-10-07T00:00:00Z',changedBy:'Ntgre',gateDigest:'a'.repeat(64)};
test('metrics exclude private inputs and count each request once',()=>{const r=metricEvent('command',{event:'TEAM_REQUEST',code:'DEPENDENCY_UNAVAILABLE',accessToken:'PRIVATE_SENTINEL',body:'PRIVATE_SENTINEL',subject:'PRIVATE_SENTINEL'},100);assert.equal(r.Requests,1);assert.equal(r.DependencyFailures,1);assert.ok(!JSON.stringify(r).includes('PRIVATE_SENTINEL'));assert.equal(metricEvent('command',{event:'CORE_DEPENDENCY_FAILED'},100).Requests,0);assert.equal(metricEvent('command',{event:'CORE_DEPENDENCY_FAILED'},100).CoreDependencyFailures,1);});
test('control starts Legacy-only and requires freeze plus exact optimistic epoch/version',()=>{const first=initialize(metadata);assert.equal(first.Item.mode,'LEGACY_WRITER');assert.match(first.ConditionExpression,/attribute_not_exists/);assert.throws(()=>transition(first.Item,'TARGET_WRITER',metadata));const frozen=transition(first.Item,'FROZEN',metadata);assert.equal(frozen.Item.epoch,2);const target=transition(frozen.Item,'TARGET_WRITER',metadata);assert.equal(target.Item.epoch,3);assert.equal(target.ExpressionAttributeValues[':mode'],'FROZEN');});
for(const field of ['changedAt','changedBy','gateDigest','epoch','version'])test('authority rejects missing '+field,()=>{const row=initialize(metadata).Item;delete row[field];assert.throws(()=>validateControl(row));});
test('runtime draft preserves exact accepted Core unqualified and latest resources',()=>{for(const kind of ['Read','Command']){const p=teamPolicy({Version:'2012-10-17',Statement:[]},kind);assert.deepEqual(p.Statement.find(s=>s.Effect==='Allow'&&s.Action==='lambda:InvokeFunction').Resource,coreInvokeResources);assert.deepEqual(p.Statement.find(s=>s.Action==='lambda:*').NotResource,coreInvokeResources);assert.equal(coreInvokeResources.length,2);assert.ok(coreInvokeResources[1].endsWith(':$LATEST'));}});
test('accepted dark NotAction fence is replaced in business candidate, not accidentally retained',()=>{const t=JSON.parse(fs.readFileSync('docs/architecture/team-hub-core-integration-evidence-2026-10-07/product.template.json'));for(const kind of ['Read','Command']){const base=t.Resources['Parity'+kind+'Role'].Properties.Policies[0].PolicyDocument,p=teamPolicy(base,kind);assert.equal(p.Statement.filter(s=>s.NotAction).length,1);assert.ok(p.Statement.find(s=>s.NotAction).NotAction.includes('dynamodb:GetItem'));assert.ok(p.Statement.find(s=>s.NotAction).NotAction.includes('secretsmanager:GetSecretValue'));assert.ok(JSON.stringify(p).length<=6144);}});
const context={team:{id:'team:alpha',slug:'alpha',name:'Alpha',version:3,authorizationEpoch:4,rosterVersion:2,settings:{plan:'FREE',logoAssetId:''}},memberships:[{id:'manager-id',subject:'manager',role:'MANAGER',status:'ACTIVE',version:5}],roster:[],capabilities:{teamsAdmin:false,brandingManage:false}};
test('website uses Core capability, Team membership and native concurrency without Legacy requests',async()=>{let subject='manager';const calls=[];const client={async call(op,input){calls.push({op,input});if(op==='GET_TEAM_HUB')return structuredClone(context);return {team:{...context.team,version:4}};}};const a=createWebsiteAdapter({client,identity:async()=>({subject}),newKey:()=> 'test-idempotency'});const r=await a.getTeamHub({teamSlug:'alpha'});assert.equal(r.isPlatformAdmin,false);assert.equal(r.capabilities.canManageMembers,true);assert.equal(r.capabilities.canManageBranding,false);await a.updateTeam({teamId:'team:alpha',name:'Next',status:'ACTIVE'});assert.equal(calls.at(-1).input.expectedTeamVersion,3);assert.equal(calls.at(-1).input.expectedMembershipVersion,5);subject='outsider';await assert.rejects(a.updateTeam({teamId:'team:alpha',name:'Denied',status:'ACTIVE'}),/refresh/);});
test('directory never invents email from minimized Core results; missing Team fails',async()=>{const a=createWebsiteAdapter({client:{call:async()=>({items:[{subject:'safe',displayName:'Name'}]})},identity:async()=>({subject:'manager'})});await assert.rejects(async()=>a.searchAssignableUsers('na'),/Select a Team/);const r=await a.searchAssignableUsers('na','team:alpha');assert.equal(r.items[0].email,undefined);});
test('branding and unsupported plan expiry fail closed',async()=>{const a=createWebsiteAdapter({client:{call:()=>assert.fail('Network must not run')},identity:async()=>({subject:'manager'})});await assert.rejects(a.requestTeamLogoUpload(),/disabled/);await assert.rejects(a.setTeamPlan('team:alpha',{plan:'PRO',expiresAt:'2030-01-01'}),/unavailable/);});
test('shared route groups contain no eager Vue page imports',()=>{for(const p of ['src/router/admin.routes.js','src/router/public.routes.js','src/router/forum.routes.js'])assert.doesNotMatch(fs.readFileSync(p,'utf8'),/^import .*\.vue['"];?$/m);assert.doesNotMatch(fs.readFileSync('src/router/index.js','utf8'),/^import .*teamHub\.service/m);});

test('Coach assessment capability matches the Vue consumer and excludes other roles',async()=>{for(const role of ['COACH','MANAGER','PLAYER']){const c=structuredClone(context);c.memberships=[{id:'role-id',subject:'actor',role,status:'ACTIVE',version:1}];const adapter=createWebsiteAdapter({client:{call:async()=>c},identity:async()=>({subject:'actor'})});const result=await adapter.getTeamHub({teamSlug:'alpha'});assert.equal(result.capabilities.canEditCoachAssessments,role==='COACH');assert.equal(result.capabilities.canEditCoachAssessment,undefined);}assert.match(fs.readFileSync('src/features/Team Hub/champion-pool/CoachPoolReview.vue','utf8'),/capabilities\?\.canEditCoachAssessments/);});
