import assert from 'node:assert/strict';import fs from 'node:fs';
import {execFileSync} from 'node:child_process';import {CloudFormationClient,DescribeStacksCommand} from '@aws-sdk/client-cloudformation';import {LambdaClient,GetFunctionConfigurationCommand} from '@aws-sdk/client-lambda';import {fromIni} from '@aws-sdk/credential-providers';
import {read,pin,identity} from '../core-live/aws.mjs';
const E='docs/architecture/core-acceptance-evidence-2026-10-06';await identity();const c=pin(),receipt=read(E+'/ordinary-receipt.json');assert.ok(receipt.complete&&!receipt.failed);const config={region:'eu-north-1',credentials:fromIni({profile:'default'}),maxAttempts:1},cfn=new CloudFormationClient(config),lambda=new LambdaClient(config),FunctionName='ProjectRespawn-Core-Ntgre-Contracts';
const start=Date.parse(receipt.checks[0].began),end=Date.now(),events=[];let nextToken;
do{const page=await aws('logs','filter-log-events',{logGroupName:'/project-respawn/Ntgre/core/contracts',startTime:start,...(nextToken?{nextToken}:{})});for(const e of page.events??[]){let raw=JSON.parse(e.message);if(raw.type==='platform.initStart'&&/^arn:aws:lambda:eu-north-1::runtime:[a-f0-9]{64}$/.test(raw.record?.runtimeVersionArn??''))raw.record.runtimeVersionArn='AWS_RUNTIME_VERSION_IDENTIFIER';const text=JSON.stringify(raw);assert.ok(!/\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\b|"(?:SecretString|accessToken|password)"\s*:|\b[a-f0-9]{64}\b/.test(text),'Sensitive log pattern: do not persist values');let app=raw.message;try{if(typeof app==='string')app=JSON.parse(app);}catch{}if(raw.Environment==='Ntgre')app=raw;if(app?.outcome)events.push({timestamp:e.timestamp,type:'application',requestId:app.requestId,contractVersion:app.contractVersion,outcome:app.outcome,dependencyFailures:app.DependencyFailures,durationMs:app.durationMs});else events.push({timestamp:e.timestamp,type:raw.type,requestId:raw.record?.requestId,status:raw.record?.status});}nextToken=page.nextToken;}while(nextToken);
const metrics={};for(const name of ['Invocations','Errors','Throttles','Duration'])metrics[name]=(await aws('cloudwatch','get-metric-statistics',{Namespace:'AWS/Lambda',MetricName:name,Dimensions:[{Name:'FunctionName',Value:FunctionName}],StartTime:new Date(Math.floor(start/60000)*60000),EndTime:new Date(end),Period:60,Statistics:[name==='Duration'?'Average':'Sum']})).Datapoints;
const sum=n=>metrics[n].reduce((a,b)=>a+(b.Sum??0),0),application=events.filter(x=>x.type==='application');assert.equal(sum('Errors'),0);assert.equal(sum('Throttles'),0);assert.ok(application.every(x=>x.dependencyFailures===0));
const alarms=(await aws('cloudwatch','describe-alarms',{AlarmNamePrefix:'ProjectRespawn-Core-Ntgre-'})).MetricAlarms.map(a=>({name:a.AlarmName,state:a.StateValue,metric:a.MetricName}));assert.equal(alarms.length,4);assert.ok(alarms.every(a=>a.state==='OK'));
const states=[];for(const StackName of ['ProjectRespawn-Core-Ntgre','ProjectRespawn-Core-Ntgre-Security']){const s=(await cfn.send(new DescribeStacksCommand({StackName}))).Stacks[0];assert.equal(s.StackStatus,'CREATE_COMPLETE');states.push({name:StackName,status:s.StackStatus,arn:s.StackId});}
const f=await lambda.send(new GetFunctionConfigurationCommand({FunctionName}));assert.equal(f.State,'Active');assert.equal(f.CodeSha256,Buffer.from(c.zipSha256,'hex').toString('base64'));
const complete=sum('Invocations')>=receipt.checks.length&&application.length>=receipt.checks.length&&metrics.Duration.length>0;
const result={at:new Date().toISOString(),window:{start:new Date(start).toISOString(),end:new Date(end).toISOString()},complete,expectedAcceptanceInvocations:receipt.checks.length,invocations:sum('Invocations'),errors:sum('Errors'),throttles:sum('Throttles'),dependencyFailures:0,logsPresent:application.length>0,applicationLogCount:application.length,events,metrics,alarms,states,runtime:'Active',runtimeHashVerified:true,secretScan:'PASS',infrastructureWrites:0};fs.writeFileSync(E+'/observability.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({complete,expected:receipt.checks.length,invocations:result.invocations,applicationLogs:application.length,errors:0,throttles:0,alarms:alarms.map(x=>x.state)}));

function aws(service,action,input){assert.ok(({logs:['filter-log-events'],cloudwatch:['get-metric-statistics','describe-alarms']})[service]?.includes(action));return JSON.parse(execFileSync('aws',[service,action,'--cli-input-json',JSON.stringify(input),'--profile','default','--region','eu-north-1','--output','json','--no-cli-pager'],{encoding:'utf8',windowsHide:true,maxBuffer:12e6}));}
