import {sessionInput} from './session-input.mjs';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import net from 'node:net';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
import {Amplify} from 'aws-amplify';import {signIn,fetchAuthSession,signOut} from 'aws-amplify/auth';import {cognitoUserPoolsTokenProvider} from 'aws-amplify/auth/cognito';
import {LambdaClient,InvokeCommand,GetFunctionConfigurationCommand,GetFunctionConcurrencyCommand} from '@aws-sdk/client-lambda';import {CognitoIdentityProviderClient,AdminGetUserCommand,AdminListGroupsForUserCommand,ListUsersCommand} from '@aws-sdk/client-cognito-identity-provider';import {CloudFormationClient,DescribeStacksCommand} from '@aws-sdk/client-cloudformation';import {fromIni} from '@aws-sdk/credential-providers';
import {pin,read,identity,sha,E as prior} from '../core-live/aws.mjs';
const E='docs/architecture/core-acceptance-evidence-2026-10-06',save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const candidate=pin();await identity();const priorLive=read(prior+'/live-contracts.json');assert.ok(priorLive.personas.includes('admin')&&!priorLive.failed);assert.ok(priorLive.checks.filter(x=>x.label.startsWith('admin-')&&x.liveTested!==false).every(x=>x.pass));
const preservation=fs.readdirSync(prior,{withFileTypes:true}).filter(x=>x.isFile()).map(x=>({path:prior+'/'+x.name,sha256:sha(prior+'/'+x.name)}));for(const f of preservation)if(f.path.endsWith('.json'))JSON.parse(fs.readFileSync(f.path));save('prior-evidence-preservation',{at:new Date().toISOString(),files:preservation,adminAccepted:true,expensiveChecksReused:true});
const credentials=fromIni({profile:'default'}),options={region:'eu-north-1',credentials,maxAttempts:1},lambda=new LambdaClient(options),cognito=new CognitoIdentityProviderClient(options),cfn=new CloudFormationClient(options),environment=read('config/environments/Ntgre.core.json');
const states=[];for(const StackName of ['ProjectRespawn-Core-Ntgre','ProjectRespawn-Core-Ntgre-Security']){const s=(await cfn.send(new DescribeStacksCommand({StackName}))).Stacks[0];assert.equal(s.StackStatus,'CREATE_COMPLETE');states.push({name:s.StackName,arn:s.StackId,status:s.StackStatus});}
const FunctionName='ProjectRespawn-Core-Ntgre-Contracts',f=await lambda.send(new GetFunctionConfigurationCommand({FunctionName})),concurrency=await lambda.send(new GetFunctionConcurrencyCommand({FunctionName}));assert.equal(f.State,'Active');assert.equal(f.CodeSha256,Buffer.from(candidate.zipSha256,'hex').toString('base64'));assert.ok(!Object.hasOwn(concurrency,'ReservedConcurrentExecutions'));save('health-before',{at:new Date().toISOString(),states,function:FunctionName,state:f.State,codeSha256:f.CodeSha256,reservedConcurrency:'NONE',infrastructureWrites:0});
const memory=new Map();Amplify.configure({Auth:{Cognito:{userPoolId:environment.poolId,userPoolClientId:environment.clientId}}});cognitoUserPoolsTokenProvider.setKeyValueStorage({async setItem(k,v){memory.set(k,v)},async getItem(k){return memory.get(k)??null},async removeItem(k){memory.delete(k)},async clear(){memory.clear()}});
const checks=[],receipt={started:new Date().toISOString(),environment:'Ntgre',identityClassification:'ORDINARY',checks,complete:false,failed:false,optional:{crossActor:'NOT_REQUIRED_FOR_RELEASE_1',disabledAccount:'UNTESTED_LIVE_WITH_OFFLINE_COVERAGE'},tokensPersisted:false,cursorsPersisted:false,personalValuesPersisted:false,secretRetrieved:false,cognitoMutations:0,teamWrites:0,legacyWrites:0,tournamentChanges:0,productionChanges:0,infrastructureWrites:0};
const record=()=>save('ordinary-receipt',{...receipt,at:new Date().toISOString()});let password='',token='',cursor;
async function invoke(label,input,verify){const began=new Date().toISOString();let response;try{response=await lambda.send(new InvokeCommand({FunctionName,InvocationType:'RequestResponse',Payload:Buffer.from(JSON.stringify(input))}));const data=JSON.parse(Buffer.from(response.Payload).toString());assert.equal(response.StatusCode,200);assert.ok(!response.FunctionError);const summary=verify(data)??{};checks.push({at:new Date().toISOString(),began,label,contractVersion:input.contractVersion,pass:true,invokeRequestId:response.$metadata.requestId,outcome:data.ok?(data.data.allowed===false?'DENY':'SUCCESS'):data.error.code,...summary});record();return data.data;}catch(error){receipt.failed=true;checks.push({at:new Date().toISOString(),label,pass:false,invokeRequestId:response?.$metadata.requestId,errorName:error.name,errorCode:error.code??null});record();throw new Error('CONTRACT_CHECK_FAILED: '+label);}}
const reject=code=>r=>{assert.equal(r.ok,false);assert.deepEqual(r.error,{code});return{expected:code,actual:r.error.code};};
function item(x){assert.deepEqual(Object.keys(x).sort(),['displayName','subject']);assert.equal(typeof x.subject,'string');assert.ok(typeof x.displayName==='string'&&x.displayName.length<=100);}
function page(r){assert.equal(r.ok,true);assert.equal(r.data.contractVersion,'directory.assignment.v1');assert.ok(r.data.items.length<=1);r.data.items.forEach(item);assert.ok(Object.keys(r.data).every(k=>['contractVersion','items','nextToken'].includes(k)));return{itemCount:r.data.items.length,fields:['subject','displayName'],minimized:true};}
try{
 password=await sessionInput();let claims;
 if(password.startsWith('@TOKEN@')){token=password.slice(7);password='';claims=JSON.parse(Buffer.from(token.split('.')[1],'base64url'));receipt.authentication='EXISTING_BROWSER_SESSION_NORMAL_AMPLIFY';}
 else {const signed=await signIn({username:'member@respawntest.test',password});password='';assert.ok(signed.isSignedIn,'Existing account requires another authentication step');const session=await fetchAuthSession();token=session.tokens.accessToken.toString();claims=session.tokens.accessToken.payload;receipt.authentication='NORMAL_AMPLIFY_LOCAL_MASKED_INPUT';}
 assert.equal(claims.iss,environment.issuer);assert.equal(claims.client_id,environment.clientId);assert.equal(claims.token_use,'access');assert.ok(claims.exp*1000>Date.now());
 const user=await cognito.send(new AdminGetUserCommand({UserPoolId:environment.poolId,Username:claims.sub}));assert.ok(user.Enabled&&user.UserStatus==='CONFIRMED');const groups=(await cognito.send(new AdminListGroupsForUserCommand({UserPoolId:environment.poolId,Username:user.Username}))).Groups.map(g=>g.GroupName);assert.ok(!groups.some(g=>['Admin','SuperAdmin'].includes(g)));receipt.identityReferenceSha256=crypto.createHash('sha256').update(environment.poolId+':'+claims.sub).digest('hex');receipt.identityChecks={enabled:true,confirmed:true,admin:false,superAdmin:false};record();console.log('Ordinary identity authenticated and classified; running Core-only checks.');
 const auth={contractVersion:'authorization.decision.v1',environment:'Ntgre',accessToken:token,capability:'teams.admin'};
 for(const capability of ['teams.admin','teams.branding.manage'])await invoke(capability,{...auth,capability},r=>{assert.equal(r.ok,true);assert.equal(r.data.allowed,false);assert.equal(r.data.environment,'Ntgre');assert.equal(r.data.subject,claims.sub);assert.equal(r.data.capability,capability);assert.ok(r.data.expiresAt-r.data.evaluatedAt<=5);return{allowed:false,bounded:true};});
 await invoke('unknown-capability',{...auth,capability:'unapproved.capability'},reject('INVALID_INPUT'));await invoke('authorization-wrong-environment',{...auth,environment:'Production'},reject('WRONG_ENVIRONMENT'));
 const attrs=u=>Object.fromEntries((u.UserAttributes??u.Attributes??[]).map(x=>[x.Name,x.Value]));let users=[],PaginationToken;do{const p=await cognito.send(new ListUsersCommand({UserPoolId:environment.poolId,Limit:60,...(PaginationToken?{PaginationToken}:{})}));users.push(...p.Users);PaginationToken=p.PaginationToken;assert.ok(users.length<=1000);}while(PaginationToken);
 const prefixes=new Map();for(const u of users.filter(u=>u.Enabled&&u.UserStatus==='CONFIRMED')){const email=attrs(u).email?.toLowerCase();if(email&&/^[a-z0-9@._+-]{2}/.test(email)){const q=email.slice(0,2);prefixes.set(q,(prefixes.get(q)??0)+1);}}const query=[...prefixes].find(([,n])=>n>=2)?.[0];assert.ok(query,'Existing pagination fixture required');
 const directory={contractVersion:'directory.assignment.v1',environment:'Ntgre',accessToken:token,action:'search',teamId:'team:core-acceptance',query,limit:1};
 await invoke('exact-resolution',{contractVersion:directory.contractVersion,environment:'Ntgre',accessToken:token,action:'resolve',teamId:directory.teamId,account:attrs(user).email},r=>{assert.equal(r.ok,true);assert.equal(r.data.subject,claims.sub);assert.deepEqual(Object.keys(r.data).sort(),['contractVersion','displayName','subject']);item({subject:r.data.subject,displayName:r.data.displayName});return{exactMatch:true,fields:['contractVersion','subject','displayName'],minimized:true};});
 const first=await invoke('bounded-search',directory,page);assert.ok(first.nextToken,'Existing fixture must provide pagination');cursor=first.nextToken;const cursorIssuedAt=Date.now();
 await invoke('valid-cursor-pagination',{...directory,nextToken:cursor},page);
 await invoke('query-minimum',{...directory,query:'a'},reject('INVALID_INPUT'));await invoke('result-maximum',{...directory,limit:11},reject('INVALID_INPUT'));await invoke('directory-wrong-environment',{...directory,environment:'Production'},reject('WRONG_ENVIRONMENT'));
 await invoke('unauthorized-search-missing-token',{...directory,accessToken:''},reject('UNAUTHENTICATED'));await invoke('unauthorized-search-invalid-token',{...directory,accessToken:'invalid-verification-token'},reject('UNAUTHENTICATED'));
 const altered=Buffer.from(cursor,'base64url');altered[30]^=1;await invoke('tampered-cursor',{...directory,nextToken:altered.toString('base64url')},reject('INVALID_INPUT'));await invoke('cursor-wrong-environment',{...directory,nextToken:cursor,environment:'Production'},reject('WRONG_ENVIRONMENT'));await invoke('cursor-wrong-contract',{...auth,nextToken:cursor},reject('INVALID_INPUT'));await invoke('cursor-wrong-team',{...directory,nextToken:cursor,teamId:'team:another'},reject('INVALID_INPUT'));await invoke('cursor-wrong-context',{...directory,nextToken:cursor,limit:2},reject('INVALID_INPUT'));await invoke('invalid-cursor',{...directory,nextToken:'invalid-cursor'},reject('INVALID_INPUT'));
 const disabled=users.find(u=>!u.Enabled&&attrs(u).email);if(disabled){await invoke('existing-disabled-account',{contractVersion:directory.contractVersion,environment:'Ntgre',accessToken:token,action:'resolve',teamId:directory.teamId,account:attrs(disabled).email},r=>{assert.equal(r.ok,false);assert.ok(['NOT_FOUND','FORBIDDEN'].includes(r.error.code));return{rejected:true};});receipt.optional.disabledAccount='PASS_EXISTING_SAFE_FIXTURE';}users=[];
 receipt.phase='WAITING_FOR_CURSOR_EXPIRY';record();console.log(JSON.stringify({passed:checks.length,phase:receipt.phase,expiryTestDue:new Date(cursorIssuedAt+305000).toISOString()}));await new Promise(resolve=>setTimeout(resolve,Math.max(0,cursorIssuedAt+305000-Date.now())));
 await invoke('expired-cursor',{...directory,nextToken:cursor},reject('INVALID_INPUT'));cursor=undefined;token='';receipt.complete=true;receipt.phase='COMPLETE';record();console.log(JSON.stringify({ordinaryAccepted:true,checks:checks.length,optional:receipt.optional}));
}catch(error){password='';token='';cursor=undefined;receipt.failed=true;receipt.failure={name:error.name,code:error.code??null,phase:receipt.phase??'AUTHENTICATION_OR_TEST',message:error.message.startsWith('CONTRACT_CHECK_FAILED:')?error.message:undefined};record();console.log(JSON.stringify({ordinaryAccepted:false,checks:checks.length,errorName:error.name,errorCode:error.code??null,stop:true}));process.exitCode=1;}finally{try{await signOut();}catch{}memory.clear();password='';token='';cursor=undefined;}
