import crypto from 'node:crypto';import path from 'node:path';import net from 'node:net';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createServer} from 'vite';
export async function sessionInput(){
 if(process.argv.includes('--private-stdin')){
  assert.ok(process.stdin.isTTY,'Private terminal required');process.stdin.setRawMode(true);process.stdin.resume();console.log('Private non-echo input ready.');
  try{return await new Promise((resolve,reject)=>{let value='';const listener=b=>{for(const ch of b.toString()){if(ch==='\u0003'){process.stdin.off('data',listener);reject(new Error('LOCAL_SIGN_IN_CANCELLED'));return;}if(ch==='\r'||ch==='\n'){process.stdin.off('data',listener);resolve(value);value='';return;}value+=ch;}};process.stdin.on('data',listener);});}finally{process.stdin.setRawMode(false);process.stdin.pause();}
 }
 const nonce=crypto.randomBytes(24).toString('hex'),route='/__core-ordinary-'+nonce;
 const vite=await createServer({cacheDir:'.tmp/core-acceptance-vite',server:{host:'localhost',port:5176,strictPort:true,open:false}});
 let resolveInput,rejectInput,submitted=false,prompt,timer;const result=new Promise((resolve,reject)=>{resolveInput=resolve;rejectInput=reject;});
 function accept(value){if(submitted)return;submitted=true;clearTimeout(timer);resolveInput(value);}
 const pipe=net.createServer(socket=>{let value='';socket.on('data',b=>{value+=b.toString();if(value.length>1024)socket.destroy();});socket.on('end',()=>{if(value.startsWith(nonce+'\n'))accept(value.slice(nonce.length+1));value='';});socket.on('error',()=>{});});
 await new Promise((resolve,reject)=>{pipe.once('error',reject);pipe.listen(49184,'127.0.0.1',resolve);});
 vite.middlewares.stack.unshift({route:'',handle:async(req,res,next)=>{if(req.url!==route&&req.url!==route+'/capture')return next();res.setHeader('Cache-Control','no-store');try{assert.equal(req.headers.host,'localhost:5176');if(req.method==='GET'&&req.url===route){res.setHeader('Content-Type','text/html');res.end(await vite.transformIndexHtml(route,`<!doctype html><title>Core ordinary-user acceptance</title><h1>Core ordinary-user acceptance</h1><p id="status">Checking the existing Ntgre localhost session automatically...</p><script type="module">import {Amplify} from 'aws-amplify';import {fetchAuthSession} from 'aws-amplify/auth';import outputs from '/amplify_outputs.json';Amplify.configure(outputs);try{const s=await fetchAuthSession();const t=s.tokens?.accessToken;const g=t?.payload['cognito:groups']??[];if(!t||g.some(x=>['Admin','SuperAdmin'].includes(x))){document.querySelector('#status').textContent='No existing ordinary session found. Use the separate masked Windows sign-in prompt.';}else{const r=await fetch('${route}/capture',{method:'POST',headers:{Origin:location.origin,Authorization:'Bearer '+t.toString(),'Content-Type':'application/json'},body:'{}'});document.querySelector('#status').textContent=r.ok?'Existing ordinary session received. Automated checks are running; this page can be closed.':'Session could not be accepted. Use the masked Windows prompt.';}}catch{document.querySelector('#status').textContent='No reusable session available. Use the separate masked Windows sign-in prompt.';}</script>`));return;}assert.equal(req.method,'POST');assert.equal(req.headers.origin,'http://localhost:5176');const token=req.headers.authorization?.replace(/^Bearer /,'');assert.ok(token&&token.length<16000);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({received:true,credentialsRecorded:false}));accept('@TOKEN@'+token);}catch{res.statusCode=400;res.end('Session not accepted.');}}});
 await vite.listen();console.log('Attempting normal Amplify session reuse on localhost:5176.');
 spawn('cmd.exe',['/c','start','','http://localhost:5176'+route],{windowsHide:true,stdio:'ignore'});
 timer=setTimeout(()=>{if(submitted)return;prompt=spawn('powershell.exe',['-NoProfile','-ExecutionPolicy','Bypass','-File',path.resolve('scripts/core-acceptance/password-prompt.ps1'),'-Nonce',nonce,'-Port','49184'],{windowsHide:false,stdio:'ignore'});prompt.on('exit',()=>{setTimeout(()=>{if(!submitted)rejectInput(new Error('LOCAL_SIGN_IN_CANCELLED'));},100);});console.log('Fallback masked Windows prompt opened for the existing ordinary account.');},20000);
 try{return await result;}finally{clearTimeout(timer);pipe.close();if(prompt)prompt.kill();await vite.close();}
}
