import {waitForIssueTime} from './core-timing.mjs';
// Local-only application acceptance harness. No DynamoDB client, deployment API,
// credentials endpoint, stored JWT, or connection to actual Team business state.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {build,preview} from 'vite';
import {LambdaClient,InvokeCommand} from '@aws-sdk/client-lambda';import {fromIni} from '@aws-sdk/credential-providers';
import {identity} from '../team-hub-2b4b/preflight/common.mjs';import {acceptedCore} from '../../domains/team-hub/core-integration/manifest.mjs';import {createCutoverHandler} from '../../domains/team-hub/cutover/handler.mjs';import {operations} from '../../domains/team-hub/cutover/contracts.mjs';import {TransactionEmulator} from '../team-hub-2b4/tests/transport.mjs';import {nativeFixture} from './browser-fixture.mjs';
await identity();const syntheticRoles=process.argv.includes('--isolated-personas-approved');assert.ok(syntheticRoles||process.argv.includes('--existing-accounts'),'Select explicit local acceptance mode');
const base='/__team-hub-2b6-'+crypto.randomBytes(16).toString('hex'),E='docs/architecture/team-hub-2b6-evidence-2026-10-07',sessions=new Map(),checks=[];
const lambda=new LambdaClient({region:'eu-north-1',credentials:fromIni({profile:'default'}),maxAttempts:1});
async function invokeCore(request){const r=await lambda.send(new InvokeCommand({FunctionName:acceptedCore.lambdaArn,InvocationType:'RequestResponse',Payload:Buffer.from(JSON.stringify(request))}));if(r.FunctionError)throw Error('CORE_UNAVAILABLE');const result=JSON.parse(Buffer.from(r.Payload).toString()); if(request.contractVersion==='authorization.decision.v1'&&result.ok){const d=result.data,now=Math.floor(Date.now()/1000);fs.appendFileSync(E+'/core-timing.jsonl',JSON.stringify({at:new Date().toISOString(),evaluatedAt:d.evaluatedAt,expiresAt:d.expiresAt,observedAt:now,ttl:d.expiresAt-d.evaluatedAt,future:d.evaluatedAt>now,expired:d.expiresAt<=now})+'\n');} return waitForIssueTime(result);}
const journal='ProjectRespawn-TeamHub-Ntgre-Journal',operational='ProjectRespawn-TeamHub-Ntgre-Operational';
class LocalTransport extends TransactionEmulator{
 async query(p){if(p.IndexName){const rows=[...this.rows.values()].filter(r=>p.IndexName==='ByTeamStatus'?r.StatusPK===p.ExpressionAttributeValues[':pk']:r.SubjectPK===p.ExpressionAttributeValues[':pk']);return {Items:structuredClone(rows)};}return super.query(p);}
 async transactWrite(p){const c=p.TransactItems[0].ConditionCheck,row=this.rows.get(this.key(journal,c.Key)),v=c.ExpressionAttributeValues;if(row?.mode!==v[':mode']||row?.epoch!==v[':epoch']||row?.version!==v[':version']){const e=Error('conflict');e.name='TransactionCanceledException';throw e;}return super.transactWrite({...p,TransactItems:p.TransactItems.slice(1)});}
}
function transport(subject,persona,run='baseline'){assert.ok(run==='baseline'||/^[a-f0-9]{32}$/.test(run));const key=crypto.createHash('sha256').update(subject+'|'+persona+'|'+run).digest('hex');if(sessions.has(key))return sessions.get(key);const t=new LocalTransport();let rows=nativeFixture();const i=['manager','coach','player'].indexOf(persona);if(i>=0){const old='00000000-0000-4000-8000-'+String(i+1).padStart(12,'0');rows=JSON.parse(JSON.stringify(rows).replaceAll(old,subject));}for(const row of rows)t.rows.set(t.key(operational,row),row);const control={PK:'CONTROL#AUTHORITY',SK:'STATE',schemaVersion:'team-hub-authority.v1',mode:'TARGET_WRITER',epoch:2,version:2,changedAt:new Date().toISOString(),changedBy:'LOCAL_SYNTHETIC_FIXTURE',gateDigest:'a'.repeat(64)};t.rows.set(t.key(journal,control),control);sessions.set(key,t);return t;}
const plugin={name:'team-hub-isolated-browser',enforce:'pre',resolveId(source){if((source.endsWith('teamHub.service.js')||source.endsWith('migration-mode.mjs')))return path.resolve('scripts/team-hub-2b6/browser-service.mjs').replaceAll('\\','/');},transform(code,id){id=id.replaceAll('\\','/');if(id.endsWith('/scripts/team-hub-2b6/browser-service.mjs'))return code.replace('!import.meta.env.DEV||','');if(id.endsWith('/src/router/admin.routes.js'))return code.replace("meta: { requiredPermission: 'teams.branding.manage' }","meta: { requiresAuth: true }");},transformIndexHtml:{order:"pre",handler(){return [{tag:'div',attrs:{id:'team-rehearsal-panel',style:'position:fixed;bottom:0;left:0;right:0;z-index:99999;background:#172333;color:white;padding:8px'},children:'Isolated Team test — live writes disabled. <select id="rehearsal-persona"><option value="ordinary">Ordinary</option><option value="admin">Admin</option><option value="manager">Manager (isolated)</option><option value="coach">Coach (isolated)</option><option value="player">Player (isolated)</option></select> <a style="color:white" href="/team-hub">Team Hub</a> · <a style="color:white" href="/team-hub/native-alpha">Synthetic Team</a> · <a style="color:white" href="/dashboard/esports/teams">Admin</a>',injectTo:'body'},{tag:'script',attrs:{type:'module'},children:"import '/scripts/team-hub-2b6/browser-checks.mjs';const s=document.querySelector('#rehearsal-persona');s.value=sessionStorage.getItem('team-hub-rehearsal-persona')||'ordinary';s.onchange=()=>{sessionStorage.setItem('team-hub-rehearsal-persona',s.value);location.href='/team-hub';};",injectTo:'body'}];}},configureServer(server){server.middlewares.use(async(req,res,next)=>{if(!req.url.startsWith(base+'/'))return next();res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');try{assert.equal(req.headers.host,'localhost:5177');if(req.headers.origin)assert.equal(req.headers.origin,'http://localhost:5177');const token=req.headers.authorization?.replace(/^Bearer /i,'');assert.ok(token&&token.length<16000);const decision=await invokeCore({environment:'Ntgre',accessToken:token,contractVersion:'authorization.decision.v1',capability:'teams.admin'});assert.equal(decision.ok,true);const claims=JSON.parse(Buffer.from(token.split('.')[1],'base64url'));assert.equal(decision.data.subject,claims.sub);const persona=req.headers['x-rehearsal-persona']??'ordinary';assert.ok((syntheticRoles?['admin','ordinary','manager','coach','player']:['admin','ordinary']).includes(persona));if(persona==='admin')assert.equal(decision.data.allowed,true);else assert.equal(decision.data.allowed,false,'Use a non-admin account for Team role fixtures');
 if(req.url===base+'/__receipt'&&req.method==='POST'){let body='';for await(const chunk of req){body+=chunk;if(body.length>16384)throw Error('BODY_TOO_LARGE');}const input=JSON.parse(body);assert.equal(input.persona,persona);assert.ok(Array.isArray(input.checks)&&input.checks.length<=30);const receipt={at:new Date().toISOString(),persona,passed:input.passed===true,checks:input.checks.map(c=>({name:String(c.name).replace(/[^A-Z_0-9 -]/gi,'').slice(0,80),passed:c.passed===true})),scope:'BROWSER_CONTRACT_CHECKS_LIVE_CORE_ISOLATED_TEAM',uiAcceptance:'PENDING',tokensStored:false};fs.writeFileSync(E+'/browser-'+persona+'.json',JSON.stringify(receipt,null,2)+'\n');res.statusCode=200;res.end(JSON.stringify({saved:true}));return;}
 const url=new URL(req.url.slice(base.length),'http://localhost:5177');let op,pathParameters;for(const [name,spec]of Object.entries(operations)){if(spec.method!==req.method)continue;const keys=[];const pattern=spec.path.replace(/\{([^}]+)\}/g,(_,key)=>{keys.push(key);return '([^/]+)';});const match=url.pathname.match(new RegExp('^'+pattern+'$'));if(match){op=name;pathParameters=Object.fromEntries(keys.map((k,i)=>[k,decodeURIComponent(match[i+1])]));break;}}assert.ok(op);let body='';for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>16384)throw Error('BODY_TOO_LARGE');}
 const handler=createCutoverHandler({runtime:operations[op].runtime,transport:transport(claims.sub,persona,req.headers['x-rehearsal-run']),invokeCore,environment:acceptedCore.environmentContract,cursorSecret:cursor});const response=await handler({routeKey:operations[op].method+' '+operations[op].path,pathParameters,queryStringParameters:Object.fromEntries(url.searchParams),body,headers:{authorization:'Bearer '+token,'x-team-authority-epoch':req.headers['x-team-authority-epoch']},requestContext:{requestId:crypto.randomUUID(),authorizer:{jwt:{claims}}}});checks.push({at:new Date().toISOString(),persona,operation:op,status:response.statusCode});fs.writeFileSync(E+'/browser-requests.json',JSON.stringify({scope:'ACTUAL_WEBSITE_LOCAL_SYNTHETIC_BUSINESS_LIVE_CORE',checks,tokensStored:false,actualBusinessWrites:0},null,2)+'\n');res.statusCode=response.statusCode;res.end(response.body);
 }catch(e){res.statusCode=403;res.end(JSON.stringify({contractVersion:'team-hub.v1',error:{code:'FORBIDDEN'}}));}});}};
const cursor=crypto.randomBytes(32).toString('hex');
plugin.configurePreviewServer=plugin.configureServer;
plugin.generateBundle=(_,bundle)=>{fs.writeFileSync(E+'/full-built-chunks.json',JSON.stringify({at:new Date().toISOString(),chunks:Object.values(bundle).filter(c=>c.type==='chunk').map(c=>({file:c.fileName,imports:c.imports,dynamicImports:c.dynamicImports,modules:Object.keys(c.modules).map(p=>p.replaceAll('\\','/').replace(process.cwd().replaceAll('\\','/')+'/',''))}))},null,2)+'\n');};
const outDir='.tmp/team-hub-2b6/browser-build';
await build({plugins:[plugin],define:{__TEAM_HUB_REHEARSAL_BASE__:JSON.stringify(base)},build:{outDir,emptyOutDir:true},logLevel:'error'});
const server=await preview({plugins:[plugin],build:{outDir},preview:{host:'localhost',port:5177,strictPort:true,open:false}});
console.log('Built isolated Team website ready at http://localhost:5177/team-hub');
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{sessions.clear();server.httpServer.close(()=>process.exit(0));});
