import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {aws,read,save,digest} from './coverage-read.mjs';
import {aws as readAws,tables} from '../team-hub-2b4b/preflight/read-only.mjs';
import {identity,targets,count} from '../team-hub-2b4b/preflight/common.mjs';
const E='docs/architecture/team-hub-2b6-evidence-2026-10-07',A='docs/architecture/team-hub-core-integration-evidence-2026-10-07',r={at:new Date().toISOString(),identity:await identity(),templates:[],runtimes:[],sources:[],target:[],temporaryTablesAbsent:[],actualAuthority:'LEGACY_WRITER',frontendLiveCutover:false,productionTouched:false,complete:false};
for(const [name,file]of [['ProjectRespawn-TeamHub-Ntgre',A+'/product.template.json'],['ProjectRespawn-TeamHub-Ntgre-ReadProofSecurity',A+'/security.template.json'],['ProjectRespawn-Core-Ntgre','docs/architecture/core-artifact-evidence-2026-10-06/product.template.json'],['ProjectRespawn-Core-Ntgre-Security','docs/architecture/core-artifact-evidence-2026-10-06/security.template.json']]){const t=(await aws('cloudformation','get-template','--stack-name',name,'--template-stage','Original')).TemplateBody;assert.equal(digest(typeof t==='string'?JSON.parse(t):t),digest(read(file)));r.templates.push({name,unchanged:true});save('preservation',r);}
for(const kind of ['Command','Read']){const f=await aws('lambda','get-function-configuration','--function-name','ProjectRespawn-TeamHub-Ntgre-Parity'+kind);const expected=Buffer.from(read(A+'/acceptance.json').runtimeSha256,'hex').toString('base64');assert.equal(f.CodeSha256,expected);assert.equal(f.Environment.Variables.TEAM_HUB_AUTHORITY,'LEGACY_WRITER');assert.equal(f.Environment.Variables.TEAM_HUB_NORMAL_WRITES,'DISABLED');r.runtimes.push({kind,unchanged:true,authority:'LEGACY_WRITER',normalWrites:'DISABLED'});}
for(const t of targets){const passes=await count(t.sourceName);assert.ok(passes.every(x=>x.count===0));r.sources.push({model:t.model,passes});}
for(const [suffix,expected]of [['Operational',0],['Journal',15]]){const name='ProjectRespawn-TeamHub-Ntgre-'+suffix;tables.add(name);const scan=await readAws('dynamodb','scan','--table-name',name,'--consistent-read','--select','COUNT');assert.equal(scan.Count,expected);r.target.push({name,count:scan.Count,stronglyConsistent:true});}
const rehearsal=read('docs/architecture/team-hub-2b5b-evidence-2026-10-07/rehearsal.json'),fence=read('docs/architecture/team-hub-2b5b-evidence-2026-10-07/fence-rehearsal.json');assert.ok(rehearsal.passed&&fence.passed&&fence.cleanup);const names=[...rehearsal.created.map(x=>x.name),'ProjectRespawn-TeamHub-Ntgre-2B5B-FenceRehearsal-20261007'];
for(const name of names){try{await readAws('dynamodb','describe-table','--table-name',name);throw Error('Temporary table remains');}catch(e){if(!e.message.includes('ResourceNotFoundException'))throw e;r.temporaryTablesAbsent.push(name);}}
const candidate=read('docs/architecture/team-hub-2b5b-evidence-2026-10-07/fence-candidates.json');for(const t of targets){let current;try{current=JSON.parse((await aws('dynamodb','get-resource-policy','--resource-arn',t.sourceArn)).Policy);}catch(e){if(!e.message.includes('PolicyNotFoundException'))throw e;}assert.equal(digest(current??null),digest(candidate.existing[t.sourceArn]??null));}
r.sourcePoliciesUnchanged=true;r.complete=true;r.ledgerRowChanges=0;save('preservation',r);console.log(JSON.stringify({preserved:true,temporaryTablesAbsent:names.length,authority:r.actualAuthority}));
