import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
export const E='docs/architecture/team-hub-2b4a-evidence-2026-10-06',product='ProjectRespawn-TeamHub-Ntgre',security=product+'-ReadProofSecurity',execution='arn:aws:iam::058264289478:role/'+product+'-ReadProofExecution',caller='arn:aws:iam::058264289478:role/'+product+'-Deploy';
export const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,'')),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');export const canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);export const c=read(E+'/deployment-candidate.json');const exec=promisify(execFile);let creds;
export async function aws(service,action,args=[],restricted=false){const v=k=>args[args.indexOf(k)+1];const writes=['create-change-set','execute-change-set','put-object'];const allowed={sts:['get-caller-identity','assume-role'],cloudformation:['describe-stacks','get-template','list-stack-resources','describe-change-set','describe-stack-events','create-change-set','execute-change-set'],iam:['get-role','get-policy','get-policy-version','get-role-policy','list-role-policies','list-attached-role-policies','simulate-custom-policy','simulate-principal-policy'],s3api:['put-object','head-object'],lambda:['get-function-configuration','get-policy'],apigatewayv2:['get-api','get-routes','get-integrations','get-authorizers','get-stages'],logs:['describe-log-streams','filter-log-events'],cloudwatch:['describe-alarms','get-metric-statistics','list-metrics']};assert.ok(allowed[service]?.includes(action),'Out-of-scope action');
if(service==='sts'&&action==='assume-role')assert.equal(v('--role-arn'),caller);
if(service==='cloudformation'){const stack=v('--stack-name');assert.ok([product,security].includes(stack));const kind=stack===product?'product':'security';if(writes.includes(action)){assert.equal(sha(E+'/proposed-'+kind+'.template.json'),c[kind+'Sha256']);assert.ok(!fs.existsSync(E+'/STOP.json'));if(action==='create-change-set'){assert.equal(v('--change-set-name'),'team-hub-2b4a-'+kind+'-20261006');assert.equal(v('--change-set-type'),'UPDATE');if(kind==='product'){assert.ok(restricted);assert.equal(v('--role-arn'),execution);assert.equal(v('--template-url'),c.url);}else assert.equal(v('--template-body'),'file://'+E+'/proposed-security.template.json');}if(action==='execute-change-set'){const gate=read(E+'/'+kind+'-execution-gate.json');assert.ok(gate.ready);assert.equal(v('--change-set-name'),gate.changeSetId);assert.ok(args.includes('--no-disable-rollback'));assert.ok(!fs.existsSync(E+'/'+kind+'-executed.json'));if(kind==='product')assert.ok(restricted);}}}
if(service==='s3api'){assert.equal(v('--bucket'),'cdk-hnb659fds-assets-058264289478-eu-north-1');assert.ok([c.key,c.assetKey].includes(v('--key')));if(action==='put-object'){assert.equal(v('--server-side-encryption'),'AES256');const file=v('--key')===c.key?E+'/proposed-product.template.json':'.tmp/team-hub-2b4/runtime.zip';assert.equal(v('--body'),file);assert.equal(sha(file),v('--key')===c.key?c.productSha256:c.assetKey.split('/').at(-1).split('.')[0]);assert.ok(read(E+'/security-installed-final.json').verified);}}
const env={...process.env,AWS_MAX_ATTEMPTS:'1'};if(restricted){assert.ok(creds);env.AWS_ACCESS_KEY_ID=creds.AccessKeyId;env.AWS_SECRET_ACCESS_KEY=creds.SecretAccessKey;env.AWS_SESSION_TOKEN=creds.SessionToken;delete env.AWS_PROFILE;delete env.AWS_DEFAULT_PROFILE;}
try{const {stdout}=await exec('aws',[service,action,...args,...(restricted?[]:['--profile','default']),'--region','eu-north-1','--output','json','--no-cli-pager'],{env,windowsHide:true,maxBuffer:64e6});const r=stdout.trim()?JSON.parse(stdout):{};if(writes.includes(action))fs.appendFileSync(E+'/aws-writes.jsonl',JSON.stringify({at:new Date().toISOString(),service,action,stack:v('--stack-name'),key:v('--key'),restricted})+'\n');return r;}catch(e){const code=(e.stderr??'').match(/\(([^)]+)\)/)?.[1]??'COMMAND_FAILED';if(writes.includes(action))save('STOP',{at:new Date().toISOString(),service,action,code});throw Error(service+' '+action+': '+code);}}
export async function identity(){const who=await aws('sts','get-caller-identity');assert.equal(who.Account,'058264289478');assert.equal(who.Arn,'arn:aws:iam::058264289478:user/RavenTest');return who;}
export async function assume(){const r=await aws('sts','assume-role',['--role-arn',caller,'--role-session-name','TeamHub2B4ADark','--duration-seconds','3600']);creds=r.Credentials;return r.AssumedRoleUser;}
