import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import Module from 'node:module';import path from 'node:path';
const E='docs/architecture/team-hub-2b4-evidence-2026-10-06/',out='docs/architecture/team-hub-2b4a-evidence-2026-10-06/';const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const expected={product:'d9e47021ffc55ee99c9477f0ff00590258f10e51375d7f8065afbf28f26c51c2',security:'8431078d29f8a5c8cbdd53737727fe3df75421c1ce2f804d09eb48e3a5d9389c',zip:'fd586f77dd3d872299e432f8e6d4631da09592cd29f47df6221ec8ede77b4a6d',bundle:'6f83d22ddc4a19c5a43d3cc6de8d1a6d5857ab287f4b731b122f1e6b59750175'};
assert.equal(sha(E+'proposed-product.template.json'),expected.product);assert.equal(sha(E+'proposed-security.template.json'),expected.security);assert.equal(sha('.tmp/team-hub-2b4/runtime.zip'),expected.zip);assert.equal(sha('.tmp/team-hub-2b4/asset/index.js'),expected.bundle);
const manifest=read(E+'source-manifest.json');for(const f of manifest.files)assert.equal(sha(f.path),f.sha256,f.path);const closure=read(E+'bundle-closure.json');assert.equal(closure.bundleSha256,expected.bundle);assert.ok(closure.inputs.every(p=>p.replaceAll('\\','/').startsWith('domains/team-hub/')));
const core=read('config/environments/Ntgre.core.json'),product=read(E+'proposed-product.template.json'),results=[];
for(const runtime of ['Command','Read']){Object.assign(process.env,product.Resources['Parity'+runtime+'Function'].Properties.Environment.Variables);const file=path.resolve('.tmp/team-hub-2b4/asset/index.js'),m=new Module(file);m.filename=file;m.paths=Module._nodeModulePaths(path.dirname(file));m._compile(fs.readFileSync(file,'utf8'),file);const routes=Object.values(product.Resources).filter(r=>r.Type==='AWS::ApiGatewayV2::Route'&&r.Properties.Target?.['Fn::Join']?.[1]?.some?.(v=>v?.Ref==='Parity'+runtime+'Integration'));
const keys=runtime==='Command'?['POST /v1/teams']:['GET /v1/teams/{teamId}','GET /v1/teams/{teamId}/me/champions','GET /v1/teams/{teamId}/champion-pools','GET /v1/teams/{teamId}/players/{membershipId}/competitive'];
// Resolve actual routes from the pinned template rather than assume route spellings.
const actual=Object.entries(product.Resources).filter(([k,r])=>r.Type==='AWS::ApiGatewayV2::Route'&&k.startsWith('ParityRoute')&&((runtime==='Read')===r.Properties.RouteKey.startsWith('GET '))).map(([,r])=>r.Properties.RouteKey);
for(const routeKey of actual){const r=await m.exports.handler({routeKey,pathParameters:{teamId:'team:nonexistent',membershipId:'membership:test',championId:'champion:test'},body:routeKey.startsWith('POST /v1/teams')?JSON.stringify({slug:'nonexistent'}):undefined,requestContext:{requestId:'offline-dark-proof',authorizer:{jwt:{claims:{iss:core.issuer,sub:'00000000-0000-0000-0000-000000000001',client_id:core.clientId,token_use:'access',exp:Math.floor(Date.now()/1000)+3600}}}}});assert.equal(r.statusCode,403);assert.equal(JSON.parse(r.body).error.code,'FORBIDDEN');results.push({runtime,routeKey,status:r.statusCode,error:'FORBIDDEN'});}}
fs.writeFileSync(out+'pinned-dark-proof.json',JSON.stringify({at:new Date().toISOString(),hashes:expected,manifestFiles:manifest.files.length,bundleClosureVerified:true,freshSynthesis:false,headSubstituted:false,offlineOnly:true,results,blocker:'Step 22 empty/not-found read behavior cannot be met by pinned disabled runtime. All four reads fail at verification gate before DynamoDB.',awsWrites:0},null,2)+'\n');console.log(JSON.stringify({hashesVerified:true,manifestFiles:manifest.files.length,routes:results,ready:false}));
