<template>
  <section class="analytics-panel compensation-panel" aria-labelledby="compensation-title">
    <header class="analytics-section-heading"><div><span class="future-badge">Future feature</span><h2 id="compensation-title">Creator Compensation</h2><p>This illustrative system is not currently active and is not a promise or offer.</p></div></header>
    <div class="compensation-notice">Project Respawn's future compensation vision will continue to evolve. Exact salary and bonus calculations are not final.</div>
    <div class="plan-comparison"><article><span>Stable Plan</span><strong>£2,150 <small>/ month</small></strong><p>Higher illustrative fixed salary. No quarterly performance bonus.</p></article><article class="selected"><span>Performance Plan · demo selection</span><strong>£1,700 <small>/ month</small></strong><p>Lower illustrative fixed salary with a quarterly bonus forecast.</p></article></div>
    <button type="button" class="compare-button" @click="showComparison=!showComparison">Compare Plans</button>
    <p v-if="showComparison" class="analytics-note">Plan comparison is informational. Any future choice would be discussed during a six-month Creator Review meeting.</p>
    <div class="review-grid"><div><span>Current six-month period</span><strong>July–December 2026</strong></div><div><span>Next Creator Review</span><strong>15 January 2027</strong></div><div><span>Predicted creator value</span><strong>Illustrative only</strong></div></div>
    <p class="salary-rule">Your base salary does not change automatically. Compensation is reviewed with you during your six-month Creator Review.</p>
    <div class="bonus-summary"><div><span>Current quarterly forecast</span><strong>£1,950</strong></div><div><span>Previous forecast</span><strong>£1,805</strong></div><div><span>Change</span><strong class="positive-text">+£145</strong></div><div><span>Next update</span><strong>6 days</strong></div><div><span>Quarter progress</span><strong>68%</strong></div></div>
    <svg class="bonus-chart" viewBox="0 0 600 130" role="img" aria-label="Illustrative fortnightly bonus forecast increased from £1,320 to £1,950"><polyline :points="points" fill="none" stroke="#4ade80" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="590" :cy="lastY" r="6" fill="#4ade80"/></svg>
    <details><summary>Latest illustrative forecast contributors</summary><ul><li>Affiliate performance: +£72</li><li>Creator Score improvement: +£41</li><li>Mission performance: +£24</li><li>Community engagement: +£18</li><li>Event participation: −£10</li></ul><p>The forecast is recalculated every two weeks and would be finalised quarterly. No production weighting formula exists.</p></details>
  </section>
</template>
<script setup>import{computed,ref}from'vue';const props=defineProps({history:{type:Array,required:true}});const showComparison=ref(false);const min=computed(()=>Math.min(...props.history));const max=computed(()=>Math.max(...props.history));const calcY=v=>115-((v-min.value)/Math.max(1,max.value-min.value))*95;const points=computed(()=>props.history.map((v,i)=>`${10+i*(580/(props.history.length-1))},${calcY(v)}`).join(' '));const lastY=computed(()=>calcY(props.history.at(-1)))</script>
