<template>
  <div class="analytics-chart">
    <svg viewBox="0 0 800 290" role="img" :aria-label="summary">
      <defs><linearGradient :id="gradientId" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#a855f7" stop-opacity=".42"/><stop offset="1" stop-color="#a855f7" stop-opacity="0"/></linearGradient></defs>
      <g class="grid"><line v-for="tick in yTicks" :key="tick.value" x1="58" x2="780" :y1="tick.y" :y2="tick.y"/><text v-for="tick in yTicks" :key="`label-${tick.value}`" x="48" :y="tick.y+4" text-anchor="end">{{ formatValue(tick.value) }}</text></g>
      <polygon :points="area" :fill="`url(#${gradientId})`"/><polyline :points="line" fill="none" stroke="#a855f7" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/>
      <g class="data-points"><circle v-for="point in visiblePoints" :key="point.index" :cx="point.x" :cy="point.y" r="4" tabindex="0"><title>{{ point.label }}: {{ formatValue(point.value) }} {{ metric }}</title></circle><text v-for="point in labelledPoints" :key="`value-${point.index}`" :x="point.x" :y="point.y-10" text-anchor="middle">{{ formatValue(point.value) }}</text></g>
      <g class="x-axis"><text v-for="label in xLabels" :key="label.index" :x="label.x" y="278" :text-anchor="label.anchor">{{ label.text }}</text></g>
      <g v-for="milestone in chartMilestones" :key="milestone.title" class="chart-milestone"><line :x1="milestone.x" :x2="milestone.x" y1="28" y2="245"/><circle :cx="milestone.x" :cy="milestone.y" r="6" tabindex="0"><title>{{ milestone.title }} — {{ milestone.date }}. {{ milestone.detail }} This does not prove causation.</title></circle><text :x="milestone.x+5" y="38"><tspan :x="milestone.x+5">{{ milestone.shortDate }}</tspan><tspan :x="milestone.x+5" dy="13">{{ milestone.title }}</tspan></text></g>
    </svg>
    <div class="chart-milestones"><details v-for="milestone in chartMilestones" :key="milestone.title"><summary>{{ milestone.title }}</summary><strong>{{ milestone.date }}</strong><p>{{ milestone.detail }} This is an observed relationship and does not prove causation.</p></details></div>
    <p class="analytics-note">{{ period }} history. Focus a plotted point for its date and value. Milestones show observed timing; correlation does not imply causation.</p><p class="sr-only">{{ summary }}</p>
  </div>
</template>
<script setup>
import{computed}from'vue'
const props=defineProps({values:{type:Array,required:true},metric:String,period:{type:String,default:'30 Days'},milestones:{type:Array,default:()=>[]}});const gradientId=`analyticsFill-${Math.random().toString(36).slice(2)}`
const plot={left:58,right:780,top:54,bottom:245};const min=computed(()=>Math.min(...props.values));const max=computed(()=>Math.max(...props.values));const axisMax=computed(()=>{const raw=max.value*1.12;const power=10**Math.floor(Math.log10(Math.max(1,raw)));return Math.ceil(raw/power)*power});const x=i=>plot.left+i*((plot.right-plot.left)/Math.max(1,props.values.length-1));const y=v=>plot.bottom-(v/Math.max(1,axisMax.value))*(plot.bottom-plot.top)
const line=computed(()=>props.values.map((v,i)=>`${x(i)},${y(v)}`).join(' '));const area=computed(()=>`${plot.left},${plot.bottom} ${line.value} ${plot.right},${plot.bottom}`);const yTicks=computed(()=>Array.from({length:5},(_,i)=>{const value=axisMax.value*i/4;return{value,y:y(value)}}))
const labelCount=computed(()=>props.period==='7 Days'?7:props.period==='30 Days'?6:props.period==='90 Days'?7:props.period==='1 Year'?7:6);const labelIndexes=computed(()=>Array.from(new Set(Array.from({length:labelCount.value},(_,i)=>Math.round(i*(props.values.length-1)/Math.max(1,labelCount.value-1))))))
const periodDays=computed(()=>({'7 Days':7,'30 Days':30,'90 Days':90,'6 Months':183,'1 Year':365,'2 Years':730,'3 Years':1095,'All Time':1460,Custom:30}[props.period]||30));const dateFor=i=>{const end=new Date('2027-05-12T00:00:00Z');const elapsed=(props.values.length-1-i)/Math.max(1,props.values.length-1);end.setUTCDate(end.getUTCDate()-Math.round(periodDays.value*elapsed));return end};const formatDate=date=>props.period==='7 Days'?date.toLocaleDateString('en-GB',{weekday:'short'}):['2 Years','3 Years','All Time'].includes(props.period)?date.toLocaleDateString('en-GB',{month:'short',year:'2-digit'}):date.toLocaleDateString('en-GB',{day:'numeric',month:'short'})
const xLabels=computed(()=>labelIndexes.value.map((index,i)=>({index,x:x(index),text:formatDate(dateFor(index)),anchor:i===0?'start':i===labelIndexes.value.length-1?'end':'middle'})));const visiblePoints=computed(()=>props.values.map((value,index)=>({index,value,x:x(index),y:y(value),label:formatDate(dateFor(index))})));const labelledPoints=computed(()=>visiblePoints.value.filter(point=>labelIndexes.value.includes(point.index)&&point.index%2===0))
const chartMilestones=computed(()=>props.milestones.map((item,i)=>{const localIndex=Math.min(props.values.length-1,Math.round((i+1)*props.values.length/(props.milestones.length+1)));return{...item,localIndex,x:x(localIndex),y:y(props.values[localIndex]),shortDate:formatDate(dateFor(localIndex))}}));const formatValue=value=>value>=1000?`${Number((value/1000).toFixed(1))}K`:Math.round(value).toLocaleString();const summary=computed(()=>`${props.metric} changed from ${formatValue(props.values[0])} to ${formatValue(props.values.at(-1))} over ${props.period}.`)
</script>
