// Offline ledger control. No AWS imports, synthesis or deployment entrypoints.
import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
export const owners=['SHARED_CORE','TOURNAMENT','TEAM_HUB','CREATOR','COMMERCE','COMMUNITY_EVENTS','APPLICATIONS_INTAKE','INVESTOR_ACCESS','FRONTEND_OR_BUILD_SUPPORT','LEGACY_COMPATIBILITY','RETIRE_CANDIDATE','UNASSIGNED','UNRESOLVED_SHARED'];
export const migrationStatuses=['LEGACY_ACTIVE','INVENTORIED','DESIGNED','INDEPENDENT_PROOF','MIGRATION_PREP','MIGRATED','CUTOVER_COMPLETE','RETIREMENT_REVIEW','RETIRED'];
export const retirementStatuses=['NOT_ELIGIBLE','POTENTIAL','READY_FOR_REVIEW','AUTHORIZED','RETIRED'];
export const sourcePath='docs/architecture/phase2-resource-domain-map.json';
export const latestPath='docs/architecture/team-hub-2b2-caller-release-evidence-2026-10-05/legacy-after.json';
export const ledgerPath='docs/architecture/legacy-resource-ownership.json';
export const read=p=>JSON.parse(fs.readFileSync(p,'utf8').replace(/^\uFEFF/,''));
export const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const coreModels=new Set(['PermissionDefinition','GroupPermission','PermissionAuditEvent','UserProfile','Brand','BrandAccess','BrandAccessPermission','MediaCollection','MediaItem']);
export function attribution(r,stack,stacks){
 const child=r.type==='AWS::CloudFormation::Stack'?stacks.find(s=>s.arn===r.physicalId):null;
 const model=r.model??child?.model;
 if(r.type==='AWS::CDK::Metadata')return ['FRONTEND_OR_BUILD_SUPPORT','CDK-generated deployment metadata; build support, not a business service.'];
 const direct={'TEAM HUB':'TEAM_HUB','CREATOR PLATFORM':'CREATOR','COMMERCE':'COMMERCE','COMMUNITY / EVENTS':'COMMUNITY_EVENTS','TOURNAMENTS':'TOURNAMENT'};
 if(direct[r.domain])return [direct[r.domain],'Retain the explicit logical domain attribution in the accepted decomposition inventory; physical ownership remains LegacyPlatform.'];
 if(r.domain==='ADMIN / OPERATIONS'){
  if(model?.startsWith('InvestorAccess')||r.operation?.includes('Investor'))return ['INVESTOR_ACCESS','Investor model/nested-handle or named Investor operation, supported by the domain-classification decision.'];
  if(model?.startsWith('Application')||r.operation?.includes('Application'))return ['APPLICATIONS_INTAKE','Application model/nested-handle or named application operation, supported by the Intake classification.'];
  if(['listAdminUsers','updateUserRoles'].includes(r.operation)||r.attribution==='Dedicated account-administration function resources')return ['SHARED_CORE','Shared account/role administration; not a separate Admin product root.'];
  return ['UNASSIGNED','Admin attribution is too coarse to choose Investor, Intake or Core from the recorded evidence.'];
 }
 if(r.domain==='CORE / SHARED'){
  if(coreModels.has(model)||r.operation)return ['SHARED_CORE','Explicit Core-owned model or operation in the accepted map and shared capability classification.'];
  if(stack.key==='002'||child?.key==='002')return ['SHARED_CORE','Existing shared Cognito/authentication stack, consumed by same-environment domains.'];
  return ['UNRESOLVED_SHARED','Shared deployment/provider/handler/API/storage attribution does not establish final physical ownership, consumer split or retirement disposition; inventory consumers before assigning.'];
 }
 return ['UNASSIGNED','No sufficiently specific approved future-owner mapping exists in the stored evidence.'];
}
export function buildLedger(source,latest){
 assert.equal(source.total,2621);assert.equal(source.resources.length,2621);assert.equal(source.stacks.length,62);assert.equal(latest.total,2621);assert.equal(latest.directive,167);
 const protectedIds=new Set(latest.protectedResources.map(r=>r.type+'|'+r.physicalId));
 const resources=source.resources.map((r,index)=>{const stack=source.stacks.find(s=>s.key===r.stackKey);assert.ok(stack);const [futureOwner,ownershipRationale]=attribution(r,stack,source.stacks);const stateful=!!r.stateful,protectedResource=protectedIds.has(r.type+'|'+r.physicalId);const high=stateful||protectedResource||r.type==='AWS::CloudFormation::Stack'||futureOwner==='UNRESOLVED_SHARED';return {resourceId:r.id,logicalId:r.logicalId,resourceType:r.type,currentStack:{key:stack.key,name:stack.name,arn:stack.arn},nestedPath:stack.path,resourcePath:stack.path+'/'+r.logicalId,physicalId:r.type==='AWS::AppSync::ApiKey'?null:r.physicalId??null,...(r.physicalIdSha256?{physicalIdSha256:r.physicalIdSha256}:{}),currentDomainAttribution:r.domain,futureOwner,ownershipRationale,ownershipBasis:'RECORDED_LOGICAL_ATTRIBUTION_NOT_PHYSICAL_TRANSFER',migrationStatus:'LEGACY_ACTIVE',stateful,shared:r.domain==='CORE / SHARED'||['SHARED_CORE','UNRESOLVED_SHARED'].includes(futureOwner),protected:protectedResource,migrationRisk:high?'HIGH':r.type==='AWS::CDK::Metadata'?'LOW':'MEDIUM',riskRationale:high?'State/protected identity, recursive nested lifecycle or unresolved shared consumers require explicit recovery and impact review.':'Verify consumers, policy/provider behavior and independent rollback before any retirement.',retirementStatus:'NOT_ELIGIBLE',currentAuthority:'LegacyPlatform',model:r.model??null,operation:r.operation??null,deletionPolicy:r.deletionPolicy??null,updateReplacePolicy:r.updateReplacePolicy??null,evidence:[{path:sourcePath,pointer:'/resources/'+index},{path:'docs/architecture/project-respawn-domain-classification.md'},{path:latestPath}],sourceAttribution:r.attribution,sourceLocations:r.source};});
 return {schemaVersion:'legacy-resource-ownership.v1',scope:'Ntgre recursive LegacyPlatform declarations only; external stacks and production are outside this ledger',inventoryStatus:'COMPLETE',ownershipResolutionStatus:'INCOMPLETE',baseline:{expectedTotal:2621,rootStacks:1,nestedStacks:61,stackCount:62,functionDirectiveResources:167,awsStatus:latest.root.status,lastVerified:latest.at,rootLastUpdated:latest.root.lastUpdated,sourceInventory:sourcePath,sourceInventorySha256:sha(sourcePath),verificationEvidence:latestPath,verificationEvidenceSha256:sha(latestPath),freshAwsReadPerformedByThisCheckpoint:false},enums:{futureOwner:owners,migrationStatus:migrationStatuses,retirementStatus:retirementStatuses},accountInventoryComplete:false,notes:['Nested-stack handles are already included in the 2621 declarations; the root is not an extra resource row.','61 stateful declarations follow the source definition: tables, buckets, keys and Cognito pool. The 62 protected identities also include AppSync. IAM, nested stacks and other resources may still be high risk.','An independent read proof does not migrate or retire a Legacy declaration. All rows remain LEGACY_ACTIVE and NOT_ELIGIBLE.','No API key value is stored: only its recorded identity hash.','Full-account/external runtime ownership and production require separate evidence before migration completion.'],resources};
}
export function validateLedger(ledger,source=read(sourcePath),latest=read(latestPath)){
 assert.equal(ledger.baseline.sourceInventorySha256,sha(sourcePath),'Source inventory hash changed');assert.equal(ledger.baseline.verificationEvidenceSha256,sha(latestPath),'Baseline evidence hash changed');assert.equal(ledger.resources.length,source.total,'Ledger total does not reconcile');assert.equal(ledger.baseline.expectedTotal,source.total);assert.equal(ledger.baseline.stackCount,source.stacks.length);
 assert.equal(new Set(ledger.resources.map(r=>r.resourceId)).size,source.total,'Duplicate resource ID');assert.equal(new Set(ledger.resources.map(r=>r.currentStack.arn+'|'+r.logicalId)).size,source.total,'Duplicate stack/logical identity');assert.equal(new Set(ledger.resources.map(r=>r.resourcePath)).size,source.total,'Duplicate nested resource path');
 for(const r of ledger.resources){if(['MIGRATED','CUTOVER_COMPLETE','RETIREMENT_REVIEW','RETIRED'].includes(r.migrationStatus)){assert.ok(r.milestoneEvidence?.reconciliation && r.milestoneEvidence?.writerAuthority,'Migration requires reconciliation and writer authority');if(r.stateful)assert.ok(r.milestoneEvidence?.backupRestore,'Stateful migration requires recovery proof');}if(['AUTHORIZED','RETIRED'].includes(r.retirementStatus))assert.ok(r.retirementAuthorization?.evidence && r.retirementAuthorization?.approvedBy,'Retirement requires separate explicit authorization');} const original=new Map(source.resources.map(r=>[r.id,r]));for(const r of ledger.resources){for(const flag of ['stateful','shared','protected'])assert.equal(typeof r[flag],'boolean');assert.ok(['LOW','MEDIUM','HIGH'].includes(r.migrationRisk));for(const e of r.evidence)assert.ok(fs.existsSync(e.path),'Missing evidence '+e.path);const old=original.get(r.resourceId);assert.ok(old,'Invented resource');assert.equal(r.logicalId,old.logicalId);assert.equal(r.resourceType,old.type);assert.equal(r.currentStack.key,old.stackKey);assert.ok(owners.includes(r.futureOwner));assert.ok(migrationStatuses.includes(r.migrationStatus));assert.ok(retirementStatuses.includes(r.retirementStatus));assert.ok(r.ownershipRationale&&r.riskRationale&&r.evidence.length);assert.equal(r.stateful,!!old.stateful);if(['UNASSIGNED','UNRESOLVED_SHARED'].includes(r.futureOwner))assert.ok(r.ownershipRationale.length>30);if(r.resourceType==='AWS::AppSync::ApiKey')assert.equal(r.physicalId,null);else assert.equal(r.physicalId,old.physicalId??null);}
 for(const s of source.stacks){const rows=ledger.resources.filter(r=>r.currentStack.key===s.key);assert.equal(rows.length,s.count,'Per-stack count mismatch '+s.key);assert.ok(rows.every(r=>r.currentStack.arn===s.arn&&r.nestedPath===s.path));const live=latest.stacks.find(x=>x.key===s.key);assert.equal(live.count,s.count);assert.equal(live.templateSha256,s.templateSha256);}
 assert.equal(ledger.resources.filter(r=>r.protected).length,latest.protectedResources.length);const p=new Set(latest.protectedResources.map(r=>r.type+'|'+r.physicalId));for(const r of ledger.resources)assert.equal(r.protected,p.has(r.resourceType+'|'+r.physicalId));
 return coverage(ledger);
}
export function coverage(ledger){const rs=ledger.resources,unassigned=rs.filter(r=>r.futureOwner==='UNASSIGNED').length,unresolvedShared=rs.filter(r=>r.futureOwner==='UNRESOLVED_SHARED').length,total=rs.length;const count=p=>rs.filter(p).length;return {expected:ledger.baseline.expectedTotal,total,assigned:total-unassigned-unresolvedShared,unassigned,unresolvedShared,inventoryCoveragePercent:100*total/ledger.baseline.expectedTotal,ownershipResolvedPercent:100*(total-unassigned-unresolvedShared)/total,shared:count(r=>r.shared),stateful:count(r=>r.stateful),protected:count(r=>r.protected),retireCandidates:count(r=>r.futureOwner==='RETIRE_CANDIDATE'||r.retirementStatus==='POTENTIAL'||r.retirementStatus==='READY_FOR_REVIEW'),migrated:count(r=>['MIGRATED','CUTOVER_COMPLETE','RETIREMENT_REVIEW','RETIRED'].includes(r.migrationStatus)),retired:count(r=>r.migrationStatus==='RETIRED'),byOwner:Object.fromEntries(owners.map(o=>[o,rs.filter(r=>r.futureOwner===o).length]))};}
export function renderReports(ledger){const c=validateLedger(ledger),pct=n=>(100*n/c.total).toFixed(2)+'%';const ownerRows=owners.map(o=>{const rs=ledger.resources.filter(r=>r.futureOwner===o),unknown=['UNASSIGNED','UNRESOLVED_SHARED'].includes(o);return `| ${o} | ${rs.length} | ${unknown?0:rs.length} | ${rs.filter(r=>['MIGRATED','CUTOVER_COMPLETE','RETIRED'].includes(r.migrationStatus)).length} | ${rs.filter(r=>r.retirementStatus==='POTENTIAL'||r.futureOwner==='RETIRE_CANDIDATE').length} | ${unknown?rs.length:0} |`;});
 fs.writeFileSync('docs/architecture/legacy-resource-ownership-summary.md',`# Legacy resource ownership coverage\n\n[Phase 2 START HERE](README-PHASE2-MIGRATION.md) · [Full ledger](legacy-resource-ownership.json) · [Human-readable ledger](legacy-resource-ownership.md)\n\nInventory coverage is **${c.inventoryCoveragePercent.toFixed(2)}%** (${c.total}/${c.expected}); future-owner resolution is **${c.ownershipResolvedPercent.toFixed(2)}%**. Inventory is complete for the accepted recursive Ntgre scope; ownership resolution and full-account/production coverage are not complete. ${ledger.latestReadOnlyReview ? "M4 performed a scoped read-only refresh; no AWS writes occurred." : "No AWS call was made for this checkpoint."} Evidence was last verified ${ledger.latestReadOnlyReview?.at ?? ledger.baseline.lastVerified}.\n\n| Measure | Count | % of Legacy |\n|---|---:|---:|\n${[['Total',c.total],['Assigned',c.assigned],['Unassigned',c.unassigned],['Unresolved shared',c.unresolvedShared],['Shared',c.shared],['Stateful',c.stateful],['Protected',c.protected],['Retirement candidates',c.retireCandidates],['Migrated',c.migrated],['Retired',c.retired]].map(([n,v])=>`| ${n} | ${v} | ${pct(v)} |`).join('\n')}\n\nStateful/shared/protected are overlapping dimensions, not additive buckets. Statefulness follows the accepted source definition (61 tables/buckets/keys/pool declarations); protected includes the AppSync API (62). Logical ownership is not physical transfer or deletion eligibility.\n\n| Future owner/domain | Current resources | Assigned | Migrated | Retirement candidates | Unresolved |\n|---|---:|---:|---:|---:|---:|\n${ownerRows.join('\n')}\n\nAll resources remain Legacy-authoritative. Tournament/Team Hub independent previews add their own resources; they do not remove any of these rows. **No Legacy resource reduction is claimed.** Mixed shared providers, APIs, IAM and storage need consumer/lifecycle evidence before resolution. Unresolved entries include an explanation and source pointers. Do not assign them merely to improve coverage.\n`);
 fs.writeFileSync('docs/architecture/legacy-resource-ownership.md',`# LegacyPlatform resource ownership ledger\n\n[START HERE](README-PHASE2-MIGRATION.md) · [Coverage summary](legacy-resource-ownership-summary.md) · [Complete JSON records](legacy-resource-ownership.json)\n\n${c.total} declarations; one root plus 61 nested stacks. Nested handles are included once; no synthetic extra root row. Every JSON record includes exact stack ARN/name, nested path, non-secret physical identity (API key hash only), attribution, future owner/rationale, status, risk, protection, retirement and source evidence. This compact table is a view of those records, not a replacement for the complete JSON. Current row migration status is recorded in JSON; MIGRATION_PREP does not transfer authority. All retirement statuses remain NOT_ELIGIBLE.\n\n| Resource ID (stack key:logical ID) | Type | Future owner | Stateful | Protected | Risk |\n|---|---|---|---|---|---|\n${ledger.resources.map(r=>`| ${r.resourceId} | ${r.resourceType} | ${r.futureOwner} | ${r.stateful} | ${r.protected} | ${r.migrationRisk} |`).join('\n')}\n`);return c;
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const action=process.argv[2];if(action==='init'){assert.ok(!fs.existsSync(ledgerPath),'Existing ledger must not be overwritten; update reviewed records and validate instead');const ledger=buildLedger(read(sourcePath),read(latestPath));fs.writeFileSync(ledgerPath,JSON.stringify(ledger,null,2)+'\n');console.log(JSON.stringify(renderReports(ledger)));}else if(action==='summary')console.log(JSON.stringify(renderReports(read(ledgerPath))));else if(action==='check')console.log(JSON.stringify(validateLedger(read(ledgerPath))));else throw Error('Use init (once), summary, or check; all operations are offline.');}
