// Offline, idempotent documentation inventory and initial status generation.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const base='docs/architecture/';
const evidence=base+'team-hub-2b2-caller-release-evidence-2026-10-05/accepted-state.json';
const accepted=JSON.parse(fs.readFileSync(evidence));
const statusPath=base+'domain-migration-status.json';
if(!fs.existsSync(statusPath)){
 const definitions=[
 ['Shared/Core','SHARED_CAPABILITY','SHARED_CORE','M0','EXISTING_SHARED_IDENTITY','UPDATE_COMPLETE',null,null,'Retain shared identity; resolve shared consumer ownership.'],
 ['Tournament','INDEPENDENT_PRODUCT_DOMAIN','TOURNAMENT','M3_ACCEPTED_M7_PENDING','PROVEN_INDEPENDENT_ARCHITECTURE','UPDATE_COMPLETE','ProjectRespawn-Tournaments-Ntgre','msipnwy39j','Separate authorization for Release 2 and restore Release 1 proof.'],
 ['Team Hub','INDEPENDENT_PRODUCT_DOMAIN','TEAM_HUB','M3_ACCEPTED','SECOND_INDEPENDENT_DOMAIN_PROVEN','CREATE_COMPLETE','ProjectRespawn-TeamHub-Ntgre','t54b88casf','2B3 / M4 state inventory and migration preparation; separate authorization.'],
 ['Creator','DOMAIN_CANDIDATE','CREATOR','M0','PAUSED','NOT_EXTRACTED',null,null,'Paused for this maintenance checkpoint; resume only with a scoped instruction.'],
 ['Commerce','DOMAIN_CANDIDATE','COMMERCE','M0','NOT_EXTRACTED','NOT_EXTRACTED',null,null,'Ownership/design review before foundation.'],
 ['Community/Events','DOMAIN_CANDIDATE','COMMUNITY_EVENTS','M0','NOT_EXTRACTED','NOT_EXTRACTED',null,null,'Ownership/design review before foundation.'],
 ['Applications/Intake','DOMAIN_CANDIDATE','APPLICATIONS_INTAKE','M0','NOT_EXTRACTED','NOT_EXTRACTED',null,null,'Review module versus independent root and contracts.'],
 ['Investor Access','DOMAIN_CANDIDATE','INVESTOR_ACCESS','M0','NOT_EXTRACTED','NOT_EXTRACTED',null,null,'Review module versus independent root and shared authorization.']
 ];
 const domains=definitions.map(([domain,classification,owner,phase,architectureStatus,awsStatus,stack,api,nextStep])=>({domain,classification,owner,phase,architectureStatus,awsStatus,stack,api,dataStatus:'LEGACY_AUTHORITATIVE_NO_BUSINESS_DATA_MIGRATED',frontendStatus:'NO_INDEPENDENT_CUTOVER',legacyAuthority:true,gitCheckpoint:owner==='TOURNAMENT'?'98dc1230dfadebbbcc1756823c85c866956ceadc':owner==='TEAM_HUB'?{reference:'CONTAINING_ACCEPTED_CHECKPOINT_COMMIT',resolve:'git log -1 -- config/domains/team-hub/domain-endpoints.Ntgre.json'}:null,blockers:owner==='TEAM_HUB'?['M4-M8 not accepted; no business data or writer cutover.']:owner==='TOURNAMENT'?['M7 update/restore proof outstanding; Phase 2A is not complete.']:['Independent extraction and migration have not been accepted.'],nextStep,lastVerified:accepted.at,evidence:[evidence,base+'project-respawn-domain-classification.md'],...(owner==='TEAM_HUB'?{restrictedCaller:accepted.caller,executionRole:accepted.execution,firstCreateAuthorityEffective:false,frontendCutover:false,businessDataMigrated:false}:{} )}));
 fs.writeFileSync(statusPath,JSON.stringify({schemaVersion:'domain-migration-status.v1',scope:'Ntgre; stored evidence reviewed offline, not a fresh AWS observation',currentDomain:'Team Hub',currentPhase:'M3 accepted; repository maintenance checkpoint; M4 pending',awsChanges:0,productionChanges:0,domains},null,2)+'\n');
}
const files=execFileSync('git',['ls-files','--cached','--others','--exclude-standard','-z'],{encoding:'utf8',maxBuffer:30*1024*1024}).split('\0').filter(Boolean);
const scoped=[...new Set(files)].filter(p=>/^(docs\/(architecture|maintenance)\/|infrastructure\/(domains|security)\/|scripts\/(team-hub|team-hub-migration|tournaments|deployment|migration|checkpoints|legacy)\/|config\/(domains|environments)\/|contracts\/|domains\/team-hub\/|src\/features\/team-hub\/|scripts\/(cloudformation-accounting|ntgre-phase1-allowance)[^/]*$)/.test(p)).sort();
const authoritative=new Set(['README-PHASE2-MIGRATION.md','domain-migration-template.md','domain-migration-status.json','legacy-resource-ownership.json','legacy-resource-ownership.md','legacy-resource-ownership-summary.md','project-respawn-domain-architecture-standard.md','new-domain-checklist.md','adding-a-new-feature.md','domain-deployment-runtime-security.md','domain-deployment-selection.md','independent-domain-deployment-callers.md','phase2-documentation-index.md','README.md']);
const currentTeam=new Set(['team-hub-2b3-empty-source-cutover.md','team-hub-2b3-writer-reader-coverage.md','team-hub-2b3-rollback-contract.md','team-hub-2b3-aws-write-proposal.md','team-hub-2b3-state-inventory.md','team-hub-2b3-recovery-plan.md','team-hub-2b3-migration-plan.md','team-hub-2b3-dark-target-readiness.md','team-hub-2b2-read-path-release1-2026-10-05.md','team-hub-migration-contract.md','team-hub-authorization-matrix.md','team-hub-current-dependency-map.md','team-hub-target-domain-model.md','team-hub-v1-api-contract.md']);
const classify=p=>{
 const n=path.posix.basename(p);
 if(p===base+n&&authoritative.has(n))return ['AUTHORITATIVE_CURRENT','Current migration control or architecture standard.'];
 if(p.startsWith('domains/team-hub/')||p.startsWith('src/features/team-hub/')||currentTeam.has(n)||/^(config\/|contracts\/|scripts\/(team-hub|team-hub-migration|deployment|checkpoints|migration|legacy)\/|infrastructure\/domains\/|infrastructure\/security\/team-hub-Ntgre-deploy-caller\/|infrastructure\/security\/tournaments-Ntgre-accepted-release1\/)/.test(p))return ['DOMAIN_CURRENT','Maintained source/contract or domain reference; historical runners still require a new authorized gate.'];
 if(/(domain-migration-roadmap|project-respawn-domain-classification|read-path-readiness|first-create-security|deployment-security-correction|extraction-plan)/.test(n))return ['SUPERSEDED','Useful dated design/gate; current deployment/status is governed by START HERE and accepted-state evidence.'];
 if(/(diagnostic|investigation|v8|v9)/i.test(p))return ['TEMPORARY_DIAGNOSTIC','Investigation retained for audit; not installed-policy authority.'];
 if(/(evidence|phase1|phase2|team-hub|tournaments-Ntgre)/.test(p))return ['HISTORICAL_EVIDENCE','Retained provenance, including earlier failed candidates; not current deployment authorization.'];
 return ['UNKNOWN','Not promoted to current Phase 2 authority; retain pending owner review.'];
};
const byHash=new Map();
const entries=scoped.filter(p=>!/(phase2-document-inventory\.json|phase2-documentation-index\.md|phase2-document-retention\.md)$/.test(p)).map(p=>{const [classification,reason]=classify(p);const hash=crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');const previous=byHash.get(hash);if(!previous)byHash.set(hash,p);return {path:p,classification,reason,...(previous?{identicalTo:previous}:{}),retain:true};});
// Identical evidence has distinct provenance. Record duplicates without erasing its historical role.
for(const e of entries)if(e.identicalTo&&!['AUTHORITATIVE_CURRENT','DOMAIN_CURRENT'].includes(e.classification)){e.originalClassification=e.classification;e.classification='DUPLICATE';e.reason='Byte-identical content at another path; retain both until references/provenance are reviewed.';}
let links=0;const inbound=new Map();
for(const p of files.filter(p=>p.endsWith('.md'))){const t=fs.readFileSync(p,'utf8');for(const m of t.matchAll(/\]\(([^)]+)\)/g)){const raw=m[1].split('#')[0].replace(/^<|>$/g,'');if(!raw||/^(https?:|mailto:|#)/.test(raw))continue;const target=path.posix.normalize(path.posix.join(path.posix.dirname(p),raw));if(target.startsWith(base)){links++;inbound.set(target,(inbound.get(target)||0)+1);}}}
const counts=Object.fromEntries(['AUTHORITATIVE_CURRENT','DOMAIN_CURRENT','HISTORICAL_EVIDENCE','SUPERSEDED','DUPLICATE','TEMPORARY_DIAGNOSTIC','UNKNOWN'].map(c=>[c,entries.filter(e=>e.classification===c).length]));
fs.writeFileSync(base+'phase2-document-inventory.json',JSON.stringify({version:1,scope:'Git-visible source/evidence; ignored dependencies, caches and local worktrees excluded',strategy:'Retain paths; indexes and status metadata',linkImpact:{architectureReferences:links,referencedPaths:inbound.size,pathsMoved:0},counts,entries},null,2)+'\n');
fs.writeFileSync(base+'phase2-documentation-index.md',`# Phase 2 documentation index\n\n[Required START HERE](README-PHASE2-MIGRATION.md) · [Machine inventory](phase2-document-inventory.json) · [Retention review](../maintenance/phase2-document-retention.md)\n\n${links} existing Markdown references target ${inbound.size} architecture paths. No paths were moved, preserving links and byte-pinned evidence. Status here separates current authority from historical instructions.\n\n## Current required reading\n\n- [Migration control](README-PHASE2-MIGRATION.md), [status](domain-migration-status.json), [ownership summary](legacy-resource-ownership-summary.md), [template](domain-migration-template.md).\n- [Architecture standard](project-respawn-domain-architecture-standard.md), [new-domain checklist](new-domain-checklist.md), [deployment callers](independent-domain-deployment-callers.md).\n\n## Domain current documents\n\n- [Team Hub M4 state inventory](team-hub-2b3-state-inventory.md), [migration plan](team-hub-2b3-migration-plan.md), [recovery proposal](team-hub-2b3-recovery-plan.md), [final preparation gate](team-hub-2b3-dark-target-readiness.md).\n- [Team Hub accepted read proof](team-hub-2b2-read-path-release1-2026-10-05.md); its accepted-state evidence selects the exact-ID steady-state policy.\n- Tournament: config/domains/tournaments/domain-endpoints.Ntgre.json and infrastructure/security/tournaments-Ntgre-accepted-release1; run the offline accepted-state verifier. Release 2/restore remains pending.\n- Other domains: dated classification/design informs ownership; current phase comes from the status JSON.\n\n## Historical deployment evidence\n\nPhase 1, Phase 2A and Phase 2B evidence directories remain in place. Repeated simulation results are retained as provenance. The machine inventory lists every scoped path and retention classification.\n\n## Superseded investigations\n\nDated roadmap/classification statuses, failed preflights, temporary first-create policies and diagnostic v8/v9 policies are not current execution authority. Retaining them never authorizes reinstalling them.\n\n| Classification | Files |\n|---|---:|\n${Object.entries(counts).map(([k,v])=>`| ${k} | ${v} |`).join('\n')}\n`);
fs.writeFileSync('docs/maintenance/phase2-document-retention.md',`# Phase 2 retention review\n\n[START HERE](../architecture/README-PHASE2-MIGRATION.md) · [Full inventory](../architecture/phase2-document-inventory.json)\n\nNo historical source/evidence was deleted or moved. ${links} architecture links make a mass path migration unnecessary churn. Existing ignore rules exclude credentials, .env files, dependencies, worktrees and deployment caches. Non-secret AWS resource identities and historical local-path strings are provenance, not credentials; local executables/caches themselves are not added.\n\nKeep regression tests, synthetic fixtures, resource accounting, accepted manifests, exact-byte receipts, current contracts and final reports. Old security candidates remain historical, never the selected live policy.\n\n## Proposed deletion review queue (not authorized)\n\nThe machine inventory's DUPLICATE entries identify byte-identical candidate outputs and their identicalTo source. TEMPORARY_DIAGNOSTIC identifies investigation records. These are a review queue only: no item is currently approved for deletion because separate runs/reports may depend on its path and provenance. Recheck inbound links, receipt hashes and audit value before any later deletion. No test is removed merely because it has passed.\n`);
console.log(JSON.stringify({files:entries.length,counts,links,pathsMoved:0}));
