import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const E='docs/architecture/core-quota-evidence-2026-10-06',P='docs/architecture/core-2b5a-evidence-2026-10-06',read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const c=read(E+'/candidate.json'),old=read(P+'/candidate.json');assert.equal(sha(P+'/product.template.json'),old.productSha256);assert.equal(sha(E+'/product.template.json'),c.productSha256);assert.equal(sha(E+'/security.template.json'),old.securitySha256);assert.equal(sha(c.zipPath),old.zipSha256);assert.equal(sha(old.zipPath),old.zipSha256);
const before=read(P+'/product.template.json'),after=read(E+'/product.template.json');assert.ok(!Object.hasOwn(after.Resources.Contracts.Properties,'ReservedConcurrentExecutions'));after.Resources.Contracts.Properties.ReservedConcurrentExecutions=5;assert.deepEqual(after,before);
assert.ok(read(E+'/validation.json').results.every(x=>x.exit===0));const iam=read(E+'/security-review.json');assert.equal(iam.failures.length,2);assert.deepEqual(iam.failures.map(f=>f.action).sort(),['cloudformation:CreateChangeSet','logs:PutLogEvents']);assert.ok(iam.analyzer.every(r=>r.findings.length===0));assert.ok(read(E+'/trust-review.json').results.every(r=>r.findings.length===0));assert.ok(read(E+'/logging-review.json').results.every(r=>r.pass));assert.ok(read(E+'/artifact-binding.json').results.every(r=>r.response.EvaluationResults.every(e=>e.EvalDecision!=='allowed')));assert.equal(read(E+'/baseline.json').legacy.total,2621);assert.equal(read(E+'/preservation.json').allAcceptedSourcesMatch,true);
const docs=['core-first-deployment-readiness.md','core-release1-acceptance.md','core-domain-plan.md'].map(n=>'docs/architecture/'+n);let links=0;for(const file of docs)for(const m of fs.readFileSync(file,'utf8').matchAll(/\]\(([^)]+)\)/g)){if(/^https?:/.test(m[1]))continue;assert.ok(fs.existsSync(path.resolve(path.dirname(file),m[1].split('#')[0])),'Broken link '+m[1]);links++;}
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).filter(d=>!['node_modules','.build','cdk.out'].includes(d.name)).flatMap(d=>d.isDirectory()?walk(p+'/'+d.name):[p+'/'+d.name]);const files=[...walk('scripts/core-quota'),...walk('domains/shared-core'),...walk('infrastructure/domains/core'),...docs,'domains/team-hub/cutover/core-client.mjs'];
for(const file of [...files,...walk(E)]){const text=fs.readFileSync(file,'utf8');for(const pattern of [/\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/,/eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/"(?:SecretAccessKey|SessionToken|password)"\s*:\s*"[^"\s]+"/])assert.ok(!pattern.test(text),'Credential literal in '+file);}
save('source-manifest',{at:new Date().toISOString(),files:files.map(p=>({path:p,sha256:sha(p)})),candidate:c.productSha256,security:c.securitySha256,runtime:c.zipSha256});
save('final-review',{at:new Date().toISOString(),verdict:'CORE QUOTA CORRECTION BLOCKED',quotaBlockerResolved:true,deployable:false,reason:'Unchanged exact-template deployment URL/object bindings reject revised product',secretScan:'PASS',documentationLinks:links,validation:read(E+'/validation.json'),analyzerFindings:0,positiveIam:{mainPassed:10,mainTotal:12,loggingDiscrepancyClassified:true,newTemplateDenied:true,additionalObjectReadPositivesPassed:0,additionalObjectReadPositivesTotal:2},negativeIam:{passed:27,total:27},runtimeUnchanged:true,securityUnchanged:true,protectedDomainsUnchanged:true,awsChanges:0,quotaChanges:0,productionChanges:0,ledgerOwnershipRowsChanged:0});console.log(JSON.stringify({quotaResolved:true,ready:false,secretScan:'PASS',links,awsChanges:0}));
