import assert from 'node:assert/strict';import {pin,read,save,E,P,core,identity} from './aws.mjs';import {op,assume} from './operations.mjs';
const [kind,mode]=process.argv.slice(2);assert.ok(['security','product'].includes(kind));assert.ok(['prepare','inspect','execute','status'].includes(mode));const c=pin(),stack=core+(kind==='security'?'-Security':''),restricted=kind==='product';const who=restricted?await assume():await identity();
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
if(mode==='prepare'){assert.equal(read(E+'/published.json').complete,true);const args=['--stack-name',stack,'--change-set-name',kind==='security'?'core-security-pinned-20261006':'core-release1-pinned-20261006','--change-set-type','CREATE','--capabilities','CAPABILITY_NAMED_IAM',...(restricted?['--template-url',c.templateUrl,'--role-arn',c.executionRole]:['--template-body','file://'+P+'/security.template.json'])];const r=await op('cloudformation','create-change-set',args,restricted);save(kind+'-prepared',{...r,at:new Date().toISOString(),identity:who});console.log(JSON.stringify(r));}
else if(mode==='inspect'||mode==='execute'){
 const id=read(E+'/'+kind+'-prepared.json').Id;const cs=await op('cloudformation','describe-change-set',['--stack-name',stack,'--change-set-name',id,'--include-property-values'],restricted);save(kind+'-change-set',cs);assert.equal(cs.Status,'CREATE_COMPLETE');assert.equal(cs.ExecutionStatus,'AVAILABLE');assert.equal(cs.StackName,stack);const desired=read(P+'/'+kind+'.template.json');const actual=await op('cloudformation','get-template',['--stack-name',stack,'--change-set-name',id,'--template-stage','Original'],restricted);assert.deepEqual(stable(typeof actual.TemplateBody==='string'?JSON.parse(actual.TemplateBody):actual.TemplateBody),stable(desired));
 const changes=cs.Changes.map(c=>c.ResourceChange);assert.equal(changes.length,kind==='security'?5:8);assert.deepEqual(changes.map(r=>r.LogicalResourceId).sort(),Object.keys(desired.Resources).sort());for(const r of changes){assert.equal(r.Action,'Add');assert.equal(r.ResourceType,desired.Resources[r.LogicalResourceId].Type);assert.ok(!r.Replacement||r.Replacement==='False');}
 const gate={at:new Date().toISOString(),ready:true,stack,changeSetId:id,identity:who,candidate:kind==='security'?c.securitySha256:c.productSha256,resources:changes.length,additions:changes.length,modifications:0,deletions:0,replacements:0,unexpected:0,rollbackEnabledForExecution:true};save(kind+'-gate',gate);console.log(JSON.stringify(gate));
 if(mode==='execute'){await op('cloudformation','execute-change-set',['--stack-name',stack,'--change-set-name',id,'--no-disable-rollback','--client-request-token','core-'+kind+'-'+gate.candidate.slice(0,24)],restricted);save(kind+'-executed',{at:new Date().toISOString(),changeSetId:id,rollbackEnabled:true,identity:who});console.log('Executed reviewed '+kind+' change set with rollback enabled.');}
}else{
 const s=(await op('cloudformation','describe-stacks',['--stack-name',stack],restricted)).Stacks[0];const events=(await op('cloudformation','describe-stack-events',['--stack-name',stack],restricted)).StackEvents;save(kind+'-status',{at:new Date().toISOString(),stack:s,events});console.log(JSON.stringify({stack,status:s.StackStatus,disableRollback:s.DisableRollback,recent:events.slice(0,7).map(e=>({id:e.LogicalResourceId,status:e.ResourceStatus,reason:e.ResourceStatusReason}))}));
}
