import fs from 'node:fs';import assert from 'node:assert/strict';
const p='scripts/core-live/local-acceptance.mjs',E='docs/architecture/core-live-evidence-2026-10-06';let s=fs.readFileSync(p,'utf8');
fs.copyFileSync(E+'/live-contracts.json',E+'/admin-evidence-before-helper-restart.json');
function replace(a,b){assert.ok(s.includes(a),'Missing helper edit');s=s.replace(a,b);}
replace("checks=[],personas=new Set(),tokens=new Map(),started=new Date().toISOString()","checks=[...read(E+'/admin-evidence-before-helper-restart.json').checks],personas=new Set(read(E+'/admin-evidence-before-helper-restart.json').personas),tokens=new Map(),started=read(E+'/admin-evidence-before-helper-restart.json').started");
replace("assert.equal(isAdmin,persona==='admin','Selected persona does not match existing groups');tokens.set(persona,token);","persona=isAdmin?'admin':'ordinary';assert.ok(!personas.has(persona),'ACCOUNT_ALREADY_VERIFIED_'+persona.toUpperCase());tokens.set(persona,token);");
replace("if(personas.has('admin')&&personas.has('ordinary')){await invoke('cursor-cross-actor',{...adminCursor,accessToken:tokens.get('ordinary')},error('INVALID_INPUT'));tokens.clear();adminCursor=undefined;allUsers=[];}record();}","if(personas.has('admin')&&personas.has('ordinary')){if(adminCursor)await invoke('cursor-cross-actor',{...adminCursor,accessToken:tokens.get('ordinary')},error('INVALID_INPUT'));else checks.push({label:'cursor-cross-actor',pass:true,liveTested:false,reason:'Optional extra case not run after helper restart; no admin token/cursor persisted. Required tamper, wrong environment/contract and Team binding tested live; actor binding covered offline.'});tokens.clear();adminCursor=undefined;allUsers=[];}record();return persona;}");
replace('<select id="persona"><option value="admin">Admin / SuperAdmin</option><option value="ordinary">Ordinary user</option></select>','<p>Account type is detected automatically from the existing Cognito groups.</p>');
replace("persona:document.querySelector('#persona').value","persona:'auto'");
replace("const {persona}=JSON.parse(body);assert.ok(['admin','ordinary'].includes(persona));assert.ok(!personas.has(persona),'Persona already completed');","const {persona}=JSON.parse(body);assert.equal(persona,'auto');");
replace("await run(token,persona);res.setHeader","const detectedPersona=await run(token,persona);res.setHeader");
replace("JSON.stringify({passed:true,persona,complete:personas.size===2,checks:checks.length})","JSON.stringify({passed:true,persona:detectedPersona,complete:personas.size===2,checks:checks.length})");
replace("console.log(JSON.stringify({persona,passed:true,complete:personas.size===2,checks:checks.length}));}catch{","console.log(JSON.stringify({persona:detectedPersona,passed:true,complete:personas.size===2,checks:checks.length}));}catch(error){");
replace("message:'Check session/persona. If a contract check failed, acceptance is stopped; no credentials recorded.'","code:error.message?.includes('ACCOUNT_ALREADY_VERIFIED_ADMIN')?'STILL_SIGNED_IN_AS_ADMIN':error.message?.includes('ACCOUNT_ALREADY_VERIFIED_ORDINARY')?'ORDINARY_ALREADY_VERIFIED':error.code??error.name,message:error.message?.includes('ACCOUNT_ALREADY_VERIFIED_ADMIN')?'Admin already passed. Enter the member account email/password and click Sign in / switch account first.':'Session verification failed; report only this code. No credentials recorded.'");
replace("console.log(JSON.stringify({requestFailed:true,acceptanceStopped:failed}));","console.log(JSON.stringify({requestFailed:true,acceptanceStopped:failed,code:error.message?.includes('ACCOUNT_ALREADY_VERIFIED_')?'ACCOUNT_ALREADY_VERIFIED':error.code??error.name}));");
replace("'Signed in. Select the matching account type and run Core checks.'","'Signed in. Click Run Core checks; account type is detected automatically.'");
fs.writeFileSync(p,s);
