import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {identity,read,save,E,P,core} from './aws.mjs';
await identity();const allowed={logs:['filter-log-events','describe-log-groups'],cloudwatch:['get-metric-statistics','describe-alarms'],secretsmanager:['describe-secret','get-resource-policy'],lambda:['get-policy']};
function aws(s,a,args=[]){assert.ok(allowed[s]?.includes(a));const out=execFileSync('aws',[s,a,...args,'--profile','default','--region','eu-north-1','--output','json','--no-cli-pager'],{encoding:'utf8',maxBuffer:12e6,windowsHide:true});return out.trim()?JSON.parse(out):{};}
const start=Date.parse(read(E+'/product-executed.json').at),end=Date.now(),logGroup='/project-respawn/Ntgre/core/contracts';
const logs=aws('logs','filter-log-events',['--log-group-name',logGroup,'--start-time',String(start)]),events=[];let secretPattern=false,dependencyErrors=0;
for(const event of logs.events??[]){const raw=JSON.parse(event.message);if(raw.type==='platform.initStart'&&/^arn:aws:lambda:eu-north-1::runtime:[a-f0-9]{64}$/.test(raw.record?.runtimeVersionArn??''))raw.record.runtimeVersionArn='AWS_RUNTIME_VERSION_IDENTIFIER';const message=JSON.stringify(raw);secretPattern ||= /\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\b|"(?:SecretString|accessToken|password)"\s*:|\b[a-f0-9]{64}\b/.test(message);let parsed;try{parsed=JSON.parse(message);}catch{parsed={type:'plain',message};}let app=parsed.message;if(typeof app==='string')try{app=JSON.parse(app);}catch{};if(parsed.Environment==='Ntgre')app=parsed;if(app?.outcome){dependencyErrors+=app.DependencyFailures??0;events.push({timestamp:event.timestamp,type:'application',requestId:app.requestId,contractVersion:app.contractVersion,outcome:app.outcome,durationMs:app.durationMs});}else events.push({timestamp:event.timestamp,type:parsed.type??'platform',requestId:parsed.record?.requestId,status:parsed.record?.status,durationMs:parsed.record?.metrics?.durationMs});}
assert.ok(events.length>0,'Logs not yet visible');assert.ok(!secretPattern,'Possible secret in live logs; stop without persisting values');assert.equal(dependencyErrors,0,'Live dependency failure; stop');
const metrics={};for(const metric of ['Invocations','Errors','Throttles','Duration']){const r=aws('cloudwatch','get-metric-statistics',['--namespace','AWS/Lambda','--metric-name',metric,'--dimensions','Name=FunctionName,Value='+core+'-Contracts','--start-time',new Date(start).toISOString(),'--end-time',new Date(end).toISOString(),'--period','60','--statistics',metric==='Duration'?'Average':'Sum']);metrics[metric]=r.Datapoints;}
const alarms=aws('cloudwatch','describe-alarms',['--alarm-name-prefix',core+'-']).MetricAlarms;const p=read(P+'/product.template.json'),expected=Object.values(p.Resources).filter(x=>x.Type==='AWS::CloudWatch::Alarm').map(x=>x.Properties);assert.deepEqual(alarms.map(x=>x.AlarmName).sort(),expected.map(x=>x.AlarmName).sort());for(const actual of alarms){const desired=expected.find(x=>x.AlarmName===actual.AlarmName);for(const key of ['Namespace','MetricName','Period','EvaluationPeriods','Threshold','ComparisonOperator','TreatMissingData'])assert.deepEqual(actual[key],desired[key]);}
const secret=aws('secretsmanager','describe-secret',['--secret-id',core+'-Cursor']);assert.equal(secret.Name,core+'-Cursor');assert.ok(!secret.KmsKeyId&&!secret.DeletedDate);const secretPolicy=aws('secretsmanager','get-resource-policy',['--secret-id',core+'-Cursor']);assert.ok(!secretPolicy.ResourcePolicy,'Unexpected secret resource policy');
const errors=metrics.Errors.reduce((n,x)=>n+(x.Sum??0),0),throttles=metrics.Throttles.reduce((n,x)=>n+(x.Sum??0),0),invocations=metrics.Invocations.reduce((n,x)=>n+(x.Sum??0),0);assert.equal(errors,0);assert.equal(throttles,0);
save('observability',{at:new Date().toISOString(),window:{start:new Date(start).toISOString(),end:new Date(end).toISOString()},events,metrics,invocations,errors,throttles,dependencyErrors,metricsVisible:invocations>0&&metrics.Duration.length>0,logsPresent:true,secretPatternScan:'PASS',secret:{arn:secret.ARN,awsManagedEncryption:true,rotationEnabled:secret.RotationEnabled??false,valueRead:false,resourcePolicyAbsent:true},alarms:alarms.map(x=>({name:x.AlarmName,state:x.StateValue,metric:x.MetricName,namespace:x.Namespace})),futureProductionMonitoring:'Assign alarm delivery and capacity ownership; validate operation/custom metric delivery before production. No new metric configuration applied.'});console.log(JSON.stringify({logs:events.length,invocations,errors,throttles,dependencyErrors,metricsVisible:invocations>0&&metrics.Duration.length>0,alarms:alarms.length,secretsRecorded:false}));
