import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
export const E='docs/architecture/team-hub-d1-execution-evidence-2026-10-08',P='docs/architecture/team-hub-c1-evidence-2026-10-07',B='docs/architecture/team-hub-core-integration-evidence-2026-10-07',product='ProjectRespawn-TeamHub-Ntgre',security=product+'-ReadProofSecurity',execution='arn:aws:iam::058264289478:role/'+product+'-ReadProofExecution',caller='arn:aws:iam::058264289478:role/'+product+'-Deploy';
export const json=p=>JSON.parse(fs.readFileSync(p)),read=n=>json(E+'/'+n+'.json'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),canonical=v=>JSON.stringify(v,(_,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
export function pin(){const c=json(P+'/candidate.json');assert.equal(sha(P+'/candidate.json'),json(P+'/final-review.json').candidateHash);for(const k of ['product','security'])assert.equal(sha(P+'/d1-after-c2-'+k+'.template.json'),c.d1AfterC2[k+'Sha256']);assert.equal(sha(c.d1.runtimePath),c.d1AfterC2.runtimeSha256);const bucket='cdk-hnb659fds-assets-058264289478-eu-north-1',key='team-hub/d1-after-c2/'+c.d1AfterC2.productSha256+'.template.json';const t=json(P+'/d1-after-c2-product.template.json'),assetKey=t.Resources.ParityReadFunction.Properties.Code.S3Key;return {...c.d1AfterC2,bucket,key,url:'https://'+bucket+'.s3.eu-north-1.amazonaws.com/'+key,zipPath:c.d1.runtimePath,zipSha256:c.d1AfterC2.runtimeSha256,assetKey,changes:read('artifact-review').changes};}
const exec=promisify(execFile);let credentials;
const allowed={sts:['get-caller-identity','assume-role'],iam:['get-role','get-policy','get-policy-version','get-role-policy','list-role-policies','list-attached-role-policies','simulate-custom-policy','simulate-principal-policy'],accessanalyzer:['validate-policy'],dynamodb:['get-item','query'],stepfunctions:['describe-state-machine'],cloudformation:['get-template','describe-stacks','list-stack-resources','describe-stack-events','create-change-set','describe-change-set','execute-change-set'],s3api:['head-object','put-object'],lambda:['get-function-configuration'],logs:['filter-log-events','describe-log-groups'],cloudwatch:['get-metric-statistics','describe-alarms','list-metrics'],apigatewayv2:['get-stage']};
export async function aws(s,a,input={},restricted=false){assert.ok(allowed[s]?.includes(a));const c=pin(),write=['create-change-set','execute-change-set','put-object'].includes(a);if(a==='assume-role')assert.equal(input.RoleArn,caller);
 if(write){assert.ok(!fs.existsSync(E+'/STOP.json'));assert.equal(read('preflight').complete,true);assert.equal(read('policy-review').complete,true);assert.equal(read('before/inventory').complete,true);assert.equal(read('before/preservation').complete,true);assert.equal(read('routes-before').complete,true);
  if(s==='s3api'){assert.equal(input.Bucket,c.bucket);assert.ok([c.key,c.assetKey].includes(input.Key));assert.equal(input.Body,input.Key===c.key?P+'/d1-after-c2-product.template.json':c.zipPath);assert.equal(input.ServerSideEncryption,'AES256');assert.equal(read('security-installed').verified,true);}
  else{const k=input.StackName===product?'product':'security';assert.equal(input.StackName,k==='product'?product:security);assert.equal(restricted,k==='product');if(a==='create-change-set'){assert.equal(input.ChangeSetType,'UPDATE');assert.equal(input.ChangeSetName,'team-hub-d1-monitoring-'+k+'-20261008');if(k==='product'){assert.equal(input.TemplateURL,c.url);assert.equal(input.RoleARN,execution);assert.equal(read('publication').verified,true);}else assert.equal(input.TemplateBody,fs.readFileSync(P+'/d1-after-c2-security.template.json','utf8'));}else{const g=read(k+'-gate');assert.equal(g.ready,true);assert.equal(input.ChangeSetName,g.changeSetId);assert.equal(input.DisableRollback,false);assert.ok(Date.now()-Date.parse(g.at)<300000);}}
 }
 const env={...process.env,AWS_MAX_ATTEMPTS:'1'};if(restricted){assert.ok(credentials);Object.assign(env,{AWS_ACCESS_KEY_ID:credentials.AccessKeyId,AWS_SECRET_ACCESS_KEY:credentials.SecretAccessKey,AWS_SESSION_TOKEN:credentials.SessionToken});delete env.AWS_PROFILE;delete env.AWS_DEFAULT_PROFILE;}
 fs.mkdirSync('.tmp/team-hub-d1',{recursive:true});const f='.tmp/team-hub-d1/'+crypto.randomUUID()+'.json',request={...input};if(a==='put-object')delete request.Body;fs.writeFileSync(f,JSON.stringify(request));
 try{const {stdout}=await exec('aws',[s,a,'--cli-input-json','file://'+f,...(a==='put-object'?['--body',input.Body]:[]),...(restricted?[]:['--profile','default']),'--region','eu-north-1','--output','json','--no-cli-pager'],{env,windowsHide:true,maxBuffer:32e6});if(write)fs.appendFileSync(E+'/aws-writes.jsonl',JSON.stringify({at:new Date().toISOString(),service:s,action:a,stack:input.StackName,key:input.Key,restricted})+'\n');return stdout.trim()?JSON.parse(stdout):{};}catch(e){const code=(e.stderr??'').match(/\(([^)]+)\)/)?.[1]??e.code??'COMMAND_FAILED';if(write)save('STOP',{at:new Date().toISOString(),service:s,action:a,code});throw Error(s+' '+a+': '+code+(write?'':': '+String(e.stderr??'').replace(/\s+/g,' ').slice(0,800)));}finally{fs.unlinkSync(f);}
}
export async function identity(){const r=await aws('sts','get-caller-identity');assert.equal(r.Account,'058264289478');assert.equal(r.Arn,'arn:aws:iam::058264289478:user/RavenTest');return r;}
export async function assume(){const r=await aws('sts','assume-role',{RoleArn:caller,RoleSessionName:'TeamHubD1Monitoring',DurationSeconds:3600});credentials=r.Credentials;const i=await aws('sts','get-caller-identity',{},true);assert.equal(i.Account,'058264289478');assert.ok(i.Arn.startsWith('arn:aws:sts::058264289478:assumed-role/ProjectRespawn-TeamHub-Ntgre-Deploy/'));save('restricted-identity',{at:new Date().toISOString(),identity:i});return i;}
