import assert from 'node:assert/strict';import {aws,read,save,product} from './aws.mjs';
const p=read('probes');assert.equal(p.complete,true);const names=['Requests','AuthorizationFailures','DependencyFailures','CoreDependencyFailures','TransactionConflicts','WriterNotAuthoritative','AuthorityUnavailable','AuthorityEpochMismatch'];
const r={at:new Date().toISOString(),window:p.metricWindow,logs:[],custom:[],native:[],complete:false,pending:[]};
const sum=points=>points.length?points.reduce((n,x)=>n+x.Sum,0):null;
async function metric(namespace,name,dimensions){const a=await aws('cloudwatch','get-metric-statistics',{Namespace:namespace,MetricName:name,Dimensions:dimensions,StartTime:p.metricWindow.start,EndTime:p.metricWindow.end,Period:60,Statistics:['Sum']});return {namespace,name,dimensions,datapoints:a.Datapoints,observed:sum(a.Datapoints)};}
function parse(message){let v;try{v=JSON.parse(message);}catch{return null;}if(typeof v.message==='string'){try{v=JSON.parse(v.message);}catch{return null;}}else if(v.message&&typeof v.message==='object')v=v.message;return v?._aws?.CloudWatchMetrics?.[0]?.Namespace==='ProjectRespawn/TeamHub'?v:null;}
for(const runtime of ['read','command']){
 let next;const events=[];do{const a=await aws('logs','filter-log-events',{logGroupName:'/project-respawn/Ntgre/team-hub/parity-'+runtime,startTime:Date.parse(p.metricWindow.start),endTime:Date.parse(p.metricWindow.end),...(next?{nextToken:next}:{})});for(const e of a.events??[]){assert.ok(!/\beyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{10,}\b|\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/.test(e.message),'Sensitive material in runtime log');const v=parse(e.message);if(!v)continue;const allowed=new Set(['_aws','Environment','Runtime','event','operation','requestId','status','code',...names]);assert.ok(Object.keys(v).every(k=>allowed.has(k)),'Unexpected application log field');assert.equal(v.Environment,'Ntgre');assert.equal(v.Runtime,runtime);assert.deepEqual(v._aws.CloudWatchMetrics[0].Dimensions,[['Environment','Runtime']]);events.push({eventId:e.eventId,timestamp:e.timestamp,logStream:e.logStreamName,metric:v});}const old=next;next=a.nextToken;if(next===old)break;}while(next);
 const expectedRequests=p.requests.filter(x=>x.runtime===runtime),expected={Requests:expectedRequests.length,AuthorizationFailures:expectedRequests.filter(x=>x.kind!=='core-success').length,DependencyFailures:0,CoreDependencyFailures:0,TransactionConflicts:0,WriterNotAuthoritative:expectedRequests.filter(x=>x.kind==='http-denial').length,AuthorityUnavailable:0,AuthorityEpochMismatch:0};
 for(const q of expectedRequests){const match=events.filter(e=>e.metric.requestId===q.requestId);if(match.length!==(q.kind==='http-denial'?2:1)){r.pending.push('logs:'+q.requestId);continue;}const counts=Object.fromEntries(names.map(n=>[n,match.reduce((v,e)=>v+e.metric[n],0)]));assert.equal(counts.Requests,1);assert.equal(counts.AuthorizationFailures,q.kind==='core-success'?0:1);assert.equal(counts.WriterNotAuthoritative,q.kind==='http-denial'?1:0);assert.equal(counts.DependencyFailures,0);}
 const unknown=events.filter(e=>!expectedRequests.some(q=>q.requestId===e.metric.requestId));assert.equal(unknown.length,0,'Unrelated invocations in bounded metric window; inspect before claiming exact counts');r.logs.push({runtime,events,expectedRequests:expectedRequests.length,expected,matchedRequestIds:expectedRequests.filter(q=>events.some(e=>e.metric.requestId===q.requestId)).length});
 for(let i=0;i<names.length;i+=4){const batch=await Promise.all(names.slice(i,i+4).map(async n=>{const v=await metric('ProjectRespawn/TeamHub',n,[{Name:'Environment',Value:'Ntgre'},{Name:'Runtime',Value:runtime}]);v.expected=expected[n];if(v.observed===null||v.observed<expected[n])r.pending.push('metric:'+runtime+':'+n);else assert.equal(v.observed,expected[n],runtime+' '+n);return v;}));r.custom.push(...batch);}
}
const checks=[['AWS/ApiGateway','Count',[{Name:'ApiId',Value:'t54b88casf'}],13],['AWS/ApiGateway','4xx',[{Name:'ApiId',Value:'t54b88casf'}],13]];
for(const q of p.requests.filter(x=>x.kind==='http-denial'))checks.push(['AWS/ApiGateway','Count',[{Name:'ApiId',Value:'t54b88casf'},{Name:'Stage',Value:'$default'},{Name:'Method',Value:q.method},{Name:'Resource',Value:q.path}],1]);
for(const runtime of ['read','command'])for(const name of ['Invocations','Errors','Throttles'])checks.push(['AWS/Lambda',name,[{Name:'FunctionName',Value:product+'-Parity'+(runtime==='read'?'Read':'Command')}],name==='Invocations'?p.requests.filter(x=>x.runtime===runtime).length:null]);
for(let i=0;i<checks.length;i+=4){const batch=await Promise.all(checks.slice(i,i+4).map(async ([ns,name,dims,minimum])=>{const v=await metric(ns,name,dims);v.minimum=minimum;if(minimum!==null&&(v.observed===null||v.observed<minimum))r.pending.push('native:'+name+':'+JSON.stringify(dims));return v;}));r.native.push(...batch);}
r.complete=r.pending.length===0;save('metrics-latest',r);console.log(JSON.stringify({complete:r.complete,pending:r.pending,logEvents:r.logs.reduce((n,x)=>n+x.events.length,0),custom:r.custom.map(x=>({runtime:x.dimensions[1].Value,name:x.name,observed:x.observed,expected:x.expected})),nativeChecks:r.native.length}));
