import assert from 'node:assert/strict';import fs from 'node:fs';import {LambdaClient,InvokeCommand} from '@aws-sdk/client-lambda';import {fromIni} from '@aws-sdk/credential-providers';import {reuseSessions} from '../team-hub-2b6/reuse-sessions.mjs';import {identity,read,save,json,P,product,E} from './aws.mjs';
await identity();assert.equal(read('product-installed').verified,true);assert.ok(!fs.existsSync(E+'/probes.json'),'Do not automatically repeat probes');
const auth=await reuseSessions();assert.ok(auth.sessions.has('admin')&&auth.sessions.has('ordinary'));const client=new LambdaClient({region:'eu-north-1',credentials:fromIni({profile:'default'}),maxAttempts:1});const token=persona=>{const s=auth.sessions.get(persona);const t=s[Object.keys(s).find(k=>k.endsWith('.accessToken'))];assert.ok(t);return t;};
const r={start:new Date().toISOString(),requests:[],complete:false,tokensPersisted:false},persist=()=>save('probes',r);persist();
function emfs(raw){const rows=[];for(const line of raw.split('\n')){try{const offset=line.indexOf('{');if(offset<0)continue;let v=JSON.parse(line.slice(offset));if(typeof v.message==='string'){try{v=JSON.parse(v.message);}catch{}}else if(v.message&&typeof v.message==='object')v=v.message;if(v._aws?.CloudWatchMetrics?.[0]?.Namespace==='ProjectRespawn/TeamHub')rows.push(v);}catch{}}return rows;}
try{
 const template=json(P+'/d1-after-c2-product.template.json');for(const [id,res]of Object.entries(template.Resources).filter(([id,x])=>id.startsWith('Parity')&&x.Type==='AWS::ApiGatewayV2::Route')){const [method,path]=res.Properties.RouteKey.split(' '),start=new Date().toISOString();const response=await fetch('https://t54b88casf.execute-api.eu-north-1.amazonaws.com'+path.replace(/\{[^}]+\}/g,'team:d1-denial-proof'),{method,headers:{Authorization:'Bearer '+token('admin'),...(method==='GET'?{}:{'Content-Type':'application/json'})},...(method==='GET'?{}:{body:'{}'}),signal:AbortSignal.timeout(15000)});const body=await response.json();const requestId=response.headers.get('apigw-requestid');r.requests.push({kind:'http-denial',id,method,path,runtime:method==='GET'?'read':'command',start,end:new Date().toISOString(),status:response.status,code:body.error?.code,requestId});persist();assert.equal(response.status,403);assert.equal(body.error?.code,'FORBIDDEN');assert.ok(requestId);}
 for(const runtime of ['read','command'])for(let repeat=0;repeat<2;repeat++)for(const persona of ['admin','ordinary']){const start=new Date().toISOString();let event={contractVersion:'team-hub.core-integration-proof.v1',accessToken:token(persona),operation:persona==='admin'?'authorization':'search',...(persona==='ordinary'?{query:'d1-nonmutating-proof',limit:1}:{})};const result=await client.send(new InvokeCommand({FunctionName:product+'-Parity'+(runtime==='read'?'Read':'Command'),InvocationType:'RequestResponse',LogType:'Tail',Payload:Buffer.from(JSON.stringify(event))}));event=null;assert.equal(result.StatusCode,200);assert.ok(!result.FunctionError);const answer=JSON.parse(Buffer.from(result.Payload).toString()),metrics=emfs(Buffer.from(result.LogResult??'','base64').toString());assert.equal(metrics.length,1);const metric=metrics[0];assert.ok(Object.keys(metric).every(k=>['_aws','Environment','Runtime','event','operation','requestId','status','code','Requests','AuthorizationFailures','DependencyFailures','CoreDependencyFailures','TransactionConflicts','WriterNotAuthoritative','AuthorityUnavailable','AuthorityEpochMismatch'].includes(k)),'Unexpected log field');assert.equal(metric.event,'TEAM_REQUEST');assert.equal(metric.Runtime,runtime);assert.equal(metric.Requests,1);assert.equal(metric.AuthorizationFailures,persona==='ordinary'?1:0);assert.equal(metric.DependencyFailures,0);assert.equal(metric.CoreDependencyFailures,0);assert.equal(metric.WriterNotAuthoritative,0);if(persona==='admin'){assert.equal(answer.ok,true);assert.equal(answer.data.teamsAdmin,true);}else{assert.equal(answer.ok,false);assert.equal(answer.error.code,'FORBIDDEN');}
 r.requests.push({kind:persona==='admin'?'core-success':'core-denial',runtime,repeat,start,end:new Date().toISOString(),ok:answer.ok,code:answer.error?.code,requestId:metric.requestId,metric});persist();}
 r.end=new Date().toISOString();r.metricWindow={start:new Date(Math.floor(Date.parse(r.start)/60000)*60000).toISOString(),end:new Date(Math.ceil(Date.parse(r.end)/60000)*60000).toISOString()};assert.equal(r.requests.length,21);r.complete=true;persist();save('routes-after',{at:r.end,complete:true,checks:r.requests.filter(x=>x.kind==='http-denial').map(x=>({id:x.id,status:x.status,requestId:x.requestId})),tokensPersisted:false});console.log(JSON.stringify({complete:true,httpDenials:13,coreSuccess:4,coreDenial:4,window:r.metricWindow}));
}finally{for(const s of auth.sessions.values())for(const k of Object.keys(s))delete s[k];auth.sessions.clear();client.destroy();}
