import assert from 'node:assert/strict';import {P,json,sha,save,canonical} from './aws.mjs';
const c=json(P+'/candidate.json');assert.equal(sha(P+'/candidate.json'),json(P+'/final-review.json').candidateHash);assert.equal(sha(c.d1.runtimePath),c.d1AfterC2.runtimeSha256);for(const f of c.d1.sourceHashes)assert.equal(sha(f.path),f.sha256,f.path);
const changes={},next={},before={};for(const k of ['product','security']){const path=P+'/d1-after-c2-'+k+'.template.json';assert.equal(sha(path),c.d1AfterC2[k+'Sha256']);const a=before[k]=json(P+'/c2-'+k+'.template.json'),b=next[k]=json(path);assert.deepEqual(Object.keys(a.Resources),Object.keys(b.Resources));changes[k]=Object.keys(b.Resources).filter(id=>canonical(a.Resources[id])!==canonical(b.Resources[id])).sort();const restored=structuredClone(b);for(const id of changes[k])restored.Resources[id]=a.Resources[id];assert.deepEqual(restored,a);}
assert.deepEqual(changes.product,['ParityCommandFunction','ParityReadFunction','Stage']);assert.deepEqual(changes.security,['ExecutionBoundary','ExecutionRole','PreparationCaller']);assert.equal(Object.keys(next.product.Resources).length,40);assert.equal(Object.keys(next.security.Resources).length,7);
for(const kind of ['Read','Command']){const id='Parity'+kind+'Function',copy=structuredClone(next.product.Resources[id]);copy.Properties.Code=before.product.Resources[id].Properties.Code;assert.deepEqual(copy,before.product.Resources[id]);assert.equal(next.product.Resources[id].Properties.Code.S3Key,next.product.Resources.ParityReadFunction.Properties.Code.S3Key);assert.deepEqual(next.product.Resources['Parity'+kind+'Role'],before.product.Resources['Parity'+kind+'Role']);assert.deepEqual(next.security.Resources['Parity'+kind+'Boundary'],before.security.Resources['Parity'+kind+'Boundary']);}
const stage=structuredClone(next.product.Resources.Stage);assert.equal(stage.Properties.DefaultRouteSettings.DetailedMetricsEnabled,true);stage.Properties.DefaultRouteSettings=before.product.Resources.Stage.Properties.DefaultRouteSettings;assert.deepEqual(stage,before.product.Resources.Stage);
const bucket='cdk-hnb659fds-assets-058264289478-eu-north-1',key='team-hub/d1-after-c2/'+c.d1AfterC2.productSha256+'.template.json',url='https://'+bucket+'.s3.eu-north-1.amazonaws.com/'+key,assetKey=next.product.Resources.ParityReadFunction.Properties.Code.S3Key,oldZip='arn:aws:s3:::'+bucket+'/team-hub/core-integration/9d16027de6526c9a787a099100dfd9b40b615382e22044e11ee93c705dbe86c8.zip',newZip='arn:aws:s3:::'+bucket+'/'+assetKey;
const undo=v=>Array.isArray(v)?v.filter(x=>x!==url&&x!=='arn:aws:s3:::'+bucket+'/'+key).map(undo):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).map(([k,x])=>[k,undo(x)])):v===newZip?oldZip:v;
assert.deepEqual(undo(next.security),before.security,'Only exact template addition and reviewed old ZIP replacement permitted');
save('artifact-review',{at:new Date().toISOString(),complete:true,manifestSha256:sha(P+'/candidate.json'),hashes:c.d1AfterC2,changes,runtimeIamUnchanged:true,c2Preserved:true,resourceCounts:{product:40,security:7},removedArtifactReference:oldZip,newArtifactReference:newZip,productUrl:url,sourceHashesVerified:c.d1.sourceHashes.length});console.log(JSON.stringify({complete:true,changes,c2Preserved:true}));
