import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {pins,read,pinned} from '../../../docs/architecture/team-hub-2b2-release-execution-evidence-2026-10-05/common.mjs';
pins();
export const dir='docs/architecture/team-hub-2b2-caller-release-evidence-2026-10-05';fs.mkdirSync(dir,{recursive:true});
const save=(n,v)=>fs.writeFileSync(dir+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const policy=read(pinned+'/deployment-caller-policy.json');
const inspections=['cloudformation:ListStackResources','cloudformation:DescribeStackResource','cloudformation:ListChangeSets'];
policy.Statement[0].NotAction.push(...inspections,'s3:GetObject','s3:GetObjectVersion');
policy.Statement[1].Action.push(...inspections);
const bucket='cdk-hnb659fds-assets-058264289478-eu-north-1',templateKey='team-hub/read-proof/0796ee8170bd0417fca6b2806e58e48c18278b4e6c32999824f55ac65898e7ee.template.json',zipKey='da4d9e570523cbbdcff21572d059f18227d03c12482620e916752f2863b87da1.zip';
const objects=[templateKey,zipKey].map(k=>'arn:aws:s3:::'+bucket+'/'+k);
policy.Statement.push({Effect:'Allow',Action:['s3:GetObject','s3:GetObjectVersion'],Resource:objects},{Effect:'Deny',Action:'s3:*',NotResource:objects});
assert.ok(JSON.stringify(policy).length<=6144);
const trust={Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{AWS:'arn:aws:iam::058264289478:user/RavenTest'},Action:'sts:AssumeRole'}]};
const old=read(pinned+'/first-create-security.template.json'),template=structuredClone(old);
template.Resources.PreparationCaller.Properties.PolicyDocument=policy;
template.Resources.DeploymentCaller={Type:'AWS::IAM::Role',Properties:{RoleName:'ProjectRespawn-TeamHub-Ntgre-Deploy',Description:'Restricted orchestration of the pinned Ntgre Team Hub read-proof product stack',MaxSessionDuration:3600,AssumeRolePolicyDocument:trust,ManagedPolicyArns:[{Ref:'PreparationCaller'}],PermissionsBoundary:{Ref:'PreparationCaller'},Tags:[{Key:'Project',Value:'ProjectRespawn'},{Key:'Domain',Value:'TeamHub'},{Key:'Environment',Value:'Ntgre'}]}};
for(const id of ['PreviewBoundary','ExecutionBoundary','ExecutionRole'])assert.deepEqual(template.Resources[id],old.Resources[id]);
save('caller-policy',policy);save('caller-trust',trust);save('caller-security.template',template);
const files=['caller-policy','caller-trust','caller-security.template'].map(n=>({path:dir+'/'+n+'.json',sha256:crypto.createHash('sha256').update(fs.readFileSync(dir+'/'+n+'.json')).digest('hex')}));
const revision=crypto.createHash('sha256').update(JSON.stringify(files)).digest('hex');
save('candidate',{revision,baseSecurityRevision:'3e5a12edf9074bb8dc8d7bf0d83783b641aefc3973514e08aa4cc80f530050de',productRevision:'d458da9a7a8d1d519aaab05418fda95097a26256da0a297b71c95a5aaef5085f',files,resources:{before:4,after:5,additions:['DeploymentCaller'],modifications:['PreparationCaller'],deletions:[],replacements:[]},operator:'arn:aws:iam::058264289478:user/RavenTest',caller:'arn:aws:iam::058264289478:role/ProjectRespawn-TeamHub-Ntgre-Deploy',execution:'arn:aws:iam::058264289478:role/ProjectRespawn-TeamHub-Ntgre-ReadProofExecution',boundary:'arn:aws:iam::058264289478:policy/ProjectRespawn-TeamHub-Ntgre-ReadProofPreparation',bucket,templateKey,zipKey,templateUrl:'https://'+bucket+'.s3.eu-north-1.amazonaws.com/'+templateKey,executionChanged:false,runtimeChanged:false,roleNameClarification:'User explicitly confirmed existing ReadProofExecution role on 2026-10-05',policyCharacters:JSON.stringify(policy).length});
console.log(JSON.stringify({revision,resources:5,additions:1,modifications:1,executionChanged:false,runtimeChanged:false,policyCharacters:JSON.stringify(policy).length}));
