import assert from 'node:assert/strict';
import {aws,read,save,verify,expiry,equal,dir} from './common.mjs';
const c=verify(),mode=process.argv[2],name='ProjectRespawn-TeamHub-Ntgre-ReadProofSecurity';
const v=read(dir+'/validation.json');assert.equal(v.findings.length,0);assert.equal(v.failures.length,0);expiry();
if(mode==='prepare'){const result=await aws('cloudformation','create-change-set','--stack-name',name,'--change-set-name','team-hub-restricted-caller-20261005','--change-set-type','UPDATE','--template-body','file://'+dir+'/caller-security.template.json','--capabilities','CAPABILITY_NAMED_IAM','--description','Restricted caller extension '+c.revision);save('extension-prepared',result);console.log(JSON.stringify(result));}
else if(mode==='inspect'||mode==='execute'){
 const p=read(dir+'/extension-prepared.json'),cs=await aws('cloudformation','describe-change-set','--change-set-name',p.Id,'--include-property-values');save('extension-change-set',cs);assert.equal(cs.Status,'CREATE_COMPLETE');assert.equal(cs.ExecutionStatus,'AVAILABLE');
 equal(cs.Changes.map(x=>({id:x.ResourceChange.LogicalResourceId,action:x.ResourceChange.Action})).sort((a,b)=>a.id.localeCompare(b.id)),[{id:'DeploymentCaller',action:'Add'},{id:'PreparationCaller',action:'Modify'}]);assert.ok(cs.Changes.every(x=>!x.ResourceChange.Replacement||x.ResourceChange.Replacement==='False'));
 const body=(await aws('cloudformation','get-template','--stack-name',name,'--change-set-name',p.Id,'--template-stage','Original')).TemplateBody;equal(typeof body==='string'?JSON.parse(body):body,read(dir+'/caller-security.template.json'));
 const gate={at:new Date().toISOString(),ready:true,candidate:c.revision,changeSet:p.Id,additions:1,modifications:1,deletions:0,replacements:0,executionChanged:false,runtimeChanged:false,time:expiry(),positive:v.positive,negative:v.negative,analyzerFindings:0};save('caller-gate',gate);console.log(JSON.stringify(gate));
 if(mode==='execute'){await aws('cloudformation','execute-change-set','--change-set-name',p.Id,'--no-disable-rollback','--client-request-token','team-hub-caller-bfc982cd-20261005');save('extension-executed',{at:new Date().toISOString(),changeSet:p.Id,rollbackEnabled:true});console.log('Caller extension executed with rollback enabled.');}
}else if(mode==='status'){const s=(await aws('cloudformation','describe-stacks','--stack-name',name)).Stacks[0];const e=(await aws('cloudformation','describe-stack-events','--stack-name',name)).StackEvents;save('security-stack',s);save('extension-events',e);console.log(JSON.stringify({status:s.StackStatus,rollbackEnabled:!s.DisableRollback,recent:e.slice(0,5).map(x=>({id:x.LogicalResourceId,status:x.ResourceStatus,reason:x.ResourceStatusReason}))}));}else throw Error('Invalid mode');
