import assert from 'node:assert/strict';
import {aws,read,save,dir} from './common.mjs';
const auth=read(dir+'/live-auth.json');assert.equal(auth.passed,true);const ownership=read(dir+'/ownership.json'),apiId=ownership.api.ApiId,fn='ProjectRespawn-TeamHub-Ntgre-PreviewRead';
const lambda=await aws('lambda','get-function-configuration','--function-name',fn);assert.equal(lambda.State,'Active');assert.equal(lambda.LastUpdateStatus,'Successful');assert.equal(lambda.CodeSha256,Buffer.from('b9138c4dda6962a05aac55a1b28eb58905424d07554669bcbc23554772915950','hex').toString('base64'));
const api={};for(const what of ['stages','authorizers','integrations','routes'])api[what]=(await aws('apigatewayv2','get-'+what,'--api-id',apiId)).Items;
assert.equal(api.routes.length,1);assert.equal(api.routes[0].RouteKey,'GET /v1/team-hub/preview');assert.equal(api.routes[0].AuthorizationType,'JWT');assert.equal(api.authorizers.length,1);assert.equal(api.authorizers[0].JwtConfiguration.Issuer,'https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_n24iLL7QE');assert.deepEqual(api.authorizers[0].JwtConfiguration.Audience,['1iq7ovjaf7d16imdvbqgfgvf86']);assert.equal(api.stages[0].StageName,'$default');
const start=read(dir+'/product-executed.json').at,end=new Date().toISOString();
const logs=await aws('logs','filter-log-events','--log-group-name','/project-respawn/Ntgre/team-hub/preview','--start-time',String(Date.parse(start)));save('runtime-logs',logs);
const metrics={};for(const [ns,name,dimension,value] of [['AWS/Lambda','Invocations','FunctionName',fn],['AWS/Lambda','Errors','FunctionName',fn],['AWS/Lambda','Duration','FunctionName',fn],['AWS/ApiGateway','Count','ApiId',apiId],['AWS/ApiGateway','4xx','ApiId',apiId],['AWS/ApiGateway','5xx','ApiId',apiId]]){metrics[ns+'/'+name]=await aws('cloudwatch','get-metric-statistics','--namespace',ns,'--metric-name',name,'--dimensions','Name='+dimension+',Value='+value,'--start-time',start,'--end-time',end,'--period','60','--statistics','Sum','Maximum');}
const alarms=(await aws('cloudwatch','describe-alarms','--alarm-names','ProjectRespawn-TeamHub-Ntgre-ReadProof-ReadErrors','ProjectRespawn-TeamHub-Ntgre-ReadProof-ApiErrors')).MetricAlarms;assert.equal(alarms.length,2);
const parsed=logs.events.map(e=>{try{return JSON.parse(e.message)}catch{return {raw:e.message}}});const reports=parsed.filter(e=>e.type==='platform.report');const app=parsed.map(e=>{try{return typeof e.message==='string'?JSON.parse(e.message):e.message}catch{return null}}).filter(e=>e?.domain==='TeamHub'&&e.status===200);
const sum=k=>metrics[k].Datapoints.reduce((n,x)=>n+(x.Sum??0),0);
const ct=await aws('cloudtrail','lookup-events','--lookup-attributes','AttributeKey=EventSource,AttributeValue=kms.amazonaws.com','--start-time',start,'--end-time',end);
const kms=ct.Events.map(e=>JSON.parse(e.CloudTrailEvent)).filter(e=>JSON.stringify(e).includes(fn)).map(e=>({at:e.eventTime,operation:e.eventName,errorCode:e.errorCode??null,errorMessage:e.errorMessage??null,requestId:e.requestID}));save('runtime-kms',kms);
const summary={at:end,start,lambda:{arn:lambda.FunctionArn,name:lambda.FunctionName,codeSha256:lambda.CodeSha256,state:lambda.State,lastUpdateStatus:lambda.LastUpdateStatus},api,metrics,alarms,initializationObserved:parsed.some(e=>e.type==='platform.initStart'),successfulReports:reports.filter(e=>e.record?.status==='success').length,applicationSuccessLogs:app.length,runtimeRequestId:reports.find(e=>e.record?.status==='success')?.record?.requestId,invocations:sum('AWS/Lambda/Invocations'),errors:sum('AWS/Lambda/Errors'),apiRequests:sum('AWS/ApiGateway/Count'),api5xx:sum('AWS/ApiGateway/5xx'),kmsSuccessfulDryRunProbes:kms.filter(e=>e.errorCode==='DryRunOperationException'&&e.errorMessage==='The request would have succeeded, but the DryRun option is set.'),kmsErrors:kms.filter(e=>e.errorCode&&!(e.errorCode==='DryRunOperationException'&&e.errorMessage==='The request would have succeeded, but the DryRun option is set.')),logErrors:logs.events.filter(e=>/AccessDenied|KMSAccessDenied|Runtime\.ImportModuleError/.test(e.message)).length};
summary.passed=summary.initializationObserved&&summary.successfulReports>=1&&summary.applicationSuccessLogs>=1&&summary.invocations>=1&&summary.errors===0&&summary.apiRequests>=5&&summary.api5xx===0&&summary.kmsErrors.length===0&&summary.logErrors===0&&alarms.every(a=>a.StateValue==='OK');save('observability',summary);console.log(JSON.stringify({...summary,api:undefined,metrics:undefined,alarms:alarms.map(a=>({name:a.AlarmName,state:a.StateValue}))}));if(!summary.passed)process.exitCode=1;

