import assert from 'node:assert/strict';
import {aws,read,save,verify,expiry,equal,dir,callerSession} from './common.mjs';
const c=verify(),mode=process.argv[2],name='ProjectRespawn-TeamHub-Ntgre',caller=await callerSession(),identity=await caller('sts','get-caller-identity');assert.ok(identity.Arn.includes(':assumed-role/ProjectRespawn-TeamHub-Ntgre-Deploy/'));
const expected=read('infrastructure/domains/team-hub/.build/offline-1791205212119/assembly/ProjectRespawn-TeamHub-Ntgre.template.json');
if(mode==='prepare'){
 const v=read(dir+'/live-validation.json');assert.equal(v.failures.length,0);assert.equal(v.findings.length,0);assert.equal(read(dir+'/legacy-after.json').beforeAfterEqual,true);assert.equal(read(dir+'/tournament-baseline.json').issues.length,0);assert.equal(read(dir+'/artifacts.json').objects.length,2);const time=expiry();
 const apis=(await aws('apigatewayv2','get-apis')).Items;const old=read('docs/architecture/team-hub-2b2-release-execution-evidence-2026-10-05/preflight.json').apis;equal(apis.map(a=>a.ApiId).sort(),old.map(a=>a.ApiId).sort());save('pre-product-apis',apis);
 const result=await caller('cloudformation','create-change-set','--stack-name',name,'--change-set-name','team-hub-read-proof-release1-20261005','--change-set-type','CREATE','--template-url',c.templateUrl,'--role-arn',c.execution,'--capabilities','CAPABILITY_NAMED_IAM','--tags','Key=Project,Value=ProjectRespawn','Key=Domain,Value=TeamHub','Key=Environment,Value=Ntgre','--description','Preserved Team Hub product d458da9a7a8d1d519aaab05418fda95097a26256da0a297b71c95a5aaef5085f');save('product-prepared',{at:new Date().toISOString(),identity,time,...result});console.log(JSON.stringify({identity,...result}));
}else if(mode==='inspect'||mode==='execute'){
 const p=read(dir+'/product-prepared.json'),cs=await caller('cloudformation','describe-change-set','--stack-name',name,'--change-set-name',p.Id,'--include-property-values');save('product-change-set',cs);assert.equal(cs.Status,'CREATE_COMPLETE');assert.equal(cs.ExecutionStatus,'AVAILABLE');assert.equal(cs.Changes.length,11);const stack=(await caller('cloudformation','describe-stacks','--stack-name',name)).Stacks[0];assert.equal(stack.RoleARN,c.execution);assert.equal(stack.DisableRollback,false);
 equal(cs.Changes.map(x=>x.ResourceChange.LogicalResourceId).sort(),Object.keys(expected.Resources).sort());for(const change of cs.Changes){const r=change.ResourceChange;assert.equal(r.Action,'Add');assert.equal(r.ResourceType,expected.Resources[r.LogicalResourceId].Type);assert.ok(!r.Replacement||r.Replacement==='False');}
 const t=(await caller('cloudformation','get-template','--stack-name',name,'--change-set-name',p.Id,'--template-stage','Original')).TemplateBody;equal(typeof t==='string'?JSON.parse(t):t,expected);save('product-aws-template',typeof t==='string'?JSON.parse(t):t);
 const head=await caller('s3api','head-object','--bucket',c.bucket,'--key',c.zipKey,'--checksum-mode','ENABLED');assert.equal(head.ServerSideEncryption,'AES256');assert.equal(head.ChecksumSHA256,Buffer.from('b9138c4dda6962a05aac55a1b28eb58905424d07554669bcbc23554772915950','hex').toString('base64'));
 const gate={at:new Date().toISOString(),ready:true,identity,execution:c.execution,product:c.productRevision,templateSha:'0796ee8170bd0417fca6b2806e58e48c18278b4e6c32999824f55ac65898e7ee',lambdaSha:'0e3fde08f1dbf3c1803ff1daac65e902117d757c76506d478112d5291814e7b3',stack:name,changeSet:p.Id,time:expiry(),additions:11,modifications:0,deletions:0,replacements:0,unexpected:0,rollbackEnabled:true,resources:Object.entries(expected.Resources).map(([id,r])=>({id,type:r.Type})),legacyVerified:true,tournamentVerified:true};save('product-execution-gate',gate);console.log(JSON.stringify(gate));
 if(mode==='execute'){await caller('cloudformation','execute-change-set','--stack-name',name,'--change-set-name',p.Id,'--no-disable-rollback','--client-request-token','team-hub-read-proof-d458da9a-20261005');save('product-executed',{at:new Date().toISOString(),identity,changeSet:p.Id,rollbackEnabled:true});console.log('Product executed USING RESTRICTED CALLER; rollback enabled.');}
}else if(mode==='status'){const stack=(await caller('cloudformation','describe-stacks','--stack-name',name)).Stacks[0];const events=(await caller('cloudformation','describe-stack-events','--stack-name',name)).StackEvents;save('product-stack',stack);save('product-events',events);console.log(JSON.stringify({status:stack.StackStatus,rollbackEnabled:!stack.DisableRollback,identity:identity.Arn,recent:events.slice(0,8).map(e=>({id:e.LogicalResourceId,status:e.ResourceStatus,reason:e.ResourceStatusReason}))}));}else throw Error('Invalid mode');

