import assert from 'node:assert/strict';
import {aws,read,save,verify,expiry,hash,dir,callerSession} from './common.mjs';
const c=verify();expiry();assert.equal(read(dir+'/installed-caller.json').canonicalEquivalent,true);
const file='infrastructure/domains/team-hub/.build/offline-1791205212119/assembly/ProjectRespawn-TeamHub-Ntgre.template.json',sha=hash(file),checksum=Buffer.from(sha,'hex').toString('base64');assert.equal(sha,'0796ee8170bd0417fca6b2806e58e48c18278b4e6c32999824f55ac65898e7ee');
let existed=false;try{await aws('s3api','head-object','--bucket',c.bucket,'--key',c.templateKey);existed=true;}catch(e){if(!/404|Not Found/.test(e.stderr??''))throw e;}
if(!existed)await aws('s3api','put-object','--bucket',c.bucket,'--key',c.templateKey,'--body',file,'--server-side-encryption','AES256','--checksum-algorithm','SHA256','--checksum-sha256',checksum,'--if-none-match','*');
const caller=await callerSession(),identity=await caller('sts','get-caller-identity');
const objects=[];for(const [key,expected,suffix] of [[c.templateKey,sha,'template.json'],[c.zipKey,'b9138c4dda6962a05aac55a1b28eb58905424d07554669bcbc23554772915950','lambda.zip']]){const head=await caller('s3api','head-object','--bucket',c.bucket,'--key',key,'--checksum-mode','ENABLED');assert.equal(head.ServerSideEncryption,'AES256');assert.equal(head.ChecksumSHA256,Buffer.from(expected,'hex').toString('base64'));const path='infrastructure/domains/team-hub/.build/offline-1791205212119/caller-readback-'+suffix;await caller('s3api','get-object','--bucket',c.bucket,'--key',key,path);assert.equal(hash(path),expected);objects.push({bucket:c.bucket,key,sha256:expected,head,actualCallerRead:true});}
save('artifacts',{at:new Date().toISOString(),templatePublished:!existed,lambdaRepublished:false,identity,objects,credentialsPersisted:false});console.log(JSON.stringify({caller:identity.Arn,objects:objects.map(x=>({key:x.key,encryption:x.head.ServerSideEncryption,sha256:x.sha256,callerRead:true}))}));
