import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {spawnSync} from 'node:child_process';
import {runtime,deployment,name,account,region,arn,executionArn} from './policies.mjs';import {E} from './aws.mjs';
assert.deepEqual(process.argv.slice(2),['--domain','core','--env','Ntgre','--offline']);
for(const k of ['AWS_REGION','AWS_DEFAULT_REGION','CDK_DEFAULT_REGION'])assert.ok(!process.env[k]||process.env[k]===region);assert.ok(!process.env.CDK_DEFAULT_ACCOUNT||process.env.CDK_DEFAULT_ACCOUNT===account);
const read=p=>JSON.parse(fs.readFileSync(p)),save=(n,v)=>fs.writeFileSync(`${E}/${n}.json`,JSON.stringify(v,null,2)+'\n'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const B='.tmp/core-2b5a';fs.mkdirSync(B,{recursive:true});fs.mkdirSync(E,{recursive:true});
const live=read(E+'/identity.json'),environment=live.environment,keys=read(E+'/encryption.json').keys.map(k=>{assert.equal(k.keyManager,'AWS');assert.equal(k.enabled,true);return k.arn;});assert.equal(keys.length,2);assert.ok(keys.includes(live.lambdaKey.arn));
const esbuild=createRequire(path.resolve('infrastructure/domains/core/package.json'))('esbuild');
const bundle=await esbuild.build({entryPoints:['domains/shared-core/entry.mjs'],outfile:B+'/index.js',bundle:true,format:'cjs',platform:'node',target:'node22',metafile:true,logLevel:'silent'});
assert.ok(Object.keys(bundle.metafile.inputs).every(p=>p.startsWith('domains/shared-core/')),'Foreign runtime closure');
// ZIP library is offline packaging, never runtime/domain coupling.
const {singleFileZip}=await import('../team-hub-2b4/zip.mjs');fs.writeFileSync(B+'/runtime.zip',singleFileZip('index.js',fs.readFileSync(B+'/index.js')));
const bucket='cdk-hnb659fds-assets-058264289478-eu-north-1',zipSha=sha(B+'/runtime.zip'),key=`core/2b5a/${zipSha}/runtime.zip`;
const {identity,boundary}=runtime(environment.poolId,keys);save('runtime-policy',identity);save('runtime-boundary',boundary);
const trust=principal=>({Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:principal,Action:'sts:AssumeRole'}]});
const product={Resources:{
 CursorSecret:{Type:'AWS::SecretsManager::Secret',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{Name:name+'-Cursor',GenerateSecretString:{PasswordLength:64,ExcludePunctuation:true,RequireEachIncludedType:false,ExcludeCharacters:'ghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'}}},
 Logs:{Type:'AWS::Logs::LogGroup',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{LogGroupName:'/project-respawn/Ntgre/core/contracts',RetentionInDays:30}},
 Runtime:{Type:'AWS::IAM::Role',Properties:{RoleName:name+'-Contracts',AssumeRolePolicyDocument:trust({Service:'lambda.amazonaws.com'}),PermissionsBoundary:arn('iam','policy/'+name+'-RuntimeBoundary'),Policies:[{PolicyName:'CoreRuntime',PolicyDocument:identity}]}},
 Contracts:{Type:'AWS::Lambda::Function',Properties:{FunctionName:name+'-Contracts',Runtime:'nodejs22.x',Handler:'index.handler',Architectures:['arm64'],MemorySize:256,Timeout:10,ReservedConcurrentExecutions:5,Role:{'Fn::GetAtt':['Runtime','Arn']},Code:{S3Bucket:bucket,S3Key:key},LoggingConfig:{LogGroup:{Ref:'Logs'},LogFormat:'JSON'},Environment:{Variables:{CORE_ENVIRONMENT:JSON.stringify(environment),CORE_CURSOR_SECRET_ARN:{Ref:'CursorSecret'}}}}}
 }};
for(const metric of ['Errors','Throttles','DependencyFailures','Denied'])product.Resources[metric]={Type:'AWS::CloudWatch::Alarm',Properties:{AlarmName:name+'-'+metric,Namespace:['Errors','Throttles'].includes(metric)?'AWS/Lambda':'ProjectRespawn/Core',MetricName:metric,Dimensions:['Errors','Throttles'].includes(metric)?[{Name:'FunctionName',Value:{Ref:'Contracts'}}]:[{Name:'Environment',Value:'Ntgre'}],Statistic:'Sum',Period:60,EvaluationPeriods:1,Threshold:metric==='Denied'?20:1,ComparisonOperator:'GreaterThanOrEqualToThreshold',TreatMissingData:'notBreaching'}};
// Product-only first synth makes the caller URL a hash of final CDK bytes.
const synth=()=>{const out=path.resolve(B+'/assembly');const r=spawnSync(process.execPath,[B+'/app.cjs'],{encoding:'utf8',env:{...process.env,CORE_OFFLINE:'1',CORE_ACCOUNT:account,CORE_REGION:region,CORE_OUT:out,CORE_INPUT:path.resolve(B)}});assert.equal(r.status,0,r.stderr);return out;};
fs.writeFileSync(B+'/product.json',JSON.stringify(product));fs.writeFileSync(B+'/security.json',JSON.stringify({Resources:{}}));
await esbuild.build({entryPoints:['infrastructure/domains/core/app.ts'],outfile:B+'/app.cjs',bundle:true,format:'cjs',platform:'node',packages:'external',logLevel:'silent'});
// Execute the isolated app with its own module resolution path.
const appText=fs.readFileSync(B+'/app.cjs','utf8');fs.writeFileSync(B+'/app.cjs',appText.replaceAll('require("aws-cdk-lib")',`require(${JSON.stringify(path.resolve('infrastructure/domains/core/node_modules/aws-cdk-lib'))})`));
let out=synth();const productPath=out+'/'+name+'.template.json',productSha=sha(productPath),templateKey=`core/2b5a/${productSha}/product.template.json`,url=`https://${bucket}.s3.${region}.amazonaws.com/${templateKey}`;
const policies=deployment({url,objects:[`arn:aws:s3:::${bucket}/${key}`,`arn:aws:s3:::${bucket}/${templateKey}`],keys});for(const[k,p]of Object.entries(policies))save(k+'-policy',p);
const managed=(suffix,document)=>({Type:'AWS::IAM::ManagedPolicy',Properties:{ManagedPolicyName:name+'-'+suffix,PolicyDocument:document}});
const security={Resources:{RuntimeBoundary:managed('RuntimeBoundary',boundary),ExecutionBoundary:managed('ExecutionBoundary',policies.executionBoundary),CallerBoundary:managed('CallerBoundary',policies.caller),Execution:{Type:'AWS::IAM::Role',Properties:{RoleName:name+'-Execution',AssumeRolePolicyDocument:trust({Service:'cloudformation.amazonaws.com'}),PermissionsBoundary:{Ref:'ExecutionBoundary'},Policies:[{PolicyName:'CoreExecution',PolicyDocument:policies.execution}]}},Caller:{Type:'AWS::IAM::Role',Properties:{RoleName:name+'-Deploy',MaxSessionDuration:3600,AssumeRolePolicyDocument:trust({AWS:live.operator.Arn}),PermissionsBoundary:{Ref:'CallerBoundary'},Policies:[{PolicyName:'CoreDeployment',PolicyDocument:policies.caller}]}}}};
fs.writeFileSync(B+'/security.json',JSON.stringify(security));out=synth();assert.equal(sha(productPath),productSha,'Security synthesis changed pinned product');
for(const[k,n]of [['product',name],['security',name+'-Security']])fs.copyFileSync(out+'/'+n+'.template.json',E+'/'+k+'.template.json');
const counts={product:Object.keys(read(E+'/product.template.json').Resources).length,security:Object.keys(read(E+'/security.template.json').Resources).length};assert.deepEqual(counts,{product:8,security:5});
save('candidate',{at:new Date().toISOString(),domain:'Core',environment:'Ntgre',account,region,stack:name,executionRole:executionArn,productSha256:productSha,securitySha256:sha(E+'/security.template.json'),zipSha256:zipSha,bundleSha256:sha(B+'/index.js'),zipPath:B+'/runtime.zip',templateUrl:url,artifact:{bucket,key,templateKey,encryption:'AES256',published:false},counts,closure:Object.keys(bundle.metafile.inputs),api:'IAM_SYNC_LAMBDA',deployed:false,awsWrites:0});
save('planned-endpoint',{schemaVersion:'core-endpoint.v1',domain:'Core',environment:'Ntgre',account,region,stack:name,status:'PLANNED_NOT_DEPLOYED',endpoint:arn('lambda','function:'+name+'-Contracts'),authMode:'AWS_IAM_AND_DELEGATED_COGNITO_ACCESS_JWT',contractVersions:['environment.v1','authorization.decision.v1','directory.assignment.v1'],deploymentRevision:null,candidateRevision:productSha,provenance:{identityEvidence:'identity.json',candidate:'candidate.json'},frontendCutover:false});
console.log(JSON.stringify({counts,productSha256:productSha,zipSha256:zipSha,awsWrites:0}));
