import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {E} from './aws.mjs';
const read=p=>JSON.parse(fs.readFileSync(p)),save=(p,v)=>fs.writeFileSync(p,JSON.stringify(v,null,2)+'\n'),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const docs=['core-domain-plan','core-contracts-v1','core-security-model','core-first-deployment-readiness','team-hub-2b5a-core-integration'].map(n=>'docs/architecture/'+n+'.md');
const candidate=read(E+'/candidate.json'),security=read(E+'/security-review.json'),logging=read(E+'/logging-review.json'),trust=read(E+'/trust-review.json'),validation=read(E+'/validation.json');
const retained=read(E+'/retained-resource-check.json');assert.equal(retained.logs.length,0);assert.equal(retained.alarms.length,0);const gateText=fs.readFileSync(docs[3],'utf8');for(const key of ['productSha256','securitySha256','zipSha256'])assert.ok(gateText.includes(candidate[key]),'Readiness pin mismatch');
assert.ok(validation.results.every(r=>r.exit===0));assert.equal(security.analyzer.length,5);assert.ok(security.analyzer.every(x=>x.findings.length===0));assert.equal(trust.results.length,3);assert.ok(trust.results.every(x=>x.findings.length===0));assert.equal(security.simulations.length,39);assert.equal(security.failures.length,1);assert.equal(security.failures[0].action,'logs:PutLogEvents');assert.equal(security.failures[0].role,'runtime');assert.equal(logging.results.length,8);assert.ok(logging.results.every(x=>x.pass));
assert.equal(sha(E+'/product.template.json'),candidate.productSha256);assert.equal(sha(E+'/security.template.json'),candidate.securitySha256);assert.equal(sha(candidate.zipPath),candidate.zipSha256);assert.equal(read(E+'/baseline.json').legacy.total,2621);assert.equal(read(E+'/preservation.json').allAcceptedSourcesMatch,true);
let links=0;for(const file of docs)for(const m of fs.readFileSync(file,'utf8').matchAll(/\]\(([^)]+)\)/g)){if(/^https?:/.test(m[1]))continue;assert.ok(fs.existsSync(path.resolve(path.dirname(file),m[1].split('#')[0])),'Broken link '+m[1]);links++;}
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).filter(d=>!['node_modules','.build','cdk.out'].includes(d.name)).flatMap(d=>d.isDirectory()?walk(p+'/'+d.name):[p+'/'+d.name]);
const files=[...walk('domains/shared-core'),...walk('infrastructure/domains/core'),...walk('scripts/core-2b5a'),...docs];
for(const file of [...files,...walk(E)]){const text=fs.readFileSync(file,'utf8');for(const regex of [/\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/,/eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/"(?:SecretAccessKey|SessionToken|password)"\s*:\s*"[^"\s]+"/])assert.ok(!regex.test(text),'Credential literal in '+file);}
save(E+'/source-manifest.json',{at:new Date().toISOString(),files:files.map(p=>({path:p,sha256:sha(p)})),productSha256:candidate.productSha256,securitySha256:candidate.securitySha256,zipSha256:candidate.zipSha256});
save(E+'/final-review.json',{at:new Date().toISOString(),readyForAwsReview:true,deploymentAuthorized:false,deployed:false,verdict:'CORE INDEPENDENT CONTRACT CANDIDATE READY FOR AWS REVIEW',documentationLinks:links,secretPatternScan:'PASS',validation,analyzerDocuments:8,analyzerFindings:0,iamSimulation:{positive:12,positivePassed:11,negative:27,negativePassed:27,retainedDiscrepancy:'Own PutLogEvents implicitDeny; independent Analyzer controls 8/8 pass; live logging pending'},awsChanges:0,businessDataWrites:0,frontendCutover:false,legacyRetired:0,productionTouched:false,ledgerOwnershipRowsChanged:0,counts:{legacy:2621,teamProduct:40,teamSecurity:7,tournamentProduct:11,coreProduct:8,coreSecurity:5,reviewedSubtotalPeak:2692}});
const p='docs/architecture/domain-migration-status.json',status=read(p);status.currentDomain='Shared/Core';status.currentPhase='M2 / Team Hub 2B5A-1 CORE_AWS_REVIEW_READY_NOT_DEPLOYED';status.scope='Ntgre independent Core contract preparation and read-only AWS review; no deployment or Team cutover';const core=status.domains.find(d=>d.domain==='Shared/Core');core.phase='M2_2B5A_REVIEW_READY';core.nextStep='CORE FIRST DEPLOYMENT REVIEW; separate authorization before AWS writes';core.independentContractCandidate={status:'AWS_REVIEW_READY_NOT_DEPLOYED',stack:'ProjectRespawn-Core-Ntgre',productResources:8,securityResources:5,report:docs[3],candidate:E+'/candidate.json',authority:'EXISTING_NTGRE_COGNITO_UNCHANGED',awsChanges:0};core.blockers=['No deployment/live acceptance performed; separate security/product execution gates required.'];core.offlineContractCandidate={...core.offlineContractCandidate,status:'SUPERSEDED_BY_2B5A',supersededBy:docs[3]};for(const d of docs)if(!core.evidence.includes(d))core.evidence.push(d);save(p,status);
const ledgerPath='docs/architecture/legacy-resource-ownership.json',ledger=read(ledgerPath);ledger.latestCore2B5AReview={at:new Date().toISOString(),report:docs[3],ownershipRowsChanged:0,coreProductProposed:8,coreSecurityProposed:5,awsChanges:0};save(ledgerPath,ledger);
status.awsChangesMeaning='Historical 42 infrastructure calls through 2B4B; 2B5 and 2B5A add zero AWS resource changes. 2B5A performed read-only inventory and policy validation. Synthetic data transactions remain separately accounted.';save(p,status);
const r='docs/architecture/README-PHASE2-MIGRATION.md';let text=fs.readFileSync(r,'utf8');if(!text.includes('**Latest 2B5A result'))text=text.replace('\n\n','\n\n**Latest 2B5A result (6 October 2026): CORE CANDIDATE READY FOR AWS REVIEW — NOT DEPLOYED.** Independent Core contracts, eight product/five security resources, fresh protected baseline and policy review prepared. No AWS changes, Team authority switch or frontend cutover. [Core readiness](core-first-deployment-readiness.md). Next: CORE FIRST DEPLOYMENT REVIEW.\n\n');saveText(r,text);
function saveText(p,text){fs.writeFileSync(p,text);}
console.log(JSON.stringify({readyForAwsReview:true,deploy:false,links,secretScan:'PASS',files:files.length,awsChanges:0}));
