import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {aws,identity,E} from './aws.mjs';
fs.mkdirSync(E,{recursive:true});const read=p=>JSON.parse(fs.readFileSync(p));const save=(n,v)=>fs.writeFileSync(`${E}/${n}.json`,JSON.stringify(v,null,2)+'\n');
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const operator=await identity(),core='ProjectRespawn-Core-Ntgre';
const absent=[];for(const name of [core,core+'-Security']){try{const r=await aws('cloudformation','describe-stacks',['--stack-name',name]);save('unexpected-core',{name,stack:r.Stacks?.map(s=>({name:s.StackName,id:s.StackId,status:s.StackStatus}))});throw Error('STOP: unexpected Core stack exists');}catch(e){if(e.code!=='ValidationError'||!e.message.includes('does not exist'))throw e;absent.push(name);}}
// Partial prior creates without a stack also block first creation.
const functions=(await aws('lambda','list-functions')).Functions.filter(f=>f.FunctionName.startsWith(core));assert.equal(functions.length,0,'Unexpected Core Lambda; stop and inventory');
for(const name of [core+'-Contracts',core+'-Execution',core+'-Deploy'])try{await aws('iam','get-role',['--role-name',name]);throw Error('Unexpected Core role '+name);}catch(e){if(e.code!=='NoSuchEntity')throw e;}
for(const name of ['RuntimeBoundary','ExecutionBoundary','CallerBoundary'])try{await aws('iam','get-policy',['--policy-arn','arn:aws:iam::058264289478:policy/'+core+'-'+name]);throw Error('Unexpected Core policy '+name);}catch(e){if(e.code!=='NoSuchEntity')throw e;}
try{await aws('secretsmanager','describe-secret',['--secret-id',core+'-Cursor']);throw Error('Unexpected Core secret');}catch(e){if(e.code!=='ResourceNotFoundException')throw e;}
const apis=(await aws('apigatewayv2','get-apis')).Items.map(a=>({id:a.ApiId,name:a.Name,protocol:a.ProtocolType,tags:a.Tags}));assert.ok(!apis.some(a=>a.name?.startsWith(core)),'Unexpected Core API');
save('absence',{at:new Date().toISOString(),operator,stacks:absent,functions:0,roles:0,policies:0,cursorSecret:false,apis,awsWrites:0});
const environment=read('config/environments/Ntgre.core.json'),outputs=read('amplify_outputs.json');assert.equal(environment.poolId,outputs.auth.user_pool_id);assert.equal(environment.clientId,outputs.auth.user_pool_client_id);
const pool=(await aws('cognito-idp','describe-user-pool',['--user-pool-id',environment.poolId])).UserPool;
const client=(await aws('cognito-idp','describe-user-pool-client',['--user-pool-id',environment.poolId,'--client-id',environment.clientId])).UserPoolClient;
assert.equal(pool.Id,environment.poolId);assert.equal(client.UserPoolId,pool.Id);assert.ok(!client.ClientSecret,'Website client must be public');
const clients=(await aws('cognito-idp','list-user-pool-clients',['--user-pool-id',pool.Id])).UserPoolClients.map(c=>({id:c.ClientId,name:c.ClientName}));
const lambdaKey=(await aws('kms','describe-key',['--key-id','alias/aws/lambda'])).KeyMetadata;assert.equal(lambdaKey.KeyManager,'AWS');assert.equal(lambdaKey.Enabled,true);
save('identity',{at:new Date().toISOString(),operator,environment:{contractVersion:environment.contractVersion,environment:environment.environment,account:environment.account,region:environment.region,poolId:pool.Id,clientId:client.ClientId,issuer:environment.issuer},clients,publicClient:true,lambdaKey:{arn:lambdaKey.Arn,keyManager:lambdaKey.KeyManager},awsWrites:0});
const inventory=read('docs/architecture/phase2-resource-domain-map.json'),stacks=[];let index=0;
await Promise.all(Array.from({length:3},async()=>{while(index<inventory.stacks.length){const s=inventory.stacks[index++];const response=await aws('cloudformation','get-template',['--stack-name',s.arn]);const t=typeof response.TemplateBody==='string'?JSON.parse(response.TemplateBody):response.TemplateBody;assert.equal(hash(t),s.templateSha256,'Legacy template changed '+s.key);const r=(await aws('cloudformation','list-stack-resources',['--stack-name',s.arn])).StackResourceSummaries.filter(r=>r.ResourceStatus!=='DELETE_COMPLETE');assert.equal(r.length,s.count);for(const live of r){const old=inventory.resources.find(x=>x.stackKey===s.key&&x.logicalId===live.LogicalResourceId);assert.equal(old.type,live.ResourceType);if(old.type==='AWS::AppSync::ApiKey')assert.equal(crypto.createHash('sha256').update(live.PhysicalResourceId).digest('hex'),old.physicalIdSha256);else assert.equal(old.physicalId,live.PhysicalResourceId);}stacks.push({key:s.key,count:r.length,templateSha256:hash(t)});}}));
const roots={};for(const name of ['amplify-projectrespawnwebsite-Ntgre-sandbox-8bd9d02332','ProjectRespawn-TeamHub-Ntgre','ProjectRespawn-TeamHub-Ntgre-ReadProofSecurity','ProjectRespawn-Tournaments-Ntgre']){const s=(await aws('cloudformation','describe-stacks',['--stack-name',name])).Stacks[0];assert.equal(s.StackStatus,'UPDATE_COMPLETE');const resources=(await aws('cloudformation','list-stack-resources',['--stack-name',name])).StackResourceSummaries.filter(r=>r.ResourceStatus!=='DELETE_COMPLETE');roots[name]={id:s.StackId,status:s.StackStatus,lastUpdated:s.LastUpdatedTime,count:resources.length,api:resources.filter(r=>r.ResourceType==='AWS::ApiGatewayV2::Api').map(r=>r.PhysicalResourceId)};}
assert.equal(roots['ProjectRespawn-TeamHub-Ntgre'].count,40);assert.equal(roots['ProjectRespawn-TeamHub-Ntgre-ReadProofSecurity'].count,7);assert.equal(roots['ProjectRespawn-Tournaments-Ntgre'].count,11);assert.deepEqual(roots['ProjectRespawn-TeamHub-Ntgre'].api,['t54b88casf']);assert.deepEqual(roots['ProjectRespawn-Tournaments-Ntgre'].api,['msipnwy39j']);
const total=stacks.reduce((n,s)=>n+s.count,0);assert.equal(total,2621);assert.equal(stacks.find(s=>s.key==='029').count,167);
save('baseline',{at:new Date().toISOString(),operator,roots,legacy:{total,directive:167,stacks:stacks.sort((a,b)=>a.key.localeCompare(b.key)),allPhysicalIdsMatch:true},awsWrites:0});console.log(JSON.stringify({coreAbsent:true,identityVerified:true,legacy:total,team:40,teamSecurity:7,tournament:11,awsWrites:0}));
