import test from 'node:test'; import assert from 'node:assert/strict'; import { readFile } from 'node:fs/promises';
import { DEMO_CALIBRATION_SETTINGS, DEMO_REVIEWER_PERFORMANCE_RECORDS, filterPerformanceRecords, getReviewerPerformance, peerComparison, reviewerDashboard, reviewerMetrics, scoreDistribution } from './reviewerPerformanceData.js';

test('reviewer summary average, median, range, distribution and coverage derive from canonical records', () => { const jordan = getReviewerPerformance('jordan-review'); const own = DEMO_REVIEWER_PERFORMANCE_RECORDS.filter(r=>r.reviewerId==='jordan-review'&&r.state==='submitted'); const sorted=own.map(r=>r.percentage).sort((a,b)=>a-b); assert.equal(jordan.average,Number((sorted.reduce((a,b)=>a+b,0)/sorted.length).toFixed(1))); assert.equal(jordan.median,(sorted[5]+sorted[6])/2); assert.equal(jordan.highest,Math.max(...sorted)); assert.equal(jordan.lowest,Math.min(...sorted)); assert.equal(scoreDistribution(own).reduce((s,b)=>s+b.count,0),own.length); assert.ok(jordan.commentCoverage>80); });
test('peer mean excludes selected reviewer and signed and absolute differences agree',()=>{const record=DEMO_REVIEWER_PERFORMANCE_RECORDS.find(r=>r.reviewerId==='casey-review'&&r.state==='submitted');const peers=DEMO_REVIEWER_PERFORMANCE_RECORDS.filter(r=>r.applicationId===record.applicationId&&r.state==='submitted'&&r.reviewerId!==record.reviewerId);const expected=peers.reduce((s,r)=>s+r.percentage,0)/peers.length;const result=peerComparison(record,DEMO_REVIEWER_PERFORMANCE_RECORDS);assert.equal(result.peerMean,Number(expected.toFixed(1)));assert.equal(result.difference,Number((record.percentage-expected).toFixed(1)));assert.equal(result.absoluteDifference,Math.abs(result.difference));});
test('minimum comparable sample prevents premature calibration labels',()=>{const limited=getReviewerPerformance('riley-limited');assert.equal(limited.calibrationStatus,'Insufficient sample');assert.ok(limited.comparableSample<DEMO_CALIBRATION_SETTINGS.minimumComparableReviews);assert.notEqual(getReviewerPerformance('casey-review').calibrationStatus,'Insufficient sample');});
test('pathway, rubric, provenance, dates and minimum sample filters work',()=>{assert.ok(filterPerformanceRecords(undefined,{pathway:'creator'}).length);assert.equal(filterPerformanceRecords(undefined,{rubricVersion:'other'}).length,0);assert.ok(filterPerformanceRecords(undefined,{provenance:'Informed admin review'}).every(r=>r.reviewLabel==='Informed admin review'));assert.ok(filterPerformanceRecords(undefined,{from:'2026-02-01'}).every(r=>!r.submittedAt||r.submittedAt>='2026-02-01'));assert.ok(reviewerDashboard({minimumSample:10}).every(r=>r.sampleSize>=10));});
test('performance routes precede dynamic application route and history links canonically',async()=>{const [routes,tabs,detail,css]=await Promise.all([readFile(new URL('../../../router/admin.routes.js',import.meta.url),'utf8'),readFile(new URL('./components/AdminApplicationsTabs.vue',import.meta.url),'utf8'),readFile(new URL('./AdminReviewerDetail.vue',import.meta.url),'utf8'),readFile(new URL('./AdminApplications.css',import.meta.url),'utf8')]);assert.ok(routes.indexOf("applications/reviewers'")<routes.indexOf("applications/:applicationId'"));assert.ok(routes.indexOf("applications/reviewers/:reviewerId")<routes.indexOf("applications/:applicationId'"));assert.match(tabs,/Reviewer performance/);assert.match(tabs,/adminOnly/);assert.match(detail,/applicationId:h\.applicationId/);assert.match(css,/reviewer-mobile-cards/);});
test('historical analytics remain isolated from APP-DEMO-0001',()=>{assert.ok(DEMO_REVIEWER_PERFORMANCE_RECORDS.every(r=>r.applicationId!=='APP-DEMO-0001'));assert.equal(reviewerMetrics('missing'),null);});
