import { DEMO_REVIEWER_PERFORMANCE_RECORDS } from './fixtures/demoReviewerPerformance.js';

export const DEMO_CALIBRATION_SETTINGS = Object.freeze({ minimumComparableReviews: 10, closeDifference: 3, materialDifference: 10, averageDifferenceMonitor: 6, averageDifferenceCalibration: 9, lowCommentCoverage: 35, staleClaimHours: 72 });
const mean = (values) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const median = (values) => { if (!values.length) return null; const sorted = [...values].sort((a,b) => a-b); const middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
const round = (value, digits = 1) => value === null ? null : Number(value.toFixed(digits));
const submitted = (records) => records.filter((record) => record.state === 'submitted');
export function peerComparison(record, records) { const peers = submitted(records).filter((item) => item.applicationId === record.applicationId && item.reviewerId !== record.reviewerId); const peerMean = mean(peers.map((item) => item.percentage)); return { peerMean: round(peerMean), difference: peerMean === null ? null : round(record.percentage - peerMean), absoluteDifference: peerMean === null ? null : round(Math.abs(record.percentage - peerMean)) }; }
export function scoreDistribution(records) { const values = submitted(records).map((r) => r.percentage); const ranges = [{ label: 'Below 35%', test: (v) => v < 35 }, { label: '35% to 49.99%', test: (v) => v >= 35 && v < 50 }, { label: '50% to 69.99%', test: (v) => v >= 50 && v < 70 }, { label: '70% to 84.99%', test: (v) => v >= 70 && v < 85 }, { label: '85% and above', test: (v) => v >= 85 }]; return ranges.map((range) => { const count = values.filter(range.test).length; return { label: range.label, count, percentage: values.length ? round(count / values.length * 100) : 0 }; }); }
export function filterPerformanceRecords(records = DEMO_REVIEWER_PERFORMANCE_RECORDS, filters = {}) { return records.filter((record) => (!filters.pathway || record.pathway === filters.pathway) && (!filters.rubricVersion || record.rubricVersion === filters.rubricVersion) && (!filters.provenance || record.reviewLabel === filters.provenance) && (!filters.from || !record.submittedAt || record.submittedAt >= `${filters.from}T00:00:00.000Z`) && (!filters.to || !record.submittedAt || record.submittedAt <= `${filters.to}T23:59:59.999Z`)); }
export function reviewerMetrics(reviewerId, records = DEMO_REVIEWER_PERFORMANCE_RECORDS, settings = DEMO_CALIBRATION_SETTINGS) { const own = records.filter((r) => r.reviewerId === reviewerId); if (!own.length) return null; const completed = submitted(own); const scores = completed.map((r) => r.percentage); const comparisons = completed.map((r) => ({ ...r, ...peerComparison(r, records) })).filter((r) => r.peerMean !== null); const comments = completed.reduce((sum,r) => sum + r.criterionComments.filter(Boolean).length, 0); const criteria = completed.reduce((sum,r) => sum + r.criterionComments.length, 0); const avgSigned = mean(comparisons.map((r) => r.difference)); const avgAbsolute = mean(comparisons.map((r) => r.absoluteDifference)); const material = comparisons.filter((r) => r.absoluteDifference >= settings.materialDifference).length; let calibrationStatus = 'Insufficient sample'; if (comparisons.length >= settings.minimumComparableReviews) calibrationStatus = Math.abs(avgSigned) >= settings.averageDifferenceCalibration || material >= Math.ceil(comparisons.length / 2) ? 'Calibration recommended' : Math.abs(avgSigned) >= settings.averageDifferenceMonitor || comments / Math.max(criteria,1) * 100 < settings.lowCommentCoverage ? 'Review pattern to monitor' : 'Within expected range'; return { reviewerId, reviewerName: own[0].reviewerName, reviewerStatus: own[0].reviewerStatus, claimed: own.length, started: own.filter(r=>r.startedAt).length, completed: completed.length, released: own.filter(r=>r.state==='released').length, average: round(mean(scores)), median: round(median(scores)), highest: scores.length ? Math.max(...scores) : null, lowest: scores.length ? Math.min(...scores) : null, atLeast85: scores.length ? round(scores.filter(v=>v>=85).length/scores.length*100) : 0, below35: scores.length ? round(scores.filter(v=>v<35).length/scores.length*100) : 0, concernRate: scores.length ? round(completed.filter(r=>r.seriousConcern).length/scores.length*100) : 0, clarificationRate: scores.length ? round(completed.filter(r=>r.clarification).length/scores.length*100) : 0, commentCoverage: criteria ? round(comments/criteria*100) : 0, averageCompletionHours: round(mean(completed.map(r=>(new Date(r.submittedAt)-new Date(r.claimedAt))/3600000))), averagePeerDifference: round(avgSigned), averageAbsoluteDifference: round(avgAbsolute), largestDifference: comparisons.length ? Math.max(...comparisons.map(r=>r.absoluteDifference)) : null, closelyAligned: comparisons.filter(r=>r.absoluteDifference<=settings.closeDifference).length, materialDisagreement: material, comparableSample: comparisons.length, sampleSize: completed.length, calibrationStatus, distribution: scoreDistribution(completed), history: comparisons.sort((a,b)=>new Date(b.submittedAt)-new Date(a.submittedAt)) }; }
export function reviewerDashboard(filters = {}, records = DEMO_REVIEWER_PERFORMANCE_RECORDS) { const filtered = filterPerformanceRecords(records, filters); const ids = [...new Set(filtered.map(r=>r.reviewerId))]; return ids.map(id=>reviewerMetrics(id, filtered)).filter(metric=>metric && metric.sampleSize >= Number(filters.minimumSample || 0)); }
export function getReviewerPerformance(reviewerId, filters = {}) { return reviewerMetrics(reviewerId, filterPerformanceRecords(DEMO_REVIEWER_PERFORMANCE_RECORDS, filters)); }
export { DEMO_REVIEWER_PERFORMANCE_RECORDS };
