import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const P='docs/architecture/core-2b5a-evidence-2026-10-06',Q='docs/architecture/core-quota-evidence-2026-10-06',E='docs/architecture/core-artifact-evidence-2026-10-06';fs.mkdirSync(E,{recursive:true});
const read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const old='89c712720e1fc09b9546865bd36b12a0123c8560ed8334d282918ac7cedbbaeb',next='4aad4b8df1b1272f12e93144b3a1e89a2addaab5e404950f924ff7d7b58b9e46',zip='4841f475dab09982d8ff5babc240c8a7d8809d05911de8e239ac9031e6fcefcf',securityHash='6b2afefb79172922e4338128a6b5fdab5e561e4055f8960650798acd4c4e8515';
const c=read(Q+'/candidate.json');assert.equal(sha(Q+'/product.template.json'),next);assert.equal(sha(c.zipPath),zip);assert.equal(sha(P+'/security.template.json'),securityHash);assert.equal(sha(P+'/product.template.json'),old);
const product=read(Q+'/product.template.json');assert.equal(Object.keys(product.Resources).length,8);assert.ok(!Object.hasOwn(product.Resources.Contracts.Properties,'ReservedConcurrentExecutions'));
const refs=[];function replace(value,path=[]){if(typeof value==='string'&&value.includes(old)){assert.ok(value.includes('/core/2b5a/'+old+'/product.template.json'));const result=value.replace(old,next);refs.push({path:'/'+path.join('/'),before:value,after:result});return result;}if(Array.isArray(value))return value.map((v,i)=>replace(v,[...path,i]));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,replace(v,[...path,k])]));return value;}
const original=read(P+'/security.template.json'),security=replace(original);assert.equal(Object.keys(security.Resources).length,5);assert.ok(refs.length>0);assert.deepEqual(JSON.parse(JSON.stringify(security).replaceAll(next,old)),original);assert.deepEqual(security.Resources.RuntimeBoundary,original.Resources.RuntimeBoundary);
save('security.template',security);fs.copyFileSync(Q+'/product.template.json',E+'/product.template.json');
for(const n of ['runtime-policy','runtime-boundary','caller-policy','execution-policy','executionBoundary-policy']){const bytes=fs.readFileSync(P+'/'+n+'.json','utf8');fs.writeFileSync(E+'/'+n+'.json',bytes.replaceAll(old,next));}
for(const n of ['runtime-policy','runtime-boundary'])assert.equal(sha(E+'/'+n+'.json'),sha(P+'/'+n+'.json'));
const findings=refs.map(r=>{const parts=r.path.split('/');const resource=parts[2];const owner=resource==='CallerBoundary'?'deployment caller boundary':resource==='Caller'?'deployment caller identity':resource==='ExecutionBoundary'?'execution boundary':'execution identity';return {...r,owner,principal:'arn:aws:iam::058264289478:role/ProjectRespawn-Core-Ntgre-'+(owner.startsWith('deployment')?'Deploy':'Execution'),action:r.before.startsWith('https:')?'cloudformation:CreateChangeSet':'s3:GetObject',bucket:c.artifact.bucket,oldKey:'core/2b5a/'+old+'/product.template.json',newKey:c.artifact.templateKey};});
save('semantic-diff',{changes:findings,onlyArtifactReferences:true,runtimeIamChanged:false,passRoleChanged:false,stackScopeChanged:false,kmsChanged:false,oldTemplateReadRetained:false,reason:'Old product was never deployed and contains unusable reserved concurrency. First-create rollback is CloudFormation rollback, not deployment of the failed candidate. Historical local templates/ZIP retained.',publicationHelper:'Prior Release 1 helper remains historical and pinned to old candidate; new review supplies deterministic metadata only, no publisher invoked.',securityTemplateObject:'Not required: reviewed bootstrap supplies local TemplateBody; no S3 read permission added.'});
save('candidate',{...c,at:new Date().toISOString(),previousSecuritySha256:securityHash,securitySha256:sha(E+'/security.template.json'),securityChanged:true,deployable:false,blocker:'Pending final validation',runtimeRebuilt:false,awsWrites:0});
console.log(JSON.stringify({product:next,previousSecurity:securityHash,newSecurity:sha(E+'/security.template.json'),changedReferences:findings.length,runtimeRebuilt:false}));
for(const n of ['preflight','preserve','check-retained','review-trust'])fs.writeFileSync('scripts/core-artifact/'+n+'.mjs',fs.readFileSync('scripts/core-2b5a/'+n+'.mjs','utf8'));
