import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {build} from 'esbuild';import {singleFileZip} from '../team-hub-2b4/zip.mjs';
const E='docs/architecture/team-hub-authority-status-evidence-2026-10-08',B='.tmp/team-hub-authority-status',P='docs/architecture/team-hub-c1-evidence-2026-10-07';
const read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
assert.deepEqual(process.argv.slice(2),['--offline']);fs.mkdirSync(B,{recursive:true});
const baseline=read(P+'/candidate.json');assert.equal(sha(P+'/candidate.json'),read(P+'/final-review.json').candidateHash);for(const k of ['product','security'])assert.equal(sha(P+'/d1-after-c2-'+k+'.template.json'),baseline.d1AfterC2[k+'Sha256']);for(const f of baseline.d1.sourceHashes)assert.equal(sha(f.path),f.sha256,f.path);assert.equal(sha(baseline.d1.runtimePath),baseline.d1AfterC2.runtimeSha256);
const bundle=await build({entryPoints:['domains/team-hub/authority-contract/entry.mjs'],outfile:B+'/index.js',bundle:true,platform:'node',format:'cjs',target:'node22',metafile:true,logLevel:'silent'});
const inputs=Object.keys(bundle.metafile.inputs);assert.ok(!inputs.some(p=>/secrets-manager|cutover\/(repository|service|entry|handler)\.mjs|amplify\//.test(p)));fs.writeFileSync(B+'/runtime.zip',singleFileZip('index.js',fs.readFileSync(B+'/index.js')));const runtimeSha256=sha(B+'/runtime.zip');
const bucket='cdk-hnb659fds-assets-058264289478-eu-north-1',assetKey='team-hub/as/'+runtimeSha256+'.zip',assetArn='arn:aws:s3:::'+bucket+'/'+assetKey;
const require=createRequire(path.resolve('infrastructure/domains/team-hub/package.json')),cdk=require('aws-cdk-lib'),{CfnInclude}=require('aws-cdk-lib/cloudformation-include');
const app=new cdk.App({outdir:B+'/assembly',context:{'aws:cdk:version-reporting':false}}),stack=new cdk.Stack(app,'ProjectRespawn-TeamHub-Ntgre',{env:{account:'058264289478',region:'eu-north-1'},analyticsReporting:false,synthesizer:new cdk.BootstraplessSynthesizer()});
const include=new CfnInclude(stack,'AcceptedD1',{templateFile:path.resolve(P+'/d1-after-c2-product.template.json'),preserveLogicalIds:true});include.getResource('ParityReadFunction').addPropertyOverride('Code',{S3Bucket:bucket,S3Key:assetKey});
const route={Type:'AWS::ApiGatewayV2::Route',Properties:{ApiId:{Ref:'HttpApi'},RouteKey:'GET /v1/authority',AuthorizationType:'JWT',AuthorizerId:{Ref:'JwtAuthorizer'},Target:{'Fn::Join':['',['integrations/',{Ref:'ParityReadIntegration'}]]}}};
const invokePermission={Type:'AWS::Lambda::Permission',Properties:{Action:'lambda:InvokeFunction',FunctionName:{Ref:'ParityReadFunction'},Principal:'apigateway.amazonaws.com',SourceAccount:'058264289478',SourceArn:'arn:aws:execute-api:eu-north-1:058264289478:t54b88casf/$default/GET/v1/authority'}};
const permission=new cdk.CfnResource(stack,'AuthorityStatusInvokePermission',{type:invokePermission.Type,properties:invokePermission.Properties});permission.overrideLogicalId('AuthorityStatusInvokePermission');
route.DependsOn=['AuthorityStatusInvokePermission'];
const addition=new cdk.CfnResource(stack,'AuthorityStatusRoute',{type:route.Type,properties:route.Properties});addition.overrideLogicalId('AuthorityStatusRoute');addition.addDependency(permission);
const assembly=app.synth(),product=assembly.getStackArtifact(stack.artifactId).template;save('product.template',product);
const prior=read(P+'/d1-after-c2-product.template.json'),restored=structuredClone(product);delete restored.Resources.AuthorityStatusRoute;delete restored.Resources.AuthorityStatusInvokePermission;restored.Resources.ParityReadFunction.Properties.Code=prior.Resources.ParityReadFunction.Properties.Code;
assert.deepEqual(restored,prior,'Synthesis must preserve every unrelated property');assert.deepEqual(product.Resources.AuthorityStatusRoute,route);assert.deepEqual(product.Resources.AuthorityStatusInvokePermission,invokePermission);assert.equal(Object.keys(product.Resources).length,42);
const productSha256=sha(E+'/product.template.json'),templateKey='team-hub/as/'+productSha256+'.template.json',templateArn='arn:aws:s3:::'+bucket+'/'+templateKey,templateUrl='https://'+bucket+'.s3.eu-north-1.amazonaws.com/'+templateKey;
const security=read(P+'/d1-after-c2-security.template.json'),oldArtifact='arn:aws:s3:::'+bucket+'/team-hub/core-integration/2992b5d6b736c90c3fc306654a38576cd861dc0e07068c92bf02c79c87948e6a.zip';
// Boundary is already 6100/6144 chars. Replace only the historical pre-D1 ZIP
// reference; retain the installed D1 and preview ZIPs for exact rollback.
for(const doc of [security.Resources.ExecutionBoundary.Properties.PolicyDocument,security.Resources.ExecutionRole.Properties.Policies[0].PolicyDocument]){
 let replaced=0;for(const s of doc.Statement)for(const k of ['Resource','NotResource'])if(Array.isArray(s[k]))s[k]=s[k].map(x=>{if(x!==oldArtifact)return x;replaced++;return assetArn;});assert.ok(replaced>0);
}
for(const s of security.Resources.PreparationCaller.Properties.PolicyDocument.Statement){if(s.Action==='cloudformation:CreateChangeSet')s.Condition.StringEquals['cloudformation:TemplateUrl'].push(templateUrl);if(s.Effect==='Allow'&&[s.Action].flat().includes('s3:GetObject'))s.Resource.push(templateArn);if(s.Effect==='Deny'&&s.Action==='s3:*')s.NotResource.push(templateArn);}
save('security.template',security);const sizes={};for(const[id,r]of Object.entries(security.Resources))if(r.Type==='AWS::IAM::ManagedPolicy'){sizes[id]=JSON.stringify(r.Properties.PolicyDocument).length;assert.ok(sizes[id]<=6144,id+' IAM quota');}
const undo=JSON.parse(JSON.stringify(security).replaceAll(assetArn,oldArtifact));for(const s of undo.Resources.PreparationCaller.Properties.PolicyDocument.Statement){if(s.Action==='cloudformation:CreateChangeSet')s.Condition.StringEquals['cloudformation:TemplateUrl']=s.Condition.StringEquals['cloudformation:TemplateUrl'].filter(x=>x!==templateUrl);for(const k of ['Resource','NotResource'])if(Array.isArray(s[k]))s[k]=s[k].filter(x=>x!==templateArn);}assert.deepEqual(undo,read(P+'/d1-after-c2-security.template.json'));
const sources=[...new Set([...inputs.filter(p=>!p.includes('node_modules')), 'scripts/team-hub-authority-status/build.mjs','src/features/team-hub/api/cutover-client.mjs','config/domains/team-hub/frontend-cutover.PROPOSAL.json','config/domains/team-hub/domain-endpoints.Ntgre.json','config/domains/core/domain-endpoints.Ntgre.json'])];
save('candidate',{status:'PREPARED_NOT_DEPLOYED',account:'058264289478',region:'eu-north-1',stack:stack.stackName,securityStack:stack.stackName+'-ReadProofSecurity',baseline:baseline.d1AfterC2,runtimePath:B+'/runtime.zip',runtimeSha256,productSha256,securitySha256:sha(E+'/security.template.json'),bucket,assetKey,templateKey,templateUrl,policySizes:sizes,removedHistoricalArtifact:oldArtifact,preservedRollbackArtifact:prior.Resources.ParityReadFunction.Properties.Code.S3Key,productChanges:{add:['AuthorityStatusRoute','AuthorityStatusInvokePermission'],modify:['ParityReadFunction.Code'],delete:[],replace:[],resources:42},securityChanges:{modify:['ExecutionBoundary','ExecutionRole','PreparationCaller'],runtimePoliciesChanged:false,resources:7},synthesis:{tool:'CDK CfnInclude from exact accepted D1 template, sibling Team Hub root',cdk:require('aws-cdk-lib/package.json').version,assembly:B+'/assembly',awsCalls:0},sourceHashes:sources.map(path=>({path,sha256:sha(path)})),awsWrites:0});save('bundle-closure',{inputs:inputs.map(path=>({path,sha256:sha(path)})),outputs:bundle.metafile.outputs});console.log(JSON.stringify({runtimeSha256,productSha256,securitySha256:sha(E+'/security.template.json'),resources:42,policySizes:sizes}));

