import assert from 'node:assert/strict';import {aws,identity,json,save,P,E,pin,canonical,product,execution,caller} from './aws.mjs';
const candidate=json(E+'/candidate.json'),c={...candidate,url:candidate.templateUrl,key:candidate.templateKey},baseline=json(P+'/d1-after-c2-security.template.json'),next=json(E+'/security.template.json'),r={at:new Date().toISOString(),identity:await identity(),analyzer:[],installed:[],checks:[],complete:false};const persist=()=>save('policy-review',r);persist();
for(const id of ['ExecutionBoundary','PreparationCaller']){const d=next.Resources[id].Properties.PolicyDocument;assert.ok(JSON.stringify(d).length<=6144);const a=await aws('accessanalyzer','validate-policy',{policyDocument:JSON.stringify(d),policyType:'IDENTITY_POLICY'});r.analyzer.push({id,findings:a.findings});assert.equal(a.findings.filter(x=>['ERROR','SECURITY_WARNING'].includes(x.findingType)).length,0);}
const executionPolicy=next.Resources.ExecutionRole.Properties.Policies[0].PolicyDocument;const a=await aws('accessanalyzer','validate-policy',{policyDocument:JSON.stringify(executionPolicy),policyType:'IDENTITY_POLICY'});r.analyzer.push({id:'ExecutionRole',findings:a.findings});assert.equal(a.findings.filter(x=>['ERROR','SECURITY_WARNING'].includes(x.findingType)).length,0);persist();
for(const [id,arn,boundaryId] of [['ExecutionRole',execution,'ExecutionBoundary'],['DeploymentCaller',caller,'PreparationCaller']]){
 const props=baseline.Resources[id].Properties,name=arn.split('/').at(-1),role=(await aws('iam','get-role',{RoleName:name})).Role;assert.equal(canonical(role.AssumeRolePolicyDocument),canonical(props.AssumeRolePolicyDocument));const bound='arn:aws:iam::058264289478:policy/'+baseline.Resources[boundaryId].Properties.ManagedPolicyName;assert.equal(role.PermissionsBoundary.PermissionsBoundaryArn,bound);
 const p=(await aws('iam','get-policy',{PolicyArn:bound})).Policy,doc=(await aws('iam','get-policy-version',{PolicyArn:bound,VersionId:p.DefaultVersionId})).PolicyVersion.Document;assert.equal(canonical(doc),canonical(baseline.Resources[boundaryId].Properties.PolicyDocument));
 const names=(await aws('iam','list-role-policies',{RoleName:name})).PolicyNames;assert.deepEqual(names.slice().sort(),(props.Policies??[]).map(x=>x.PolicyName).sort());for(const n of names){const d=(await aws('iam','get-role-policy',{RoleName:name,PolicyName:n})).PolicyDocument;assert.equal(canonical(d),canonical(props.Policies.find(x=>x.PolicyName===n).PolicyDocument));}
 const attached=(await aws('iam','list-attached-role-policies',{RoleName:name})).AttachedPolicies.map(x=>x.PolicyArn).sort();assert.deepEqual(attached,(props.ManagedPolicyArns??[]).map(x=>typeof x==='string'?x:'arn:aws:iam::058264289478:policy/'+baseline.Resources[x.Ref].Properties.ManagedPolicyName).sort());r.installed.push({id,arn,boundary:bound,version:p.DefaultVersionId,inline:names,attached,acceptedD1Match:true});persist();
}
const region={ContextKeyName:'aws:RequestedRegion',ContextKeyValues:['eu-north-1'],ContextKeyType:'string'},resource='arn:aws:cloudformation:eu-north-1:058264289478:stack/'+product+'/*',templateContext=[region,{ContextKeyName:'cloudformation:RoleArn',ContextKeyValues:[execution],ContextKeyType:'string'},{ContextKeyName:'cloudformation:TemplateUrl',ContextKeyValues:[c.url],ContextKeyType:'string'}];
const cases=[
 ['own-invoke-policy',execution,'ExecutionRole','ExecutionBoundary',['lambda:AddPermission','lambda:RemovePermission','lambda:GetPolicy'],['arn:aws:lambda:eu-north-1:058264289478:function:ProjectRespawn-TeamHub-Ntgre-ParityRead'],[region],true,true],
 ['foreign-invoke-policy',execution,'ExecutionRole','ExecutionBoundary',['lambda:AddPermission','lambda:RemovePermission','lambda:GetPolicy'],['arn:aws:lambda:eu-north-1:058264289478:function:ProjectRespawn-Core-Ntgre-Contracts'],[region],false,false],
 ['accepted-D1-rollback',execution,'ExecutionRole','ExecutionBoundary',['s3:GetObject'],['arn:aws:s3:::'+c.bucket+'/'+c.preservedRollbackArtifact],[region],true,true],
 ['own-route',execution,'ExecutionRole','ExecutionBoundary',['apigateway:POST'],['arn:aws:apigateway:eu-north-1::/apis/t54b88casf/routes'],[region],true,true],
 ['foreign-route',execution,'ExecutionRole','ExecutionBoundary',['apigateway:POST'],['arn:aws:apigateway:eu-north-1::/apis/msipnwy39j/routes'],[region],false,false],
 ['execution-artifact',execution,'ExecutionRole','ExecutionBoundary',['s3:GetObject'],['arn:aws:s3:::'+c.bucket+'/'+c.assetKey],[region],false,true],
 ['removed-pre-D1-artifact',execution,'ExecutionRole','ExecutionBoundary',['s3:GetObject'],['arn:aws:s3:::'+c.bucket+'/team-hub/core-integration/2992b5d6b736c90c3fc306654a38576cd861dc0e07068c92bf02c79c87948e6a.zip'],[region],true,false],
 ['unreviewed-artifact',execution,'ExecutionRole','ExecutionBoundary',['s3:GetObject'],['arn:aws:s3:::'+c.bucket+'/team-hub/unreviewed.zip'],[region],false,false],
 ['own-code',execution,'ExecutionRole','ExecutionBoundary',['lambda:UpdateFunctionCode'],['arn:aws:lambda:eu-north-1:058264289478:function:'+product+'-ParityRead','arn:aws:lambda:eu-north-1:058264289478:function:'+product+'-ParityCommand'],[region],true,true],
 ['foreign-code',execution,'ExecutionRole','ExecutionBoundary',['lambda:UpdateFunctionCode'],['arn:aws:lambda:eu-north-1:058264289478:function:ProjectRespawn-Core-Ntgre-Contracts','arn:aws:lambda:eu-north-1:058264289478:function:ProjectRespawn-Tournaments-Ntgre-Preview'],[region],false,false],
 ['own-stage',execution,'ExecutionRole','ExecutionBoundary',['apigateway:PATCH'],['arn:aws:apigateway:eu-north-1::/apis/t54b88casf/stages/$default'],[region],true,true],
 ['foreign-api',execution,'ExecutionRole','ExecutionBoundary',['apigateway:PATCH'],['arn:aws:apigateway:eu-north-1::/apis/msipnwy39j/stages/$default'],[region],false,false],
 ['log-administration',execution,'ExecutionRole','ExecutionBoundary',['logs:PutResourcePolicy','logs:DeleteResourcePolicy','logs:CreateLogDelivery','logs:UpdateLogDelivery'],['*'],[region],false,false],
 ['private-services',execution,'ExecutionRole','ExecutionBoundary',['cognito-idp:AdminGetUser','secretsmanager:GetSecretValue','kms:Encrypt','kms:Decrypt'],['*'],[region],false,false],
 ['caller-template',caller,'DeploymentCaller','PreparationCaller',['cloudformation:CreateChangeSet'],[resource],templateContext,false,true],
 ['caller-object',caller,'DeploymentCaller','PreparationCaller',['s3:GetObject'],['arn:aws:s3:::'+c.bucket+'/'+c.key],[region],false,true],
 ['caller-foreign-stack',caller,'DeploymentCaller','PreparationCaller',['cloudformation:CreateChangeSet'],[resource.replace('TeamHub','Tournaments')],templateContext,false,false],
 ['caller-pass-role',caller,'DeploymentCaller','PreparationCaller',['iam:PassRole'],[execution],[region,{ContextKeyName:'iam:PassedToService',ContextKeyValues:['cloudformation.amazonaws.com'],ContextKeyType:'string'}],true,true],
 ['caller-foreign-role',caller,'DeploymentCaller','PreparationCaller',['iam:PassRole'],[execution.replace('TeamHub','Core')],[region,{ContextKeyName:'iam:PassedToService',ContextKeyValues:['cloudformation.amazonaws.com'],ContextKeyType:'string'}],false,false]
 ];
for(let start=0;start<cases.length;start+=3)await Promise.all(cases.slice(start,start+3).map(async ([label,arn,id,bid,actions,resources,context,before,after])=>{for(const mode of ['actual','candidate']){const policy=id==='DeploymentCaller'?next.Resources[bid].Properties.PolicyDocument:executionPolicy;const answer=await aws('iam',mode==='actual'?'simulate-principal-policy':'simulate-custom-policy',{...(mode==='actual'?{PolicySourceArn:arn}:{PolicyInputList:[JSON.stringify(policy)],PermissionsBoundaryPolicyInputList:[JSON.stringify(next.Resources[bid].Properties.PolicyDocument)]}),ActionNames:actions,ResourceArns:resources,ContextEntries:context});const decisions=answer.EvaluationResults.flatMap(x=>x.ResourceSpecificResults?.length?x.ResourceSpecificResults.map(y=>({action:x.EvalActionName,resource:y.EvalResourceName,decision:y.EvalResourceDecision})):[{action:x.EvalActionName,resource:x.EvalResourceName,decision:x.EvalDecision}]);const expected=mode==='actual'?before:after;r.checks.push({label,mode,expected,decisions});persist();assert.equal(decisions.length,actions.length*resources.length);for(const d of decisions)assert.equal(d.decision==='allowed',expected,label+' '+mode+' '+d.action);}}));
r.complete=true;persist();console.log(JSON.stringify({complete:true,decisions:r.checks.flatMap(x=>x.decisions).length,analyzerPolicies:r.analyzer.length}));
