import fs from 'node:fs';
import assert from 'node:assert/strict';
import {read,E} from './read-only.mjs';
const stop=read(E+'/stop-confirmation.json'),review=read(E+'/reconciliation.json'),after=read(E+'/source-after.json');
assert.equal(stop.executed,false);assert.equal(review.ready,false);assert.equal(after.empty,true);
const report='docs/architecture/team-hub-2b3-gate1-legacy-recovery-protection.md';
const statusPath='docs/architecture/domain-migration-status.json',status=read(statusPath);
status.scope='Ntgre; Team Hub Gate 1 change-set preparation only; execution blocked; no data migration/cutover';
status.currentPhase='M4 / 2B3 Gate 1 stopped before execution: AWS change set exceeds reviewed protection scope';
status.awsChanges=7;
status.awsChangesMeaning='Seven explicit preparation writes: six pinned S3 template objects and one CreateChangeSet request (nine nested change sets generated by AWS). Zero executed stack/resource changes.';
status.executedDeploymentChanges=0;
const team=status.domains.find(d=>d.domain==='Team Hub');assert.ok(team);
team.phase='M4_GATE1_STOPPED_CHANGESET_SCOPE';team.m4RecoveryAccepted=false;
team.gate1={status:'NOT_READY_NOT_EXECUTED',lastVerified:stop.at,changeSet:stop.changeSet.id,counts:review.counts,recoveryProtectionEstablished:false,backupsCreated:0,evidence:report};
team.lastVerified=stop.at;
team.blockers[0]='Gate 1 stopped: AWS reports 238 modifications, 185 replacements and four conditional table replacements; protections/backups not established. Gate 2 restore rehearsal remains prohibited.';
team.nextStep='Review the blocked Gate 1 nested-reference/replacement discrepancy separately; no execution, retry, backup creation or Gate 2 authority is implied.';
if(!team.evidence.includes(report))team.evidence.push(report);
fs.writeFileSync(statusPath,JSON.stringify(status,null,2)+'\n');
const ledgerPath='docs/architecture/legacy-resource-ownership.json',ledger=read(ledgerPath);
ledger.latestTeamGate1Review={at:stop.at,status:'NOT_READY_NOT_EXECUTED',report,changeSet:stop.changeSet.id,resources:2621,functionDirective:167,protectedIdentitiesUnchanged:62,monitoredLambdaHashesUnchanged:5,recoveryProtectionEstablished:false,backupsCreated:0,migrated:0,retired:0};
for(const row of ledger.resources.filter(r=>r.currentDomainAttribution==='TEAM HUB'&&r.resourceType==='Custom::AmplifyDynamoDBTable')){
 assert.equal(row.migrationStatus,'MIGRATION_PREP');assert.equal(row.deletionPolicy,'Delete');assert.equal(row.retirementStatus,'NOT_ELIGIBLE');
 row.recoveryProtectionStatus='NOT_ESTABLISHED_GATE1_STOPPED';
 if(!row.evidence.some(e=>e.path===report))row.evidence.push({path:report});
}
fs.writeFileSync(ledgerPath,JSON.stringify(ledger,null,2)+'\n');
const summaryPath='docs/architecture/legacy-resource-ownership-summary.md';let summary=fs.readFileSync(summaryPath,'utf8');
const note='\n## Latest Team Hub Gate 1 result — 5 October 2026\n\nGate 1 stopped before execution. The prepared AWS plan reports 238 modifications, 185 replacements and four conditional replacements; it is not approved to execute. All 2,621 Legacy resources, 62 protected identities and five monitored Lambda hashes remain unchanged. All 55 table protection configurations are unchanged. The four Team tables remain `MIGRATION_PREP`, Legacy-authoritative, PITR/deletion protection disabled, with no new backups. No migration or retirement status advanced. Seven explicit AWS preparation writes created six template objects and the root change set; no deployment occurred. See [Gate 1 report](team-hub-2b3-gate1-legacy-recovery-protection.md).\n';
if(!summary.includes('## Latest Team Hub Gate 1 result')){const split=summary.indexOf('\n');summary=summary.slice(0,split+1)+note+summary.slice(split+1);fs.writeFileSync(summaryPath,summary);}
const startPath='docs/architecture/README-PHASE2-MIGRATION.md';let start=fs.readFileSync(startPath,'utf8');
const current='\n**Latest Gate 1 result (5 October 2026): STOPPED BEFORE EXECUTION.** The protection-only candidate produced 238 AWS modifications, 185 replacement classifications and four conditional table replacements. No protections/backups were installed, no live stack changed, and Gate 2 is not authorized. Preparation created six pinned template objects and an unexecuted root/nested change-set hierarchy. Read the [Gate 1 recovery-protection report](team-hub-2b3-gate1-legacy-recovery-protection.md) before any further action. The read-only preparation described below is historical.\n';
if(!start.includes('**Latest Gate 1 result')){const split=start.indexOf('\n');start=start.slice(0,split+1)+current+start.slice(split+1);fs.writeFileSync(startPath,start);}
console.log('Recorded Gate 1 stop without advancing migration or recovery acceptance.');
