import { reactive } from 'vue'; import { getDemoIdentity } from '../AdminApplications/applicationAdminData.js'; import * as legacy from '../AdminApplications/inductionAvailabilityData.js';
const clone=value=>JSON.parse(JSON.stringify(value));
const seeds=[{id:'booking-type-induction',name:'Induction',slug:'induction',shortDescription:'Project Respawn induction meeting',instructions:'Choose a suitable time and an eligible facilitator.',status:'active',accessType:'invitation-only',audience:'Accepted applicants',accountRequired:true,invitationRequired:true,duration:60,bufferBefore:15,bufferAfter:15,minimumNoticeHours:24,bookingHorizonDays:60,cancellationPolicy:'Reschedule or cancel at least 24 hours before the meeting where possible.',eligibleStaffIds:['riley-staff','sam-staff'],displayOrder:1,publicVisibility:true,confirmationMessage:'Your induction booking is confirmed.',preparationInstructions:'Bring any questions about the programme.'},{id:'booking-type-consultation',name:'Creator consultation',slug:'creator-consultation',shortDescription:'Fictional creator support consultation.',instructions:'Draft future service.',status:'draft',accessType:'account-required',audience:'Creators',accountRequired:true,invitationRequired:false,duration:45,bufferBefore:10,bufferAfter:10,minimumNoticeHours:48,bookingHorizonDays:30,cancellationPolicy:'Fictional cancellation policy.',eligibleStaffIds:['riley-staff'],displayOrder:2,publicVisibility:false,confirmationMessage:'Consultation confirmed.',preparationInstructions:''},{id:'booking-type-company',name:'Company introduction',slug:'company-introduction',shortDescription:'Fictional company introduction.',instructions:'Inactive future service.',status:'inactive',accessType:'internal',audience:'Partners',accountRequired:true,invitationRequired:false,duration:30,bufferBefore:10,bufferAfter:10,minimumNoticeHours:72,bookingHorizonDays:21,cancellationPolicy:'Fictional cancellation policy.',eligibleStaffIds:['sam-staff'],displayOrder:3,publicVisibility:false,confirmationMessage:'Introduction confirmed.',preparationInstructions:''}];
export const bookingAvailabilityDemo=reactive({bookingTypes:clone(seeds),revision:0});const touch=()=>bookingAvailabilityDemo.revision++;
export function listBookingTypes({includeUnpublished=false}={}){bookingAvailabilityDemo.revision;return bookingAvailabilityDemo.bookingTypes.filter(type=>includeUnpublished||type.status==='active'&&type.publicVisibility&&type.accessType!=='internal').sort((a,b)=>a.displayOrder-b.displayOrder)}
export function getBookingType(value){return bookingAvailabilityDemo.bookingTypes.find(type=>type.slug===value||type.id===value)||null}
export function validateBookingType(input,{activating=input.status==='active'}={}){const errors=[];if(!String(input.name||'').trim())errors.push('Name is required.');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(input.slug||''))errors.push('Slug must use unique lowercase hyphenated words.');if(bookingAvailabilityDemo.bookingTypes.some(type=>type.slug===input.slug&&type.id!==input.id))errors.push('Slug must be unique.');if(Number(input.duration)<=0)errors.push('Duration must be valid.');if(Number(input.bookingHorizonDays)<=0)errors.push('Booking horizon must be valid.');if(activating&&!input.eligibleStaffIds?.length)errors.push('At least one eligible staff member is required before activation.');if(activating&&!legacy.availabilityDemo.hours.some(window=>window.active&&input.eligibleStaffIds?.includes(window.staffId)))errors.push('At least one usable availability window is required before activation.');return errors}
export function saveBookingType(input){if(getDemoIdentity()?.role!=='admin')throw new Error('Admin demo view required.');const value={accessType:'public',audience:'General',accountRequired:false,invitationRequired:false,bufferBefore:0,bufferAfter:0,minimumNoticeHours:0,publicVisibility:false,eligibleStaffIds:[],displayOrder:99,...clone(input)};const errors=validateBookingType(value);if(errors.length)throw new Error(errors.join(' '));const existing=getBookingType(value.id);if(existing)Object.assign(existing,value);else bookingAvailabilityDemo.bookingTypes.push({...value,id:value.id||`booking-type-${Date.now()}`});touch();return existing||bookingAvailabilityDemo.bookingTypes.at(-1)}
export function setBookingTypeStatus(id,status){const type=getBookingType(id);if(!type)throw new Error('Booking type not found.');return saveBookingType({...type,status,publicVisibility:status==='active'?type.publicVisibility:false})}
export function genericBookingSlots(typeSlug,from='2026-09-14',days=14){const type=getBookingType(typeSlug);if(!type||type.status!=='active')return[];return legacy.generatedSlots(from,days).filter(slot=>type.eligibleStaffIds.includes(slot.staffId)).map(slot=>{const[h,m]=slot.startTime.split(':').map(Number),end=h*60+m+type.duration;return{...slot,bookingTypeId:type.id,bookingTypeName:type.name,duration:type.duration,bufferBefore:type.bufferBefore,bufferAfter:type.bufferAfter,endTime:`${String(Math.floor(end/60)).padStart(2,'0')}:${String(end%60).padStart(2,'0')}`}})}
export function availableDates(typeSlug='induction'){return[...new Set(genericBookingSlots(typeSlug).map(slot=>slot.date))]}
export function availableTimes(date,typeSlug='induction'){const slots=genericBookingSlots(typeSlug).filter(slot=>slot.date===date);return[...new Set(slots.map(slot=>slot.startTime))].map(startTime=>{const matches=slots.filter(slot=>slot.startTime===startTime);return{startTime,endTime:matches[0].endTime,duration:matches[0].duration,staffCount:matches.length}})}
export function availableStaff(date,startTime,typeSlug='induction'){return genericBookingSlots(typeSlug).filter(slot=>slot.date===date&&slot.startTime===startTime).map(slot=>slot.staff)}
export function invitation(token){const value=legacy.invitation(token);if(value&&!value.bookingTypeId)value.bookingTypeId='booking-type-induction';return value}
export function confirmBooking(token,selection,options){const result=legacy.confirmBooking(token,selection,options),invite=invitation(token);if(result.booking){if(invite){invite.used=true;invite.revoked=false;}Object.assign(result.booking,{bookingTypeId:'booking-type-induction',bookingTypeName:'Induction',invitationId:token,originalTimeZone:selection.timeZone,bookingOrigin:result.booking.acceptanceOrigin,createdAt:result.booking.createdAt||new Date().toISOString(),rescheduledAt:result.booking.createdAt?new Date().toISOString():null,cancelledAt:null});}return result}
export function cancelApplicantBooking(token){const booking=legacy.cancelApplicantBooking(token);booking.cancelledAt=new Date().toISOString();return booking}
export const availabilityDemo=legacy.availabilityDemo;export const DEMO_STAFF_PROFILES=legacy.DEMO_STAFF_PROFILES;export const DEMO_INVITATIONS=legacy.DEMO_INVITATIONS;export const resetAvailabilityDemo=legacy.resetAvailabilityDemo;export const createRecurringHours=legacy.createRecurringHours;export const reportUnavailability=legacy.reportUnavailability;export const removeOwnUnavailability=legacy.removeOwnUnavailability;export const capacitySummary=legacy.capacitySummary;export const simulateAccount=legacy.simulateAccount;
