import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {read,save,E,digest} from './read-only.mjs';
const require=createRequire(path.resolve('infrastructure/domains/team-hub/package.json'));
const {App,Stack,BootstraplessSynthesizer}=require('aws-cdk-lib');
const {CfnInclude}=require('aws-cdk-lib/cloudformation-include');
const F='docs/architecture/team-hub-2b3-final-evidence-2026-10-05';
const baseline=read('docs/architecture/team-hub-2b2-caller-release-evidence-2026-10-05/ownership.json').productTemplate;
const proposal=read(F+'/dark-target.template.json');
const app=new App({outdir:path.resolve('.tmp/team-hub-gate3/assembly'),analyticsReporting:false});
const stack=new Stack(app,'ProjectRespawn-TeamHub-Ntgre',{env:{account:'058264289478',region:'eu-north-1'},synthesizer:new BootstraplessSynthesizer()});
new CfnInclude(stack,'AcceptedDarkTarget',{templateFile:path.resolve(F+'/dark-target.template.json'),preserveLogicalIds:true});
const assembly=app.synth();
const product=assembly.getStackArtifact(stack.artifactId).template;
for(const [id,r]of Object.entries(baseline.Resources))assert.deepEqual(product.Resources[id],r,id);
for(const id of ['OperationalTable','JournalTable']){const expected=structuredClone(proposal.Resources[id]);expected.Properties.Tags.sort((a,b)=>a.Key.localeCompare(b.Key));assert.deepEqual(product.Resources[id],expected);}
assert.equal(Object.keys(product.Resources).length,13);
save('product.template',product);
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const hash=sha(E+'/product.template.json'),key=`team-hub/gate3/${hash}.template.json`;
const url=`https://cdk-hnb659fds-assets-058264289478-eu-north-1.s3.eu-north-1.amazonaws.com/${key}`;
const security=read(F+'/dark-security.template.json');
const policy=security.Resources.PreparationCaller.Properties.PolicyDocument;
const old=policy.Statement.find(s=>s.Action==='cloudformation:CreateChangeSet').Condition.StringEquals['cloudformation:TemplateUrl'];
const oldKey=old.split('.amazonaws.com/')[1];
const updated=JSON.parse(JSON.stringify(policy).replaceAll(old,url).replaceAll(oldKey,key));
security.Resources.PreparationCaller.Properties.PolicyDocument=updated;
save('security.template',security);
save('execution-policy',security.Resources.ExecutionBoundary.Properties.PolicyDocument);
save('caller-policy',updated);
assert.deepEqual(security.Resources.ExecutionBoundary.Properties.PolicyDocument,security.Resources.ExecutionRole.Properties.Policies[0].PolicyDocument);
assert.ok(JSON.stringify(security.Resources.ExecutionBoundary.Properties.PolicyDocument).length<=6144);
const schema=read(F+'/target-schema.json');
save('schema',{...schema,journalTable:'ProjectRespawn-TeamHub-Ntgre-Journal',authority:'LEGACY_WRITER',targetWriterEnabled:false,seedRecords:0});
save('candidate',{at:new Date().toISOString(),productSha256:hash,securitySha256:sha(E+'/security.template.json'),key,url,stack:stack.stackName,securityStack:'ProjectRespawn-TeamHub-Ntgre-ReadProofSecurity',schema:'team-hub-state.v1',productCount:13,securityCount:5,expectedProductChanges:{Add:['OperationalTable','JournalTable'],Modify:[],Remove:[]},expectedSecurityChanges:{Add:[],Modify:['ExecutionBoundary','ExecutionRole','PreparationCaller'],Remove:[]},originalTemplateUrl:old,runtimeUnchanged:true,legacySynthesized:false,tournamentSynthesized:false,lambdaBundled:false,productDigest:digest(product)});
console.log(JSON.stringify({hash,key,product:13,security:5,securityModifications:3}));
