<template>
  <section class="admin-orders-page">
    <header class="admin-orders-hero"><div><p class="admin-orders-kicker">Commerce</p><h1>Orders</h1><p>Review payments and provider-aware fulfillment.</p></div><button @click="loadOrders" :disabled="loading">Refresh</button></header>
    <form class="admin-orders-filters" @submit.prevent="importExistingRevolutOrder"><input v-model.trim="legacyRevolutOrderId" placeholder="Existing Revolut order ID"><button :disabled="actionLoading || !legacyRevolutOrderId">Import Existing Revolut Order</button></form>
    <p v-if="error" class="admin-orders-alert error">{{ error }}</p><p v-if="message" class="admin-orders-alert success">{{ message }}</p>
    <section class="admin-orders-filters"><input v-model="search" placeholder="Order ID or customer email"><select v-model="paymentFilter"><option value="">All payments</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select><select v-model="fulfillmentFilter"><option value="">All fulfillment</option><option value="pending">Pending</option><option value="partially_fulfilled">Partially fulfilled</option><option value="fulfilled">Fulfilled</option><option value="failed">Failed</option><option value="recovery_required">Recovery required</option><option value="recovered">Recovered</option></select></section>
    <section class="admin-orders-grid"><article class="admin-orders-panel"><p v-if="loading">Loading orders…</p><button v-for="order in filteredOrders" :key="order.id" class="order-row" :class="{ selected: selectedOrder?.id === order.id }" @click="selectOrder(order)"><strong>{{ order.projectOrderId }}</strong><span>{{ order.email }}</span><span>{{ order.paymentStatus }} · {{ fulfillmentSummary(order) }}</span><span>{{ formatDate(order.createdAt) }}</span></button><p v-if="!loading && !filteredOrders.length">No stored orders match these filters.</p></article>
      <article class="admin-orders-panel" v-if="selectedOrder"><h2>Order details</h2><dl><dt>Project Respawn</dt><dd>{{ selectedOrder.projectOrderId }}</dd><dt>Revolut</dt><dd>{{ selectedOrder.revolutOrderId }}</dd><dt>Payment</dt><dd>{{ selectedOrder.paymentStatus }} · {{ selectedOrder.currency || '—' }} {{ selectedOrder.paymentAmount ?? '—' }}</dd><dt>Payment date</dt><dd>{{ formatDate(selectedOrder.paymentDate) }}</dd><dt>Fulfillment</dt><dd>{{ fulfillmentSummary(selectedOrder) }}</dd><dt>Customer</dt><dd>{{ selectedOrder.customerName }} · {{ selectedOrder.email }}</dd><dt>Shipping</dt><dd>{{ selectedOrder.shippingAddress?.address }}, {{ selectedOrder.shippingAddress?.city }}, {{ selectedOrder.shippingAddress?.postcode }}, {{ selectedOrder.shippingAddress?.country }}</dd></dl><h3>Items</h3><div v-for="item in selectedOrder.items || []" :key="`${item.productId}-${item.fulfillmentVariantId}`" class="order-item">{{ item.productId }} × {{ item.quantity }} · {{ item.fulfillmentProvider }} · {{ item.fulfillmentVariantId || 'No fulfillment variant' }}</div><h3>Providers</h3><div v-for="(status, provider) in selectedOrder.providerStatuses || {}" :key="provider" class="order-item">{{ provider }}: {{ status.status }} <span v-if="status.providerOrderId">· Provider order {{ status.providerOrderId }}</span><span v-if="status.lastAttempt">· Last attempt {{ formatDate(status.lastAttempt) }}</span><span v-if="status.lastError">· Error {{ status.lastError }}</span></div><h3>Audit history</h3><div v-for="entry in selectedOrder.auditHistory || []" :key="`${entry.timestamp}-${entry.action}`" class="order-item">{{ formatDate(entry.timestamp) }} · {{ entry.action }} · {{ entry.provider || 'order' }} · {{ entry.result }}</div><button class="recover" :disabled="actionLoading || selectedOrder.paymentStatus !== 'completed' && selectedOrder.paymentStatus !== 'paid'" @click="recoverOrder(selectedOrder)">{{ actionLoading ? 'Recovering…' : 'Recover Fulfillment' }}</button></article><article class="admin-orders-panel" v-else><p>Select an order to view provider details or recover fulfillment.</p></article></section>
  </section>
</template>
<script src="./AdminOrders.js"></script><style src="./AdminOrders.css"></style>
