import { normalizeEmailForConfirmation } from './applicationSubmission.js';
const trim = (value) => String(value ?? '').trim();
const httpsUrl = (value) => { try { const url = new URL(trim(value)); return url.protocol === 'https:' && !url.username && !url.password; } catch { return false; } };
const email = (value) => { const raw = normalizeEmailForConfirmation(value); const at = raw.lastIndexOf('@'); return at > 0 && at === raw.indexOf('@') && at < raw.length - 1 && raw.length <= 320 && !/[\s\u0000-\u001f\u007f]/u.test(raw) && raw.slice(at + 1).includes('.'); };
export const FIELD_MAP = Object.freeze({
  applicationType:{step:1,section:'Pathway',label:'Application pathway',selector:'[data-field="applicationType"]'}, name:{step:2,section:'Basic details',label:'Full name'}, creatorName:{step:2,section:'Basic details',label:'Creator name'}, discord:{step:2,section:'Basic details',label:'Discord username'}, email:{step:2,section:'Contact',label:'Contact email'}, confirmEmail:{step:2,section:'Contact',label:'Confirm contact email'}, timezone:{step:2,section:'Basic details',label:'Time zone',selector:'#timezone'},
  creatorPlatform:{step:3,section:'Creator profile',label:'Primary platform'}, customPlatformLabel:{step:3,section:'Creator profile',label:'Platform name'}, creatorHandle:{step:3,section:'Creator profile',label:'Public handle'}, channelLink:{step:3,section:'Creator profile',label:'Main channel link'}, otherProfiles:{step:3,section:'Creator profile',label:'Other public profile links'}, discordInvite:{step:3,section:'Discord',label:'Public Discord invite'}, streamerRole:{step:3,section:'Creator profile',label:'Creator role',selector:'[data-field="streamerRole"]'}, whyApplyStreamer:{step:3,section:'Creator profile',label:'Why you want to apply'}, confidenceFit:{step:3,section:'Creator profile',label:'How Project Respawn fits'}, genres:{step:3,section:'Content',label:'Content genres',selector:'[data-field="genres"]'}, favouriteGames:{step:3,section:'Content',label:'Favourite games'}, scheduleDay:{step:3,section:'Schedule',label:'Usual stream day'}, scheduleStart:{step:3,section:'Schedule',label:'Stream start time'}, scheduleEnd:{step:3,section:'Schedule',label:'Stream end time'},
  fitReason:{step:4,section:'Alignment and consent',label:'Mission fit'}, termsAccepted:{step:4,section:'Alignment and consent',label:'Code of conduct declaration'}, publicContentConsent:{step:4,section:'Alignment and consent',label:'Public-content review consent'},
});
const issue=(field,message,index)=>({code:'APPLICATION_VALIDATION_FAILED',field,section:FIELD_MAP[field]?.section||'Application',message,...(index===undefined?{}:{index})});
export function validateCreatorApplication(state,{step}={}) { const issues=[]; const add=(field,message,index)=>{if(!step||FIELD_MAP[field]?.step===step)issues.push(issue(field,message,index));};
  if(!state.applicationType)add('applicationType','Select the Creator Programme pathway.'); else if(state.applicationType!=='creator')add('applicationType','This application pathway is not open.');
  if(!trim(state.profile.name))add('name','Enter your full name.'); else if(trim(state.profile.name).length>200)add('name','Enter no more than 200 characters.');
  if(!trim(state.profile.creatorName))add('creatorName','Enter your creator or channel name.'); if(!trim(state.profile.discord))add('discord','Enter your Discord username.');
  if(!email(state.profile.email))add('email','Enter a valid email address.'); if(!email(state.profile.confirmEmail))add('confirmEmail','Enter a valid email address.'); else if(normalizeEmailForConfirmation(state.profile.email)!==normalizeEmailForConfirmation(state.profile.confirmEmail))add('confirmEmail','The email addresses do not match.');
  if(!trim(state.profile.timezone))add('timezone','Choose your time zone.'); else {try{Intl.DateTimeFormat('en-GB',{timeZone:state.profile.timezone}).format();}catch{add('timezone','Choose a valid IANA time zone.');}}
  if(!trim(state.streamerProfile.platform))add('creatorPlatform','Select a primary platform.'); if(state.streamerProfile.platform==='Other'&&!trim(state.streamerProfile.customPlatformLabel))add('customPlatformLabel','Enter the platform name.'); if(!trim(state.streamerProfile.handle))add('creatorHandle','Enter your public handle.');
  if(!httpsUrl(state.streamerProfile.channelLink))add('channelLink','Enter a complete profile URL beginning with https://.');
  trim(state.streamerProfile.otherProfiles).split(/\r?\n|,/).filter(Boolean).forEach((url,index)=>{if(!httpsUrl(url))add('otherProfiles',`Profile ${index+2} needs a complete URL beginning with https://.`,index)}); if(trim(state.streamerProfile.discordInvite)&&!httpsUrl(state.streamerProfile.discordInvite))add('discordInvite','Enter a complete Discord URL beginning with https://.');
  if(!trim(state.streamerRole))add('streamerRole','Choose the creator role you want to fill.'); if(!trim(state.streamerProfile.whyApply))add('whyApplyStreamer','Explain why you want to apply.'); if(!trim(state.streamerProfile.confidenceFit))add('confidenceFit','Explain how Project Respawn fits your content.');
  if(!state.streamerProfile.genres.length)add('genres','Select at least one content genre.'); else if(state.streamerProfile.genres.length>5)add('genres','Select no more than five genres.'); if(trim(state.streamerProfile.games).split(/\r?\n|,/).filter(Boolean).length>3)add('favouriteGames','Add no more than three favourite games.');
  if(!state.schedule.scheduleVaries&&state.schedule.hasRegularSchedule){if(!trim(state.schedule.dayOfWeek))add('scheduleDay','Choose the usual stream day.');if(!trim(state.schedule.startLocalTime))add('scheduleStart','Enter the stream start time.');if(!trim(state.schedule.endLocalTime))add('scheduleEnd','Enter the stream end time.');else if(state.schedule.startLocalTime&&state.schedule.endLocalTime<=state.schedule.startLocalTime)add('scheduleEnd','The stream end time must be later than the start time.');}
  if(!trim(state.alignment.fitReason))add('fitReason','Explain why you are a good fit for our mission.'); if(state.alignment.termsAccepted!==true)add('termsAccepted','Accept this declaration before submitting.'); if(state.alignment.publicContentConsent!==true)add('publicContentConsent','Accept this declaration before submitting.'); return issues; }
const BACKEND_KEYS={contact_email:'email',CONTACT_EMAIL:'email',EMAIL_CONFIRMATION_MISMATCH:'confirmEmail',applicant_name:'name',creator_name:'creatorName',time_zone:'timezone',profile_url:'channelLink',PROFILE_PLATFORM:'creatorPlatform',SCHEDULE_DAY:'scheduleDay',start_time:'scheduleStart',end_time:'scheduleEnd',SCHEDULE_END:'scheduleEnd',CONSENT:'termsAccepted',why_apply:'whyApplyStreamer',confidence_fit:'confidenceFit',fit_reason:'fitReason'};
export function mapBackendValidation(message){const raw=String(message||'');const key=Object.keys(BACKEND_KEYS).find(k=>raw.includes(k));const field=key?BACKEND_KEYS[key]:null;return field?[issue(field, field==='confirmEmail'?'The email addresses do not match.':field==='email'?'Enter a valid email address.':`Please correct ${FIELD_MAP[field].label.toLowerCase()}.`)]:[{code:'APPLICATION_VALIDATION_FAILED',field:null,section:'Application',message:'Some submitted information was not accepted. Please review this section and try again.'}];}
export function mapBackendIssues(issues){if(!Array.isArray(issues))return mapBackendValidation('');const aliases={'creatorProfiles[0].url':'channelLink','schedule[0].startTime':'scheduleStart','schedule[0].endTime':'scheduleEnd','schedule[0].dayOfWeek':'scheduleDay',contactEmailConfirmation:'confirmEmail'};return issues.map(item=>{const field=aliases[item?.field]||item?.field;return FIELD_MAP[field]?{code:'APPLICATION_VALIDATION_FAILED',field,section:FIELD_MAP[field].section,message:String(item.message||`Please correct ${FIELD_MAP[field].label.toLowerCase()}.`),...(item.index===undefined?{}:{index:item.index})}:{code:'APPLICATION_VALIDATION_FAILED',field:null,section:String(item?.section||'Application'),message:'Some submitted information was not accepted. Please review this section and try again.'}});}
export function sectionReview(state){const issues=validateCreatorApplication(state);return [1,2,3,4].map(step=>{const relevant=issues.filter(x=>FIELD_MAP[x.field]?.step===step);const optionalEmpty=step===4&&!trim(state.alignment.questions);return{step,label:['Pathway','Basic details','Creator profile and schedule','Alignment and consent'][step-1],status:relevant.length?'Needs attention':optionalEmpty?'Complete · Optional information not provided':'Complete',issues:relevant}});}
