import assert from 'node:assert/strict'; import test from 'node:test'; import fs from 'node:fs'; import { FIELD_MAP, mapBackendIssues, sectionReview, validateCreatorApplication } from './applicationValidation.js';
const valid=()=>({applicationType:'creator',profile:{name:'Alex Applicant',creatorName:'Alex Creates',discord:'alex',email:'Alex+tag@Example.COM',confirmEmail:'Alex+tag@example.com',timezone:'Europe/London'},streamerRole:'community-streamer',streamerProfile:{platform:'Twitch',customPlatformLabel:'',handle:'alex',channelLink:'https://twitch.tv/alex',otherProfiles:'https://youtube.com/@alex',discordInvite:'https://discord.gg/example',whyApply:'A meaningful reason.',confidenceFit:'A mission fit.',genres:['Cosy'],games:'Celeste'},schedule:{hasRegularSchedule:true,scheduleVaries:false,dayOfWeek:'Tuesday',startLocalTime:'19:00',endLocalTime:'21:00'},alignment:{fitReason:'Shared values.',termsAccepted:true,publicContentConsent:true,questions:''}});
test('valid creator-v1 data has no issues and review reports completed sections',()=>{const state=valid();assert.deepEqual(validateCreatorApplication(state),[]);assert.ok(sectionReview(state).every(x=>x.status.startsWith('Complete')))});
test('step validation returns every exact blocking field while preserving the input',()=>{const state=valid(),snapshot=structuredClone(state);state.profile.name='';state.profile.email='bad';state.profile.confirmEmail='other@example.com';const issues=validateCreatorApplication(state,{step:2});assert.deepEqual(issues.map(x=>x.field),['name','email','confirmEmail']);assert.deepEqual(state,{...snapshot,profile:{...snapshot.profile,name:'',email:'bad',confirmEmail:'other@example.com'}})});
test('email mismatch targets confirmation and schedule order targets the exact end field',()=>{const state=valid();state.profile.confirmEmail='other@example.com';state.schedule.endLocalTime='18:00';const issues=validateCreatorApplication(state);assert.match(issues.find(x=>x.field==='confirmEmail').message,/do not match/);assert.match(issues.find(x=>x.field==='scheduleEnd').message,/later/)});
test('nested profile links include row index and genre/game limits are explicit',()=>{const state=valid();state.streamerProfile.otherProfiles='https://example.com\nnot-a-url';state.streamerProfile.genres=[];state.streamerProfile.games='one,two,three,four';const issues=validateCreatorApplication(state);assert.equal(issues.find(x=>x.field==='otherProfiles').index,1);assert.match(issues.find(x=>x.field==='genres').message,/at least one/);assert.match(issues.find(x=>x.field==='favouriteGames').message,/no more than three/)});
test('server nested keys map canonically and unknown fields get a safe section fallback',()=>{assert.equal(mapBackendIssues([{field:'creatorProfiles[0].url',message:'Fix profile'}])[0].field,'channelLink');assert.equal(mapBackendIssues([{field:'schedule[0].endTime',message:'Fix time'}])[0].field,'scheduleEnd');const unknown=mapBackendIssues([{field:'internal.table',section:'profiles',message:'secret'}])[0];assert.equal(unknown.field,null);assert.doesNotMatch(unknown.message,/secret|table/)});
test('canonical field map provides stable step and selector destinations',()=>{assert.equal(FIELD_MAP.confirmEmail.step,2);assert.equal(FIELD_MAP.scheduleEnd.step,3);assert.equal(FIELD_MAP.termsAccepted.step,4)});
test('form exposes accessible inline errors, focused summary, linked review, and non-colour status text',()=>{const template=fs.readFileSync(new URL('./Applications.vue',import.meta.url),'utf8'),feedback=fs.readFileSync(new URL('./FieldValidation.vue',import.meta.url),'utf8');for(const token of ['aria-invalid','aria-describedby','application-error-summary','tabindex="-1"','Some information needs attention','goToIssue(issue)','Review your application'])assert.match(template,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(feedback,/✓/);assert.match(feedback,/Server validation:/);});
