<template>
  <main class="creator-analytics">
    <header class="analytics-hero"><div><p>Creator intelligence · simulated data</p><h1>Analytics Overview</h1><span>Understand your audience, connected community, content and future commercial opportunities.</span></div><span class="demo-badge">Frontend demo</span></header>
    <CreatorAnalyticsNav :sections="analyticsSections" :active="activeSection" @select="selectSection" />
    <p v-if="plannedMessage" class="planned-message" role="status">{{ plannedMessage }}</p>
    <CreatorAnalyticsFilterBar :state="state" :times="timeOptions" :sources="sourceOptions" :audiences="audienceOptions" :presets="analyticsPresets" @update="updateFilter" @preset="setPreset" @reset="resetDemo" />
    <p v-if="state.time==='Custom'" class="custom-notice">Custom range is represented by a curated demo window. A future analytics API will supply exact dates.</p>

    <section v-if="!data" class="analytics-empty" aria-labelledby="empty-title"><span>Fresh analytics state</span><h2 id="empty-title">Connect creator data to begin</h2><p>Connect Twitch or Discord to see platform reporting. Cross-platform analytics additionally require Respawn members to link the relevant accounts.</p><button type="button" @click="router.push({name:'CreatorIntegrations'})">Open Integrations</button></section>
    <template v-else>
      <section class="analytics-metric-grid" aria-label="Primary analytics"><CreatorAnalyticsMetricCard v-for="metric in primaryMetrics" :key="metric.key" :metric="metric" /></section>

      <section class="audience-community-grid">
        <section class="analytics-panel audience-panel" aria-labelledby="audience-title"><header class="analytics-section-heading"><div><p>Independent platforms</p><h2 id="audience-title">Audience Overview</h2><span>Platform totals are not combined into unique people.</span></div></header><div class="platform-grid"><details v-for="platform in visiblePlatforms" :key="platform.name" open class="platform-card" :class="`platform-card--${platform.tone}`"><summary><span class="platform-title"><span class="platform-brand" aria-hidden="true"><img v-if="platformIcons[platform.name]" :src="platformIcons[platform.name]" alt=""><svg v-else-if="platform.name==='Twitch'" viewBox="0 0 24 24"><path fill="currentColor" d="M4 2h18v13l-5 5h-4l-3 3v-3H5V6zm2 2v14h5v2l2-2h4l3-3V4zm5 4h2v6h-2zm5 0h2v6h-2z"/></svg><svg v-else viewBox="0 0 24 24"><path fill="currentColor" d="M21.6 7.2a2.8 2.8 0 0 0-2-2C17.8 4.7 12 4.7 12 4.7s-5.8 0-7.6.5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2 12a29 29 0 0 0 .4 4.8 2.8 2.8 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.8 2.8 0 0 0 2-2A29 29 0 0 0 22 12a29 29 0 0 0-.4-4.8ZM10 15.2V8.8l5.5 3.2z"/></svg></span>{{ platform.name }}</span><strong>{{ platform.total }}</strong><small>{{ platform.label }} · {{ platform.change }}</small></summary><ul><li v-for="metric in platform.metrics.slice(0,3)" :key="metric">{{ metric }}</li></ul></details></div></section>
        <section class="connected-grid"><article class="analytics-panel connected-card"><header class="analytics-section-heading"><div><p>This creator's linked members</p><h2>Connected Community</h2></div><CreatorAnalyticsInfoPopover text="Only accounts explicitly linked to this creator's Project Respawn community contribute to person-level cross-platform analysis." /></header><div class="connected-total"><span>Total Respawn Members</span><strong>{{ data.connected.total }}</strong></div><div class="connected-list"><div v-for="item in data.connected.linked" :key="item[0]"><span>{{ item[0] }}</span><strong>{{ item[1] }}</strong></div></div><div class="coverage-inline"><span>Cross-platform coverage</span><progress :value="data.confidence.coverage" max="100"/><strong>{{ data.confidence.coverage }}%</strong></div></article><article class="analytics-panel confidence-card"><header class="analytics-section-heading"><div><p>Data confidence</p><h2>{{ data.confidence.level }}</h2></div></header><div class="confidence-shield" aria-hidden="true">✓</div><p>{{ data.confidence.text }}</p></article></section>
      </section>
      <aside class="identity-notice"><strong>Cross-platform identity safeguard</strong><p>Cross-platform insights use only Project Respawn members who linked the relevant accounts. Project Respawn does not assume Twitch, Discord, YouTube or Instagram accounts belong to the same person.</p></aside>

      <section class="growth-intelligence-grid">
        <section class="analytics-panel growth-panel" aria-labelledby="growth-title"><header class="analytics-section-heading"><div><p>Long-term intelligence</p><h2 id="growth-title">Community Growth Over Time</h2><span>{{ state.time }} · {{ state.source }} · {{ state.audience }}</span></div><label>Metric<select v-model="state.chartMetric"><option v-for="metric in chartMetrics" :key="metric">{{ metric }}</option></select></label></header><CreatorAnalyticsChart :values="history" :metric="state.chartMetric" :period="state.time" :milestones="currentMilestones" /></section>
        <section class="insight-columns"><article class="analytics-panel positive-panel"><header class="analytics-section-heading"><div><p>Positive signals</p><h2>What's Working</h2></div></header><CreatorAnalyticsDisclosure v-for="item in insights.working" :key="item.title" :item="item" /></article><article class="analytics-panel warning-panel"><header class="analytics-section-heading"><div><p>Opportunities</p><h2>Areas for Improvement</h2></div></header><CreatorAnalyticsDisclosure v-for="item in insights.improve" :key="item.title" :item="item" tone="warning" /></article></section>
      </section>

      <section v-if="state.source==='Cross Platform' || state.source==='All Creator Data'" class="analytics-panel cross-platform-panel"><header class="analytics-section-heading"><div><p>Explicitly linked members only</p><h2>Cross Platform Coverage</h2></div></header><div class="analytics-mini-grid cross-grid"><div v-for="item in data.crossPlatform" :key="item[0]"><span>{{ item[0] }}</span><strong>{{ item[1] }}</strong></div></div></section>

      <section class="outcome-grid">
        <section class="analytics-panel journey-panel" aria-labelledby="journey-title"><header class="analytics-section-heading"><div><p>Creator-scoped, attributable members</p><h2 id="journey-title">Your Connected Community Journey</h2></div></header><ol class="community-journey"><li v-for="step in journey" :key="step[0]"><span>{{ step[0] }}</span><strong>{{ Number(step[1]).toLocaleString() }}</strong></li></ol><p class="analytics-note">Only members who linked the relevant accounts to this creator's Respawn community can move through cross-platform stages.</p></section>
        <article class="analytics-panel content-panel"><header class="analytics-section-heading"><div><p>Top performing content</p><h2>Content Performance</h2></div></header><div class="analytics-table-wrap"><table><thead><tr><th>Content</th><th>Reach</th><th>Engagement</th><th>Respawn Conversions</th></tr></thead><tbody><tr v-for="row in contentPerformance" :key="row[0]"><th>{{ row[0] }}</th><td>{{ row[1] }}</td><td>{{ row[2] }}</td><td>{{ row[4] }}</td></tr></tbody></table></div><p class="analytics-note">Conversions are simulated and attribution-dependent.</p></article>
        <article class="analytics-panel mission-panel"><header class="analytics-section-heading"><div><p>Respawn-owned data</p><h2>Mission Performance</h2></div></header><div class="mission-visual"><div class="mission-donut"><strong>58.8%</strong><span>Completion rate</span></div><div class="mission-totals"><div v-for="item in missions.totals" :key="item[0]"><span>{{ item[0] }}</span><strong>{{ item[1] }}</strong></div></div></div><details><summary>Best-performing missions</summary><div class="mission-bars"><div v-for="item in missions.top" :key="item[0]"><span>{{ item[0] }} <b>{{ item[1] }}%</b></span><progress :value="item[1]" max="100"/></div></div></details></article>
      </section>

      <section class="earnings-heading"><p>Separate creator-facing systems</p><h2>Earnings & Commercial Intelligence</h2><span>No combined “total revenue” is shown. Each source has different rules and status.</span></section>
      <section class="economy-dashboard-grid">
        <CreatorSupportMembershipCard :data="memberships" />
        <article class="analytics-panel affiliate-panel"><header class="analytics-section-heading"><div><p>Creator-facing results</p><h2>Affiliate Performance</h2></div></header><div class="affiliate-summary"><div><span>Creator Affiliate Earnings</span><strong>£842</strong></div><div><span>Clicks</span><strong>1,424</strong></div><div><span>Conversions</span><strong>101</strong></div><div><span>Conversion Rate</span><strong>7.1%</strong></div></div><div class="affiliate-bars" aria-label="Illustrative partner performance"><i style="--value:68%"></i><i style="--value:92%"></i><i style="--value:34%"></i></div><details><summary>Provider breakdown</summary><table><tbody><tr v-for="row in affiliates" :key="row[0]"><th>{{ row[0] }}</th><td>{{ row[1] }} clicks</td><td>{{ row[2] }} conversions</td><td>{{ row[3] }}</td></tr></tbody></table></details></article>
        <CreatorCompensationCard :history="bonusHistory" />
        <section class="analytics-panel trends-panel"><header class="analytics-section-heading"><div><p>Observed relationships</p><h2>Trends & Correlations</h2></div></header><div class="trend-grid"><article><strong>Mission Completion ↔ Retention</strong><p>Strong positive relationship</p></article><article><strong>Discord Engagement ↔ Events</strong><p>Strong positive relationship</p></article><article><strong>Achievements ↔ Retention</strong><p>Moderate positive relationship</p></article><article><strong>Mission Activity ↔ Affiliate Conversion</strong><p>Emerging relationship</p></article></div><p class="analytics-note">Creator-scoped simulated observations. Correlation does not prove causation.</p></section>
      </section>
      <section class="analytics-panel campaign-card"><span class="planned-badge">Planned feature</span><h2>Campaigns & Sponsorships</h2><p>Future campaign and commercial-mission income will remain separate from affiliates, memberships and Creator Compensation.</p></section>
      <section class="commercial-intelligence-panel analytics-panel" aria-labelledby="commercial-title"><header class="analytics-section-heading"><div><p>Separate creator-facing systems</p><h2 id="commercial-title">Earnings & Commercial Intelligence</h2><span>No combined total revenue. Each source has different rules and status.</span></div></header><div class="commercial-intelligence-grid"><article><span class="planned-badge">Planned feature</span><h3>Support & Memberships</h3><p>Engagement insights only; membership purchasing and Project Respawn economics remain private.</p><div class="commercial-metrics"><span>Engagement <b>87</b></span><span>Retention <b>82%</b></span><span>Activity <b>+12%</b></span></div></article><article><span class="demo-badge">Creator-facing results</span><h3>Affiliate Performance</h3><strong class="commercial-value">£842</strong><div class="commercial-metrics"><span>Clicks <b>1,424</b></span><span>Conversions <b>101</b></span><span>Rate <b>7.1%</b></span></div></article><article class="commercial-compensation"><span class="future-badge">Future feature</span><h3>Creator Compensation</h3><p>Illustrative future functionality, not an active offer.</p><div class="commercial-plan-pair"><span>Stable <b>£2,150</b></span><span>Performance <b>£1,700</b></span></div><div class="commercial-metrics"><span>Forecast <b>£1,950</b></span><span>Next update <b>6 days</b></span><span>Progress <b>68%</b></span></div></article><article><span class="demo-badge">Observed relationships</span><h3>Trends & Correlations</h3><ul><li>Mission Completion ↔ Retention</li><li>Discord Engagement ↔ Events</li><li>Achievements ↔ Retention</li><li>Mission Activity ↔ Conversion</li></ul></article></div></section>
    </template>
    <footer class="analytics-demo-footer"><strong>Demo mode</strong><span>All Analytics values are simulated. No real connections, payments, compensation or exports occur.</span></footer>
  </main>
</template>
<script setup>
import{computed,reactive,ref}from'vue';import{useRouter}from'vue-router';import CreatorAnalyticsNav from '../../components/analytics/CreatorAnalyticsNav.vue';import CreatorAnalyticsFilterBar from '../../components/analytics/CreatorAnalyticsFilterBar.vue';import CreatorAnalyticsInfoPopover from '../../components/analytics/CreatorAnalyticsInfoPopover.vue';import CreatorAnalyticsMetricCard from '../../components/analytics/CreatorAnalyticsMetricCard.vue';import CreatorAnalyticsChart from '../../components/analytics/CreatorAnalyticsChart.vue';import CreatorAnalyticsDisclosure from '../../components/analytics/CreatorAnalyticsDisclosure.vue';import CreatorSupportMembershipCard from '../../components/analytics/CreatorSupportMembershipCard.vue';import CreatorCompensationCard from '../../components/analytics/CreatorCompensationCard.vue';import{affiliates,analyticsPresets,analyticsSections,audienceOptions,bonusHistory,chartMetrics,contentPerformance,createAnalyticsState,getPresetData,insights,journey,memberships,missions,selectHistory,sourceOptions,sourcePlatforms,timeOptions,visibleMilestones}from'./creatorAnalyticsDemoState.js'
import instagramIcon from '../../../../assets/Icons/Instagram-logo.svg';import discordIcon from '../../../../assets/Icons/Discord-logo.svg'
const platformIcons={Instagram:instagramIcon,Discord:discordIcon}
const router=useRouter();const state=reactive(createAnalyticsState());const activeSection=ref('overview');const plannedMessage=ref('');const data=computed(()=>getPresetData(state.preset));const primaryMetrics=computed(()=>{if(!data.value)return[];const factor=state.time==='3 Years'?1.08:state.time==='7 Days'?.96:1;return data.value.primary.map(item=>({...item,value:item.key==='viewers'?String(Math.round(Number(item.value)*factor)):item.value,change:`${item.change} · ${state.audience}`}))});const visiblePlatforms=computed(()=>sourcePlatforms(data.value,state.source));const history=computed(()=>selectHistory(state.chartMetric,state.time));const currentMilestones=computed(()=>visibleMilestones(state.time));
function setPreset(key){Object.assign(state,createAnalyticsState(key));plannedMessage.value=''}function resetDemo(){setPreset('fresh')}function updateFilter(key,value){state[key]=value}function selectSection(item){if(item.available){activeSection.value=item.key;plannedMessage.value='';return}plannedMessage.value=`${item.label} is a planned Analytics destination. Its relevant preview remains available in Overview.`}
</script>
<style src="./CreatorAnalytics.css"></style>
