export const BUILDER_DEMO_VERSION=1
const fixed='2026-08-13T15:00:00.000Z'
const seeds={text:{name:'Creator Information',size:[620,150],settings:{text:'Your stream. Your community.',fontSize:52,textAlign:'center',color:'#ffffff',background:'#111827',opacity:1,cornerRadius:18}},alerts:{name:'Follower Alert',size:[800,250],settings:{messageTemplate:'{user} is now following!',duration:6,animation:'slide',background:'#24143d',opacity:1,cornerRadius:24}},'twitch-chat':{name:'Unified Chat',size:[430,620],settings:{showUsername:true,showBadges:true,maxMessages:6,fontSize:24,background:'#111827',opacity:1,cornerRadius:20}},goal:{name:'Community Goal',size:[700,170],settings:{title:'Community Goal',current:64,target:100,unit:'members',barColor:'#8b5cf6',background:'#111827',opacity:1,cornerRadius:18}},'upcoming-event':{name:'Upcoming Event',size:[620,230],settings:{title:'Custom Lobby Night',dateTime:'Sunday · 20:00',attendees:28,countdown:'2d 04h',background:'#14263b',opacity:1,cornerRadius:22}},'webcam-frame':{name:'Webcam Frame',size:[520,320],settings:{kicker:'Creator camera',title:'LIVE',subtitle:'Webcam frame preview',background:'#101827',color:'#fff',opacity:.72,cornerRadius:12}}}
function seedWidget(type,key,index,position){const d=seeds[type],now=fixed;return{schemaVersion:1,id:`widget-${key}-${type}-${index+1}`,type,name:d.name,enabled:true,locked:false,frame:{x:position.x,y:position.y,width:d.size[0],height:d.size[1],rotation:0},zIndex:index+1,settings:cloneSerializableData(d.settings),themeId:'respawn-purple',dataSource:{provider:'demo',topics:[]},animations:{entrance:d.settings.animation||'fade',exit:'fade',durationMs:900},createdAt:now,updatedAt:now}}
export function createBuilderScenes(){
  const specs=[['starting-soon','Starting Soon','studio'],['main-gameplay','Main Gameplay','dark-gameplay'],['just-chatting','Just Chatting','camera'],['brb','Be Right Back','minimal'],['stream-ending','Stream Ending','bright-gameplay']]
  return specs.map(([key,name,background],index)=>{const scene={schemaVersion:1,id:`scene-${key}`,brandId:'local-demo-brand',ownerContext:'local-demo',name,description:'',resolution:{width:1920,height:1080,label:'1080p',preset:'1080p'},runtime:{status:'demo',credentialStatus:'not-provisioned'},version:1,createdAt:fixed,updatedAt:fixed,required:true,isDefault:index===1,themeId:'respawn-purple',preview:{backgroundType:'reference',referenceAssetId:background,brightness:background.includes('bright')?'bright':'dark',motion:background.includes('gameplay')?'high':'low',color:'#0b1020'},widgets:[]};const items=index===1?[['alerts',{x:60,y:60}],['twitch-chat',{x:1410,y:120}],['goal',{x:70,y:780}],['upcoming-event',{x:70,y:520}],['webcam-frame',{x:1160,y:650}]]:index===0?[['text',{x:650,y:360}],['upcoming-event',{x:650,y:560}] ]:[['text',{x:650,y:420}]];scene.widgets=items.map(([type,position],i)=>seedWidget(type,key,i,position));return scene})
}
export function createBuilderProject(){return{schemaVersion:BUILDER_DEMO_VERSION,name:'Creator Overlay',themeId:'respawn-purple',selectedSceneId:'scene-main-gameplay',selectedWidgetId:'',grid:true,snapping:true,safeZone:true,animationsPaused:false,publishReady:false,scenes:createBuilderScenes(),obsMappings:[]}}
export function restoreBuilderProject(value){try{const parsed=typeof value==='string'?JSON.parse(value):value;if(parsed?.schemaVersion!==BUILDER_DEMO_VERSION||!Array.isArray(parsed.scenes)||!parsed.scenes.length)throw Error();return cloneSerializableData(parsed)}catch{return createBuilderProject()}}
export function demoImportFindings(){return{sceneCount:6,browserSourceCount:4,resolution:'1920 × 1080',sceneNames:['Starting Soon','Main Gameplay','Just Chatting','Be Right Back','Stream Ending','Sponsor Break']}}
export function exportSummary(project,scope='current',strategy='universal'){return{scope,strategy,sceneCount:scope==='all'?project.scenes.length:1,preserveExisting:true,status:'Demo export prepared · No OBS changes were made'}}
export const DEMO_SOURCE_PLACEHOLDER='demo://project-respawn/overlay-not-live'
import { cloneSerializableData } from './overlaySnapshots.js'
