import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {makeRequest,validateRequest,validateWindow,workflow,table} from './package.mjs';import {createDarkMonitoringHandler} from '../../domains/team-hub/dark-monitoring/handler.mjs';import {createCoreIntegrationHandler,proofVersion} from '../../domains/team-hub/core-integration/handler.mjs';import {acceptedCore} from '../../domains/team-hub/core-integration/manifest.mjs';
const E='docs/architecture/team-hub-c1-evidence-2026-10-07',req=JSON.parse(fs.readFileSync(E+'/c1-request.json'));
async function execute(input,store){const definition=workflow(req);let state=definition.StartAt,data=input;const at=(p)=>p.split('.').slice(1).reduce((v,k)=>v?.[k],data);for(let i=0;i<20;i++){const s=definition.States[state];if(s.Type==='Pass'){data=s.Result;state=s.Next;}else if(s.Type==='Task'){assert.equal(s.Parameters.TableName,table);const key=s.Parameters.Key??s.Parameters.Item;const id=key.PK.S+'/'+key.SK.S;if(s.Resource.endsWith('getItem'))data=store.has(id)?{Item:structuredClone(store.get(id))}:{};else {assert.equal(s.Resource,'arn:aws:states:::dynamodb:putItem');assert.equal(s.Parameters.ConditionExpression,'attribute_not_exists(PK) AND attribute_not_exists(SK)');if(store.has(id))throw Error('ConditionalCheckFailedException');store.set(id,structuredClone(s.Parameters.Item));data={};}state=s.Next;}else if(s.Type==='Choice'){const match=c=>c.And?c.And.every(match):c.IsPresent!==undefined?(at(c.Variable)!==undefined)===c.IsPresent:at(c.Variable)===c.StringEquals;state=s.Choices.find(match)?.Next??s.Default;}else if(s.Type==='Fail')throw Error(s.Error);else if(s.Type==='Succeed')return store;}throw Error('Workflow did not terminate');}
test('fixed workflow creates one exact Legacy epoch-1 item and verifies',async()=>{const store=await execute({},new Map());assert.equal(store.size,1);assert.deepEqual(store.get('CONTROL#AUTHORITY/STATE'),req.Item);});
test('duplicate create stops without replacement',async()=>{const store=await execute({},new Map());const prior=JSON.stringify([...store]);await assert.rejects(execute({},store),/AuthorityAlreadyExists/);assert.equal(JSON.stringify([...store]),prior);});
for(const input of [{TableName:'Legacy'},{Item:{PK:{S:'TEAM#business'}}},{environment:'Production'},{mode:'TARGET_WRITER',epoch:99},{SK:'OTHER'}])test('untrusted execution input cannot alter fixed target: '+JSON.stringify(input),async()=>{const store=new Map([['OTHER/STATE',{untouched:true}],['CONTROL#AUTHORITY/OTHER',{untouched:true}]]);await execute(input,store);assert.deepEqual(store.get('CONTROL#AUTHORITY/OTHER'),{untouched:true});assert.deepEqual(store.get('OTHER/STATE'),{untouched:true});assert.deepEqual(store.get('CONTROL#AUTHORITY/STATE'),req.Item);});
for(const field of ['TableName','ConditionExpression'])test('request substitution rejected: '+field,()=>{const bad=structuredClone(req);bad[field]='wrong';assert.throws(()=>validateRequest(bad,req));});
for(const field of ['PK','SK','mode','epoch','version'])test('wrong key/state/epoch rejected: '+field,()=>{const bad=structuredClone(req);bad.Item[field]=field==='epoch'||field==='version'?{N:'2'}:{S:'wrong'};assert.throws(()=>validateRequest(bad,req));});
test('wrong environment and oversized grant window rejected',()=>{assert.throws(()=>makeRequest({environment:'Production'}));assert.throws(()=>validateWindow('2026-10-08T10:00:00Z','2026-10-08T11:00:00Z'));validateWindow('2026-10-08T10:00:00Z','2026-10-08T10:15:00Z');});
const subject='00000000-0000-0000-0000-000000000001',token='offline.'+Buffer.from(JSON.stringify({sub:subject,iss:acceptedCore.environmentContract.issuer,client_id:acceptedCore.environmentContract.clientId,token_use:'access',exp:2000})).toString('base64url')+'.fixture';const config={TEAM_HUB_RUNTIME:'read',TEAM_HUB_AUTHORITY:'LEGACY_WRITER',TEAM_HUB_STAGE:'PRE_CUTOVER',TEAM_HUB_NORMAL_WRITES:'DISABLED'};
for(const scenario of ['http','success','forbidden','dependency'])test('D1 preserves dark response and classifies '+scenario,async()=>{const events=[];const invokeCore=async r=>{if(scenario==='dependency')throw Error('private');return {ok:true,data:{contractVersion:r.contractVersion,subject,capability:r.capability,environment:'Ntgre',allowed:false,decisionVersion:1,evaluatedAt:1000,expiresAt:1005}};};const input=scenario==='http'?{routeKey:'POST /v1/teams',requestContext:{requestId:'test-http'}}:{contractVersion:proofVersion,accessToken:token,operation:scenario==='forbidden'?'search':'authorization',...(scenario==='forbidden'?{query:'ab'}:{})};const prior=await createCoreIntegrationHandler({invokeCore,clock:()=>1000})(input);const actual=await createDarkMonitoringHandler({invokeCore,clock:()=>1000,configuration:config,emit:e=>events.push(e)})(input);assert.deepEqual(actual,prior);const sum=k=>events.reduce((n,e)=>n+e[k],0);assert.equal(sum('Requests'),1);assert.equal(sum('CoreDependencyFailures'),scenario==='dependency'?1:0);assert.equal(sum('WriterNotAuthoritative'),scenario==='http'?1:0);assert.equal(sum('AuthorizationFailures'),['http','forbidden'].includes(scenario)?1:0);assert.equal(sum('DependencyFailures'),scenario==='dependency'?1:0);assert.ok(!JSON.stringify(events).includes(token));assert.ok(!JSON.stringify(events).includes(subject));});
test('D1 invalid environment guards fail closed without Core',async()=>{const events=[];const r=await createDarkMonitoringHandler({invokeCore:()=>assert.fail('Core must not run'),configuration:{...config,TEAM_HUB_AUTHORITY:'TARGET_WRITER'},emit:e=>events.push(e)})({});assert.equal(r.statusCode,503);assert.equal(events.reduce((n,e)=>n+e.AuthorityUnavailable,0),1);});
test('D1 has no new resources and changes only two Code references and stage metrics',()=>{const old=JSON.parse(fs.readFileSync('docs/architecture/team-hub-core-integration-evidence-2026-10-07/product.template.json'));const next=JSON.parse(fs.readFileSync(E+'/d1-product.template.json'));assert.equal(Object.keys(next.Resources).length,40);for(const kind of ['Read','Command'])old.Resources['Parity'+kind+'Function'].Properties.Code=next.Resources['Parity'+kind+'Function'].Properties.Code;old.Resources.Stage.Properties.DefaultRouteSettings.DetailedMetricsEnabled=true;assert.deepEqual(next,old);});
test('direct proof uses Lambda request ID for safe metric correlation',async()=>{const events=[];await createDarkMonitoringHandler({invokeCore:async()=>{throw Error('offline')},clock:()=>1000,configuration:config,emit:e=>events.push(e)})({contractVersion:proofVersion,accessToken:token,operation:'authorization'},{awsRequestId:'lambda-request-123'});assert.ok(events.length>0);assert.ok(events.every(e=>e.requestId==='lambda-request-123'));});
