import assert from 'node:assert/strict';import {initialize} from '../team-hub-2b5b/authority-control.mjs';
export const account='058264289478',region='eu-north-1',name='ProjectRespawn-TeamHub-Ntgre-C1Initialize',table='ProjectRespawn-TeamHub-Ntgre-Journal',arn=`arn:aws:dynamodb:${region}:${account}:table/${table}`,machineArn=`arn:aws:states:${region}:${account}:stateMachine:${name}`;
export function makeRequest({environment='Ntgre',changedAt,gateDigest}){assert.equal(environment,'Ntgre');const r=initialize({changedAt,changedBy:'team-hub-c1-executor',gateDigest});return {...r,Item:Object.fromEntries(Object.entries(r.Item).map(([k,v])=>[k,typeof v==='number'?{N:String(v)}:{S:v}])),ReturnValues:'NONE'};}
export function validateRequest(r,approved){assert.deepEqual(r,approved,'Only exact reviewed request permitted');assert.equal(r.TableName,table);assert.equal(r.Item.PK.S,'CONTROL#AUTHORITY');assert.equal(r.Item.SK.S,'STATE');assert.equal(r.Item.mode.S,'LEGACY_WRITER');assert.equal(r.Item.epoch.N,'1');assert.equal(r.Item.version.N,'1');assert.equal(r.ConditionExpression,'attribute_not_exists(PK) AND attribute_not_exists(SK)');}
export function workflow(request){validateRequest(request,request);const key={PK:{S:'CONTROL#AUTHORITY'},SK:{S:'STATE'}},get={TableName:table,Key:key,ConsistentRead:true};const verify=Object.entries(request.Item).map(([k,v])=>({Variable:'$.Item.'+k+'.'+Object.keys(v)[0],StringEquals:Object.values(v)[0]}));return {Comment:'Fixed Ntgre C1 create only. Input discarded. No retries or authority transition.',StartAt:'DiscardInput',TimeoutSeconds:120,States:{DiscardInput:{Type:'Pass',Result:{},Next:'ReadExisting'},ReadExisting:{Type:'Task',Resource:'arn:aws:states:::dynamodb:getItem',Parameters:get,Next:'RequireAbsent'},RequireAbsent:{Type:'Choice',Choices:[{Variable:'$.Item.PK',IsPresent:true,Next:'AlreadyExists'}],Default:'CreateLegacy'},AlreadyExists:{Type:'Fail',Error:'AuthorityAlreadyExists'},CreateLegacy:{Type:'Task',Resource:'arn:aws:states:::dynamodb:putItem',Parameters:request,Catch:[{ErrorEquals:['States.ALL'],Next:'CreateStopped'}],Next:'Verify'},CreateStopped:{Type:'Fail',Error:'ConditionalCreateNotConfirmed'},Verify:{Type:'Task',Resource:'arn:aws:states:::dynamodb:getItem',Parameters:get,Next:'VerifyExact'},VerifyExact:{Type:'Choice',Choices:[{And:verify,Next:'Done'}],Default:'VerificationFailed'},VerificationFailed:{Type:'Fail',Error:'AuthorityReadbackMismatch'},Done:{Type:'Succeed'}}};}
export function policy(window={DateGreaterThanEquals:{'aws:CurrentTime':{'Ref':'WindowStart'}},DateLessThan:{'aws:CurrentTime':{'Ref':'WindowEnd'}}}){return {Version:'2012-10-17',Statement:[{Effect:'Allow',Action:['dynamodb:GetItem','dynamodb:PutItem'],Resource:arn,Condition:{'ForAllValues:StringEquals':{'dynamodb:LeadingKeys':['CONTROL#AUTHORITY']},Null:{'dynamodb:LeadingKeys':'false'},...window}},{Effect:'Deny',NotAction:['dynamodb:GetItem','dynamodb:PutItem'],Resource:'*'},{Effect:'Deny',Action:'dynamodb:*',NotResource:arn}]};}
export function validateWindow(start,end){assert.ok(Number.isFinite(Date.parse(start))&&Number.isFinite(Date.parse(end)));assert.ok(Date.parse(end)>Date.parse(start)&&Date.parse(end)-Date.parse(start)<=15*60*1000,'Maximum 15 minute approved window');}
export function template(request){return {AWSTemplateFormatVersion:'2010-09-09',Description:'TEMPORARY Ntgre C1 security-owned fixed authority initializer; remove after terminal execution',Parameters:{WindowStart:{Type:'String',AllowedPattern:'[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'},WindowEnd:{Type:'String',AllowedPattern:'[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z'}},Resources:{ExecutorRole:{Type:'AWS::IAM::Role',Properties:{RoleName:name,MaxSessionDuration:3600,AssumeRolePolicyDocument:{Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{Service:'states.amazonaws.com'},Action:'sts:AssumeRole',Condition:{StringEquals:{'aws:SourceAccount':account},ArnEquals:{'aws:SourceArn':machineArn}}}]},Policies:[{PolicyName:'FixedAuthorityCreateAndReadback',PolicyDocument:policy()}]}},Initializer:{Type:'AWS::StepFunctions::StateMachine',Properties:{StateMachineName:name,StateMachineType:'STANDARD',RoleArn:{'Fn::GetAtt':['ExecutorRole','Arn']},Definition:workflow(request),LoggingConfiguration:{Level:'OFF',IncludeExecutionData:false},TracingConfiguration:{Enabled:false}}}}};}

