import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {aws,identity} from '../core-2b5a/aws.mjs';
const E='docs/architecture/team-hub-c2-execution-evidence-2026-10-07',P='docs/architecture/team-hub-c1-evidence-2026-10-07',B='docs/architecture/team-hub-core-integration-evidence-2026-10-07';
const read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const c=read(P+'/candidate.json');assert.equal(sha(P+'/candidate.json'),read(P+'/final-review.json').candidateHash);
const changes={};for(const k of ['product','security']){assert.equal(sha(P+'/c2-'+k+'.template.json'),c.c2[k+'Sha256']);const old=read(B+'/'+k+'.template.json'),next=read(P+'/c2-'+k+'.template.json');assert.deepEqual(Object.keys(old.Resources),Object.keys(next.Resources));changes[k]=Object.keys(old.Resources).filter(id=>JSON.stringify(old.Resources[id])!==JSON.stringify(next.Resources[id])).sort();const restored=structuredClone(next);for(const id of changes[k])restored.Resources[id]=old.Resources[id];assert.deepEqual(restored,old);}
assert.deepEqual(changes.product,['ParityCommandRole','ParityReadRole']);assert.deepEqual(changes.security,['ParityCommandBoundary','ParityReadBoundary','PreparationCaller']);
const expected={Sid:'ReadOnlyAuthorityPartition',Effect:'Allow',Action:'dynamodb:GetItem',Resource:'arn:aws:dynamodb:eu-north-1:058264289478:table/ProjectRespawn-TeamHub-Ntgre-Journal',Condition:{'ForAllValues:StringEquals':{'dynamodb:LeadingKeys':['CONTROL#AUTHORITY']},Null:{'dynamodb:LeadingKeys':'false'}}};
const policies=[];for(const kind of ['Read','Command'])for(const type of ['product','security']){const old=read(B+'/'+type+'.template.json'),next=read(P+'/c2-'+type+'.template.json'),id='Parity'+kind+(type==='product'?'Role':'Boundary'),get=r=>type==='product'?r.Properties.Policies[0].PolicyDocument:r.Properties.PolicyDocument;const before=get(old.Resources[id]),after=get(next.Resources[id]);const restored=structuredClone(after);assert.deepEqual(restored.Statement.pop(),expected);const deny=restored.Statement.find(s=>s.Effect==='Deny'&&s.NotAction);assert.ok(deny.NotAction.includes('dynamodb:GetItem'));deny.NotAction=deny.NotAction.filter(a=>a!=='dynamodb:GetItem');assert.deepEqual(restored,before);policies.push({id,type,document:after});}
save('artifact-review',{at:new Date().toISOString(),pinsVerified:true,manifest:sha(P+'/candidate.json'),hashes:c.c2,changes,permission:expected,complete:true});
console.log(JSON.stringify({pinsVerified:true,changes}));
