// Read-only verifier; no deployment/imported application entrypoints.
import fs from 'node:fs';
import crypto from 'node:crypto';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile), read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex');
const phase=process.argv[2];if(!['before','after'].includes(phase))throw Error('Use before or after');
const dir='docs/architecture/team-hub-2b3-direct-protection-evidence-2026-10-05';fs.mkdirSync(dir,{recursive:true});
async function aws(args){const allowed={sts:['get-caller-identity'],cloudformation:['describe-stacks','get-template','list-stack-resources'],lambda:['get-function-configuration'], 'cognito-idp':['describe-user-pool','describe-user-pool-client'],dynamodb:['describe-table'],s3api:['head-bucket'],kms:['describe-key']};if(!allowed[args[0]]?.includes(args[1]))throw Error('Non-read command');for(let n=0;;n++){try{const {stdout}=await exec('aws',[...args,'--profile','default','--region','eu-north-1','--output','json'],{maxBuffer:20e6,windowsHide:true});return stdout.trim()?JSON.parse(stdout):{};}catch(e){if(n>=4||!/Throttling|Rate exceeded/.test(e.stderr||''))throw e;await new Promise(r=>setTimeout(r,1000*2**n));}}}
async function pool(items,fn){let i=0;const results=[];await Promise.all(Array.from({length:3},async()=>{while(i<items.length){const x=i++;results[x]=await fn(items[x]);}}));return results;}
const check=(condition,message)=>{if(!condition)throw Error(message);};
const inventory=read('docs/architecture/phase2-resource-domain-map.json'), outputs=read('amplify_outputs.json');
const identity=await aws(['sts','get-caller-identity']);check(identity.Account==='058264289478','Wrong account');
const root=(await aws(['cloudformation','describe-stacks','--stack-name','amplify-projectrespawnwebsite-Ntgre-sandbox-8bd9d02332'])).Stacks[0];check(root.StackStatus==='UPDATE_COMPLETE','Root unstable');
const all=[];
const stacks=await pool(inventory.stacks,async s=>{const [t,r]=await Promise.all([aws(['cloudformation','get-template','--stack-name',s.arn]),aws(['cloudformation','list-stack-resources','--stack-name',s.arn])]);const template=typeof t.TemplateBody==='string'?JSON.parse(t.TemplateBody):t.TemplateBody;check(hash(template)===s.templateSha256,'Template changed '+s.key);const resources=r.StackResourceSummaries.filter(x=>x.ResourceStatus!=='DELETE_COMPLETE');check(resources.length===s.count,'Count changed '+s.key);for(const live of resources){const prior=inventory.resources.find(x=>x.stackKey===s.key&&x.logicalId===live.LogicalResourceId);check(prior&&prior.type===live.ResourceType,'Resource changed');if(prior.type==='AWS::AppSync::ApiKey')check(crypto.createHash('sha256').update(live.PhysicalResourceId).digest('hex')===prior.physicalIdSha256,'API key identity changed');else check(prior.physicalId===live.PhysicalResourceId,'Physical ID changed');}all.push(...resources);return {key:s.key,templateSha256:hash(template),count:resources.length,identitiesSha256:hash(resources.map(x=>({id:x.LogicalResourceId,type:x.ResourceType,physical:x.PhysicalResourceId})).sort((a,b)=>a.id.localeCompare(b.id)))};});
const protectedResources=await pool(all.filter(r=>/DynamoDB|Cognito::UserPool$|S3::Bucket$|KMS::Key$|AppSync::GraphQLApi$/.test(r.ResourceType)),async r=>{const id=r.PhysicalResourceId;if(/DynamoDB/.test(r.ResourceType)){const t=(await aws(['dynamodb','describe-table','--table-name',id])).Table;check(t.TableStatus==='ACTIVE','Table unavailable');}else if(r.ResourceType==='AWS::Cognito::UserPool'){const p=(await aws(['cognito-idp','describe-user-pool','--user-pool-id',id])).UserPool;check(id===outputs.auth.user_pool_id,'Pool mismatch');}else if(r.ResourceType==='AWS::S3::Bucket')await aws(['s3api','head-bucket','--bucket',id]);else if(r.ResourceType==='AWS::KMS::Key'){const k=(await aws(['kms','describe-key','--key-id',id])).KeyMetadata;check(k.Enabled,'Key disabled');}return {logicalId:r.LogicalResourceId,type:r.ResourceType,physicalId:id,present:true};});
const client=(await aws(['cognito-idp','describe-user-pool-client','--user-pool-id',outputs.auth.user_pool_id,'--client-id',outputs.auth.user_pool_client_id])).UserPoolClient;check(client.UserPoolId===outputs.auth.user_pool_id&&!client.ClientSecret,'Client must be existing public client');
const lambdas=await pool(read('docs/architecture/phase1-ntgre-artifact-evidence/deployed-packages.json'),async p=>{const f=await aws(['lambda','get-function-configuration','--function-name',p.Arn]);check(f.CodeSha256===p.CodeSha256&&f.State==='Active'&&f.LastUpdateStatus==='Successful','Lambda changed');return {arn:p.Arn,hash:f.CodeSha256,configurationSha256:hash({runtime:f.Runtime,role:f.Role,environment:f.Environment,memory:f.MemorySize,timeout:f.Timeout,layers:f.Layers}),state:f.State};});
const result={phase,at:new Date().toISOString(),identity,region:'eu-north-1',root:{arn:root.StackId,name:root.StackName,status:root.StackStatus,lastUpdated:root.LastUpdatedTime,disableRollback:root.DisableRollback},total:all.length,directive:stacks.find(s=>s.key==='029').count,stacks,protectedResources,lambdas,coreIdentity:{poolId:outputs.auth.user_pool_id,clientId:client.ClientId,issuer:`https://cognito-idp.eu-north-1.amazonaws.com/${outputs.auth.user_pool_id}`,source:'amplify_outputs.json',sourceSha256:crypto.createHash('sha256').update(fs.readFileSync('amplify_outputs.json')).digest('hex'),authStackArn:inventory.stacks.find(s=>s.key==='002').arn},awsWrites:0};
check(result.total===2621&&result.directive===167&&protectedResources.length===62,'Unexpected totals');
if(phase==='after'){const before=read('docs/architecture/phase2a-tournament-runtime-kms-evidence-2026-10-04/legacy-after.json');const normalize=(key,value)=>key==='protectedResources'?[...value].sort((a,b)=>a.physicalId.localeCompare(b.physicalId)):value;for(const key of ['root','stacks','protectedResources','lambdas','coreIdentity'])check(hash(normalize(key,result[key]))===hash(normalize(key,before[key])),'Before/after mismatch '+key);result.beforeAfterEqual=true;}
fs.writeFileSync(dir+'/legacy-'+phase+'.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({phase,total:result.total,directive:result.directive,protected:protectedResources.length,lambdaHashes:lambdas.length,status:root.StackStatus,timestamp:root.LastUpdatedTime,beforeAfterEqual:result.beforeAfterEqual}));


