<template>
  <aside class="builder-panel inspector-panel">
    <header class="builder-panel__heading"><strong>{{ tab==='suggestions'?'Suggestions':'Widget Settings' }}</strong><small>{{ widget?.name||'No selection' }}</small></header>
    <div v-if="!hideTabs" class="inspector-tabs"><button :class="{active:tab==='settings'}" @click="tab='settings'">Settings</button><button :class="{active:tab==='suggestions'}" @click="tab='suggestions'">Suggestions <span>{{ suggestions.length }}</span></button></div>
    <template v-if="tab==='settings'">
      <div v-if="widget&&definition" class="inspector-fields">
        <label>Display name<input :value="widget.name" @change="patch({name:$event.target.value})"></label>
        <label>Widget theme<select :value="widget.themeId||themeId" @change="patch({themeId:$event.target.value})"><option v-for="t in themes" :key="t.id" :value="t.id">{{ t.name }}</option></select></label>
        <div class="theme-swatches" aria-label="Widget themes"><button v-for="t in themes" :key="t.id" :class="{active:(widget.themeId||themeId)===t.id}" :style="{'--swatch':t.primary,'--swatch-accent':t.accent}" @click="patch({themeId:t.id})"><i></i>{{ t.name }}</button></div>
        <fieldset><legend>Position and size</legend><div class="frame-fields"><label v-for="key in ['x','y','width','height']" :key="key">{{ key.toUpperCase() }}<input type="number" min="0" :value="widget.frame[key]" @change="frame(key,$event.target.value)"></label></div></fieldset>
        <fieldset v-if="widget.type==='twitch-chat'" class="chat-move-controls"><legend>Move Unified Chat</legend><p>Keyboard-accessible positioning fallback</p><div><button type="button" :disabled="widget.locked" @click="$emit('move','left')">← Move Left</button><button type="button" :disabled="widget.locked" @click="$emit('move','right')">Move Right →</button><button type="button" :disabled="widget.locked" @click="$emit('move','up')">↑ Move Up</button><button type="button" :disabled="widget.locked" @click="$emit('move','down')">Move Down ↓</button><button type="button" :disabled="widget.locked" @click="$emit('move','left-edge')">Move chat to left</button><button type="button" :disabled="widget.locked" @click="$emit('move','right-edge')">Move chat to right</button></div><small v-if="widget.locked">Unlock Unified Chat in Layers to reposition it.</small></fieldset>
        <fieldset><legend>{{ definition.displayName }} options</legend><label v-for="field in definition.settings" :key="field.key"><span>{{ field.label }}</span><input v-if="field.type==='checkbox'" type="checkbox" :checked="widget.settings[field.key]" @change="setting(field,$event.target.checked)"><textarea v-else-if="field.type==='textarea'" :value="widget.settings[field.key]" @change="setting(field,$event.target.value)"></textarea><select v-else-if="field.type==='select'" :value="widget.settings[field.key]" @change="setting(field,$event.target.value)"><option v-for="o in field.options" :key="o">{{ o }}</option></select><input v-else :type="field.type" :min="field.min" :max="field.max" :step="field.step" :value="widget.settings[field.key]" @change="setting(field,$event.target.value)"></label></fieldset>
        <fieldset><legend>Animation</legend><label>Entrance<select :value="widget.animations.entrance" @change="patch({animations:{...widget.animations,entrance:$event.target.value}})"><option>slide</option><option>fade</option><option>pop</option><option>none</option></select></label><label>Duration (ms)<input type="number" :value="widget.animations.durationMs" min="100" max="30000" @change="patch({animations:{...widget.animations,durationMs:Number($event.target.value)}})"></label></fieldset>
      </div>
      <div v-else class="empty-inspector"><strong>Select a widget</strong><p>Choose one from the library, canvas, or Layers to edit it here.</p></div>
    </template>
    <div v-else class="suggestion-list"><article v-if="!suggestions.length"><b>Layout looks balanced</b><p>No deterministic suggestions for this scene.</p></article><article v-for="item in suggestions" :key="item.id" :class="item.severity"><b>{{ item.title }}</b><p>{{ item.message }}</p><button v-if="item.action" @click="$emit('suggestion',item)">{{ item.actionLabel }}</button></article></div>
  </aside>
</template>
<script setup>
import{computed,ref}from'vue';import{widgetRegistry}from'../../widgets/registry/index.js'
const props=defineProps({widget:Object,suggestions:{type:Array,default:()=>[]},themes:{type:Array,default:()=>[]},themeId:String,defaultTab:{type:String,default:'settings'},hideTabs:Boolean});const emit=defineEmits(['change','suggestion','move']);const tab=ref(props.defaultTab);const definition=computed(()=>props.widget?widgetRegistry[props.widget.type]:null)
function patch(next){if(props.widget)emit('change',{...props.widget,...next,updatedAt:'2026-08-13T15:00:00.000Z'})}function frame(key,value){patch({frame:{...props.widget.frame,[key]:Math.max(0,Number(value))}})}function setting(field,value){patch({settings:{...props.widget.settings,[field.key]:['number','range'].includes(field.type)?Number(value):value}})}
</script>
