const BOARD_LIBRARY = {
  'feature-ideas': {
    id: 'feature-ideas',
    name: 'Feature Ideas',
    description: 'Suggest ideas for improving Project Respawn and discuss what should be built next.',
    rules: 'Use this board to suggest product ideas, workflow improvements, creator tools, and community features. Explain the problem clearly and try to keep each thread focused on one main idea.',
    tags: ['Feedback', 'Ideas', 'Product'],
    threadCount: 28,
    postCount: 213,
    watchers: 41,
    sortLabel: 'Latest',
    threads: [
      {
        id: 'thread-1',
        threadSlug: 'creator-milestones-profile-rewards',
        title: 'Should creator milestones unlock profile rewards?',
        excerpt: 'A discussion about whether progress on the platform should unlock profile cosmetics, badges, or extra visibility features.',
        author: 'RespawnMember',
        createdAt: '4h ago',
        replies: 18,
        views: 240,
        isPinned: true,
        isFeatured: true,
        isLocked: false,
        latestReply: {
          title: 'Reward tiers could help retention',
          author: 'Founder',
          time: '18m ago',
        },
      },
      {
        id: 'thread-2',
        threadSlug: 'creator-milestones-profile-rewards',
        title: 'Would a weekly community challenge improve engagement?',
        excerpt: 'Exploring whether rotating social and confidence-based challenges could give users a reason to return each week.',
        author: 'CommunityBuilder',
        createdAt: '7h ago',
        replies: 11,
        views: 136,
        isPinned: false,
        isFeatured: true,
        isLocked: false,
        latestReply: {
          title: 'Challenge streaks might be a strong hook',
          author: 'RespawnGuide',
          time: '35m ago',
        },
      },
      {
        id: 'thread-3',
        threadSlug: 'creator-milestones-profile-rewards',
        title: 'Better onboarding for Discord community joining',
        excerpt: 'How should the site encourage users to move naturally into the Discord community without feeling pushed?',
        author: 'NewMember',
        createdAt: '10h ago',
        replies: 9,
        views: 112,
        isPinned: false,
        isFeatured: false,
        isLocked: false,
        latestReply: {
          title: 'Use interest-based role prompts first',
          author: 'CommunityBuilder',
          time: '1h ago',
        },
      },
      {
        id: 'thread-4',
        threadSlug: 'creator-milestones-profile-rewards',
        title: 'Should feature suggestions be grouped by app area?',
        excerpt: 'Looking at whether suggestions should be split into onboarding, profile, forum, events, and creator tools.',
        author: 'BuilderPath',
        createdAt: '1d ago',
        replies: 7,
        views: 84,
        isPinned: false,
        isFeatured: false,
        isLocked: false,
        latestReply: {
          title: 'This would help staff triage faster',
          author: 'Admin',
          time: '3h ago',
        },
      },
      {
        id: 'thread-5',
        threadSlug: 'creator-milestones-profile-rewards',
        title: 'Should we surface staff-picked suggestions more clearly?',
        excerpt: 'A thread about how to show users which ideas are under review or actively being considered.',
        author: 'ForumTester',
        createdAt: '2d ago',
        replies: 14,
        views: 154,
        isPinned: false,
        isFeatured: false,
        isLocked: true,
        latestReply: {
          title: 'Locked after duplicate merge',
          author: 'Moderator',
          time: '8h ago',
        },
      },
    ],
  },

  'discord-communities': {
    id: 'discord-communities',
    name: 'Discord Communities',
    description: 'Talk about Discord setup, moderation, onboarding, bots, and stronger communities.',
    rules: 'Use this board for Discord strategy, server structure, role systems, moderation ideas, and community onboarding.',
    tags: ['Discord', 'Community', 'Moderation'],
    threadCount: 19,
    postCount: 152,
    watchers: 29,
    sortLabel: 'Latest',
    threads: [
      {
        id: 'discord-thread-1',
        threadSlug: 'forum-permissions-role-discussion',
        title: 'Best way to onboard people from site to Discord?',
        excerpt: 'How should users move from browsing the website into Discord without losing momentum?',
        author: 'CommunityBuilder',
        createdAt: '8h ago',
        replies: 16,
        views: 178,
        isPinned: true,
        isFeatured: true,
        isLocked: false,
        latestReply: {
          title: 'Progress-based invite prompts might work',
          author: 'Founder',
          time: '42m ago',
        },
      },
      {
        id: 'discord-thread-2',
        threadSlug: 'forum-permissions-role-discussion',
        title: 'Should new users pick interest roles immediately?',
        excerpt: 'Discussing whether role selection should happen on arrival or after a welcome flow.',
        author: 'RespawnCreator',
        createdAt: '13h ago',
        replies: 8,
        views: 102,
        isPinned: false,
        isFeatured: false,
        isLocked: false,
        latestReply: {
          title: 'Early role choice makes channels clearer',
          author: 'Moderator',
          time: '2h ago',
        },
      },
    ],
  },

  'app-development': {
    id: 'app-development',
    name: 'App Development',
    description: 'Discuss roadmap ideas, architecture, UX decisions, and development updates.',
    rules: 'Use this board for roadmap planning, architecture discussion, app feedback, and build updates tied to Project Respawn.',
    tags: ['Build', 'Roadmap', 'Development'],
    threadCount: 17,
    postCount: 137,
    watchers: 33,
    sortLabel: 'Latest',
    threads: [
      {
        id: 'app-thread-1',
        threadSlug: 'forum-permissions-role-discussion',
        title: 'How should forum permissions work by role?',
        excerpt: 'A working discussion on how staff, moderators, and members should interact with the forum system.',
        author: 'Founder',
        createdAt: '1d ago',
        replies: 21,
        views: 266,
        isPinned: true,
        isFeatured: true,
        isLocked: false,
        latestReply: {
          title: 'Board-level overrides are probably needed',
          author: 'Admin',
          time: '22m ago',
        },
      },
      {
        id: 'app-thread-2',
        threadSlug: 'forum-permissions-role-discussion',
        title: 'Should the admin permissions matrix control forum actions too?',
        excerpt: 'Discussing whether the same admin dashboard should be the source of truth for all site and forum access.',
        author: 'Admin',
        createdAt: '1d ago',
        replies: 10,
        views: 131,
        isPinned: false,
        isFeatured: false,
        isLocked: false,
        latestReply: {
          title: 'One system would be easier to maintain',
          author: 'Founder',
          time: '1h ago',
        },
      },
    ],
  },
};

const DEFAULT_BOARD = {
  id: 'community-board',
  name: 'Community Board',
  description: 'General community discussion for Project Respawn.',
  rules: 'Keep conversations constructive, helpful, and focused on community growth.',
  tags: ['Community'],
  threadCount: 0,
  postCount: 0,
  watchers: 0,
  sortLabel: 'Latest',
  threads: [],
};

export default {
  name: 'ForumBoard',

  props: {
    boardSlug: {
      type: String,
      default: '',
    },
  },

  computed: {
    board() {
      return BOARD_LIBRARY[this.boardSlug] || DEFAULT_BOARD;
    },
  },

  methods: {
    goToThread(threadSlug) {
      this.$router.push(`/forum/thread/${threadSlug}`);
    },
  },
};