<template>
  <div class="bot-page"><BotSidebar title="Twitch Alerts" colourBrand1="#7c3aed" colourBrand2="#a78bfa" colourBoxShadow="rgba(124,58,237,.35)" />
    <main class="bot-main">
      <section class="hero-card alerts-hero"><div class="hero-copy"><p class="eyebrow">Canonical alert control centre</p><h2>Configure Preview and Browser Source alerts</h2><p class="hero-text">Preview reflects unsaved edits. Send Test Alert saves first, then delivers the saved Brand configuration through the canonical WebSocket path.</p>
        <label v-if="brands.length > 1" class="field brand-selector"><span class="field-label">Creator Brand</span><select :value="brandId" @change="changeBrand($event.target.value)"><option value="">Select a Brand</option><option v-for="brand in brands" :key="brand.brandId || brand.id" :value="brand.brandId || brand.id">{{ brand.name }}</option></select></label>
        <div class="hero-actions"><button class="primary-btn" type="button" :disabled="!canManage || busy" @click="saveSettings()">{{ saving ? 'Saving…' : 'Save Alert Settings' }}</button><button class="secondary-btn" type="button" :disabled="!canManage || busy" @click="sendTest">{{ testing ? 'Sending…' : `Send Test ${selectedDefinition.name}` }}</button></div>
        <p v-if="status.message" class="operation-status" :class="status.kind" role="status">{{ status.message }}</p><p v-if="contextError" class="operation-status error" role="alert">{{ contextError }}</p></div>
        <div class="hero-stats"><div class="mini-stat"><span class="mini-label">Selected Brand</span><strong>{{ selectedBrandName || 'Not selected' }}</strong></div><div class="mini-stat"><span class="mini-label">Browser Source</span><strong>{{ connectionLabel }}</strong></div><div class="mini-stat"><span class="mini-label">Saved revision</span><strong>{{ revision || 'Not loaded' }}</strong></div></div></section>

      <section class="dashboard-section"><div class="section-heading"><div><p class="section-kicker">Supported in Phase 1</p><h3>Choose an alert type</h3></div><div class="inline-status">Brand-scoped</div></div><div class="alert-type-grid"><button v-for="definition in definitions" :key="definition.key" type="button" class="alert-type-card" :class="{active:selectedKey===definition.key}" @click="selectedKey=definition.key"><span class="card-badge">Ready</span><h4>{{ definition.name }}</h4><p>{{ definition.description }}</p></button></div></section>

      <section v-if="selectedConfig" class="dashboard-section editor-layout"><div class="editor-main"><div class="section-heading"><div><p class="section-kicker">Settings</p><h3>{{ selectedDefinition.name }} configuration</h3></div><span v-if="dirty" class="inline-status">Unsaved preview</span></div><div class="editor-card">
        <div class="form-row split"><label class="field"><span class="field-label">Enable alert</span><select v-model="selectedConfig.enabled"><option :value="true">Enabled</option><option :value="false">Disabled</option></select></label><label class="field"><span class="field-label">Duration</span><input v-model.number="selectedConfig.duration" type="number" min="1" max="60" step="1"></label></div>
        <div class="form-row"><label class="field"><span class="field-label">Title template</span><input v-model="selectedConfig.titleTemplate" maxlength="240" placeholder="{user} followed!"></label></div><div class="form-row"><label class="field"><span class="field-label">Message template</span><textarea v-model="selectedConfig.messageTemplate" maxlength="500" rows="3" placeholder="Welcome to the community, {user}."></textarea></label></div>
        <div class="form-row split"><label class="field"><span class="field-label">Image / GIF HTTPS URL</span><input v-model.trim="selectedConfig.mediaUrl" type="url" placeholder="https://..."></label><label class="field"><span class="field-label">Sound HTTPS URL</span><input v-model.trim="selectedConfig.soundUrl" type="url" placeholder="https://..."></label></div>
        <div class="form-row split"><label class="field"><span class="field-label">Entry animation</span><select v-model="selectedConfig.entryAnimation"><option v-for="animation in animations" :key="animation" :value="animation">{{ animation }}</option></select></label><label class="field"><span class="field-label">Exit animation</span><select v-model="selectedConfig.exitAnimation"><option v-for="animation in animations" :key="animation" :value="animation">{{ animation }}</option></select></label></div>
        <div class="form-row"><label class="field"><span class="field-label">Volume · {{ Math.round(selectedConfig.volume*100) }}%</span><input v-model.number="selectedConfig.volume" type="range" min="0" max="1" step="0.01"></label></div></div>
        <div class="preview-card prototype-note"><p><strong>Deferred:</strong> resub, gift sub, donation, variations, hype train, and stream online/offline remain unavailable until their canonical contracts exist.</p></div></div>
        <aside class="editor-side"><div class="preview-card"><div class="section-heading compact"><div><p class="section-kicker">Shared renderer</p><h3>Live local preview</h3></div></div><div class="alert-preview-stage"><AlertPresentation :event="previewEvent" :configuration="selectedConfig" :style="previewStyle" :play-audio="previewAudio" /></div><div class="preview-meta"><div class="mini-stat"><span class="mini-label">Entry / Exit</span><strong>{{ selectedConfig.entryAnimation }} / {{ selectedConfig.exitAnimation }}</strong></div><div class="mini-stat"><span class="mini-label">Duration</span><strong>{{ selectedConfig.duration }} seconds</strong></div></div><div class="hero-actions preview-actions"><button class="secondary-btn" type="button" @click="previewSound">Preview sound</button></div><p class="preview-note">Preview uses unsaved local values. Browser-source tests always use saved canonical configuration.</p></div>
          <div class="preview-card helper-card"><div class="section-heading compact"><div><p class="section-kicker">Browser Source readiness</p><h3>{{ readiness.title }}</h3></div></div><ul class="helper-list"><li v-for="item in readiness.items" :key="item">{{ item }}</li></ul></div></aside></section>
    </main>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import BotSidebar from '@/components/BotSidebar/BotSidebar.vue'
import AlertPresentation from '@/features/creator-tools/components/overlays/AlertPresentation.vue'
import { useCreatorBrandContext } from '@/features/creator-tools/composables/useCreatorBrandContext.js'
import { ALERT_ANIMATIONS, normalizeAlertConfiguration, previewEventForKind } from '@/features/creator-tools/overlays/alertPresentation.js'
import { createTestOverlayEvent } from '@/features/creator-tools/overlays/overlayEventContract.js'
import { getActiveOverlayPublication, getTwitchOverlayConfig, sendOverlayTestEvent, updateTwitchOverlayConfig } from '@/features/creator-tools/services/overlaySource.js'

const route=useRoute(),router=useRouter(),brandContext=useCreatorBrandContext(route,router)
const definitions=Object.freeze([{key:'follow',name:'Follow Alert',type:'stream.follow',description:'New follower alerts.'},{key:'subscription',name:'Subscription Alert',type:'stream.subscription',description:'New subscription alerts.'},{key:'raid',name:'Raid Alert',type:'stream.raid',description:'Incoming raid alerts.'},{key:'cheer',name:'Bits Alert',type:'stream.cheer',description:'Twitch cheer and Bits alerts.'},{key:'redemption',name:'Redemption Alert',type:'reward.redeemed',description:'Channel-point reward alerts.'}])
const animations=ALERT_ANIMATIONS,selectedKey=ref('follow'),workspaceId=ref(''),brandId=ref(''),revision=ref(0),canonicalConfig=ref(null),savedSnapshot=ref(''),configs=reactive({}),saving=ref(false),testing=ref(false),previewAudio=ref(false),previewNonce=ref(0),contextError=ref(''),publication=ref(null),status=reactive({kind:'',message:''})
const brands=computed(()=>brandContext.brands.value||[]),busy=computed(()=>saving.value||testing.value),selectedDefinition=computed(()=>definitions.find(item=>item.key===selectedKey.value)||definitions[0]),selectedConfig=computed(()=>configs[selectedKey.value]||null),selectedBrandName=computed(()=>brands.value.find(item=>(item.brandId||item.id)===brandId.value)?.name||''),canManage=computed(()=>Boolean(workspaceId.value&&brandId.value&&canonicalConfig.value&&selectedConfig.value)),dirty=computed(()=>Boolean(canonicalConfig.value&&JSON.stringify(configs)!==savedSnapshot.value)),previewEvent=computed(()=>({...previewEventForKind(selectedKey.value),id:`preview-${selectedKey.value}-${previewNonce.value}`})),previewStyle={background:'linear-gradient(135deg,rgba(91,33,182,.7),rgba(15,23,42,.96))',borderRadius:'20px',border:'1px solid rgba(167,139,250,.3)'}
const connectionLabel=computed(()=>!publication.value?'Not published':Number(publication.value.connectionCount||0)>0?`● Connected (${publication.value.connectionCount})`:'○ Not connected')
const readiness=computed(()=>{const items=[];if(!publication.value)items.push('Create and publish a Browser Source in Overlay Builder.');else{if(!publication.value.hasAlertsWidget)items.push('The published scene needs an enabled Alerts widget.');else if(!(publication.value.alertTopics||[]).includes(selectedDefinition.value.type))items.push(`The Alerts widget is not subscribed to ${selectedDefinition.value.type}.`);if(Number(publication.value.connectionCount||0)===0)items.push('Open the Browser Source in OBS or another tab.')}if(!items.length)items.push('Active publication, matching Alerts widget, and connected Browser Source detected.');return{title:items.length===1&&items[0].startsWith('Active')?'Ready':'Action required',items}})
function setStatus(kind,message){status.kind=kind;status.message=message}
function applyConfig(result){canonicalConfig.value=result.config;revision.value=Number(result.revision||0);for(const definition of definitions)configs[definition.key]=normalizeAlertConfiguration(result.config?.alerts?.[definition.key]);savedSnapshot.value=JSON.stringify(configs)}
async function loadConfig(){contextError.value='';setStatus('','');const [configResult,publicationResult]=await Promise.all([getTwitchOverlayConfig(workspaceId.value,brandId.value),getActiveOverlayPublication(workspaceId.value,brandId.value)]);applyConfig(configResult);publication.value=publicationResult.publication||null}
async function resolveContext(){try{const resolved=await brandContext.load();workspaceId.value=resolved.workspaceId;brandId.value=resolved.brandId;await loadConfig()}catch(error){workspaceId.value='';brandId.value='';canonicalConfig.value=null;contextError.value=error?.message||'Select an accessible Creator Brand.'}}
async function changeBrand(next){try{const resolved=await brandContext.select(next);workspaceId.value=resolved.workspaceId;brandId.value=resolved.brandId;await loadConfig()}catch(error){contextError.value=error?.message||'Could not select Brand.'}}
async function saveSettings({quiet=false}={}){if(!canManage.value)return false;saving.value=true;if(!quiet)setStatus('','');try{const alerts={...canonicalConfig.value.alerts};for(const definition of definitions)alerts[definition.key]={...configs[definition.key]};const result=await updateTwitchOverlayConfig(workspaceId.value,brandId.value,{...canonicalConfig.value,alerts});applyConfig(result);if(!quiet)setStatus('success',`Alert settings saved · revision ${revision.value}`);return true}catch(error){setStatus('error',error?.message||'Could not save alert settings.');return false}finally{saving.value=false}}
async function refreshPublication(){const result=await getActiveOverlayPublication(workspaceId.value,brandId.value);publication.value=result.publication||null;return publication.value}
async function sendTest(){if(!canManage.value)return;testing.value=true;setStatus('','');try{if(dirty.value&&!await saveSettings({quiet:true}))return;const active=await refreshPublication();if(!active)throw new Error('Create and publish a Browser Source before sending a test alert.');if(!active.hasAlertsWidget)throw new Error('The published scene does not contain an enabled Alerts widget.');if(!(active.alertTopics||[]).includes(selectedDefinition.value.type))throw new Error(`The published Alerts widget is not subscribed to ${selectedDefinition.value.type}.`);const result=await sendOverlayTestEvent(active.publicationId,createTestOverlayEvent(selectedDefinition.value.type));publication.value={...active,connectionCount:result.delivered};if(Number(result.delivered||0)===0)setStatus('warning','No browser source is currently connected.');else setStatus('success',`Test alert delivered to ${result.delivered} browser source${result.delivered===1?'':'s'}.`)}catch(error){setStatus('error',error?.message||'Test alert failed.')}finally{testing.value=false}}
function previewSound(){previewAudio.value=true;previewNonce.value+=1}
void resolveContext()
</script>
<style scoped src="./TwitchAlerts.css"></style>
