<template>
  <main class="creator-discord">
    <header class="discord-hero">
      <div class="discord-page-identity"><span class="discord-page-icon"><CreatorFeatureIcon name="discord" /></span><div><div class="discord-badges"><span>Work in progress</span><span>Interactive demo</span></div><h1>Discord</h1><p class="discord-page-description">Connect your server and bring your Discord community into Project Respawn.</p></div></div>
      <div class="discord-connection"><i></i><strong>Not connected — interactive demo</strong><small>No Discord bot is currently connected</small></div>
    </header>
    <aside class="discord-demo-warning"><strong>Demonstration only</strong><span>Settings are saved only inside this demonstration. Nothing is being sent to Discord.</span></aside>
    <DiscordDemoNav :sections="discordSections" :active="state.activeSection" @select="openSection" />
    <p v-if="state.savedMessage" class="discord-toast" role="status">✓ {{ state.savedMessage }}</p>

    <DiscordOverview v-if="state.activeSection==='overview'" @open="openSection" />

    <section v-else-if="state.activeSection==='commands'" class="discord-workspace">
      <header class="discord-section-heading"><div><p>Command centre</p><h2>Commands</h2><span>Preview built-in commands and design local custom responses.</span></div><button @click="saveDemo('Command catalogue saved')">Save in demo</button></header>
      <div class="command-grid"><article v-for="command in allCommands" :key="command.key" class="discord-panel command-card"><header><code>{{ command.key }}</code><label class="demo-switch"><input v-model="command.enabled" type="checkbox"><span></span></label></header><h3>{{ command.description }}</h3><div class="tag-row"><span>{{ command.category }}</span><span>{{ command.permission }}</span><span>{{ command.status }}</span></div><details><summary>Example response</summary><p>{{ command.response }}</p></details></article></div>
      <section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Frontend-only editor</p><h2>Create a custom command</h2></div></header><div class="form-grid"><label>Command name<input v-model="state.customCommandDraft.name" placeholder="loadout"></label><label>Description<input v-model="state.customCommandDraft.description" placeholder="Show the community loadout"></label><label class="wide">Example response<textarea v-model="state.customCommandDraft.response" rows="3" placeholder="Your response preview…"></textarea></label></div><p v-if="commandError" class="field-error">{{ commandError }}</p><button class="primary-action" @click="addCustomCommand">Add to demo catalogue</button></section>
    </section>

    <section v-else-if="state.activeSection==='greetings'" class="discord-workspace two-column">
      <section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Member journey</p><h2>Welcome & goodbye</h2></div></header><div class="toggle-row"><label><input v-model="state.greetings.welcomeEnabled" type="checkbox"> Welcome messages</label><label><input v-model="state.greetings.goodbyeEnabled" type="checkbox"> Goodbye messages</label><label><input v-model="state.greetings.welcomeImage" type="checkbox"> Welcome image concept</label></div><label>Welcome channel<select v-model="state.greetings.welcomeChannelId"><option v-for="channel in demoChannels" :key="channel.id" :value="channel.id">#{{ channel.name }} · {{ channel.id }}</option></select></label><label>Welcome template<textarea v-model="state.greetings.welcomeTemplate" rows="5"></textarea><small>Safe placeholders: {user}, {server}, {memberCount}</small></label><label>Goodbye template<textarea v-model="state.greetings.goodbyeTemplate" rows="3"></textarea></label><p v-if="!welcomePreview.valid" class="field-error">{{ welcomePreview.error }}</p><div class="action-row"><button class="primary-action" @click="saveDemo('Greeting settings saved')">Save in demo</button><button @click="resetGreetings">Reset greetings</button></div></section>
      <section><header class="discord-section-heading"><div><p>Safe local rendering</p><h2>Discord-style preview</h2></div></header><DiscordPreview :message="welcomePreview.text || 'Fix the template to restore this preview.'" :footer="state.greetings.welcomeImage?'Welcome image concept enabled · Preview only':'Text welcome · Preview only'"/><div class="safety-note"><strong>Mention safety</strong><span>Mass mentions are neutralised. This preview cannot ping anyone or send a message.</span></div></section>
    </section>

    <section v-else-if="state.activeSection==='roles'" class="discord-workspace two-column">
      <section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Role journeys</p><h2>Roles & autoroles</h2></div></header><label>Default autorole<select v-model="state.roles.autoroleId"><option v-for="role in demoRoles" :key="role.id" :value="role.id">{{ role.name }} · {{ role.id }}</option></select></label><p v-if="autoroleRestriction" class="field-error">{{ autoroleRestriction }}</p><label>Verified member role<select v-model="state.roles.verifiedRoleId"><option v-for="role in assignableRoles" :key="role.id" :value="role.id">{{ role.name }}</option></select></label><label>Creator role<select v-model="state.roles.creatorRoleId"><option v-for="role in assignableRoles" :key="role.id" :value="role.id">{{ role.name }}</option></select></label><label>Supporter role<select v-model="state.roles.supporterRoleId"><option v-for="role in assignableRoles" :key="role.id" :value="role.id">{{ role.name }}</option></select></label><button class="primary-action" :disabled="!!autoroleRestriction" @click="saveDemo('Role settings saved')">Save in demo</button></section>
      <div class="stack"><section class="discord-panel role-preview"><p>Example assignment</p><div class="member-avatar">N</div><h2>Nova</h2><span v-for="role in selectedRoles" :key="role.id">{{ role.name }}</span><small>IDs remain immutable behind these labels.</small></section><section class="discord-panel"><h3>Reaction-role concepts</h3><ul class="concept-list"><li>🎮 Game Night → Event Player</li><li>🎨 Creator Showcase → Respawn Creator</li><li>💜 Supporter News → Supporter</li></ul><p class="muted-copy">Managed roles and roles above the future bot are blocked by design.</p></section></div>
    </section>

    <section v-else-if="state.activeSection==='moderation'" class="discord-workspace two-column">
      <section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Interface demonstration</p><h2>Moderation settings</h2></div></header><div class="control-list"><label v-for="item in moderationToggles" :key="item.key"><span><strong>{{ item.label }}</strong><small>{{ item.copy }}</small></span><input v-model="state.moderation[item.key]" type="checkbox"></label></div><div class="form-grid"><label>Mention limit<input v-model.number="state.moderation.mentionLimit" type="number" min="1" max="20"></label><label>Warnings before timeout<input v-model.number="state.moderation.warningThreshold" type="number" min="1" max="10"></label><label>Timeout minutes<input v-model.number="state.moderation.timeoutMinutes" type="number" min="1" max="1440"></label><label>Log channel<select v-model="state.moderation.logChannelId"><option v-for="c in demoChannels" :key="c.id" :value="c.id">#{{ c.name }}</option></select></label><label class="wide">Word filter<input v-model="state.moderation.wordFilter"></label></div><button class="primary-action" @click="saveDemo('Moderation settings saved')">Save in demo</button></section>
      <section><header class="discord-section-heading"><div><p>Example only</p><h2>Moderation event</h2></div></header><DiscordPreview title="Repeated message detected" message="A demonstration message from PixelPilot matched the repeat threshold. Suggested action: warning 2 of 3." footer="#mod-log · No enforcement occurred"/><div class="escalation"><span>Warn</span><b>→</b><span>Threshold</span><b>→</b><span>10 min timeout</span><b>→</b><span>Notify moderators</span></div></section>
    </section>

    <section v-else-if="state.activeSection==='announcements'" class="discord-workspace two-column"><section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Community broadcasts</p><h2>Announcement composer</h2></div></header><label>Channel<select v-model="state.announcement.channelId"><option v-for="c in demoChannels" :key="c.id" :value="c.id">#{{ c.name }}</option></select></label><label>Title<input v-model="state.announcement.title"></label><label>Message<textarea v-model="state.announcement.message" rows="5"></textarea></label><label>Audience<select v-model="state.announcement.audienceRoleId"><option v-for="r in assignableRoles" :key="r.id" :value="r.id">{{ r.name }}</option></select></label><div class="toggle-row"><label><input v-model="state.announcement.timing" type="radio" value="Now"> Immediate concept</label><label><input v-model="state.announcement.timing" type="radio" value="Schedule"> Scheduled concept</label></div><button class="primary-action" @click="saveDemo('Announcement draft saved')">Save in demo</button></section><section><header class="discord-section-heading"><div><p>Preview</p><h2>Scheduled post</h2></div></header><DiscordPreview :title="state.announcement.title" :message="state.announcement.message" :footer="`${channelName(state.announcement.channelId)} · ${state.announcement.timing==='Schedule'?state.announcement.scheduledFor:'Immediate concept'}`"/></section></section>

    <section v-else-if="state.activeSection==='campaigns'" class="discord-workspace campaign-grid"><section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Community pulse</p><h2>Poll</h2></div></header><label>Question<input v-model="state.poll.question"></label><label>Options<textarea v-model="state.poll.options" rows="5"></textarea></label><label>Duration<select v-model="state.poll.duration"><option>1 hour</option><option>24 hours</option><option>3 days</option></select></label><div class="poll-preview"><strong>{{ state.poll.question }}</strong><button v-for="option in pollOptions" :key="option">○ {{ option }}</button></div><button class="primary-action" @click="saveDemo('Poll saved')">Save in demo</button></section><section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Celebration concept</p><h2>Giveaway</h2></div></header><label>Prize<input v-model="state.giveaway.prize"></label><label>Entry requirement<input v-model="state.giveaway.requirement"></label><label>Winners<input v-model.number="state.giveaway.winners" type="number" min="1" max="10"></label><div class="giveaway-preview"><span>★ GIVEAWAY</span><h3>{{ state.giveaway.prize }}</h3><p>{{ state.giveaway.requirement }}</p><strong>{{ state.giveaway.winners }} winners · Ends {{ state.giveaway.ends }}</strong></div><button class="primary-action" @click="saveDemo('Giveaway saved')">Save in demo</button></section></section>

    <section v-else-if="state.activeSection==='community'" class="discord-workspace"><header class="discord-section-heading"><div><p>Project Respawn convergence</p><h2>Connected Community</h2><span>Concepts join Discord participation with explicitly linked Respawn profiles.</span></div></header><div class="community-grid"><article v-for="item in communityConcepts" :key="item.title" class="discord-panel"><span>{{ item.icon }}</span><h3>{{ item.title }}</h3><p>{{ item.copy }}</p><strong>{{ item.value }}</strong></article></div><section class="discord-panel journey"><span>Twitch achievement</span><b>→</b><span>Respawn profile</span><b>→</b><span>Discord celebration</span><b>→</b><span>Role reward</span></section></section>

    <section v-else-if="state.activeSection==='events'" class="discord-workspace two-column"><section class="discord-panel event-showcase"><p>Sunday · 19:00 Europe/London</p><h2>Project Respawn Showcase</h2><span>Creator updates, community highlights and the next roadmap reveal.</span><div><button>✓ Going · 28</button><button>Maybe · 12</button><button>Can't go · 4</button></div><ul><li>Reminder · 24 hours before</li><li>Reminder · 30 minutes before</li><li>Role invitation · Verified Member</li><li>Recurring · Monthly</li><li>Attendance reward · 250 points</li></ul></section><section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Event automation</p><h2>Delivery settings</h2></div></header><label>Announcement channel<select v-model="state.events.channelId"><option v-for="c in demoChannels" :key="c.id" :value="c.id">#{{ c.name }} · {{ c.id }}</option></select></label><div class="control-list"><label><span><strong>Reminders</strong><small>Preview scheduled reminders</small></span><input v-model="state.events.reminders" type="checkbox"></label><label><span><strong>Role invitations</strong><small>Target eligible roles</small></span><input v-model="state.events.roleInvites" type="checkbox"></label><label><span><strong>Recurring events</strong><small>Time-zone-aware concept</small></span><input v-model="state.events.recurring" type="checkbox"></label><label><span><strong>Attendance rewards</strong><small>Award community points</small></span><input v-model="state.events.attendanceRewards" type="checkbox"></label></div><button class="primary-action" @click="saveDemo('Event settings saved')">Save in demo</button></section></section>

    <section v-else-if="state.activeSection==='automation'" class="discord-workspace"><header class="discord-section-heading"><div><p>Trigger → conditions → actions</p><h2>Automation studio</h2><span>Every rule below is a local interface demonstration.</span></div><button @click="saveDemo('Automation rules saved')">Save in demo</button></header><div class="automation-list"><article v-for="rule in state.automation" :key="rule.id" class="discord-panel"><label class="demo-switch"><input v-model="rule.enabled" type="checkbox"><span></span></label><div><small>WHEN</small><strong>{{ rule.trigger }}</strong></div><b>→</b><div><small>IF</small><strong>{{ rule.condition }}</strong></div><b>→</b><div><small>THEN</small><strong>{{ rule.action }}</strong></div></article></div></section>

    <section v-else-if="state.activeSection==='analytics'" class="discord-workspace"><header class="discord-section-heading"><div><p>Deterministic demonstration data</p><h2>Discord analytics possibilities</h2><span>Illustrative values only. No Discord or member data has been collected.</span></div><span class="confidence-badge">Data confidence · Demo only</span></header><div class="analytics-demo-grid"><article v-for="metric in analyticsMetrics" :key="metric.label" class="discord-panel"><span>{{ metric.label }}</span><strong>{{ metric.value }}</strong><small>{{ metric.detail }}</small></article></div><section class="discord-panel demo-chart"><div v-for="(height,index) in chartBars" :key="index" :style="{height:`${height}%`}"></div></section></section>

    <section v-else-if="state.activeSection==='settings'" class="discord-workspace two-column"><section class="discord-panel editor-panel"><header class="discord-section-heading"><div><p>Bot preferences</p><h2>General settings</h2></div></header><label>Display-name concept<input v-model="state.settings.displayName"></label><label>Response style<select v-model="state.settings.responseStyle"><option>Friendly & concise</option><option>Playful community</option><option>Clear & professional</option></select></label><label>Language<select v-model="state.settings.language"><option>English (UK)</option><option>English (US)</option></select></label><label>Time zone<select v-model="state.settings.timezone"><option>Europe/London</option><option>UTC</option><option>America/New_York</option></select></label><label>Default channel<select v-model="state.settings.defaultChannelId"><option v-for="c in demoChannels" :key="c.id" :value="c.id">#{{ c.name }}</option></select></label><label>Moderator role<select v-model="state.settings.moderatorRoleId"><option v-for="r in demoRoles" :key="r.id" :value="r.id">{{ r.name }}</option></select></label><label><input v-model="state.settings.notifications" type="checkbox"> Demonstration notifications</label><button class="primary-action" @click="saveDemo('General settings saved')">Save in demo</button></section><section class="stack"><section class="discord-panel feature-summary"><h2>Feature summary</h2><div v-for="item in settingsSummary" :key="item[0]"><span>{{ item[0] }}</span><strong>{{ item[1] }}</strong></div></section><section class="discord-panel reset-card"><h2>Reset interactive demo</h2><p>Restore every local control to the deterministic showcase state.</p><button @click="resetDemo">Reset demo</button></section></section></section>

    <footer class="discord-footer"><strong>INTERACTIVE DEMO</strong><span>No bot, OAuth connection, installation, moderation action, message or Discord request exists on this page.</span></footer>
  </main>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import DiscordDemoNav from './components/DiscordDemoNav.vue'
import DiscordOverview from './components/DiscordOverview.vue'
import DiscordPreview from './components/DiscordPreview.vue'
import CreatorFeatureIcon from '../../components/CreatorFeatureIcon.vue'
import { analyticsMetrics, createDiscordDemoState, demoChannels, demoRoles, discordSections, renderGreeting, roleRestriction, validateCustomCommand } from './discordDemoState.js'

const state=reactive(createDiscordDemoState());const commandError=ref('');const chartBars=[28,36,31,48,52,46,61,58,72,68,81,76]
const moderationToggles=[['spam','Spam protection','Rate and burst concept'],['links','Link filtering','Unsafe link concept'],['invites','Invite filtering','External server invites'],['repeats','Repeated messages','Duplicate content concept'],['caps','Caps filtering','Excessive capital letters']].map(([key,label,copy])=>({key,label,copy}))
const communityConcepts=[['◈','Community points','Recognise healthy participation across connected experiences.','2.4m demo points'],['♥','Supporter recognition','Map supporter tiers to Discord recognition.','418 linked members'],['▣','Event participation','RSVP, attendance and participation rewards.','38% participation'],['◆','Role rewards','Celebrate milestones with safe role concepts.','4 reward paths'],['★','Achievements','Announce Twitch, Discord and Respawn milestones.','126 this month'],['↗','Respawn profiles','Link back to opted-in Project Respawn profiles.','Identity-safe concept']].map(([icon,title,copy,value])=>({icon,title,copy,value}))
const allCommands=computed(()=>[...state.commands,...state.customCommands]);const welcomePreview=computed(()=>renderGreeting(state.greetings.welcomeTemplate));const assignableRoles=computed(()=>demoRoles.filter(role=>role.assignable));const autoroleRestriction=computed(()=>roleRestriction(state.roles.autoroleId));const selectedRoles=computed(()=>Object.values(state.roles).map(id=>demoRoles.find(role=>role.id===id)).filter(Boolean));const pollOptions=computed(()=>state.poll.options.split('\n').map(v=>v.trim()).filter(Boolean).slice(0,10));const settingsSummary=computed(()=>[['Commands',`${allCommands.value.filter(c=>c.enabled).length} enabled`],['Welcome',state.greetings.welcomeEnabled?'Enabled in demo':'Disabled'],['Autorole',demoRoles.find(r=>r.id===state.roles.autoroleId)?.name||'Restricted'],['Moderation',`${moderationToggles.filter(i=>state.moderation[i.key]).length} controls enabled`],['Automation',`${state.automation.filter(r=>r.enabled).length} rules enabled`]])
function openSection(key){state.activeSection=key;state.savedMessage='';window.scrollTo({top:0,behavior:'smooth'})}function saveDemo(label){state.savedMessage=`${label} — Saved in demo. Nothing was sent to Discord.`;window.setTimeout(()=>{state.savedMessage=''},3500)}function addCustomCommand(){const result=validateCustomCommand(state.customCommandDraft,allCommands.value);if(!result.valid){commandError.value=result.error;return}state.customCommands.push(result.command);state.customCommandDraft={name:'',description:'',response:''};commandError.value='';saveDemo(`${result.command.key} added`)}function resetGreetings(){Object.assign(state.greetings,createDiscordDemoState().greetings);saveDemo('Greeting settings reset')}function resetDemo(){Object.assign(state,createDiscordDemoState());saveDemo('Discord demonstration reset')}function channelName(id){return `#${demoChannels.find(c=>c.id===id)?.name||'unknown-channel'}`}
</script>
<style src="./CreatorDiscord.css"></style>
