<template><div class="demo-widget chat-widget unified-chat" :style="{...widgetStyle(s),background:hexAlpha(s.background,s.backgroundOpacity),border:'var(--overlay-border)',borderRadius:'var(--overlay-radius)',boxShadow:'var(--overlay-shadow)',fontFamily:'var(--overlay-font)'}"><header><b>Unified Chat</b><div class="chat-sources"><i v-for="source in enabledSources" :key="source">{{ source }}</i></div></header><div class="chat-lines" :class="s.direction"><p v-for="message in visible" :key="message.id"><span class="chat-platform" :class="message.platform.toLowerCase()">{{ message.platform[0] }}</span><strong v-if="s.showUsername">{{ s.showBadges?message.badge:'' }}{{ message.user }}</strong> {{ message.text }}</p></div><footer v-if="runtimeMode !== 'browser-source'">Merged platform preview · Browser-only demo</footer></div></template>
<script setup>
import { computed, ref, watch } from 'vue';import { widgetStyle, useWidgetEvents } from '../../widgetHelpers.js'
const props=defineProps({widget:{type:Object,required:true},runtimeMode:{type:String,default:'editor-preview'},runtimeConfig:{type:Object,default:null}}),s=props.widget.settings
const previewMessages=[{id:1,platform:'Twitch',user:'PixelPioneer',badge:'◆ ',text:'gg!'},{id:2,platform:'YouTube',user:'NexusKnight',badge:'▶ ',text:'that play 🔥'},{id:3,platform:'Kick',user:'StreamBel',badge:'● ',text:'join our Discord!'},{id:4,platform:'Discord',user:'Moonlight',badge:'◉ ',text:'insane combo'}];const messages=ref(props.runtimeMode==='browser-source'?[]:previewMessages);const event=useWidgetEvents(props.widget,props.runtimeMode==='browser-source'?null:{id:'initial',actor:{displayName:''},payload:{text:''}})
watch(event,(next)=>{if(!next)return;const config=props.runtimeConfig?.chat||{},text=String(next.payload?.text||''),blocked=config.blockedTerms||[];if(config.enabled===false||!text||blocked.some(term=>text.toLowerCase().includes(term))||(s.hideBotMessages&&next.payload?.isBot)||(s.hideCommands&&text.startsWith('!')))return;messages.value.push({id:next.id,platform:next.payload?.platform||'Twitch',user:next.actor?.displayName||'Viewer',badge:'◆ ',text});messages.value=messages.value.slice(-Number(config.maxMessages||s.maxMessages||6))},{deep:true})
const enabledSources=computed(()=>props.runtimeMode==='browser-source'?(props.runtimeConfig?.chat?.platforms||['Twitch']):String(s.platforms||'Twitch,YouTube,Kick,Discord').split(',').map(x=>x.trim()).filter(Boolean));const visible=computed(()=>{const allowed=new Set(enabledSources.value),list=messages.value.filter(x=>allowed.has(x.platform)).slice(-Number(props.runtimeConfig?.chat?.maxMessages||s.maxMessages||6));return s.direction==='down'?[...list].reverse():list});function hexAlpha(hex,alpha){if(!/^#[0-9a-f]{6}$/i.test(hex||''))return hex;return `${hex}${Math.round(Number(alpha)*255).toString(16).padStart(2,'0')}`}
</script>
<style scoped>.unified-chat{border:var(--overlay-border);border-radius:var(--overlay-radius);box-shadow:var(--overlay-shadow);font-family:var(--overlay-font)}header{align-items:center}.chat-sources{display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end}.chat-sources i{padding:3px 6px;border-radius:5px;background:rgba(255,255,255,.1);font-size:.48em;font-style:normal}.chat-platform{display:inline-grid;width:23px;height:23px;margin-right:7px;place-items:center;border-radius:5px;background:var(--overlay-primary);font-size:.62em;font-weight:900}.chat-platform.youtube{background:#dc2626}.chat-platform.kick{background:#22c55e}.chat-platform.discord{background:#5865f2}footer{margin-top:8px;color:#94a3b8;font-size:.5em}</style>
