export default {
  name: "TherapistDashboard",

  data() {
    return {
      overviewMetrics: [
        {
          id: "clients",
          icon: "👥",
          value: 12,
          label: "Active Clients",
          detail: "+2 this month",
          tone: "purple",
        },
        {
          id: "sessions",
          icon: "▣",
          value: 4,
          label: "Sessions Today",
          detail: "View schedule →",
          tone: "blue",
        },
        {
          id: "quests",
          icon: "✓",
          value: 18,
          label: "Active Quests",
          detail: "3 due this week",
          tone: "green",
        },
        {
          id: "reports",
          icon: "▤",
          value: 3,
          label: "Reports Ready",
          detail: "View reports →",
          tone: "orange",
        },
      ],

      quickActions: [
        {
          id: "create-quest",
          icon: "+",
          title: "Create Quest",
          description: "Assign a new goal to a client",
          route: "/therapist/quests/new",
          tone: "purple",
        },
        {
          id: "clients",
          icon: "👥",
          title: "View Clients",
          description: "Open your client workspace",
          route: "/therapist/clients",
          tone: "blue",
        },
        {
          id: "reports",
          icon: "▤",
          title: "View Reports",
          description: "Prepare for upcoming sessions",
          route: "/therapist/reports",
          tone: "green",
        },
        {
          id: "templates",
          icon: "◆",
          title: "Quest Templates",
          description: "Manage reusable activities",
          route: "/therapist/quests",
          tone: "orange",
        },
      ],

      todaysSessions: [
        {
          id: 1,
          time: "10:00",
          period: "AM",
          initials: "AM",
          name: "Alex Morgan",
          questProgress: "4 / 5 quests completed",
          status: "Report Ready",
          statusTone: "purple",
          action: "View Report",
          route: "/therapist/clients/alex-morgan/reports",
        },
        {
          id: 2,
          time: "11:30",
          period: "AM",
          initials: "SC",
          name: "Sarah Chen",
          questProgress: "2 / 3 quests completed",
          status: "Basic Summary",
          statusTone: "neutral",
          action: "View Client",
          route: "/therapist/clients/sarah-chen",
        },
        {
          id: 3,
          time: "14:00",
          period: "PM",
          initials: "JW",
          name: "Jamie Wilson",
          questProgress: "5 / 6 quests completed",
          status: "Report Ready",
          statusTone: "purple",
          action: "View Report",
          route: "/therapist/clients/jamie-wilson/reports",
        },
        {
          id: 4,
          time: "16:30",
          period: "PM",
          initials: "CT",
          name: "Chris Taylor",
          questProgress: "0 / 2 quests completed",
          status: "No Activity",
          statusTone: "red",
          action: "View Client",
          route: "/therapist/clients/chris-taylor",
        },
      ],

      attentionItems: [
        {
          id: 1,
          client: "Jamie Wilson",
          title: "2 overdue quests",
          detail: "Due 2 days ago",
          icon: "!",
          tone: "red",
          route: "/therapist/clients/jamie-wilson/quests",
        },
        {
          id: 2,
          client: "Sarah Chen",
          title: "Report ready for tomorrow’s session",
          detail: "Generated 1 hour ago",
          icon: "▣",
          tone: "orange",
          route: "/therapist/clients/sarah-chen/reports",
        },
        {
          id: 3,
          client: "Alex Morgan",
          title: "Permissions changed",
          detail: "Review updated sharing",
          icon: "🔒",
          tone: "purple",
          route: "/therapist/clients/alex-morgan",
        },
        {
          id: 4,
          client: "Chris Taylor",
          title: "No quest activity this week",
          detail: "Last update 7 days ago",
          icon: "i",
          tone: "blue",
          route: "/therapist/clients/chris-taylor",
        },
      ],

      recentQuestActivity: [
        {
          id: 1,
          icon: "✓",
          tone: "green",
          title: 'Alex Morgan completed "Join a community activity"',
          detail: "Earned 250 Respawn Points",
          when: "2h ago",
          points: "+250",
        },
        {
          id: 2,
          icon: "✎",
          tone: "blue",
          title: 'Jamie Wilson reflected on "Start one conversation"',
          detail: "Marked: Better than expected",
          when: "Yesterday",
          points: "+150",
        },
        {
          id: 3,
          icon: "✓",
          tone: "green",
          title: 'Sarah Chen completed "Attend planned social activity"',
          detail: "Earned 200 Respawn Points",
          when: "Yesterday",
          points: "+200",
        },
        {
          id: 4,
          icon: "☆",
          tone: "purple",
          title: 'Chris Taylor completed "Daily gratitude reflection"',
          detail: "Earned 100 Respawn Points",
          when: "2 days ago",
          points: "+100",
        },
      ],

      progressSummary: [
        {
          id: "improving",
          value: 8,
          direction: "↑",
          label: "Clients improving",
          detail: "More quest completions this week",
          tone: "green",
        },
        {
          id: "stable",
          value: 3,
          direction: "–",
          label: "Clients stable",
          detail: "Similar activity as last week",
          tone: "blue",
        },
        {
          id: "lower",
          value: 1,
          direction: "↓",
          label: "Clients with fewer completions",
          detail: "Check in recommended",
          tone: "red",
        },
      ],

      insightReports: [
        {
          id: 1,
          initials: "AM",
          name: "Alex Morgan",
          days: 7,
          activities: 5,
          confidence: "↑",
          confidenceTone: "green",
          route: "/therapist/clients/alex-morgan/reports",
        },
        {
          id: 2,
          initials: "JW",
          name: "Jamie Wilson",
          days: 6,
          activities: 4,
          confidence: "→",
          confidenceTone: "blue",
          route: "/therapist/clients/jamie-wilson/reports",
        },
        {
          id: 3,
          initials: "SC",
          name: "Sarah Chen",
          days: 7,
          activities: 6,
          confidence: "↑",
          confidenceTone: "green",
          route: "/therapist/clients/sarah-chen/reports",
        },
      ],
    };
  },
};