import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';import {generateKeyPairSync,sign} from 'node:crypto';
import {createCoreService} from '../../../domains/shared-core/service.mjs';
const e=JSON.parse(fs.readFileSync('config/environments/Ntgre.core.json')),subject='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
function fixture(){let groups=['Admin'],enabled=true,page=0;const user=sub=>({Username:sub,Enabled:enabled,UserStatus:'CONFIRMED',UserAttributes:[{Name:'sub',Value:sub},{Name:'email',Value:'player@example.invalid'},{Name:'name',Value:'Display'}],Secret:'MUST_NOT_ESCAPE'});const claims={iss:e.issuer,sub:subject,client_id:e.clientId,token_use:'access',exp:2000};const directory={get:async sub=>user(sub),groups:async()=>groups,list:async()=>({Users:[user(other)],...(page++===0?{PaginationToken:'private-cognito-page'}:{})})};const service=createCoreService({environment:e,verifyAccessToken:async()=>claims,directory,cursorKey:Buffer.alloc(32,1),clock:()=>1000});return {service,claims,directory,disable:()=>{enabled=false},revoke:()=>{groups=[]},base:{contractVersion:'authorization.decision.v1',environment:'Ntgre',accessToken:'offline-token',capability:'teams.admin'},search:{contractVersion:'directory.assignment.v1',environment:'Ntgre',accessToken:'offline-token',action:'search',teamId:'team:alpha',query:'pl',limit:2}};}
test('fresh global capability grants Admin and revokes without trusting JWT groups',async()=>{const f=fixture();assert.equal((await f.service(f.base)).allowed,true);f.claims['cognito:groups']=['SuperAdmin'];f.revoke();assert.equal((await f.service(f.base)).allowed,false);});
test('branding explicitly unavailable; unsupported capabilities rejected',async()=>{const f=fixture();assert.equal((await f.service({...f.base,capability:'teams.branding.manage'})).allowed,false);await assert.rejects(f.service({...f.base,capability:'commerce.admin'}),/INVALID_INPUT/);});
test('disabled actor denied; no cached grant',async()=>{const f=fixture();f.disable();await assert.rejects(f.service(f.base),/FORBIDDEN/);});
for(const change of [{environment:'production'},{actor:{subject:other}},{subject:other}])test('reject untrusted identity/environment '+Object.keys(change)[0],async()=>{const f=fixture();await assert.rejects(f.service({...f.base,...change}));});
for(const change of [{iss:'https://foreign'},{client_id:'foreign'},{token_use:'id'},{exp:900},{nbf:1100}])test('reject delegated JWT '+Object.keys(change)[0],async()=>{const f=fixture();Object.assign(f.claims,change);await assert.rejects(f.service(f.base),/UNAUTHENTICATED/);});
test('directory exact resolution minimizes attributes and rejects ambiguity',async()=>{const f=fixture();f.directory.list=async()=>({Users:[await f.directory.get(other)]});const r=await f.service({...f.search,action:'resolve',query:undefined,limit:undefined,account:'player@example.invalid'}).catch(e=>e);assert.equal(r.code,'INVALID_INPUT');const req={contractVersion:'directory.assignment.v1',environment:'Ntgre',accessToken:'offline-token',action:'resolve',teamId:'team:alpha',account:'player@example.invalid'};assert.deepEqual(await f.service(req),{contractVersion:'directory.assignment.v1',subject:other,displayName:'Display'});f.directory.list=async()=>({Users:[await f.directory.get(other),await f.directory.get(other)]});await assert.rejects(f.service(req),/NOT_FOUND/);});
test('bounded directory search encrypts pagination and binds actor/query/Team',async()=>{const f=fixture(),r=await f.service(f.search);assert.deepEqual(r.items,[{subject:other,displayName:'Display'}]);assert.ok(r.nextToken&&!r.nextToken.includes('private-cognito-page'));assert.ok(!JSON.stringify(r).includes('email'));await assert.rejects(f.service({...f.search,nextToken:r.nextToken,teamId:'team:other'}),/INVALID_INPUT/);f.claims.sub=other;await assert.rejects(f.service({...f.search,nextToken:r.nextToken}),/INVALID_INPUT/);f.claims.sub=subject;assert.equal((await f.service({...f.search,nextToken:r.nextToken})).items.length,1);});
test('directory bounds and dependency failure fail closed',async()=>{const f=fixture();await assert.rejects(f.service({...f.search,limit:11}),/INVALID_INPUT/);f.directory.list=async()=>{throw Error('secret provider detail')};await assert.rejects(f.service(f.search),/^Error: DEPENDENCY_UNAVAILABLE$/);});
test('real JWT signature verifier rejects tampering, wrong client and expired token',()=>{const require=createRequire(new URL('../../../domains/shared-core/package.json',import.meta.url)),{CognitoJwtVerifier}=require('aws-jwt-verify');const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk={...publicKey.export({format:'jwk'}),kid:'offline-key',alg:'RS256',use:'sig'},verifier=CognitoJwtVerifier.create({userPoolId:e.poolId,tokenUse:'access',clientId:e.clientId});verifier.cacheJwks({keys:[jwk]});const jwt=claims=>{const b=x=>Buffer.from(JSON.stringify(x)).toString('base64url'),body=b({alg:'RS256',kid:jwk.kid})+'.'+b({iss:e.issuer,sub:subject,client_id:e.clientId,token_use:'access',exp:Math.floor(Date.now()/1000)+120,...claims});return body+'.'+sign('RSA-SHA256',Buffer.from(body),privateKey).toString('base64url');};assert.equal(verifier.verifySync(jwt({})).sub,subject);assert.throws(()=>verifier.verifySync(jwt({client_id:'foreign'})));assert.throws(()=>verifier.verifySync(jwt({exp:1})));const token=jwt({});const parts=token.split('.');parts[1]=Buffer.from(JSON.stringify({sub:other})).toString('base64url');assert.throws(()=>verifier.verifySync(parts.join('.')));});
