import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {op,journal,coreArn} from '../security.mjs';
const E='docs/architecture/team-hub-2b5-evidence-2026-10-06',read=n=>JSON.parse(fs.readFileSync(E+'/'+n+'.json'));
const list=x=>Array.isArray(x)?x:[x],match=(p,v)=>new RegExp('^'+p.replace(/[.+^${}()|[\]\\]/g,'\\$&').replaceAll('*','.*').replaceAll('?','.')+'$').test(v);
function allows(policy,action,resource,context={}){let allowed=false;for(const s of policy.Statement){if(s.Action&&!list(s.Action).some(a=>match(a,action)))continue;if(s.NotAction&&list(s.NotAction).some(a=>match(a,action)))continue;if(s.Resource&&!list(s.Resource).some(r=>match(r,resource)))continue;if(s.NotResource&&list(s.NotResource).some(r=>match(r,resource)))continue;let ok=true;for(const[operator,pairs]of Object.entries(s.Condition??{}))for(const[k,wanted]of Object.entries(pairs)){const values=context[k]===undefined?[]:list(context[k]);if(operator==='Null')ok&&=String(values.length===0)===wanted;else if(operator==='ForAllValues:StringLike')ok&&=values.every(v=>list(wanted).some(p=>match(p,v)));else if(operator==='ForAnyValue:StringEquals')ok&&=values.some(v=>list(wanted).includes(v));else if(operator==='ForAllValues:StringNotEquals')ok&&=values.every(v=>!list(wanted).includes(v));else throw Error('Unsupported operator');}if(ok&&s.Effect==='Deny')return false;if(ok&&s.Effect==='Allow')allowed=true;}return allowed;}
const business={'dynamodb:LeadingKeys':['TEAM#team:actual'],'dynamodb:EnclosingOperation':['TransactWriteItems']};
for(const kind of ['command','read']){
 const p=read(kind+'-policy');
 test(kind+' exact owned reads, Core invocation and transactional separation',()=>{assert.ok(allows(p,'dynamodb:GetItem',op,business));assert.ok(allows(p,'lambda:InvokeFunction',coreArn));assert.ok(allows(p,'dynamodb:GetItem',journal,{'dynamodb:LeadingKeys':['CONTROL#AUTHORITY']}));assert.equal(allows(p,'dynamodb:PutItem',op,business),kind==='command');assert.equal(allows(p,'dynamodb:PutItem',op,{'dynamodb:LeadingKeys':['TEAM#team:actual']}),false);assert.equal(allows(p,'dynamodb:PutItem',journal,{'dynamodb:LeadingKeys':['CONTROL#AUTHORITY'],'dynamodb:EnclosingOperation':['TransactWriteItems']}),false);});
 for(const [action,resource]of [['cognito-idp:ListUsers','*'],['cognito-idp:AdminGetUser','*'],['cognito-idp:AdminCreateUser','*'],['cognito-idp:AdminUpdateUserAttributes','*'],['appsync:GraphQL','*'],['iam:PassRole','*'],['cloudformation:UpdateStack','*'],['s3:PutObject','arn:aws:s3:::business/object'],['kms:Decrypt','arn:aws:kms:eu-north-1:058264289478:key/business'],['dynamodb:Scan',op],['dynamodb:DeleteItem',journal],...['Tournament','Creator','Commerce','Community','Legacy'].map(n=>['dynamodb:GetItem',`arn:aws:dynamodb:eu-north-1:058264289478:table/${n}`]),['lambda:InvokeFunction',coreArn.replace('Core','Tournament')]])test(kind+' rejects '+action+' '+resource,()=>assert.equal(allows(p,action,resource,business),false));
}
test('Core exact pool directory-only permissions; no Team storage or user mutation',()=>{const p=read('core-runtime-policy'),pool='arn:aws:cognito-idp:eu-north-1:058264289478:userpool/eu-north-1_n24iLL7QE';for(const action of ['ListUsers','AdminGetUser','AdminListGroupsForUser']){assert.ok(allows(p,'cognito-idp:'+action,pool));assert.equal(allows(p,'cognito-idp:'+action,pool+'foreign'),false);}for(const action of ['AdminCreateUser','AdminUpdateUserAttributes','AdminAddUserToGroup','AdminDeleteUser'])assert.equal(allows(p,'cognito-idp:'+action,pool),false);assert.equal(allows(p,'dynamodb:GetItem',op),false);});
