import assert from 'node:assert/strict';import {decode} from '../../../domains/team-hub/parity/codec.mjs';import {canonical} from '../../../domains/team-hub/parity/repository.mjs';
export async function exercise({call,snapshot,subjects,runId,record=()=>{}}){const slug='phase2b4-test-'+runId+'-one',id='team:'+slug,id2='team:phase2b4-test-'+runId+'-two';let seq=0;const results=[];const state=async()=>decode((await snapshot()).operational.filter(r=>r.PK==='TEAM#'+id||r.PK==='SLUG#'+slug));const member=n=>'team-membership:'+id+':'+subjects[n].subject;
const c=async n=>{const a=await state();return {teamId:id,idempotencyKey:'b4b-request-'+(++seq),expectedTeamVersion:a.team.version,expectedAuthorizationEpoch:a.team.authorizationEpoch,expectedMembershipVersion:a.memberships[member(n)]?.version??0};};
async function check(op,req,n='admin',status=200,label=op){const before=status===200?null:canonical(await snapshot());const r=await call(n,op,req);results.push({label,operation:op,persona:n,status:r.status,expected:status,response:r.body,requestId:r.requestId});record(results);assert.equal(r.status,status,label+' unexpected response '+JSON.stringify(r.body));if(status!==200){assert.equal(canonical(await snapshot()),before,label+' changed state');assert.equal(r.body.error?.code,status===403?'FORBIDDEN':status===404?'NOT_FOUND':'CONFLICT');}return r.body.data;}
await check('CREATE_TEAM',{slug,name:'Synthetic verification',gameKey:'LEAGUE_OF_LEGENDS',idempotencyKey:'b4b-normal-denial'},'outsider',403,'normal command before first write');await check('GET_TEAM_HUB',{teamId:id},'outsider',403,'normal read before first write');await check('GET_TEAM_HUB',{teamId:'team:phase2b4-test-wrongrun-one'},'admin',404,'unknown Team returns not found to global administrator');
await check('CREATE_TEAM',{slug,name:'Synthetic verification',gameKey:'LEAGUE_OF_LEGENDS',idempotencyKey:'b4b-create-one'});await check('CREATE_TEAM',{slug:id2.slice(5),name:'Synthetic isolated Team',gameKey:'LEAGUE_OF_LEGENDS',idempotencyKey:'b4b-create-two'});
await check('SET_MANAGER',{...await c('admin'),action:'ASSIGN',targetAccount:'manager@example.invalid',expectedTargetMembershipVersion:0});for(const n of ['coach','player'])await check('MANAGE_MEMBER',{...await c('manager'),role:n.toUpperCase(),action:'ASSIGN',targetAccount:n+'@example.invalid',expectedTargetMembershipVersion:0},'manager');
await check('UPDATE_TEAM',{...await c('admin'),name:'Synthetic updated',status:'ACTIVE'});await check('SET_TEAM_PLAN',{...await c('admin'),plan:'PRO'});
await check('SET_ROSTER_SLOT',{...await c('manager'),action:'ASSIGN',membershipId:member('player'),gameRoleKey:'MID',slotType:'STARTER',expectedRosterVersion:0,expectedTargetMembershipVersion:1},'manager');
await check('UPSERT_MY_CHAMPION',{...await c('player'),championId:'Ahri',gameRoleKey:'MID',comfortLevel:'A',priority:'NORMAL',competitiveReady:true,playerNotes:'synthetic',expectedEntryVersion:0},'player');
await check('UPSERT_COACH_ASSESSMENT',{...await c('coach'),membershipId:member('player'),championId:'Ahri',teamVisible:'Synthetic visible assessment',privateNote:'',expectedAssessmentVersion:0,expectedTargetMembershipVersion:1},'coach');
for(const n of ['manager','coach','player'])await check('GET_TEAM_HUB',{teamId:id},n,200,'Team context '+n);const own=await check('LIST_MY_CHAMPION_POOL',{teamId:id},'player');assert.ok(!JSON.stringify(own).includes('teamVisible')&&!JSON.stringify(own).includes('privateNote'));
const pools=await check('LIST_TEAM_CHAMPION_POOLS',{teamId:id},'manager');assert.ok(!JSON.stringify(pools).includes('privateNote'));const detail=await check('GET_PLAYER_COMPETITIVE_DETAIL',{teamId:id,membershipId:member('player')},'coach');const inspectPrivacy=v=>{if(v&&typeof v==='object')for(const [k,x]of Object.entries(v)){if(k==='privateNote')assert.equal(x,'');inspectPrivacy(x);}};inspectPrivacy(detail);
const replay={...await c('admin'),name:'Synthetic replay',status:'ACTIVE'},first=await check('UPDATE_TEAM',replay),beforeReplay=canonical(await snapshot());assert.deepEqual(await check('UPDATE_TEAM',replay,'admin',200,'idempotent replay'),first);assert.equal(canonical(await snapshot()),beforeReplay);await check('UPDATE_TEAM',{...replay,name:'Different'},'admin',409,'idempotency conflict');
for(const [field,label]of [['expectedTeamVersion','stale Team revision'],['expectedAuthorizationEpoch','stale epoch'],['expectedMembershipVersion','stale membership revision']]){const req={...await c('manager'),role:'PLAYER',action:'REVOKE',targetMembershipId:member('player'),expectedTargetMembershipVersion:1};req[field]+=99;await check('MANAGE_MEMBER',req,'manager',409,label);}
await check('SET_ROSTER_SLOT',{...await c('manager'),action:'ASSIGN',membershipId:member('player'),gameRoleKey:'TOP',slotType:'STARTER',expectedRosterVersion:(await state()).team.rosterVersion,expectedTargetMembershipVersion:1},'manager',409,'duplicate starter/player guard');
for(const n of ['player','coach'])await check('MANAGE_MEMBER',{...await c(n),role:'PLAYER',action:'REVOKE',targetMembershipId:member('player'),expectedTargetMembershipVersion:1},n,403,'wrong Manager role '+n);
await check('UPSERT_COACH_ASSESSMENT',{...await c('player'),membershipId:member('player'),championId:'Ahri',teamVisible:'',privateNote:'',expectedAssessmentVersion:1,expectedTargetMembershipVersion:1},'player',403,'Player cannot Coach assessment');await check('UPSERT_COACH_ASSESSMENT',{...await c('manager'),membershipId:member('player'),championId:'Ahri',teamVisible:'',privateNote:'',expectedAssessmentVersion:1,expectedTargetMembershipVersion:1},'manager',403,'Manager cannot Coach assessment');
await check('UPSERT_COACH_ASSESSMENT',{...await c('coach'),membershipId:member('player'),championId:'Ahri',teamVisible:'',privateNote:'synthetic-private-denial-probe',expectedAssessmentVersion:1,expectedTargetMembershipVersion:1},'coach',403,'private persistence denied');await check('GET_TEAM_HUB',{teamId:id2},'manager',403,'cross-Team membership denied');await check('GET_TEAM_HUB',{teamId:id},'outsider',403,'wrong subject');
await check('SET_TEAM_PLAN',{...await c('manager'),plan:'FREE'},'manager',403,'membership is not global entitlement');
const raceBase={...await c('admin'),status:'ACTIVE'},raceBefore=await snapshot(),raceVersion=(await state()).team.version;const races=await Promise.all(['A','B'].map(async suffix=>{const req={...raceBase,idempotencyKey:'b4b-race-'+suffix,name:'Synthetic race '+suffix},r=await call('admin','UPDATE_TEAM',req);results.push({label:'concurrent update '+suffix,operation:'UPDATE_TEAM',persona:'admin',status:r.status,response:r.body,requestId:r.requestId});return r;}));record(results);assert.deepEqual(races.map(r=>r.status).sort(),[200,409]);assert.equal((await state()).team.version,raceVersion+1);assert.equal((await snapshot()).journal.length,raceBefore.journal.length+2);
await check('DELETE_MY_CHAMPION',{...await c('player'),championId:'Ahri',expectedEntryVersion:1},'player');await check('MANAGE_MEMBER',{...await c('manager'),role:'PLAYER',action:'REVOKE',targetMembershipId:member('player'),expectedTargetMembershipVersion:1},'manager');await check('GET_TEAM_HUB',{teamId:id},'player',403,'revoked Player denied');
await check('SET_MANAGER',{...await c('admin'),action:'ASSIGN',targetAccount:'player@example.invalid',expectedTargetMembershipVersion:(await state()).memberships[member('player')].version});await check('MANAGE_MEMBER',{...await c('manager'),role:'COACH',action:'REVOKE',targetMembershipId:member('coach'),expectedTargetMembershipVersion:1},'manager',403,'former Manager revoked');
return {results,teamIds:[id,id2],complete:true};}
