import test from 'node:test';import assert from 'node:assert/strict';
import {createCutoverHandler} from '../../../domains/team-hub/cutover/handler.mjs';
import {operations} from '../../../domains/team-hub/cutover/contracts.mjs';
import {TransactionEmulator} from '../../team-hub-2b4/tests/transport.mjs';
import {environment,claims,subjects,now} from '../../team-hub/tests/fixtures.mjs';
import {exercise} from './sequence.mjs';
const journal='ProjectRespawn-TeamHub-Ntgre-Journal',operational='ProjectRespawn-TeamHub-Ntgre-Operational';
class Transport extends TransactionEmulator {
 async transactWrite(p){if(this.beforeWrite){const fn=this.beforeWrite;this.beforeWrite=null;fn();}const first=p.TransactItems[0].ConditionCheck;assert.equal(first.Key.PK,'CONTROL#AUTHORITY');const row=this.rows.get(this.key(journal,first.Key)),v=first.ExpressionAttributeValues;if(row.mode!==v[':mode']||row.epoch!==v[':epoch']||row.version!==v[':version']){const error=Error('conflict');error.name='TransactionCanceledException';throw error;}await super.transactWrite({...p,TransactItems:p.TransactItems.slice(1)});this.transactions[this.transactions.length-1]=structuredClone(p);}
}
function fixture(){const transport=new Transport(),control={PK:'CONTROL#AUTHORITY',SK:'STATE',schemaVersion:'team-hub-authority.v1',mode:'TARGET_WRITER',epoch:2,version:2,changedAt:'2026-10-07T00:00:00Z',changedBy:'offline-test',gateDigest:'a'.repeat(64)};transport.rows.set(transport.key(journal,control),control);let revoked=false;const invokeCore=async r=>{if(r.contractVersion==='authorization.decision.v1')return {ok:true,data:{contractVersion:r.contractVersion,subject:subjects[r.accessToken],capability:r.capability,environment:'Ntgre',allowed:r.accessToken==='admin'&&!revoked&&r.capability==='teams.admin',decisionVersion:1,evaluatedAt:now,expiresAt:now+5}};if(r.action==='resolve'){const name=r.account.split('@')[0];return {ok:true,data:{contractVersion:r.contractVersion,subject:subjects[name],displayName:name}};}return {ok:true,data:{contractVersion:r.contractVersion,items:[]}};};const handlers=Object.fromEntries(['command','read'].map(runtime=>[runtime,createCutoverHandler({runtime,transport,invokeCore,environment,cursorSecret:'offline-stable-cursor-secret-at-least-32-bytes',clock:()=>now})]));
 const call=async(persona,op,req)=>{const spec=operations[op],body={...req},pathParameters={};for(const m of spec.path.matchAll(/\{([^}]+)\}/g)){pathParameters[m[1]]=body[m[1]];delete body[m[1]];}const r=await handlers[spec.runtime]({routeKey:spec.method+' '+spec.path,pathParameters,headers:{authorization:'Bearer '+persona,'x-team-authority-epoch':'2'},...(spec.method==='GET'?{queryStringParameters:Object.fromEntries(Object.entries(body).map(([k,v])=>[k,String(v)]))}:{body:JSON.stringify(body)}),requestContext:{requestId:'offline-test',authorizer:{jwt:{claims:claims(persona)}}}});return {status:r.statusCode,body:JSON.parse(r.body)};};return {transport,control,call,revoke:()=>{revoked=true},snapshot:async()=>({operational:[...transport.rows.entries()].filter(([k])=>k.startsWith(operational+'|')).map(([,v])=>structuredClone(v)).sort((a,b)=>(a.PK+a.SK).localeCompare(b.PK+b.SK)),journal:[...transport.rows.entries()].filter(([k,v])=>k.startsWith(journal+'|')&&v.PK!=='CONTROL#AUTHORITY').map(([,v])=>structuredClone(v)).sort((a,b)=>(a.PK+a.SK).localeCompare(b.PK+b.SK))})};}
const create={slug:'real-team',name:'Real candidate',gameKey:'LEAGUE_OF_LEGENDS',idempotencyKey:'candidate-create'};
test('ordinary Team create uses real capability client and atomic authority condition',async()=>{const f=fixture();assert.equal((await f.call('admin','CREATE_TEAM',create)).status,200);assert.equal(f.transport.transactions.length,1);assert.equal(f.transport.transactions[0].TransactItems[0].ConditionCheck.Key.PK,'CONTROL#AUTHORITY');assert.equal((await f.call('player','CREATE_TEAM',{...create,slug:'other'})).status,403);});
for(const mode of ['LEGACY_WRITER','FROZEN'])test(mode+' denies target writes including synthetic-looking names',async()=>{const f=fixture();f.control.mode=mode;assert.equal((await f.call('admin','CREATE_TEAM',{...create,slug:'phase2b4-test-abcdefgh-one'})).status,403);assert.equal(f.transport.transactions.length,0);});
test('authority missing/outage fails closed',async()=>{const f=fixture();f.transport.rows.clear();assert.notEqual((await f.call('admin','CREATE_TEAM',create)).status,200);assert.equal(f.transport.transactions.length,0);});
test('freeze between read and transaction prevents all domain/audit/idempotency writes',async()=>{const f=fixture();f.transport.beforeWrite=()=>{f.control.mode='FROZEN';f.control.version++;};assert.equal((await f.call('admin','CREATE_TEAM',create)).status,403);assert.equal(f.transport.rows.size,1);});
test('fresh global revocation prevents idempotency replay',async()=>{const f=fixture();assert.equal((await f.call('admin','CREATE_TEAM',create)).status,200);f.revoke();assert.equal((await f.call('admin','CREATE_TEAM',create)).status,403);assert.equal(f.transport.transactions.length,1);});
test('41 adapted mutation/privacy/concurrency checks with ordinary authority adapter',async()=>{const f=fixture();const mapped=Object.fromEntries(Object.entries(subjects).map(([k,subject])=>[k,{subject}]));const result=await exercise({call:f.call,snapshot:f.snapshot,subjects:mapped,runId:'b4b20261006'});assert.ok(result.complete);assert.equal(result.results.length,41);});

test('Core-backed assignment resolution exposes only identity display and Team-owned membership version',async()=>{const f=fixture();await f.call('admin','CREATE_TEAM',create);const req={teamId:'team:real-team',account:'manager@example.invalid'};const r=await f.call('admin','RESOLVE_TEAM_ASSIGNABLE_USER',req);assert.equal(r.status,200);assert.deepEqual(Object.keys(r.body.data).sort(),['displayName','membershipVersion','subject']);assert.equal(r.body.data.membershipVersion,0);assert.equal((await f.call('outsider','RESOLVE_TEAM_ASSIGNABLE_USER',req)).status,403);});
test('stale client authority epoch denies before business transaction',async()=>{const f=fixture();f.control.epoch=3;assert.equal((await f.call('admin','CREATE_TEAM',create)).status,409);assert.equal(f.transport.transactions.length,0);});
test('missing authority audit metadata fails closed',async()=>{const f=fixture();delete f.control.changedAt;assert.equal((await f.call('admin','CREATE_TEAM',create)).status,503);assert.equal(f.transport.transactions.length,0);});
