import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const E='docs/architecture/team-hub-2b5-evidence-2026-10-06',read=p=>JSON.parse(fs.readFileSync(p)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),save=(n,v)=>fs.writeFileSync(E+'/'+n+'.json',JSON.stringify(v,null,2)+'\n');
const docs=['cutover-dependency-review','core-contracts','legacy-writer-fence','frontend-cutover','cutover-runbook','rollback-rehearsal'].map(n=>'docs/architecture/team-hub-2b5-'+n+'.md');
let links=0;for(const file of docs)for(const m of fs.readFileSync(file,'utf8').matchAll(/\]\(([^)]+)\)/g)){if(/^https?:/.test(m[1]))continue;assert.ok(fs.existsSync(path.resolve(path.dirname(file),m[1].split('#')[0])),'Broken link '+m[1]);links++;}
const walk=p=>fs.readdirSync(p,{withFileTypes:true}).filter(d=>!['node_modules','.build'].includes(d.name)).flatMap(d=>d.isDirectory()?walk(p+'/'+d.name):[p+'/'+d.name]);
const files=[...walk('domains/shared-core'),...walk('domains/team-hub/cutover'),...walk('scripts/team-hub-2b5'),...docs,'src/features/team-hub/api/cutover-client.mjs','src/features/team-hub/services/cutover-consumers.mjs'];
for(const file of [...files,...walk(E)]){
 const text=fs.readFileSync(file,'utf8');for(const pattern of [/\b(?:AKIA|ASIA)[A-Z0-9]{16}\b/,/eyJ[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/"(?:SecretAccessKey|SessionToken|password)"\s*:\s*"[^"\s]+"/])assert.ok(!pattern.test(text),'Credential literal in '+file);
 }
save('source-manifest',{at:new Date().toISOString(),files:files.map(p=>({path:p,sha256:sha(p)})),templates:['team-product.template','team-security-runtime-only.template','core-product.template','core-security-runtime-only.template'].map(n=>({path:E+'/'+n+'.json',sha256:sha(E+'/'+n+'.json')})),awsWrites:0,deployable:false});
save('final-review',{at:new Date().toISOString(),ready:false,verdict:'TEAM HUB CUTOVER REMAINS BLOCKED',documentationLinks:links,credentialPatternScan:'PASS',credentialsOrTokensWritten:false,awsCalls:0,awsChanges:0,businessDataWrites:0,authority:'LEGACY_WRITER',frontendCutover:false,retirement:false,productionTouched:false,acceptedSourcesPreserved:read(E+'/preservation.json').acceptedFilesUnchanged,validation:read(E+'/validation.json'),candidate:read(E+'/build.json').proposed});
const sPath='docs/architecture/domain-migration-status.json',status=read(sPath),team=status.domains.find(x=>x.domain==='Team Hub');status.scope='Ntgre Team Hub 2B5 offline cutover dependency preparation; blocked; no AWS changes';status.currentPhase='M5 / Phase 2B5 PREPARED_BLOCKED; Legacy authority retained';status.awsChangesMeaning='42 historical calls through 2B4B: includes four temporary configuration activate/restore writes; 2B5 adds zero AWS calls/writes. Synthetic data transactions accounted separately.';
team.phase='M5_2B5_PREPARED_BLOCKED';team.nextStep='TEAM HUB 2B5/2B6 CUTOVER CANDIDATE REVIEW after Core deployment security/live acceptance, real frontend conversion, fence proof and rollback blockers are closed';team.cutoverDependencyReview={status:'PREPARED_BLOCKED',awsChanges:0,authority:'LEGACY_WRITER',frontendCutover:false,coreDeployed:false,legacyFenceInstalled:false,targetOrdinaryWriter:false,report:docs[0],validation: E+'/validation.json'};
for(const doc of docs)if(!team.evidence.includes(doc))team.evidence.push(doc);
const shared=status.domains.find(x=>x.domain==='Shared/Core');shared.offlineContractCandidate={status:'PREPARED_NOT_DEPLOYED',report:docs[1],proposedProductResources:6,proposedRuntimeBoundary:1,deploymentSecurityReserved:4};
fs.writeFileSync(sPath,JSON.stringify(status,null,2)+'\n');
const lPath='docs/architecture/legacy-resource-ownership.json',ledger=read(lPath);ledger.latestTeam2B5Review={at:new Date().toISOString(),report:docs[0],awsWrites:0,ownershipRowsChanged:0,migrationStatusUnchanged:true,physicalTeamAttribution:192,teamOwnerRows:188,buildMetadataRows:4};fs.writeFileSync(lPath,JSON.stringify(ledger,null,2)+'\n');
const rPath='docs/architecture/README-PHASE2-MIGRATION.md';let content=fs.readFileSync(rPath,'utf8');if(!content.includes('**Latest 2B5 result'))content=content.replace('\n\n','\n\n**Latest 2B5 result (6 October 2026): OFFLINE CUTOVER PREPARATION — BLOCKED.** Core contracts, ordinary-authority runtime, policy fences and dormant client candidates are prepared/tested. Core deployment security/live acceptance, full Vue/shell integration, installed fence proof and live rollback rehearsal remain open. No AWS calls, authority switch or frontend cutover. [2B5 dependency review](team-hub-2b5-cutover-dependency-review.md).\n\n');content=content.replace('2B5 Core/fence preparation next. Fence/cutover NOT performed.','2B5 offline candidates prepared; cutover blocked pending dependency/security/frontend/rehearsal acceptance. Fence/cutover NOT performed.');fs.writeFileSync(rPath,content);
console.log(JSON.stringify({ready:false,documentationLinks:links,credentialPatternScan:'PASS',files:files.length,awsChanges:0,ledgerOwnershipRowsChanged:0}));
