import fs from 'node:fs';import path from 'node:path';import {gzipSync} from 'node:zlib';import {createRequire} from 'node:module';import {build as viteBuild} from 'vite';
const E='docs/architecture/team-hub-2b5-evidence-2026-10-06',esbuild=createRequire(path.resolve('infrastructure/domains/team-hub/package.json'))('esbuild');
const client=await esbuild.build({entryPoints:['src/features/team-hub/services/cutover-consumers.mjs'],bundle:true,format:'esm',platform:'browser',write:false,metafile:true,logLevel:'silent'});
const candidateInputs=Object.keys(client.metafile.inputs);if(candidateInputs.some(p=>!/^(src\/features\/team-hub\/|domains\/team-hub\/(contracts.mjs|cutover\/contracts.mjs))/.test(p)))throw Error('Foreign candidate frontend import');
const candidate={bytes:client.outputFiles[0].contents.length,gzip:gzipSync(client.outputFiles[0].contents).length,inputs:candidateInputs,foreignDomainImports:0,liveRegistered:false};
let graph;
await viteBuild({build:{outDir:'.tmp/team-hub-2b5/site-build',emptyOutDir:true},logLevel:'warn',plugins:[{name:'team-cutover-measure',generateBundle(_,bundle){const entries=Object.values(bundle).filter(c=>c.type==='chunk'&&c.isEntry);graph={entries:entries.map(c=>({file:c.fileName,bytes:Buffer.byteLength(c.code),gzip:gzipSync(c.code).length,imports:c.imports})),chunks:Object.values(bundle).filter(c=>c.type==='chunk').map(c=>({file:c.fileName,isEntry:c.isEntry,imports:c.imports,dynamicImports:c.dynamicImports,modules:Object.keys(c.modules).filter(m=>m.includes('/src/')).map(m=>path.relative(process.cwd(),m).replaceAll('\\','/'))}))};}}]});
const evidence={at:new Date().toISOString(),candidate,site:graph,beforeAfter:'Live frontend source and registration unchanged; this is the current shell baseline and isolated dormant-client measurement, not a claimed application cutover improvement.',browserInitializationAndNetworkProof:'NOT_PERFORMED; global eager foreign modules remain a cutover blocker',awsWrites:0};
fs.writeFileSync(E+'/frontend-measure.json',JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({candidate,entries:graph.entries}));
