import test from 'node:test';
import assert from 'node:assert/strict';
import {read,digest} from './read-only.mjs';
const E='docs/architecture/team-hub-2b3-evidence-2026-10-05/';
const design=read(E+'dark-target.template.json'),prior=read('docs/architecture/team-hub-2b2-caller-release-evidence-2026-10-05/ownership.json').productTemplate;
test('dark proposal preserves all eleven accepted product declarations; adds only 2 tables/bucket/policy',()=>{assert.equal(Object.keys(design.Resources).length,15);for(const [k,v] of Object.entries(prior.Resources))assert.equal(digest(design.Resources[k]),digest(v));assert.equal(Object.values(design.Resources).filter(r=>r.Type==='AWS::DynamoDB::Table').length,2);});
test('native state protected by PITR/delete protection/retention; only two sparse key-only GSIs',()=>{for(const name of ['OperationalTable','JournalTable']){const r=design.Resources[name];assert.equal(r.DeletionPolicy,'Retain');assert.equal(r.UpdateReplacePolicy,'Retain');assert.equal(r.Properties.PointInTimeRecoverySpecification.PointInTimeRecoveryEnabled,true);assert.equal(r.Properties.DeletionProtectionEnabled,true);}assert.equal(design.Resources.OperationalTable.Properties.GlobalSecondaryIndexes.length,2);assert.ok(design.Resources.OperationalTable.Properties.GlobalSecondaryIndexes.every(i=>i.Projection.ProjectionType==='KEYS_ONLY'));assert.equal(design.Resources.JournalTable.Properties.GlobalSecondaryIndexes,undefined);});
test('logo bucket private/versioned/AES256/retained; old runtime gets no new privileges',()=>{const r=design.Resources.LogoBucket;assert.equal(r.Properties.VersioningConfiguration.Status,'Enabled');assert.equal(r.Properties.BucketEncryption.ServerSideEncryptionConfiguration[0].ServerSideEncryptionByDefault.SSEAlgorithm,'AES256');assert.ok(Object.values(r.Properties.PublicAccessBlockConfiguration).every(Boolean));assert.equal(r.DeletionPolicy,'Retain');assert.deepEqual(design.Resources.ReadRole,prior.Resources.ReadRole);});
const proposal=read(E+'migration-identity-proposal.json');
const matches=(p,s)=>new RegExp('^'+p.replace(/[.*+?^${}()|[\]\\]/g,'\\$&').replaceAll('\\*','.*')+'$','i').test(s);
const list=x=>Array.isArray(x)?x:[x];
const context={'aws:RequestedRegion':'eu-north-1','aws:CurrentTime':'2026-10-06T10:00:00Z','s3:prefix':'team-logos/','s3:x-amz-server-side-encryption':'AES256'};
function allowed(action,resource,ctx=context){return proposal.identityPolicy.Statement.some(s=>list(s.Action).some(a=>matches(a,action))&&list(s.Resource).some(r=>matches(r,resource))&&Object.entries(s.Condition??{}).every(([op,pairs])=>Object.entries(pairs).every(([k,v])=>op==='StringEquals'?ctx[k]===v:op==='DateLessThan'?Date.parse(ctx[k])<Date.parse(v):op==='DateGreaterThan'?Date.parse(ctx[k])>Date.parse(v):false)));}
test('migration identity and boundary identical; exact source read and target write allowed in window',()=>{assert.deepEqual(proposal.identityPolicy,proposal.permissionsBoundary);for(const arn of proposal.sourceArns)assert.equal(allowed('dynamodb:Scan',arn),true);for(const arn of proposal.targetArns)assert.equal(allowed('dynamodb:PutItem',arn),true);});
for(const action of ['dynamodb:PutItem','dynamodb:DeleteItem','dynamodb:UpdateTable','dynamodb:CreateBackup'])test('migration cannot mutate/protect source '+action,()=>assert.equal(allowed(action,proposal.sourceArns[0]),false));
for(const action of ['iam:CreateRole','cloudformation:ExecuteChangeSet','cognito-idp:AdminCreateUser','kms:Decrypt','lambda:InvokeFunction','appsync:GraphQL','sts:AssumeRole'])test('migration lacks '+action,()=>assert.equal(allowed(action,'*'),false));
for(const domain of ['Tournament','Creator','Commerce','Community','production'])test('migration denies foreign '+domain,()=>assert.equal(allowed('dynamodb:PutItem','arn:aws:dynamodb:eu-north-1:058264289478:table/'+domain),false));
test('migration denies expired/not-yet-valid/wrong-region calls',()=>{for(const ctx of [{...context,'aws:CurrentTime':'2026-10-07T00:00:00Z'},{...context,'aws:CurrentTime':'2026-10-05T00:00:00Z'},{...context,'aws:RequestedRegion':'us-east-1'}])assert.equal(allowed('dynamodb:PutItem',proposal.targetArns[0],ctx),false);});
test('logo copy scoped to owned prefix and explicit AES256',()=>{const arn='arn:aws:s3:::'+proposal.targetBucket+'/team-logos/synthetic.png';assert.equal(allowed('s3:PutObject',arn),true);assert.equal(allowed('s3:PutObject',arn,{...context,'s3:x-amz-server-side-encryption':'aws:kms'}),false);assert.equal(allowed('s3:PutObject',arn.replace('team-logos/','foreign/')),false);assert.equal(allowed('s3:ListBucket','arn:aws:s3:::'+proposal.targetBucket,{...context,'s3:prefix':''}),false);});
