// Offline concrete proposals only. No deployment CLI/SDK and no synthesis of Legacy.
import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
import {read,save,digest} from './read-only.mjs';
import {transform,reconcile,reverse} from './transform.mjs';
import {fixture,options} from './fixtures.mjs';
const inventory=read('docs/architecture/team-hub-2b3-evidence-2026-10-05/table-inventory.json');
const logos=read('docs/architecture/team-hub-2b3-evidence-2026-10-05/logo-inventory.json');
const account='058264289478',region='eu-north-1',prefix='ProjectRespawn-TeamHub-Ntgre';
const operational=prefix+'-Operational',journal=prefix+'-Journal',targetBucket='projectrespawn-teamhub-ntgre-058264289478-eu-north-1';
const table=name=>({Type:'AWS::DynamoDB::Table',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{TableName:name,BillingMode:'PAY_PER_REQUEST',AttributeDefinitions:[{AttributeName:'PK',AttributeType:'S'},{AttributeName:'SK',AttributeType:'S'}],KeySchema:[{AttributeName:'PK',KeyType:'HASH'},{AttributeName:'SK',KeyType:'RANGE'}],PointInTimeRecoverySpecification:{PointInTimeRecoveryEnabled:true},DeletionProtectionEnabled:true,SSESpecification:{SSEEnabled:false},Tags:[{Key:'Project',Value:'ProjectRespawn'},{Key:'Domain',Value:'TeamHub'},{Key:'Environment',Value:'Ntgre'}]}});
// SSEEnabled false selects DynamoDB-owned default encryption, never unencrypted storage.
const additions={OperationalTable:table(operational),JournalTable:table(journal),LogoBucket:{Type:'AWS::S3::Bucket',DeletionPolicy:'Retain',UpdateReplacePolicy:'Retain',Properties:{BucketName:targetBucket,VersioningConfiguration:{Status:'Enabled'},PublicAccessBlockConfiguration:{BlockPublicAcls:true,BlockPublicPolicy:true,IgnorePublicAcls:true,RestrictPublicBuckets:true},OwnershipControls:{Rules:[{ObjectOwnership:'BucketOwnerEnforced'}]},BucketEncryption:{ServerSideEncryptionConfiguration:[{ServerSideEncryptionByDefault:{SSEAlgorithm:'AES256'}}]},Tags:[{Key:'Project',Value:'ProjectRespawn'},{Key:'Domain',Value:'TeamHub'},{Key:'Environment',Value:'Ntgre'}]}},LogoTransportPolicy:{Type:'AWS::S3::BucketPolicy',Properties:{Bucket:{Ref:'LogoBucket'},PolicyDocument:{Version:'2012-10-17',Statement:[{Sid:'DenyInsecureTransport',Effect:'Deny',Principal:'*',Action:'s3:*',Resource:['arn:aws:s3:::'+targetBucket,'arn:aws:s3:::'+targetBucket+'/*'],Condition:{Bool:{'aws:SecureTransport':'false'}}}]}}}};
const op=additions.OperationalTable.Properties;
for(const [name,pk,sk] of [['BySubject','SubjectPK','SubjectSK'],['ByTeamStatus','StatusPK','StatusSK']]){op.AttributeDefinitions.push({AttributeName:pk,AttributeType:'S'},{AttributeName:sk,AttributeType:'S'});(op.GlobalSecondaryIndexes??=[]).push({IndexName:name,KeySchema:[{AttributeName:pk,KeyType:'HASH'},{AttributeName:sk,KeyType:'RANGE'}],Projection:{ProjectionType:'KEYS_ONLY'}});}
additions.JournalTable.Properties.TimeToLiveSpecification={AttributeName:'expiresAt',Enabled:true};
const prior=read('docs/architecture/team-hub-2b2-caller-release-evidence-2026-10-05/ownership.json').productTemplate;
const proposal={...structuredClone(prior),Description:'PROPOSAL ONLY: Ntgre Team Hub dark state; no routes or runtime access added',Resources:{...structuredClone(prior.Resources),...additions}};
save('dark-target.template',proposal);
const sourceArns=inventory.tables.map(r=>r.table.TableArn),targetArns=[operational,journal].map(n=>'arn:aws:dynamodb:'+region+':'+account+':table/'+n);
const start='2026-10-06T08:00:00Z',end='2026-10-06T12:00:00Z';
const condition={StringEquals:{'aws:RequestedRegion':region},DateGreaterThan:{'aws:CurrentTime':start},DateLessThan:{'aws:CurrentTime':end}};
const statement=(Sid,Action,Resource,Condition=condition)=>({Sid,Effect:'Allow',Action,Resource,Condition});
const policy={Version:'2012-10-17',Statement:[statement('ExactSourceTables',['dynamodb:DescribeTable','dynamodb:Scan','dynamodb:GetItem','dynamodb:BatchGetItem'],sourceArns),statement('ExactTargetTables',['dynamodb:DescribeTable','dynamodb:Scan','dynamodb:GetItem','dynamodb:PutItem','dynamodb:BatchWriteItem','dynamodb:ConditionCheckItem'],targetArns),statement('SourceLogoRead',['s3:GetObject','s3:GetObjectVersion'],['arn:aws:s3:::'+logos.bucket+'/team-logos/*']),statement('TargetLogoRead',['s3:GetObject','s3:GetObjectVersion'],['arn:aws:s3:::'+targetBucket+'/team-logos/*']),statement('TargetLogoWrite',['s3:PutObject'],['arn:aws:s3:::'+targetBucket+'/team-logos/*'],{...condition,StringEquals:{...condition.StringEquals,'s3:x-amz-server-side-encryption':'AES256'}}),statement('ExactLogoListings',['s3:ListBucket','s3:ListBucketVersions'],['arn:aws:s3:::'+logos.bucket,'arn:aws:s3:::'+targetBucket],{...condition,StringEquals:{...condition.StringEquals,'s3:prefix':'team-logos/'}})]};
save('migration-identity-proposal',{status:'DESIGN_ONLY_NOT_CREATED',roleName:prefix+'-Migration',identityPolicy:policy,permissionsBoundary:policy,trust:{Version:'2012-10-17',Statement:[{Effect:'Allow',Principal:{AWS:'arn:aws:iam::058264289478:user/RavenTest'},Action:'sts:AssumeRole',Condition:{DateGreaterThan:{'aws:CurrentTime':start},DateLessThan:{'aws:CurrentTime':end}}}]},roleMaxSessionSeconds:3600,requestedSessionSeconds:900,window:'ILLUSTRATIVE ONLY; bind fresh reviewed timestamps at later gate',sourceArns,targetArns,targetBucket,normalRuntimeUnchanged:true,missingGate:'CloudTrail data-event coverage/log destination and custodian approval; no role exists',awsWrites:0});
save('resource-accounting',{legacyTotal:2621,functionDirective:167,legacyTeamAttributed:192,ledgerTeamOwner:188,buildMetadata:4,currentIndependentProduct:11,currentSecurity:5,darkTargetAdditions:4,proposedIndependentProduct:15,proposedSecurity:5,additions:Object.fromEntries(Object.entries(additions).map(([k,v])=>[k,v.Type])),modifications:0,deletions:0,replacements:0,temporaryMigrationProposal:{iamRole:1,managedBoundary:1,inlinePolicyNotSeparateResource:true,total:2,restoreRehearsalTablesUpTo:4,monitoringAndDataEventAudit:'not yet priced/provisioned; excluded from base candidate'},potentialRetirement:{reviewScope:192,authorized:0,eligibleNow:0},templateDigest:digest(proposal),deployed:false});
const files=execFileSync('git',['ls-files','-z'],{encoding:'utf8',maxBuffer:20e6}).split('\0').filter(p=>/^(src|amplify|scripts|domains|infrastructure)\//.test(p)&&/\.(ts|js|mjs|vue|json|yml)$/.test(p)&&!p.endsWith('package-lock.json'));
const terms=/TeamHub|teamHub|team-hub|TEAM_HUB_|models\\.Team\\b|TeamMembership|TeamRosterSlot|PlayerChampionPoolEntry|mutateTeamHub|readTeamHub|team-logos\/|CREATE_TEAM|UPSERT_MY_CHAMPION/;
const sourceReferences=[];for(const p of files){const lines=fs.readFileSync(p,'utf8').split(/\r?\n/);const hits=lines.flatMap((s,i)=>terms.test(s)?[i+1]:[]);if(hits.length)sourceReferences.push({path:p,lines:hits,scope:/test|fixture/i.test(p)?'TEST_ONLY':/^(domains\/team-hub|src\/features\/team-hub\/|infrastructure\/domains\/team-hub)/.test(p)?'OFFLINE_TARGET':/^amplify\//.test(p)||/^src\//.test(p)?'LIVE_LEGACY_SOURCE':'REVIEWED_TOOLING_REFERENCE'});}
const writes=['CREATE_TEAM','UPDATE_TEAM','SET_MANAGER','MANAGE_MEMBER','SET_ROSTER_SLOT','UPSERT_MY_CHAMPION','DELETE_MY_CHAMPION','UPSERT_COACH_ASSESSMENT','SET_TEAM_PLAN','REQUEST_TEAM_LOGO_UPLOAD','COMMIT_TEAM_LOGO','REMOVE_TEAM_LOGO'].map(action=>({id:action,classification:'ACTIVE',path:'amplify/myFunction/teamHub/gateway.ts',meaning:'Enabled source route, not a claim of recent invocation',authority:'LegacyPlatform'}));
writes.push({id:'GENERATED_MODEL_AND_DIRECT_DYNAMODB',classification:'POSSIBLE',path:'amplify/myFunction/teamHub/index.ts',meaning:'Shared Lambda generated model access and direct transaction adapter; IAM-capable bypasses must be fenced.'},{id:'PRESIGNED_LOGO_PUT',classification:'ACTIVE',path:'amplify/myFunction/teamHub/branding.ts',meaning:'Outstanding upload URLs outlive frontend flags; deny/drain uploads before final reconciliation.'},{id:'PRIVILEGED_OPERATOR_CLI',classification:'POSSIBLE',meaning:'Operator has scan authority; all effective write grants/session paths not exhaustively enumerated.'},{id:'SYNTHETIC_TARGET_AND_TESTS',classification:'TEST_ONLY',path:'domains/team-hub/repository.mjs'},{id:'EXTERNAL_SCHEDULED_OR_UNTRACKED_WRITERS',classification:'UNKNOWN',meaning:'Source search cannot establish absence of account-external clients, scheduled jobs or privileged scripts; data-event/identity review required.'});
const readers=[{id:'TEAM_HUB_PAGES',classification:'ACTIVE',path:'src/features/Team Hub'},{id:'HOME_SHORTCUTS',classification:'ACTIVE',path:'src/views/UserHomepage/UserHomepage.js'},{id:'ADMIN_TEAM_UI',classification:'ACTIVE',path:'src/features/Team Hub/TeamAdministration.vue'},{id:'LEGACY_READ_GATEWAY',classification:'ACTIVE',path:'amplify/myFunction/teamHub/gateway.ts'},{id:'LOGO_SIGNED_READ',classification:'ACTIVE',path:'amplify/myFunction/teamHub/branding.ts'},{id:'OLD_CLIENT_READ_CONTRACTS',classification:'COMPATIBILITY_REQUIRED',path:'amplify/data/resource.ts'},{id:'GENERATED_MODEL_ACCESS',classification:'COMPATIBILITY_REQUIRED',path:'amplify/myFunction/teamHub/index.ts'},{id:'EXTERNAL_DIRECT_CONSUMERS',classification:'UNKNOWN',meaning:'No exhaustive runtime principal/telemetry inventory; blocks retirement.'}];
save('reader-writer-inventory',{sourceCheckpoint:'4591f326de5c8ef6f09fc0b3a3d459d5d0d8580f',searchedTrackedSourceFiles:files.length,sourceReferences,writers:writes,readers,unknownWritersBlockMigration:true,unknownReadersBlockRetirement:true,limitations:['ACTIVE means reachable source path, not observed traffic.','No source-only search proves absence of deployed external clients.','No account-wide production resource operation performed.']});
const synthetic=transform(fixture(),options);save('synthetic-transform',{summary:synthetic.summary,reverseRoundTrip:JSON.stringify(reverse(synthetic.items,synthetic.recovery,options))===JSON.stringify(synthetic.recovery),reconciliation:reconcile(fixture(),synthetic.items,options),sensitivePayloadPersisted:false});
if(inventory.tables.every(t=>t.first.count===0&&t.second.count===0)){const empty=transform({},options);save('live-dry-run',{...empty.summary,evidence:'Two complete count passes on four tables; no item payloads fetched',recordsEvaluated:0,reconciliation:reconcile({},empty.items,options),restartCheckpoint:empty.checkpoint,atomicSnapshot:false,sourceAuthority:'LegacyPlatform',noWrites:true});}
console.log(JSON.stringify({darkAdditions:4,temporaryMigration:2,writerUnknown:1,readerUnknown:1,sourceFiles:sourceReferences.length,syntheticAccepted:synthetic.summary.accepted}));
