// Offline, deterministic preparation; deliberately no AWS import or deployment operation.
import fs from 'node:fs';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import {read,save,F,digest} from './final-read.mjs';
import {schemaVersion,fields,settingsFields,issuer} from './native-state.mjs';
const E='docs/architecture/team-hub-2b3-evidence-2026-10-05';
const inventory=read(E+'/table-inventory.json'),iam=read(F+'/iam-coverage.json'),resolver=read(F+'/resolver-coverage.json');
const old=read(E+'/reader-writer-inventory.json');
const role=iam.principals.find(p=>p.arn.includes('myFunctionrebuildlambdaSe')).arn;
const allTables=inventory.tables.map(t=>t.table.TableName),bucket=read(E+'/logo-inventory.json').bucket;
const evidence=[F+'/iam-coverage.json',F+'/resolver-coverage.json',F+'/resolver-functions.json',F+'/principal-functions.json',F+'/schedule-coverage.json',F+'/logo-resource-policy.json',F+'/reader-edges.json',E+'/live-consumers.json'];
const writer=(id,classification,source,principal,operation,targets,purpose,enabled=true)=>({id,classification,source,principal,operation,targets,enabled,reachable:enabled?'CAPABILITY_PRESENT_NOT_INVOCATION_PROOF':'NO_CURRENT_MATCHING_SOURCE_GRANT',environment:'Ntgre data only; principal may also have unrelated authority',businessPurpose:purpose,fence:'E: authoritative journal row + all-principal source data-write deny; maintenance/deployment freeze for control-plane paths; exact logo prefix deny',retirement:'After verified target authority, reject Legacy writes explicitly; remove exact legacy grants only at separate retirement review',evidence});
const operations={CREATE_TEAM:['Team'],UPDATE_TEAM:['Team'],SET_MANAGER:['Team','TeamMembership','TeamRosterSlot'],MANAGE_MEMBER:['Team','TeamMembership','TeamRosterSlot'],SET_ROSTER_SLOT:['Team','TeamRosterSlot'],UPSERT_MY_CHAMPION:['PlayerChampionPoolEntry'],DELETE_MY_CHAMPION:['PlayerChampionPoolEntry'],UPSERT_COACH_ASSESSMENT:['PlayerChampionPoolEntry'],SET_TEAM_PLAN:['Team'],REQUEST_TEAM_LOGO_UPLOAD:['team-logos/'],COMMIT_TEAM_LOGO:['Team','team-logos/'],REMOVE_TEAM_LOGO:['Team','team-logos/']};
const writers=Object.entries(operations).map(([id,targets])=>writer(id,'ACTIVE_BUSINESS_WRITER','amplify/myFunction/teamHub/gateway.ts',role,id,targets,'Enabled Legacy Team business command'));
writers.push(writer('PRESIGNED_LOGO_PUT','ACTIVE_BUSINESS_WRITER','amplify/myFunction/teamHub/branding.ts',role,'s3:PutObject',[bucket+'/team-logos/*'],'Previously issued URLs remain usable until expiry or policy denial'));
writers.push(writer('SHARED_LAMBDA_DIRECT_ADAPTER','POSSIBLE_BUSINESS_WRITER','amplify/myFunction/teamHub/dynamo.ts',role,'TransactWriteItems governed by underlying PutItem/UpdateItem permissions',allTables.filter(t=>!t.startsWith('PlayerChampionPoolEntry-')),'Internal direct table transaction bypass of the public gateway'));
writers.push(writer('SYNTHETIC_TESTS','TEST_ONLY','scripts/team-hub/tests; scripts/team-hub-migration','NONE','in-memory only',[],'Offline fixtures',false));
const principals=[];
for(const p of iam.principals){
 let classification='UNKNOWN',reason='Requires review';
 if(p.arn===role){classification='ACTIVE_BUSINESS_WRITER';reason='Covered by named gateway/direct/logo rows';}
 else if(p.arn.includes('adminusermanagementlambda')){classification='POSSIBLE_BUSINESS_WRITER';reason='Admin Lambda has generated Team GraphQL authority; no Team business intent assumed';}
 else if(p.administrationCapability){classification='PRIVILEGED_MANUAL';reason='Potential administration/deployment authority; conditions and boundaries may limit escalation, not presumed business use';}
 else if(p.arn.includes('lookup-role')){classification='PRIVILEGED_MANUAL';reason='Read-only inspection role; not a data writer';}
 else if(p.arn.includes('deploy-role')){classification='DEAD';reason='Matched S3 statement excludes this account via s3:ResourceAccount; deployment delegation remains maintenance-frozen';}
 else if(resolver.sources.some(s=>s.role===p.arn)||read(F+'/principal-functions.json').functions.some(f=>f.role===p.arn&&read(F+'/provider-artifacts.json').providers.some(v=>v.arn===f.arn))){classification='GENERATED_INTERNAL';reason='Exact deployed data-source or hash-verified table-provider role mapping; preserve ownership, fence by role/path';}
 principals.push({arn:p.arn,classification,reason,trust:p.trust,boundary:p.boundary,grants:p.grants});
 if(p.arn===role||p.arn.includes('lookup-role'))continue;
 writers.push(writer('PRINCIPAL:'+p.arn.split('/').at(-1),classification,'Deployed IAM / resolver / CloudFormation metadata',p.arn,[...new Set(p.grants.flatMap(g=>g.actions))],allTables,reason,classification!=='DEAD'));
}
writers.push(writer('ACCOUNT_ROOT','PRIVILEGED_MANUAL','AWS account root',iam.rootPrincipal,'account administration and potential data writes',allTables,'Break-glass; explicit operator maintenance freeze, cannot technically prevent root policy removal'));
const logoPolicy=read(F+'/logo-resource-policy.json');
for(const s of logoPolicy.policy.Statement.filter(s=>s.Effect==='Allow')){
 const principal=s.Principal?.AWS;
 const known=typeof principal==='string'&&principal.includes('CustomS3AutoDeleteObjects');
 writers.push(writer('LOGO_CLEANUP_PROVIDER',known?'GENERATED_INTERNAL':'UNKNOWN',F+'/logo-resource-policy.json',principal,s.Action,[bucket+'/team-logos/*'],'Generated bucket teardown path; no lifecycle changes permitted during cutover'));
}
const readers=old.readers.filter(r=>r.classification!=='UNKNOWN').map(r=>({...r,classification:r.classification==='ACTIVE'?'ACTIVE':'COMPATIBILITY_REQUIRED',principal:role,operation:r.id==='LOGO_SIGNED_READ'?'s3:GetObject':'readTeamHub / generated model query',fieldsDTO:r.id==='LOGO_SIGNED_READ'?'authorized logo URL':'Existing gateway DTO; target must use minimized allowlisted projection, no Coach-private fields',futureContract:'Team Hub owner API v1; Manager/Coach assessment projection only',retirementCondition:'Client switched or explicit DOMAIN_MOVED response; no silent stale reads',evidence}));
for(const p of principals.filter(p=>p.arn!==role))readers.push({id:'PRINCIPAL:'+p.arn.split('/').at(-1),classification:p.classification==='UNKNOWN'?'UNKNOWN':p.classification==='GENERATED_INTERNAL'?'GENERATED_INTERNAL':'PRIVILEGED_OR_POSSIBLE',principal:p.arn,operation:[...new Set(p.grants.flatMap(g=>g.actions))],fieldsDTO:'Potential raw fields through granted query/scan/stream/export/GraphQL routes; never a public DTO guarantee',compatibilityRequirement:'Quiesce raw readers at freeze; inspect rights rather than infer use',futureContract:'Owner API for application consumers; separately authorized verifier for recovery',retirementCondition:'Exact source grants removed after evidence-backed review',evidence});
readers.push({id:'ACCOUNT_ROOT',classification:'PRIVILEGED_OR_POSSIBLE',principal:iam.rootPrincipal,operation:'privileged inspection',fieldsDTO:'raw administrative access',futureContract:'break-glass only',retirementCondition:'operational control, not deletable principal',evidence});
const missingPipeline=resolver.resolvers.flatMap(r=>r.pipeline?.functions??[]).filter(id=>!read(F+'/resolver-functions.json').functions.some(f=>f.id===id));
const edges=read(F+'/reader-edges.json');
missingPipeline.push(...edges.subscriptionResolvers.flatMap(r=>r.pipeline?.functions??[]).filter(id=>!edges.subscriptionFunctions.some(f=>f.id===id)));
readers.push({id:'GENERATED_TEAM_SUBSCRIPTIONS',classification:'GENERATED_INTERNAL',principal:iam.principals.filter(p=>p.grants.some(g=>g.actions.includes('appsync:GraphQL')&&g.resources.some(r=>r.includes('/Subscription/')))).map(p=>p.arn),operation:edges.subscriptionResolvers.map(r=>r.field),fieldsDTO:'Generated model mutation payload; raw model fields, not owner DTO',compatibilityRequirement:'Block new subscriptions and drain existing connections/queued delivery at freeze; no source mutation events after target authority',futureContract:'Explicit owner event contract or no subscription support; never implicit Legacy subscription fallback',retirementCondition:'No remaining client subscriptions; exact subscription IAM grants removed at review',evidence});
for(const r of readers)r.compatibilityRequirement??='Preserve authorized Legacy reads before freeze; switch to owner contract or explicit rejection at cutover';
if(!iam.paginationCompleted||iam.missingPolicyDocuments||missingPipeline.length||edges.streams.some(s=>!s.absent)){writers.push(writer('INCOMPLETE_COVERAGE','UNKNOWN','coverage validation','UNKNOWN','UNKNOWN',allTables,'Incomplete identity/resolver/resource-policy evidence'));readers.push({id:'INCOMPLETE_COVERAGE',classification:'UNKNOWN'});}
const counts={activeBusiness:writers.filter(r=>r.classification==='ACTIVE_BUSINESS_WRITER').length,possible:writers.filter(r=>r.classification==='POSSIBLE_BUSINESS_WRITER').length,privilegedManual:writers.filter(r=>r.classification==='PRIVILEGED_MANUAL').length,generatedInternal:writers.filter(r=>r.classification==='GENERATED_INTERNAL').length,testOnly:1,dead:writers.filter(r=>r.classification==='DEAD').length,unknownWriters:writers.filter(r=>r.classification==='UNKNOWN').length,activeReaders:5,compatibilityReaders:2,unknownReaders:readers.filter(r=>r.classification==='UNKNOWN').length};
save('coverage',{at:iam.at,counts,writers,readers,principals,inventory:{roles:iam.rolesEnumerated,users:iam.usersEnumerated,policies:iam.policiesEnumerated,missingDocuments:iam.missingPolicyDocuments,missingPipeline},scope:'Snapshot of exact Ntgre Team authority paths; known potential and privileged principals retained, not a claim of no future access or complete CloudTrail data audit',evidence});
const prior=read('docs/architecture/team-hub-2b2-caller-release-evidence-2026-10-05/ownership.json').productTemplate;
const oldDark=read(E+'/dark-target.template.json');
const resources={...structuredClone(prior.Resources),OperationalTable:oldDark.Resources.OperationalTable,JournalTable:oldDark.Resources.JournalTable};
const template={...structuredClone(prior),Description:'PROPOSAL ONLY: two dark Team Hub tables; branding deferred; no runtime writes',Resources:resources};
save('dark-target.template',template);
save('target-schema',{schemaVersion,issuer,closedFields:fields,commonFields:['schemaVersion','entityType','PK','SK','version','createdAt','updatedAt'],settingsFields,operational:'ProjectRespawn-TeamHub-Ntgre-Operational',journal:'ProjectRespawn-TeamHub-Ntgre-Journal',gsis:resources.OperationalTable.Properties.GlobalSecondaryIndexes,privacy:{player:'own player fields; no Coach fields',assessment:'active Manager or Coach only, never Player or implicit admin',private:'authoring active Coach only; disabled during rollback window'},journal:{authority:{PK:'CONTROL#AUTHORITY',SK:'STATE',fields:['mode','epoch','version','changedAt','changedBy','gateDigest'],ttl:false},audit:{PK:'TEAM#<teamId>',SK:'AUDIT#<UTC ISO time>#<requestId>',fields:['actorIssuer','actorSubject','operation','teamId','requestId','resultingVersion','authorizationEpoch','at','expiresAt'],retentionDays:365,privateTextForbidden:true},idempotency:{PK:'IDEMP#<issuer SHA256>#<subject>#<teamId>',SK:'<operation>#<requestKey>',fields:['digest','response','expiresAt','authorizationEpoch','version'],retentionSeconds:86400,currentAuthorizationRequiredOnReplay:true,privateResponseForbidden:true}},rollbackWindow:{durationHours:24,closure:'explicit accepted rollback proof and operator signoff; time alone does not close window',coachPrivate:'NON_REVERSIBLE_DURING_ROLLBACK_WINDOW',branding:'DISABLED_NO_BUCKET'},runtimeAdapterInstalled:false});
save('resource-accounting',{legacy:2621,legacyTeamAttribution:192,functionDirective:167,currentTeamProduct:11,currentTeamSecurity:5,tournament:11,trackedScopeCurrent:2648,darkAdditions:{OperationalTable:1,JournalTable:1},proposedTeamProduct:13,proposedTeamSecurity:5,legacyProtectionNewDeclarations:0,restoreTemporaryTables:4,migrationIamModeA:0,fenceNewDeclarations:0,fenceControlRow:1,sourceTableResourcePolicies:4,existingLogoBucketPolicyUpdate:1,existingExecutionPolicyUpdates:'Modify existing deployment grants only; no new role/managed policy',trackedScopePeakIncludingRestoreTables:2654,onDemandBackupArtifacts:4,fullAccountPeak:'NOT_MEASURED: no account-wide physical resource inventory; 2654 is scoped declaration/table accounting, backups are separate service artifacts',modeBAdditionalIamDeclarations:2,modeBNotAuthorized:true,retirement:0,savingsClaimed:0,deployed:false,templateDigest:digest(template)});
const providerPath='node_modules/@aws-amplify/graphql-api-construct/node_modules/@aws-amplify/graphql-model-transformer/lib/resources/amplify-dynamodb-table/amplify-table-manager-lambda/amplify-table-manager-handler.js';
const downloaded='.tmp/team-hub-provider-review/amplify-projectrespawnweb-TableManagerCustomProvid-UvXMendxwsce/amplify-table-manager-handler.js';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
if(sha(providerPath)!==sha(downloaded))throw Error('Provider source mismatch');
const require=createRequire(import.meta.url),provider=require('../../'+providerPath);
const off=provider.getPointInTimeRecoveryUpdate({PointInTimeRecoveryDescription:{PointInTimeRecoveryStatus:'ENABLED'}},{tableName:'SYNTHETIC'});
const deletionOff=provider.getDeletionProtectionUpdate({DeletionProtectionEnabled:true},{tableName:'SYNTHETIC'});
save('provider-review',{deployedZipSha256:read(F+'/provider-artifacts.json').providers[0].codeSha256,handlerSha256:sha(providerPath),localMatchesDeployed:true,pureHelperResults:{pitrDesiredAbsent:off,deletionProtectionDesiredAbsent:deletionOff,pitrDesiredTrue:provider.getPointInTimeRecoveryUpdate({PointInTimeRecoveryDescription:{PointInTimeRecoveryStatus:'ENABLED'}},{tableName:'SYNTHETIC',pointInTimeRecoverySpecification:{pointInTimeRecoveryEnabled:true}})??null,deletionDesiredTrue:provider.getDeletionProtectionUpdate({DeletionProtectionEnabled:true},{tableName:'SYNTHETIC',deletionProtectionEnabled:true})??null},lifecycle:{keyReplacement:'checks before protection update; rejects when destructive flag false',gsiReplacement:'requires both destructive and replace-GSI flags true',replacementWhenProtected:'throws before DeleteTable',deleteWhenProtected:'returns success without deleting; retained physical table may become unmanaged',pitrOob:'next Update with omitted/false desired setting disables PITR',deletionProtectionOob:'next Update with omitted desired setting disables protection',backup:'provider has no DeleteBackup call; independent on-demand backups not removed by its table update/replacement code'},sourceLineReferences:{replacement:145,pitrUpdate:192,deletionUpdate:199,delete:260,replace:345,deleteHelper:620,pitrHelper:672},proposal:'Set desired PITR/deletion protection true, destructive/GSI replacement false, Retain/Retain; reject all identity/schema/index changes',providerModified:false,awsWrites:0});
console.log(JSON.stringify({coverage:counts,darkAdditions:2,providerHashVerified:true}));
